### ISSUE TITLE
Replace or remove puente from our dependencies

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1012]
Puente is not properly maintained and it makes updating libraries a bit difficult. We also need to enhance our extract/merge string process by passing more arguments to `msgmerge` something that it's not possible with puente at the moment

**Comment by akatsoulas** [comment]
relevant information
https://github.com/mozilla/addons-server/issues/19076

**Comment by smithellis** [comment]
WIP Pull is here: https://github.com/mozilla/kitsune/pull/5207

**Comment by akatsoulas** [comment]
Closing in favor of #1105
