### ISSUE TITLE
"Avatar for username" text is displayed instead of the actual image when signing in

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1017]
**Stesp to reproduce:** 
1. Go to https://support.allizom.org/en-US/
2.  Sign in/Sign up. 
3. Notice the username and the avatar of the signed in account. 

**Actual results:**
![image](https://user-images.githubusercontent.com/53306802/164222814-5cacf751-154e-48aa-b0e0-d8b159b50787.png)
![image](https://user-images.githubusercontent.com/53306802/164234155-47e6c10d-16a7-4cb1-a759-ac95912e90fd.png)

**Expected results:** 
![image](https://user-images.githubusercontent.com/53306802/164222841-bee0bb72-6b7e-49c6-a325-2ec495c10a7b.png)

**Comment by mirunacurtean** [comment]
@akatsoulas This issue seemed resolved, until I aded a profile picture in FxA side and signed out and signed in again. 

![image](https://user-images.githubusercontent.com/53306802/166210027-0b330ffa-5f6a-4635-b82d-f884fbb0e8e9.png)

![image](https://user-images.githubusercontent.com/53306802/166209946-c542384d-b407-4c9b-8b5a-55e71ed5300c.png)

**Comment by akatsoulas** [comment]
@mirunacurtean this should be now fixed

**Comment by mirunacurtean** [comment]
Verified fixed on Windows 10 across Firefox, Chrome and Edge and on macOS on Safari. 
The proper avatar is showing when logging in with a profile with or without a profile picture. 
![image](https://user-images.githubusercontent.com/53306802/166232415-ae9d4942-7e5d-401a-b52c-6b8fbf3912da.png)
