### ISSUE TITLE
Use local storage for banner

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1028]
https://bugzilla.mozilla.org/show_bug.cgi?id=1682190

**Comment by mirunacurtean** [comment]
Verified across Windows 10 and android 9 using Firefox, Chrome and Edge browsers. 
Unless it's an incognito or a private session, the "Avoid support scams" banner will be dismissed and will no longer pop up across the support site. 
Tested on [Support forums](https://support.allizom.org/en-US/questions/firefox?show=all) from main page to questions and verified that dismissing the banner in one tab/ window will affect the other open tabs and pages after a refresh. 
The banner is no longer displayed in the same browser upon closing and reopening it. 
High level test cases can be seen [here](https://testrail.stage.mozaws.net/index.php?/runs/view/58470&group_by=cases:section_id&group_order=asc).
