### ISSUE TITLE
"Firefox" isn't always appropriate in "If you need help with Firefox, please ask a question."

### ISSUE THREAD

**Issue by wsmwk** [mozilla/sumo#1034]
Example 
1. User is at https://support.mozilla.org/en-US/kb/installing-thunderbird-windows/
2. User clicks discussin
3. https://support.mozilla.org/en-US/kb/installing-thunderbird-windows/discuss/8259 shows:
This forum is a discussion about improving the "Installing Thunderbird on Windows" article.
If you need help with Firefox, please [ask a question](https://support.mozilla.org/en-US/questions/new).

SUMO provides support for growing number of non-Firefox products: Mozilla VPN, Hubs, MDN Plus, etc

"a product" or some other language could be substituted for the word "Firefox".

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5146

**Comment by mirunacurtean** [comment]
Works as intended for both English and non-English locales. Redirects to the fist step of the AAQ. The banner is displayed in the  main Discussion page and also on each thread. 
![image](https://user-images.githubusercontent.com/53306802/173090711-22e14141-15d9-431c-8ad7-09a5534c7c54.png)
![image](https://user-images.githubusercontent.com/53306802/173090897-70023463-5269-496f-b38f-f6a7a14d3a1b.png)
@akatsoulas Should the "If you need product support, please [ask a question](https://support.allizom.org/es/questions/new)." line also be translated?
