### ISSUE TITLE
[project] Realignment of tiles on the AAQ page, Main landing page, and KB landing page

### ISSUE THREAD

**Issue by cindij** [mozilla/sumo#1039]
**Is your feature request related to a problem? Please describe.**
The tiles surfaced on the SUMO Main Landing page, KB Landing page, and AAQ Landing page are all different. Some are outdated, some are out of order based on preferred tile display ordering.

**Describe the solution you'd like**
We created a list of preferred tile placement on the SUMO Main Landing page, KB Landing page, and AAQ Landing page. This preferred list takes into account products that are or will be sunset soon, as well as low traffic product to ensure optimal placement on the SUMO site.

**Describe alternatives you've considered**
Should we update the main landing page and kb landing page now/separately and update the AAQ page later as part of the AAQ Extraction milestone work?

**What is the requested timeline for completion?**
Ideal timeline for this project proposal.
This tile placement update is only a piece of the larger Obsolete Content project the CX Team is working on, which is a multi-quarter project. Updating the tiles displayed is not a blocker to moving on to other pieces of the larger project, however to ensure an optimal customer experience, the update is necessary.

**Who is the audience**
Audience of this project. Internal or external, feature request or improvement.
Customers on SUMO for all products show on the Main Landing page, KB Landing page, and AAQ Landing page.

**Additional context**
This is part of the overall Obsolete Content project. 

**Applicable resources**
Project brief, JIRA, Bugzilla or GitHub, any documentation, use cases.
https://trello.com/c/R3z2qkJZ
Doc in Trello: Sunset (existing and upcoming) Product List and Tile Placement

**Comment by cindij** [comment]
Verified with Kiki, Abby and JR - all agreed they'd like to move forward with updating the Main landing page and the KB landing page first, knowing that the AAQ landing page will need to wait.

**Comment by cindij** [comment]
https://docs.google.com/spreadsheets/d/13NufuxvdNaNzK212vtUnjNCfean_4ZXsKYetQ88HVJU/edit#gid=0

**Comment by akatsoulas** [comment]
@akatsoulas to break this out to 2 issues - one for KB and products and another one for AAQ.

**Comment by akatsoulas** [comment]
AAQ will be tracked in issue #1057
