### ISSUE TITLE
Fix ratelimit and is_ratelimited

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1052]
While working on mozilla/kitsune#5156, I discovered that the SUMO utils `ratelimit` and `is_ratelimited` were seriously broken and misleading, the main reason being that the `name` and `method` arguments were completely ignored.

All rate limits were counted against the one group `sumo.utils.is_ratelimited`, with the only differentiator being the `rate` argument (e.g., `"10/d"`). This meant that all uses of `ratelimit` and `is_ratelimited` that used the same `rate` argument were counted against the same limit, no matter if they specified different `name` arguments like `kbforum-post-day` and `primate-message-day`. So for SUMO, this means that currently the following rate limits, which seem like different limits due to their differing names, are actually the same limit (requests to any one counted against the same limit):
- `forum-post` and `aaq-day` (since both used the rate of `"5/d"`)
- `kbforum-post-day` and `primate-message-day` (since both used the rate of `"50/d"`)
- `question-vote`, `answer-vote`, and `document-vote` (since they all used the rate of `"10/d"`)

Also, since the `method` argument was ignored, the default of the `django-ratelimit` package was used, which is **all** HTTP methods. So if the endpoint being rate-limited accepted more than just POST requests, non-POST requests also counted against the limit. Fortunately, this case isn't currently a problem, since all of the rate-limited endpoints only accept POST requests.

**Comment by mirunacurtean** [comment]
Superuser accounts are permitted to vote without the rate limited affecting them. 
Non-superuser accounts will get a total of 10 votes/day/support forum, even spread between different questions. 
After 24hours this rate limit is removed and the user is permitted to vote again, but not on answers it has voted before. 
The rate limit is applied again when the 10 votes has been distributed. This is applied even after the user signs out/ sign in out, or uses another browser/ clear profile/ incognito tab. 
Tested across Firefox, Chrome and Edge browsers. 
Voting on support forum does not affect the ability to vote in articles, in which the a rate limit is not applied (I was able to vote over 50 articles in one day using the same non-superuser account).
