### ISSUE TITLE
Copy improvement for "Needs more information" 

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1059]
**Describe the bug**
"Needs more information" checklist under the reply field needs better copy to make it clearer. 

**To Reproduce**
1. Go to any forum thread. For example: https://support.mozilla.org/en-US/questions/1381015 
2. Go to the reply field
3. See the "Needs more information" checklist

**Expected behavior**
Contributor understands what the checklist is for. 

**Actual behavior**
"Needs more information" doesn't specify enough what information we need, or from who do we need the information in the first place. 

**Proposed change**
Modify the copy into "Needs more information from the user" to make it clearer that we need the more information from the user to be able to help resolve the issue. 

**Screenshots**
![gambar](https://user-images.githubusercontent.com/4922388/175896600-5224b0b8-be94-45fe-84c2-071b07e26288.png)

**Additional context**
- See https://bugzilla.mozilla.org/show_bug.cgi?id=1236622

**Comment by mirunacurtean** [comment]
This has been applied successfuly and no display issues were noticed on larger vs smaller layouts. 
It will need to be localised. 
![image](https://user-images.githubusercontent.com/53306802/176171830-23601962-9b78-4a04-b21b-676615b711ea.png)
