### ISSUE TITLE
An Error Occurred - 500 error when viewing images listed as part of the search results for "Fx"

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1061]
**Describe the bug**
The image is not being displayed when it is selected. 

**To Reproduce**
1. Go to https://support.allizom.org/en-US/gallery/images/search?q=fx
2. Click on one of the images (initially this occured with the images in the first row too, but now it cannot be reproduced) in the second row. 
3. Notice the result.

**Expected behavior**
The image, it's description, and if logged in with an account that has the rights/permission to delete or edit the page, they are also able to see those buttons. 

**Screenshots**
![fx search results error](https://user-images.githubusercontent.com/53306802/176168762-88281843-fc55-40fc-8a09-6ea831eba780.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Edge, Chrome
 - Version Stable

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - Browser Firefox

**Additional context**
This only occurs in stage, not in production and an additional clue is that the error prone images are the one that are displayed with only a link and no preview image, so there probably are no images left and only this li nk towards them is available on the frontend. This would be then a stage only issue.

**Comment by escattone** [comment]
This is an issue with stage only. The kitsune database metadata for a set of images existed, but their actual image files did not exist in the stage user media S3 bucket -- for example, https://support.allizom.org/en-US/gallery/image/30524 was one of them. I simply copied some of the images from the prod user media S3 bucket into the stage S3 bucket, and the errors for those images disappeared.

I suspect the origin of these errors is that some of the prod kitsune database data was used to update the stage database, but the corresponding S3 data was not copied from the prod user media S3 bucket into the stage user media S3 bucket.
