### ISSUE TITLE
New Account Read more link redirects to Page not Found

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1062]
**Describe the bug**
The link from the create account greeen banner redirects to a page not found. 

**To Reproduce**
1. Go to support.allizom.org.
2. Click on Sign up and create a new account 
4. After sign up in the SUMO page a green welcome banner will be displayed. 
5. Select the Read More link. 
6. Notice the resulting page. 

**Expected behavior**
Redirect to FAQ page. 
![image](https://user-images.githubusercontent.com/53306802/176208759-7906cf95-5d2a-4eea-91e1-b5720c4b2454.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/53306802/176208261-0475f5b7-bd31-45c4-9236-071f58ae116d.png)
![image](https://user-images.githubusercontent.com/53306802/176208186-c55ade2a-3a0d-4e74-93a4-853fb6b37a72.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Firefox

**Additional context**
Behavior does not occur in production.

**Comment by akatsoulas** [comment]
This is happening in staging because the KB does not have the linked article. Prod though works fine. There is a redirect to point to the right url
https://support.mozilla.org/en-US/kb/firefox-accounts-supportmozillaorg?redirectslug=firefox-accounts-mozilla-support-faq&redirectlocale=en-US
