### ISSUE TITLE
Remove pickle as a serialization option for our Celery tasks

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1066]
Allowing `pickle` as a serialization option for our Celery tasks is a security vulnerability (see https://docs.celeryq.dev/en/latest/userguide/security.html#security-serializers), so let's remove the need for `pickle` serilization within SUMO.

**Comment by escattone** [comment]
### Notes for QA Testing

#### Endpoints to test
##### Forums
- Test that new posts to forum threads notifies "watchers" as usual (`/en-US/forums/<slug>/<thread>/reply`).
- Test that the creation of new forums notifies "watchers" as usual (`/en-US/forums/<slug>/new`)
##### KBForums
- Test that new posts to KB discussion threads notifies "watchers" as usual (`/en-US/kb/<doc-slug>/discuss/<thread-id>/reply`)
- Test that the creation of new KB discussion threads notifies "watchers" as usual `/en-US/kb/<doc-slug>/discuss/new`
##### Questions
- Test that new posts to questions notifies "watchers" as usual (`/en-US/questions/<question-id>/reply`)
- Test that marking an answer as the solution to a question notifies "watchers" as usual (`/en-US/questions/<question-id>/solve/<answer-id>`)
##### Wiki
- Test that approving a review notifies "watchers" as usual (the approver and the creator of the revision are excluded)(`/en-US/kb/<doc-slug>/review/<revision-id>`)
- Test that marking a KB article as ready for localzation notifies "watchers" as usual (the one marking as ready and the creator of the revision are excluded) (`/en-US/kb/<doc-slug>/readyforl10n/<revision-id>`)
- Test that creating a new KB article notifies "watchers" as usual (`/en-US/kb/new`)
- Test that editing a KB article notifies "watchers" as usual (`/en-US/kb/<doc-slug>/edit`)
- Test that translating a KB article notifies "watchers" as usual (`/en-US/kb/<doc-slug>/translate`)

**Comment by mirunacurtean** [comment]
Hello @escattone. I've started [this document](https://docs.google.com/document/d/1cwQeS3b3t5pwcez9X-qx-UjLR2moL_AP5mkVkX5b7U8/edit#) to which you shgould have access to, in order to keep track of the cases in which a user should be notified and the examples created for each use case.

**Comment by mirunacurtean** [comment]
After receiving confirmation from @escattone that the email notifications are received in the DB (as otherwise they are not available in stage), I am setting this as Ready for Release.
