### ISSUE TITLE
High data consumption in NR

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1067]

**Comment by smarnach** [comment]
It looks like what we had enabled before was _tranaction tracing_: https://github.com/mozilla/kitsune/blob/main/newrelic.ini#L124

What was enabled in that release by default was _distributed tracing_. We should disable the latter using

    distributed_tracing.enabled = false

The purported reason why New Relic enabled this by default is [that they deprecated "cross-application tracing" in the same release](https://docs.newrelic.com/whats-new/2021/10/python-update%20-7-0-0-166/). Honi soit qui mal y pense.
