### ISSUE TITLE
Profile images are no longer displayed 

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1068]
**Describe the bug**
Sign in with an account that has a profile image added in the FxA Manage account page. 

**To Reproduce**
1. Sign in with an account that has not profile picture.
2. From https://support.allizom.org/en-US/users/edit select Manage Firefox account 
3. Add a photo.
4. Return to Sumo - the image as possibly not been applied. This also [occurs on mdn ](https://github.com/mdn/yari/issues/6696).
5. Sign out and sign in.

**Expected behavior**
The iamge is displayed instead of the "Avatar for username" text.

**Screenshots**
![image](https://user-images.githubusercontent.com/53306802/178288681-241900b2-acdb-4916-b5d2-6118275f8736.png)

**Desktop (please complete the following information):**
 - Windows
 - Firefox, Chrome. 
 - Stable

**Additional Context:**
This is a verification of https://bugzilla.mozilla.org/show_bug.cgi?id=1778729.

**Comment by akatsoulas** [comment]
This is because of CSP

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5189

**Comment by mirunacurtean** [comment]
Fixed in profile and verified that the image is displayed in question threads, on the community hub search results and in My profile. 
The only place that has not been updated community hub [Top Contributors avatar](https://support.allizom.org/en-US/community/). See the M profile in Knowledge base. Could this be due to a delay @akatsoulas?
![image](https://user-images.githubusercontent.com/53306802/181234327-fcc3b6ef-d687-4109-beb4-ceaaec924824.png)
