### ISSUE TITLE
Leverage profile change event to refersh FxA avatars

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1070]
We should investigate if it is possible to listen to a profile change event from Firefox Accounts when a user changes their profile avatar in order to instantly update the avatar on our end. 

https://github.com/mozilla/fxa/tree/main/packages/fxa-event-broker#profile-change

**Comment by akatsoulas** [comment]
@smithellis How would you feel about giving this a go?

**Comment by smithellis** [comment]
I love it.  Thanks!

**Comment by smithellis** [comment]
We discovered that FXA doesn't send a change event for avatar changes. Closing.
