### ISSUE TITLE
Manage Firefox account redirect arrives to previously logged in account settings page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1071]
**Describe the bug**
Account A was logged in in stage and using the Manage my account link page, its firefox account settings page was accessed. 
After logout from that account and login with a different account, let's call it Account B, when using Manage my account to see the FxA page belonging to Account B, the redirect was instead performed to Account A's page. 

Precondition:
Sign in with Account A and reach FxA settings page.
Sign out and Sign in with Account B.

**To Reproduce**
1. Go to https://support.allizom.org/en-US/users/edit
2. Click on Manage my Account.
3. View redirect result.

**Expected behavior**
Manage my Account redirects to the FxA settings page for account B. 

**Screenshots**

![Manage my account redirect to previosly logged in Firefox account](https://user-images.githubusercontent.com/53306802/181223376-0e1b1ecb-7a82-40e4-9436-01108a319d49.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. Firefox]
 - Version [e.g. 102.0.1]

**Additional context**
I also noticed a need to sign in again when using Manage my Account after first signing in on SUMO, so this all rather points out to some sync issues with FxA. 
![required to login again in FXA](https://user-images.githubusercontent.com/53306802/181224852-89c78f60-d3d6-4295-bc0e-cd6a5ec067fc.gif)

**Comment by akatsoulas** [comment]
the redirect from the button points to FxA prod but we are using FxA staging in our staging instance. Can this be the source of confusion here?

**Comment by mirunacurtean** [comment]
Yes, probably.
