### ISSUE TITLE
Required to login in the first redirect from Manage Firefox Account to FxA settings

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1072]
**Describe the bug**
When redirected to the FxA page, the account holder is required to sign in again. 

**To Reproduce**
1. Go to https://support.allizom.org/en-US/ and sign in.
2. Click on profile> edit profile.
3. Scroll down to Manage Firefox Account
4. Notice sign in page 

**Expected behavior**
The experience is seamless and as the account has been logged in in sumo and is an existing FxA account, it should redirect without a need to login again, to the FxA settings page. 

**Screenshots**
![required to login again in FXA](https://user-images.githubusercontent.com/53306802/181224852-89c78f60-d3d6-4295-bc0e-cd6a5ec067fc.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. WIndows]
 - Browser [Firefox]
 - Version [102.0.1]

**Additional context**
Added a note about it in https://github.com/mozilla/sumo/issues/1071

In production, after login in SUMO, these is no need to login again to reach FxA settings page.

**Comment by akatsoulas** [comment]
This is not something that we can control from Sumo. The redirect is taking users to the Firefox Accounts portal to manage their settings. If the user is logged in to their Firefox Account the user will be redirected to the Firefox Account management page. If not the user will need to login twice.

In staging we are using the staging instance of Firefox Accounts so even if the user is logged into FxA from their browser, will be asked to login again. In prod this won't happen
