### ISSUE TITLE
Upgrade to the latest version of JQuery

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1079]
Mainly a placeholder. Additional issues may be needed for this effort.

**Comment by mirunacurtean** [comment]
Coule these be related https://github.com/mozilla/sumo/issues/1084

**Comment by mirunacurtean** [comment]
Pages tested:

https://support.allizom.org/en-US/questions/new/desktop
https://support.allizom.org/en-US/kb/search-based-one-word-part-two
https://support.allizom.org/en-US/products/thunderbird/install-migrate-and-update/copy-your-personal-information-one-thunderbird-another
https://support.allizom.org/en-US/questions/firefox
https://support.allizom.org/en-US/questions/firefox?show=responded&tagged=cookies
https://support.allizom.org/en-US/questions/firefox?show=responded&tagged=cookies&filter=solution-provided&owner=mine
https://support.allizom.org/en-US/products/ios#search
https://support.allizom.org/en-US/products/firefox/fix-problems/procedures-diagnose-and-fix-problems
https://support.allizom.org/en-US/messages
https://support.allizom.org/en-US/messages/sent

https://support.allizom.org/en-US/products/thunderbird
https://support.allizom.org/es/kb/obtener-ayuda-de-la-comunidad?exit_aaq=1
https://support.allizom.org/es/questions/new
https://support.allizom.org/es/questions
https://support.allizom.org/en-US/questions/746975#answer-1082916
https://support.allizom.org/en-US/questions/1207256
- choose solution/ undo 
- add/remove  tag
- Browser image 
- Preview reply 

https://support.allizom.org/en-US/questions/1207256#search

https://support.allizom.org/en-US/forums/contributors/712915


https://support.allizom.org/en-US/contributors?category=10
https://support.allizom.org/en-US/kb/dashboard/metrics/en-US?product=firefox&category=
https://support.allizom.org/en-US/kb/revisions?locale=es&users=mcurtean&start=2022-04-04&end=2022-08-17

https://support.allizom.org/en-US/user/mcurtean%20231
https://support.allizom.org/en-US/users/edit
https://support.allizom.org/en-US/users/settings

https://support.allizom.org/en-US/forums/contributors/
https://support.allizom.org/en-US/forums/contributors/new
- cancel
- preview 
- add line/ link
- post 

https://support.allizom.org/en-US/forums/contributors/712963
- watch thread

https://support.allizom.org/en-US/forums/contributors/712963/edit
- cancel/ update
https://support.allizom.org/en-US/kb/article-about-cats/discuss
https://support.allizom.org/en-US/kb/new#preview
https://support.allizom.org/en-US/kb/jquery-update
https://support.allizom.org/en-US/user/Verdi


@akatsoulas I was able to create a couple new [articles](https://support.allizom.org/en-US/kb/verify-new-article/history#preview)  with no issues without using the toggle syntax highlight.  Maybe there were some specific conditions under which you encountered this issue? 

Also, I have thought about it and there still is a fair amount of testing to be done, about as much as was done by now, so leaving the release for the week after next would be best, to account for the testing needed to confirm and bug fixes as well.

**Comment by mirunacurtean** [comment]
Another update with areas tested. Focus was on articles and Forum threads. 

https://support.allizom.org/en-US/forums/contributors/712963/edit
- cancel/ update
https://support.allizom.org/en-US/kb/search-working-article-test/discuss/new#post-preview
https://support.allizom.org/en-US/kb/search-working-article-test/discuss/7478#post-preview
https://support.allizom.org/en-US/kb/search-working-article-test/edit 
- update summary
-Update content
-preview changes/ content
- Submit/ notify me of changes 
https://support.allizom.org/en-US/kb/search-working-article-test/history
-show helpfulness chart
https://support.allizom.org/en-US/kb/search-working-article-test/compare?locale=en-US&from=157613&to=157462
-Back to history
https://support.allizom.org/en-US/kb/search-working-article-test/links

https://support.allizom.org/en-US/forums/watch-and-notify/712964
https://support.allizom.org/en-US/forums/watch-and-notify/712964/edit
 
Only https://github.com/mozilla/sumo/issues/1089 might be a jquery caused issues.

**Comment by mirunacurtean** [comment]
The latest batch of pages tested. No particular jquery caused issues found. 

https://support.allizom.org/en-US/products/contributor
https://support.allizom.org/en-US/get-involved/kb
https://support.allizom.org/en-US/kb/category/60
https://support.allizom.org/en-US/kb/category/60?page=2
https://support.allizom.org/en-US/kb/revisions?page=7

https://support.allizom.org/en-US/kb/plushies-are-awesome-test-wildcard-test?redirectslug=plushies-are-awesome-test&redirectlocale=en-US

Should the links to the Contributions for the deactivated account be redirecting to Page not found?
https://support.allizom.org/en-US/user/user1470091


https://support.allizom.org/en-US/badges/
a 404 on of the the badges- probably image no longer found  on stage 


https://support.allizom.org/es/kb/plushies-are-awesome-test-wildcard-test/translate
https://support.allizom.org/es/kb/plushies-are-awesome-test-wildcard-test/translate#preview
https://support.allizom.org/es/kb/titulo-en-easpanol/history#preview
https://support.allizom.org/es/kb/titulo-en-easpanol/compare?locale=es&to=157675&from=157674


https://support.allizom.org/es/community/top-contributors/kb
https://support.allizom.org/es/community/?product=firefox
https://support.allizom.org/es/community/top-contributors/l10n
https://support.allizom.org/es/community/top-contributors/l10n?product=firefox&locale=de
https://support.allizom.org/es/community/top-contributors/questions
https://support.allizom.org/es/contributors
https://support.allizom.org/es/community/top-contributors/kb?product=firefox

https://support.allizom.org/en-US/flagged/
Logged as moderator/ superuser
- view, edit, delete, update

https://support.allizom.org/en-US/questions/1207073#answer-1082917 

- Unmark spam
- Add/ preview/ edit common response 
- Add tag
- Edit system details

https://support.allizom.org/en-US/questions/1207073/delete

**Comment by mirunacurtean** [comment]
I've verified the fix for the Toogle syntax issue and did a quick sanity check.
Adding questions, question forums, community discussions and tools, article edit, review and translate, community hub ans media gallery. 
I did not see any other issues, so my recommendation for next week's release is to resolve https://github.com/mozilla/sumo/issues/1085 as well and then it can proceed.
