### ISSUE TITLE
[SUMO]  Rework  locale-specific shortened link

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1082]
**Is your feature request related to a problem? Please describe.**
No locale specific shortlinks in KB articles
Copied from https://github.com/mozilla/sumo/issues/1065#issuecomment-120912302:
" There are a few things I'd like to clarify after I tested this: 
* I found that the link is locale-specific. I'm not sure if this was intended. The thing with this is that, contributors often share the shortened link to users, which may use a different locale. With regards to this scenario, it's actually better to use a locale-agnostic link so users will be directed to their preference locale automatically. This being said, this will require a different approach, which is, that we will have the same shortened link for the same article in different locales. 
* Regardless of the above point, I found that the current automation doesn't work for Indonesian locale. For example: [this article](https://support.allizom.org/id/kb/instalasi-firefox-pada-ipad-iphone-atau-ipod-anda) (for comparison, this is the same article for [de](https://support.allizom.org/de/kb/firefox-auf-dem-ipad-iphone-oder-ipod-installieren), [fr](https://support.allizom.org/fr/kb/installer-firefox-sur-ipad-iphone-ipod), or [ko](https://support.allizom.org/ko/kb/install-firefox-your-ipad-iphone-or-ipod)). I haven't tested all locales, but out of 15 locales that I tested, this only happen with id locale. "

**Describe the solution you'd like**
Locale specific shortlinks in Kb articles. 

**Describe alternatives you've considered**
TBD.

**What is the requested timeline for completion?**
TBD.

**Who is the audience**
Contributors who use and read articles. 
No administration category articles, because users can get to those from in product links. 

**Applicable resources**
TBD.

**Comment by kelimuttu** [comment]
@mirunacurtean This issue title is a bit confusing, since the intention here should be to remove locale-specific shortened link. 

The goal here should be to make the shortened link locale-agnostic. As I mentioned in https://github.com/mozilla/sumo/issues/1065, it requires us to use a different approach, which is using the same link for the same article in the different locales. So, the reference here should be the link of the English KB without the locale code. That way, users will be directed to their preference locale automatically. 

The locale redirection will not work with non-EN KB article link. For example, 
if you go to https://support.mozilla.org/id/kb/troubleshoot-time-errors-secure-websites (note that we're using id locale code here), you'll be redirected to the translated version: https://support.mozilla.org/id/kb/mengatasi-galat-terkait-waktu-pada-situs-aman. However, if you change the locale code of a translated article, for example: https://support.mozilla.org/en-US/kb/mengatasi-galat-terkait-waktu-pada-situs-aman (note that we're using en-US here as opposed to id), you will get "page not found" error message. 

I hope I explained it better this time.

**Comment by escattone** [comment]
@kelimuttu That explains the locale issue with short links perfectly, thanks so much!

**Comment by mirunacurtean** [comment]
I can confirm that now https://support.mozilla.org/id/kb/troubleshoot-time-errors-secure-websites redirects to an english content article while https://support.allizom.org/en-US/kb/mengatasi-galat-terkait-waktu-pada-situs-aman is still Page not Found. 
@kelimuttu Can you take a look and see if you can spot any issues?

**Comment by kelimuttu** [comment]
The Parent doc shortened link: http://mzl.la/15sSfJR (works)
DE version: http://mzl.la/1OGsvM6 (doesn't work)
FR version: http://mzl.la/1SGjNOX (doesn't work)

It seems that the function is still returning the locale slug instead of the parent slug.

**Comment by mirunacurtean** [comment]
> The Parent doc shortened link: http://mzl.la/15sSfJR (works) DE version: http://mzl.la/1OGsvM6 (doesn't work) FR version: http://mzl.la/1SGjNOX (doesn't work)
> 
> It seems that the function is still returning the locale slug instead of the parent slug.

Thank you for looking into this. 
These examples are on production where nothing should have changed yet, since the work done here has not been release. 
However, I can reproduce this on stage with the translated articles of the [en-us](https://support.allizom.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) version. 
[DE article](https://support.allizom.org/de/kb/firefox-bereinigen)  and [shortlink](http://mzl.la/1OGsvM6). 
[Fr article](https://support.allizom.org/fr/kb/reinitialiser-firefox-restaurer-modules-parametres) and [shortlink](http://mzl.la/1SGjNOX).

The links in the example below, for FR, DE and KO all redirect to the english article in production.
 * Regardless of the above point, I found that the current automation doesn't work for Indonesian locale. For example: [this article](https://support.allizom.org/id/kb/instalasi-firefox-pada-ipad-iphone-atau-ipod-anda) (for comparison, this is the same article for [de](https://support.allizom.org/de/kb/firefox-auf-dem-ipad-iphone-oder-ipod-installieren), [fr](https://support.allizom.org/fr/kb/installer-firefox-sur-ipad-iphone-ipod), or [ko](https://support.allizom.org/ko/kb/install-firefox-your-ipad-iphone-or-ipod)). I haven't tested all locales, but out of 15 locales that I tested, this only happen with id locale. "

@escattone Above are the test results based on Kiki's examples and I guess I'm still a bit confused. I understand that generated shortlinks in stage point to production from this cases, so that is not the issue. but why does one series of test results get the redirect to en-us article and the first one to a page not found?

**Comment by kelimuttu** [comment]
> Regardless of the above point, I found that the current automation doesn't work for Indonesian locale. 

I filed another bug report for this. See https://github.com/mozilla/sumo/issues/1096

**Comment by mirunacurtean** [comment]
> > The Parent doc shortened link: http://mzl.la/15sSfJR (works) DE version: http://mzl.la/1OGsvM6 (doesn't work) FR version: http://mzl.la/1SGjNOX (doesn't work)
> > It seems that the function is still returning the locale slug instead of the parent slug.
> 
> Thank you for looking into this. These examples are on production where nothing should have changed yet, since the work done here has not been release. However, I can reproduce this on stage with the translated articles of the [en-us](https://support.allizom.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) version. [DE article](https://support.allizom.org/de/kb/firefox-bereinigen) and [shortlink](http://mzl.la/1OGsvM6). [Fr article](https://support.allizom.org/fr/kb/reinitialiser-firefox-restaurer-modules-parametres) and [shortlink](http://mzl.la/1SGjNOX).
> 
> The links in the example below, for FR, DE and KO all redirect to the english article in production.
> 
> * Regardless of the above point, I found that the current automation doesn't work for Indonesian locale. For example: [this article](https://support.allizom.org/id/kb/instalasi-firefox-pada-ipad-iphone-atau-ipod-anda) (for comparison, this is the same article for [de](https://support.allizom.org/de/kb/firefox-auf-dem-ipad-iphone-oder-ipod-installieren), [fr](https://support.allizom.org/fr/kb/installer-firefox-sur-ipad-iphone-ipod), or [ko](https://support.allizom.org/ko/kb/install-firefox-your-ipad-iphone-or-ipod)). I haven't tested all locales, but out of 15 locales that I tested, this only happen with id locale. "
> 
> @escattone Above are the test results based on Kiki's examples and I guess I'm still a bit confused. I understand that generated shortlinks in stage point to production from this cases, so that is not the issue. but why does one series of test results get the redirect to en-us article and the first one to a page not found?

Confusion resolved. This is due to tetsing being performed on old articles. The new shortlinks are not being applied to the old articles, only new ones. 

See [share this article](https://support.allizom.org/en-US/kb/share-article) and its [ro](https://support.allizom.org/ro/kb/distribue-acest-articol), [de](https://support.allizom.org/de/kb/teile-diesen-artikel) and [ko](https://support.allizom.org/ko/kb/%EC%9D%B4%20%EA%B8%B0%EC%82%AC%EB%A5%BC%20%EA%B3%B5%EC%9C%A0) translations. All translated article shortlinks redirect to the original en-us article. 
Setting this one as ready for release.
