### ISSUE TITLE
Revision Content for "Edit Article based on this revision" does not show until Toggle syntax highlighting is selected 

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1089]
**Describe the bug**
Using the article editing tool "Show history" we can see current, unreviwed, approved and previous versions of the article. 
By selecting a revision link from under that same name column, we can see that exact revision summary, content and so on. 
In that revision page, an Edit article based on this revision link is enabled. Using it will redirect to  an editibale version of that revision, however the content of it is blank until syntax highlighting is enabled.

**To Reproduce**
1. Go to https://support.allizom.org/en-US/kb/search-working-article-test/history
2. Click on [Feb 1, 2017, 7:57:56 PM](https://support.allizom.org/en-US/kb/search-working-article-test/revision/139143)
3. Scroll down to Revision Source and Revision Content and select to open them and view the content.
4. View [Edit article based on this revision](https://support.allizom.org/en-US/kb/search-working-article-test/edit/139245)
5. Select that link and then scroll to Content table. 

**Expected behavior**
The Text in the Revision Source from step 3 is available to be edited 

**Actual behavior**
The Content secction is blank until syntax highlighting has been seelcted.

**Screenshots**
![Toggle syntax highlights](https://user-images.githubusercontent.com/53306802/186122883-d8b1b938-e5f1-43ce-b628-e958f4f63a98.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Twice, it seemed not to occur on more recent revisions, but I cannot reproduce this at the moment and I only get blank sections for all attempts to edit revisions.  Maybe there's a nother trigger that I cannot figure out at the moment. 

Also, I could not reproduce the issue in production using the same [article](https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox/history) so this could be a result of the recent updates.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5212

**Comment by mirunacurtean** [comment]
Just an update with another example to verify for confirmation testing. This also occurs when trying to edit a translated version of an article. 

![Toogle syntax in trasnalted articles](https://user-images.githubusercontent.com/53306802/187900011-a6398f0c-8f00-4832-b514-73404ed172eb.gif)

**Comment by mirunacurtean** [comment]
Verified fixed for en-us editing and translations. 
![Toogle syntax confirmed fix](https://user-images.githubusercontent.com/53306802/188115961-1fe1496c-d96e-4f14-9b6f-20f7f27dbae2.gif)

Non-English locale test. 
![Toogle syntax confirmed fix](https://user-images.githubusercontent.com/53306802/188116666-db115398-d1f7-4364-8f3a-c8ff2873eea9.gif)

Verified on Firefox and Chrome.
