### ISSUE TITLE
Youtube "Video unavailable- This video is private"

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1090]
**Describe the bug**
On  https://support.mozilla.org/en-US/kb/how-does-support-localization-work article the youtube videos cannnot be watched and the redirect launches the youtube homepage. 

**To Reproduce**
1. Login with a contributor account (I also logged in with one that was part of a localisation group and other moderator groups)
2. Go to https://support.mozilla.org/en-US/kb/how-does-support-localization-work
3. Scroll down to the youtube videos
5. See that they are not available to be watched. 

**Expected behavior**
Working videos. 

**Screenshots**
![image](https://user-images.githubusercontent.com/53306802/186738844-37455624-f9e8-48ac-9a7d-d4812c73245a.png)

**Desktop (please complete the following information):**
 - OS: Windwos
 - Browser Firefox, Chrome

**Additional context**
Also occurs on [production](https://support.mozilla.org/en-US/kb/how-does-support-localization-work).

**Comment by akatsoulas** [comment]
This resides on the content side and it's not a functional problem. Closing the issue
