### ISSUE TITLE
Copy update - contributor onboarding email

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1104]
**Describe the bug**
In line with the contributor onboarding project, we would like to update the copy of our contributor onboarding email that we sent when a user signed up as a contributor to align with the latest experience.

Updated copy is coming up as we're still finalizing [a new name for the Mobile Support program](https://support.mozilla.org/en-US/forums/contributors/715982?last=84256).

**Comment by mirunacurtean** [comment]
@kelimuttu Is this the correct new copy? Currently this is what I am receiving in stage in the process of creating a new account through the Onboarding flow. 
![image](https://user-images.githubusercontent.com/53306802/198589218-5243cf68-6000-4aa7-8a18-4907a1d8486b.png)

**Comment by kelimuttu** [comment]
Hi @mirunacurtean , 

I just shared the copy document to you. You should get that email after you sign up as a contributor from one of the contribution area in the [Contribute page](https://support.allizom.org/contribute).

**Comment by mirunacurtean** [comment]
This will have to be tested on production since we did not have the setup in place at the moment to test emails in stage, or to sign up through the contributor path in dev.

**Comment by kelimuttu** [comment]
Aah, I will see if I can test from my side as well. Thanks for your note, Miruna!

**Comment by mirunacurtean** [comment]
I can confirm receiving the onboarding email after signup through the Contributor path and it matches the copy, all links are working as expected. The only thing I wouls be nitpicky about would be:
1.  having the same bold text from the copy, showing as such in the email as well
2. Adding a Colon after :There are many ways you can contribute to SUMO" 
but if that is needed, we can create another ticket. 
![image](https://user-images.githubusercontent.com/53306802/199790738-88020854-f9b0-4228-b060-783682699f34.png)
