### ISSUE TITLE
Add a preference in user profiles to select contribution areas/groups

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1112]

**Comment by mirunacurtean** [comment]
@akatsoulas Should these contribution area preferences, when applied, provide additional permissions as well? I can confirm adding changes made in sumo reflect in admin chosen groups, but are there any other areas of sumo that these group changes should be reflected in?

**Comment by mirunacurtean** [comment]
Confirmed:

- an "Edit contribution area" is listed in the user profile where new useres that sign up through the onboarding flow get their area of contribution checked, or older users can manually select an area
- My profile contains a Groups section in which the same contribution area group name as in "edit..."  is listed 
- these groups are added in the admin side as well
