### ISSUE TITLE
Migrate contributors to new groups

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1113]
When an existing contributor picks a contribution area from their profile, we will need to remove them from the old groups.

**Comment by mirunacurtean** [comment]
@akatsoulas Where do I find the list with the old groups? Are there any exceptions - like Adminstrators?
![New contribution area and old groups](https://user-images.githubusercontent.com/53306802/198596980-b5b01319-b177-48c9-9d83-101237ad711d.gif)

**Comment by akatsoulas** [comment]
Old groups here are considered only `Contributors` and `Trusted Contributors`
