### ISSUE TITLE
A border shows around the page header when first loading the page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1117]
**Describe the bug**
H1 headers display a border when first loading acordss [contribution](https://support.allizom.org/en-US/contribute) pages. 

![border](https://user-images.githubusercontent.com/53306802/196133643-893d8103-bd05-4a6f-8ed4-7682e1de62b5.gif)

**Comment by akatsoulas** [comment]
This is actually the intended behavior to indicate which component has the focus for accessibility reasons. We can hide that by applying:
```css
*:focus-visible {
  outline: none;
}
```
but I believe there is some value in keeping that highlight. Thoughts?

**Comment by mirunacurtean** [comment]
To my understanding in regards to acessibility it was enough to have headings labeled so that a screen reader could identify them, and not for them to be visually distinct. I have not encountered this case before, but if it's intended, then I don't have the knowledge to propose a better solution.
