### ISSUE TITLE
URL path displayed in the last content div

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1118]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53306802/196134693-fd65f788-841f-41f8-b8bc-c4e748d13a3d.png)

**Comment by akatsoulas** [comment]
Similar to the issue with the focused area, this is used to announce navigation to a screen reader. Any thoughts on it?

**Comment by mirunacurtean** [comment]
I would have expected it to be hidden, visually, but since it's intended I have no other suggestions.
