### ISSUE TITLE
Logout doesn't keep the user on the same page

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/sumo#113]
**STR:** 
Login to sumo staging
Navigate to search page (https://support.allizom.org/en-US/search)
Click Logout

**Expected:**
Search page should be returned (https://support.allizom.org/en-US/search)

**Actual:**
Homepage is returned (https://support.allizom.org/en-US/) 

**Note:**
1. Same happens for other pages, like
- [advanced search](https://support.mozilla.org/en-US/questions)
- [questions](https://support.mozilla.org/en-US/questions)
2. This seems related to https://github.com/mozilla/kitsune/issues/3569. Also, it is not happening in prod.

**Comment by mirunacurtean** [comment]
Update: The logout from search or questions pages redirecting back to homepage occurs in stage and production. 
@akatsoulas At this point the current behavior is to redirect the user back to homepage when logging out so what needs to be confirmed is if staying on the current page after logout is still the preferred behavior.
