### ISSUE TITLE
Unnecessary text in the new contribute page

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1136]
**Describe the bug**
Unnecessary text is present in the new contribute page

**To Reproduce**
1. Go to the new contribute page or the individual contribution area page.
2. Scroll to the bottom.
3. See the "Navigated to /" text in the bottom-left corner of the page.

**Expected behavior**
No text 

**Screenshots**
![gambar](https://user-images.githubusercontent.com/4922388/200373762-09ee7a3f-a31f-4530-b977-d014b7041be1.png)

**Comment by emilghittasv** [comment]
It seems that this issue was fixed along the way. I'm unable to reproduce it on both stage & production environments. 

Verified on both desktop (Firefox, Chrome & Edge) and mobile (Android - Huawei P40 Pro) 

@kelimuttu feel free to re-open this ticket if this is still occurring for you!
