### ISSUE TITLE
"reload_question_traffic_stats" bug

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1140]
The `./manage.py reload_question_traffic_stats` command, which is run on a cron schedule, fails most of the time, but not always. It's using the new `GA_KEY` and `GA_ACCOUNT`.

**Comment by escattone** [comment]
When I run it locally, with `verbose=True`, I see the following:
```
Fetching data for 2022-08-20 to 2022-11-18:
- Got 10000 of 1000000 results.
- Got 20000 of 1000000 results.
- Got 30000 of 1000000 results.
- Got 40000 of 1000000 results.
...
```
The request is for a year's worth of results, and it seems to be limited at 1 million results.

It seems that the command is running in production, but perhaps takes so long that something happens before it can finish.

**Comment by akatsoulas** [comment]
I believe that command was limited to the last year or so. Is there any chance that we missed that range with the upgrade of the oauth lib?

**Comment by akatsoulas** [comment]
@escattone is this solved?

**Comment by escattone** [comment]
@akatsoulas It does report to its Snitch sometimes, but not every day as it should, so I don't think it's resolved yet. I think the next step is to add some logging to get some visibility into what's happening.

**Comment by escattone** [comment]
https://sentry.io/share/issue/32f7caa62355453f93f30822d4b74049/

<img width="954" alt="image" src="https://user-images.githubusercontent.com/3743693/211388717-78acfb20-b877-44af-9c93-6867aae5e5f6.png">

**Comment by escattone** [comment]
This bug should be resolved with https://github.com/mozilla/kitsune/pull/5973.
