### ISSUE TITLE
Terminology update

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1142]
**Describe the bug**
Change "support article" terminology to "help article" as per Abby suggestion based on industry known term. 

**To Reproduce**
1. Go to https://support.mozilla.org/contribute/kb

**Expected behavior**
Change the terminologies in the following section of the page: 
| Section | Old copy | Updated copy |
| --- | ----------- | ----------- |
| Breadcrumb | Support articles | Help articles |
| Header | Help us write support articles | Help us write help articles |

**Comment by mirunacurtean** [comment]
![image](https://user-images.githubusercontent.com/53306802/205964462-5a1ef91f-b220-41a9-b4e5-19f2c5b10935.png)
