### ISSUE TITLE
Remove trailing slash from messages urls.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1158]
https://github.com/mozilla/kitsune/pull/5336

**Comment by mirunacurtean** [comment]
@smithellis IF I understand this correctly, does it mean that besides new/sent/delete/bulk sections, shouldn't the trailing slash be removed from the inbox url as well? 
![image](https://user-images.githubusercontent.com/53306802/211513673-50ec6b5d-f97a-4f54-8edf-44f5af9b2b1b.png)

**Comment by smithellis** [comment]
Ah, I see the source of confusion.  @mirunacurtean The task for me was to clean up the routes in the urls.py file by removing the *leading* slash, not the trailing. In some cases a trailing slash had to be added to certain routes, but that would be rare.  So if existing routes/urls/clickstreams still work in the messages section, then trailing slash isn't the critical check.

**Comment by mirunacurtean** [comment]
Great, thank you, then I can move this to Ready for Release.
