### ISSUE TITLE
str decoding bug in dashboards

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1168]
https://sentry.io/share/issue/2d042b9659ce4c4d95e9f73a77593d48/

<img width="940" alt="image" src="https://user-images.githubusercontent.com/3743693/211381593-e3318af5-b46a-4863-9bde-fed14f414fad.png">

**Comment by mirunacurtean** [comment]
![image](https://user-images.githubusercontent.com/53306802/212853980-f6769d76-522e-4a14-b405-bd8ce08d42c5.png)
