### ISSUE TITLE
update all Python related dependecies

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1181]
Update all of the following:
- [x] CircleCI Docker and remote Docker images in `.circleci/config.yml`
- [x] All poetry dependencies -- only update `elasticsearch` to latest version `7` (the upgrade to version `8` is a separate task
- [x] Update to latest Python 3.11
- [x] Update to latest `pip`
- [x] Update versions in `.pre-commit-config.yaml` to match poetry

**Comment by escattone** [comment]
# QA Notes
(cc @mirunacurtean)
This can only be tested via a general test of the entire site.

**Comment by mirunacurtean** [comment]
So far I have navigated AAQ, support and discussion forums, articles, tools, profile and messages with regular, moderator and superusers accounts and have encountered no new issues.
