### ISSUE TITLE
upgrade @mozilla-protocol/core to version 16

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1182]
Upgrade Node.js package `@mozilla-protocol/core` to version `16` ([changelog](https://github.com/mozilla/protocol/blob/main/CHANGELOG.md))

**Comment by emilghittasv** [comment]
The a/b testing session for protocol is done. 

During this testing session, [3](https://github.com/mozilla/sumo/issues?q=1237+1236+1239) protocol-related issues were encountered.

[2 out of 3](https://github.com/mozilla/sumo/issues?q=1236+1239) issues were verified as fixed and only [1237](https://github.com/mozilla/sumo/issues/1237) remains reproducible.

@akatsoulas @escattone The only protocol-related ticket which remains open is the increased font-size for the top-navbar h4 elements. If we decide to go with this increase in font-size, this ticket can be marked as ready for release.

Testing activities were performed on:
- Desktop: Windows 10 & macOS
- Browsers: Chrome, Firefox & Safari
- Mobile: OnePlus 7T (physical device) & iPhone 13Pro (Simulator)
- Browsers: Firefox (Android) & Safari (iOS)
