### ISSUE TITLE
Use an m2m field for Announcement.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1195]
This change will allow Announcement to target multiple groups at once. The announcement should be displayed to users once regardless if they belong to multiple groups. This affects only logged in users.

Additional requirements:
- Remove current ForeignKey
- Migrate data from the ForeignKey to the new m2m field

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5407

**Comment by escattone** [comment]
# QA Notes
- Create an announcement on the stage site via the admin console (https://support.allizom.org/admin/announcements/announcement/add/)
    - Add some content
    - Add two or more groups (may want to create two or more groups and add a unique user for which you control their email address to each group)
    - Click the `Send email` checkbox
    - Save
- Verify that all of the users in all of the groups received emails
- Create another announcement and verify that if the `Send email` checkbox is unchecked, no emails are sent

**Comment by escattone** [comment]
Just FYI, I successfully verified all of the QA tests above locally. ✅ 🎉
