### ISSUE TITLE
Users view is not automatically moved to the top of the search result list when interacting with the pagination elements

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1206]
**Describe the bug**
When interacting with the pagination elements from the search results page, the user's view remains at the bottom of the search result list and they have to perform an extra step of manually scrolling to the top of the list.

**To Reproduce**
1. Go to https://support.mozilla.org/en-US/products/firefox?as=u&utm_source=inproduct
2. Type anything inside the search bar that has many results (which triggers pagination)  (ex: "delete")
3. Scroll to the bottom of the search results and click on the next page of results.

**Expected behavior**
The next page of results is displayed and the page automatically brings the user to the top (in order to see the list from the beginning).

**Actual behavior**
The next page of results is displayed but the users view remains positioned at the bottom of the list

**Screencast**
![scrollRemainsAtBottom](https://user-images.githubusercontent.com/28087895/223090675-40280fae-2d66-4abb-98bd-04d57bcbc2e7.gif)

**Desktop:**
   - OS: Windows 10 64bit
   - Browser Firefox 110.0 & Chrome 110.0.5481.178

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox 110.0.1

**Additional context**
Originally filled in https://bugzilla.mozilla.org/show_bug.cgi?id=1745509

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6329

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The user view is automatically moved at the top after interacting with the pagination elements.

Moving this ticket inside the `release` column.
