### ISSUE TITLE
The view gets automatically scrolled above the targeted fragment identifier on some KB articles

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1213]
**Describe the bug**
Sumo seems to have a hiccup with fragment identifiers when some page content (like images) is being loaded after the desired section of the page thus scrolling the user's view higher than desired.

**To Reproduce**
1. Go to https://support.mozilla.org/en-US/kb/relay-integration#w_frequently-asked-questions (or SHIFT + refresh the page if already visited).

**Expected behavior**
The user's view is targeting the "Frequently asked questions" section without having them to manually scroll down to the desired section.

**Actual behavior**
The user's view is scrolled above the desired section ("Frequently asked questions"). 

**Screencast**
**Firefox:**
![FirefoxFragment](https://user-images.githubusercontent.com/28087895/223985855-7becd38c-4ec3-4bd8-b2ba-6a1b5c3854aa.gif)

**Chrome:**
![ChromeFragment](https://user-images.githubusercontent.com/28087895/223985949-30bca5af-8f22-4da5-9e2e-5505acd16fc5.gif)

**Desktop:**
 - OS: Windows 10 64bit & macOS 11
 - **Reproducible on:** Firefox 110 & latest nightly. 
 - **Not Reproducible on:** Safari 16.3 not reproducible & Chrome 111.0.5563.65 

**Smartphone:**
 - Device: Huawei P40Pro
 - **Reproduced on:** Firefox 110.0.1

**Additional context**
- This issue seems to be reproducible on Firefox browsers (on other browsers this issue is not reproducible or the scroll is not performed that far away from the targeted section). 
- I tried searching for a Firefox regression (in order to pinpoint that this might be a Firefox-related issue) but I managed to reproduce this issue with builds from 2019 as well.
- This issue is reproducible on other page fragments as well (https://support.mozilla.org/en-US/kb/troubleshoot-time-errors-secure-websites#w_set-your-system-clock-to-the-correct-time) in which images are present above the targeted content.
- On a second, normal refresh, this is not reproducible because those images are cached. If we disable caching and reload the page, this issue is always reproducible.
- It does seem that the page is initially at the correct spot (#w_frequently-asked-questions) but after that, we load the images and the view moves away from that fragment.
- I've noticed that this seems to happen if the content targeted by the fragment identifier is placed below the images that are about to be loaded (maybe this happens due to a page reflow?)

**Comment by emilghittasv** [comment]
I'm getting mixed results for the https://support.allizom.org/en-US/kb/relay-integration#w_frequently-asked-questions link.

I have disabled cache from the network tab via dev tools and I've noticed that:
* Sometimes the page loads just fine with the view being positioned correctly on the fragment identifier.
* Sometimes the view is a bit above the "Frequently asked questions" section.
* Sometimes the view is misplaced totally.

In order to replicate I have opened the above link in multiple new browser tabs.

Screencast:
![totally](https://github.com/mozilla/sumo/assets/28087895/2512450b-c1e4-4ac8-b380-c0a8253620ee)

**Comment by escattone** [comment]
@emilghittasv With https://github.com/mozilla/kitsune/pull/5544 merged, I'm seeing consistent results now for the https://support.allizom.org/en-US/kb/relay-integration#w_frequently-asked-questions link.

**Comment by emilghittasv** [comment]
@escattone, @smithellis. Unfortunately, I'm still getting mixed results.

The good news is that I'm no longer reproducing the "Sometimes the view is a bit above the "Frequently asked questions" section." symptom!

I'm still reproducing the symptom in which the view is totally misplaced if I'm opening the  https://support.allizom.org/en-US/kb/relay-integration#w_frequently-asked-questions  page several times in new browser tabs.

I'm going to mark this ticket as partially fixed and track the still reproducible symptom in https://github.com/mozilla/sumo/issues/1335 

I think that we can move this ticket inside the Ready for Release column.
