### ISSUE TITLE
Consider expanding our product download links 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1225]
**Description**
Currently, we have download links for: 
- Firefox (when the SUMO page is visited via a non-Firefox browser)
- Thunderbird

**Proposal**
Note: Please feel free to add different links for products if others are more appropriate. 

We should consider expanding that list by adding download links for our other products as well:
- Firefox for Enterprise (link redirects to: https://www.mozilla.org/en-US/firefox/enterprise/) 
- Firefox Focus (link redirects to: https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/)
- Firefox for Android (link redirects to: https://www.mozilla.org/en-US/firefox/browsers/mobile/android/)
- Firefox for iOS (link redirects to: https://www.mozilla.org/en-US/firefox/browsers/mobile/ios/)

Also, maybe we could add a link/button like "Check out <product_name>" ,in order to help users find the product page with more ease, for our other products like:
- Hubs (link redirects to: https://hubs.mozilla.com/)
- MDN plus (link redirects to: https://developer.mozilla.org/en-US/plus)
- Firefox Relay (link redirects to: https://relay.firefox.com/)
- Mozilla VPN (link redirects to: https://www.mozilla.org/en-US/products/vpn/)
- Firefox Monitor (link redirects to: https://monitor.firefox.com/)
- Firefox Private Network (link redirects to: https://fpn.firefox.com/)

**Comment by akatsoulas** [comment]
With the latest changes there is no plan to work on the UX to make this possible.
