### ISSUE TITLE
Consider changing the backend logic applied to when closing an account via the "Close account and delete all profile information" option

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1228]
Currently, when a user closes their account via the "Close account and delete all profile information" option from the https://support.allizom.org/en-US/users/edit page, the following things seem to happen:

1. We keep the user id saved and map the previous posts (which the user made before closing their account) to that particular id. Example: user250618756319108692945522609979745436832  -> https://support.allizom.org/en-US/questions/1207323#answer-1084009.
2. At Kitsune admin panel level, the user is deleted/replaced by the userid -> https://support.allizom.org/admin/auth/user/1470448/change/?_changelist_filters=q%3Duser250618756319108692945522609979745436832. Anonymizing their e-mail address as well.

So this process seems to be destructive in terms that we fully anonymize the account without the ability to recover.

There are some cases in which this logic might bring some limitations or even risks:

**Limitations**:
We are not providing the user an option to re-open that previously closed account. There are situations in which a user, for different reasons, might want to re-open their closed account and start contributing again using the same account, history, achievements/badges, conversation history,etc.

So, currently if:
1. The user closes their account via the "Close account and delete all profile information" option.
2. Logs in with the same FxA credentials to SUMO 

He will notice at step 2 that a new instance/ a fresh profile is created rather than re-activating the previous profile.

**Risks**
I've noticed that an abusive user can take profit from this situation by performing the following steps:
1. Opens a profile using an FxA account.
2. Posts some abusive content (example: replies to questions).
3. Closes the SUMO profile via the "Close account and deletes all profile information" option.
4. Opens a fresh instance/new profile with the same FxA account.
5. Posts some abusive content again.

Since the previous abusive posts are mapped to their previous userID, I'm not if admins can easily find and ban the actual culprit (the email linked to that abusive FxA account) via the kitsune admin panel.

**Proposal**
- Consider keeping that previous SUMO profile in our DB linked to the FxA account.
- Consider keeping the account, of course, in a deactivated state (also their posts should have their display name or username followed by (deactivated). Example: eghitta (deactivated).
- When the user Logs in with the same FxA credentials, the account is re-opened.

**Comment by akatsoulas** [comment]
There is an effort to change how we are handling the closing of user accounts that will start next sprint.
