### ISSUE TITLE
Articles with a long search result summary are overlapping the "Filter by product" section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1229]
**Describe the bug**
Articles that contain a long search result summary are overlapping the "Filter by product" section on the search results page.

**To Reproduce**
1. Go to https://support.allizom.org/en-US/kb/new.
2. Inside the "Search result summary" filed add a long text (ex: `How to sync your tests accounts 
wdwaawfawfawfawfcascvasvdsfhsdghbsdghjdsbgjhdsbgjdsbjghbsdhjgbdsjhgbdsjhgbsdjhbgsjhdbgjshdbgjshdbghjsdbgjhsdbgjhsdbgjhsdbgjhsd`)
3. Complete the required fields and submit the article.
4. Inside the "Find Help" searchbar search for the article name.

**Expected behavior**
No UI issues are displayed.

**Actual behavior**
The search result summary overlaps the "Filter by product" section.

**Screenshot**
![image](https://user-images.githubusercontent.com/28087895/228575590-94a2034a-2218-461d-a792-d7bc9f6205f1.png)

**Desktop:**
 - OS: Windows 10 64bit
 - Browser: Firefox & Chrome

**Smartphone:**
- Phone: Huawei P40Pro
- Browser: Firefox

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6343

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
