### ISSUE TITLE
[Protocol] Paragraph tags no longer have margin-bottom applied

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1236]
**To Reproduce**
1. Go to https://support.allizom.org/en-US/
2. Navigate to the page footer.

**Expected behavior**
The `<p>` tags contain  `margin: 0 0 1.25em` as in `prod`

**Actual behavior**
The `<p>` tags contain `margin 0 and padding 0` on `stage`

**Screenshots Desktop**
**Stage Environment**
![image](https://user-images.githubusercontent.com/28087895/229775679-3546b424-dfb0-4f19-a691-bb726b63693c.png)

**Prod Environment**
![image](https://user-images.githubusercontent.com/28087895/229775757-2b1f8658-53cd-41e6-a540-2479ce0bf2f1.png)

**Screenshots Mobile**
**Stage Environment iOS**
![image](https://user-images.githubusercontent.com/28087895/229775824-5561d8d2-9d9f-4b31-aadb-9398efb5486b.png)

**Stage Environment Android**
![image](https://user-images.githubusercontent.com/28087895/229775939-c63fd8c1-69d3-48a0-be3f-ea1c3ebb908c.png)

**Prod Environment**
![image](https://user-images.githubusercontent.com/28087895/229776025-f61f70a6-43b8-42ad-9ed9-5bb2faa73533.png)

**Desktop:**
 - OS: Windows 10 64bit and macOS 11.7.4
 - Browser: Firefox 111.0.1, Chrome 111.0.5563.147, Safari 16.3

**Smartphone:**
- Device: Huawei P40Pro, Firefox 110.0.1
- Device: Pixel 7, Chrome 111.0.5563.116
- Device: iPhone 13 Pro, Safari 14

**Additional context**
- Reproducible only on stage env.  
- Since this affects a broader part of the SUMO page, I've tracked the encountered areas/sections by this change in https://docs.google.com/document/d/1Dr6w7WiL6kB0JXK2iQxKSc5I_VAMrL-mBzmajzvjyGA/edit?usp=sharing

**Comment by escattone** [comment]
This appears to be due to a change introduced in [`@mozilla-protocol` version 14.0.2 that removed the bottom padding for the last element in a container](https://github.com/mozilla/protocol/blob/main/CHANGELOG.md#bug-fixes-8), which applies, for example, to the case of the "Pick your product" paragraph:

```html
<div class="text-center-to-left-on-large">
      <h2 class="sumo-page-subheading">Get Help</h2>
      <p class="sumo-page-intro">Pick your product</p><p class="sumo-page-intro">Pick your product</p>
</div>
```

**Comment by emilghittasv** [comment]
This issue is verified fixed on stage env.

The `p` tag has the `margin: 0 0 1.25em;` applied and the mentioned UI issues (in this ticket + in the Gdoc) are no longer reproducible.

Tested on:
- Desktop: Windows 10 & macOS
- Browsers: Firefox, Chrome & Safari
- Mobile: OnePlus 7T & iPhone 13Pro
- Browsers: Firefox & Safari

This ticket can be marked as ready for release.
