### ISSUE TITLE
Preserve incoming query parameters on in-product links

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1246]
Query parameters (for example, UTM parameters) on in-product links should be preserved, or in other words, passed through to their targets. This is necessary for tracking purposes.

Companion issue in JIRA: https://mozilla-hub.atlassian.net/browse/FIDEFE-3611

**Comment by 1234abcd-sys** [comment]
can you something to this hacker >_discord
slaughter#0006
he has fuck the whole system
also my bank account
###
