### ISSUE TITLE
Add https://accounts.firefox.com/metrics-flow as a connect-src for at least the switching-devices page

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1253]
One of the things that the new device migration wizard needs to do is present a `<form>` to the user to offer them the ability to enter their email address on SUMO, but then to continue the sign-up / sign-in procedure for a Firefox Account on a Firefox Accounts page.

According to [the documentation](https://mozilla.github.io/ecosystem-platform/relying-parties/reference/metrics-for-relying-parties#relying-party-hosted-email-form), one of the first things we do before presenting that form is to acquire a `flowID` and a `flowBeginTime` pair of values via an XHR GET request to `https://accounts.firefox.com/metrics-flow`.

The CSP on SUMO doesn't allow such an XHR. Is it possible to modify the CSP to allow connections to `https://accounts.firefox.com/metrics-flow`, at least on the switching-devices page?

**Comment by emilghittasv** [comment]
Hey @escattone!

I have enable UI tour for stage by performing the following steps:

1. Go to about:config
2. Search for the browser.uitour.testingOrigins pref and edit it
3. Add https://support.allizom.org/ to the end of the comma-separated list
4. Reload the https://support.allizom.org/en-US/kb/switching-devices page

As soon as I land on the switching-devices page I get:

`XHRGET
https://accounts.stage.mozaws.net/metrics-flow?utm_source=help-menu&utm_campaign=migration&entrypoint=fx-new-device-sync
CORS Missing Allow Origin`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.stage.mozaws.net/metrics-flow?utm_source=help-menu&utm_campaign=migration&entrypoint=fx-new-device-sync. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 401.
TypeError: NetworkError when attempting to fetch resource. switching-devices.67c39585657943a4.js:1:7461`

**Comment by mikeconley** [comment]
I've reached out to the FxA team to see if we can add support.allizom.org to the list of sites that can XHR to the FxA staging server.
