### ISSUE TITLE
Stub out initial SwitchingDevicesWizardManager object for switching-devices page

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1254]
[This document](https://docs.google.com/document/d/1VtAYdReNjKGLE9Ie0SCwmRsY6kKntjnxG5OzGcwIA58/edit#) lays out the general architecture that we're aiming for here. One part of it is something called the `SwitchingDevicesWizardManager` which will manage the state, ingest events and callbacks, and update the UI with state changes.

This ticket is for stubbing out the initial version of the `SwitchingDevicesWizardManager`, which probably won't be very exciting, but gets us off of the ground.

**Comment by escattone** [comment]
The initial stub was done.
