### ISSUE TITLE
Unable to use custom elements in hook_device_migration_wizard.html

### ISSUE THREAD

**Issue by hannajones** [mozilla/sumo#1260]
For the device migration work we're starting to build a `<form-wizard>` custom element. The idea is that the `<form-wizard>` will control the visibility of different form steps by assigning one child element at a time to an `active` named slot. 

Currently when we try to use the `<form-wizard>` in `hook_device_migration_wizard.html` all child elements seem to get removed from `<form-wizard>`, which breaks this slotting mechanism. For example adding this markup to `hook_device_migration_wizard.html`:

```html
<form-wizard id="switching-devices-wizard">
    <div name="first">
        <p>this is the first step</p>
    </div>
    <div name="second">
        <p>this is the second step</p>
    </div>
    <div name="third">
        <p>this is the third step</p>   
    </div>
</form-wizard>
```

results in this rendered output:

<img width="372" alt="Screenshot 2023-05-05 at 12 59 27 PM" src="https://user-images.githubusercontent.com/15138046/236520631-332a678e-e8b8-44e5-addd-11dfe43099cd.png">

The `<form-wizard>` is still in the DOM, but it's wrapped in a `<p>` and its children are now siblings of that wrapper element.

@mikeconley did some digging and it seems this is likely due to some of the wiki parser sanitization logic. For the purposes of this project we're wondering if it's possible to allow certain custom elements in wiki pages - possibly by adding to/amending restrictions around `ALLOWED_TAGS`.

**Comment by hannajones** [comment]
Hey @emilghittasv! I can confirm that this issue is fixed now that https://github.com/mozilla/kitsune/pull/5464 was merged and the `<form-wizard>` is no longer wrapped in a `<p>` tag, thanks for checking. I'm not sure about the additional empty `<p>` tags - @escattone might know more about that.

**Comment by emilghittasv** [comment]
Thanks, Hanna!

Moving this ticket to the "Ready for release" column.

**Comment by escattone** [comment]
@emilghittasv (cc @hannajones)
> Note: I've noticed that some additional, empty <p> tags are created above and below the <form-wizard> I'm wondering if that's expected?
Yes, that's expected (although maybe not ideal). It's what the underlying `py-wikimarkup` parser does when it encounters empty lines.
