### ISSUE TITLE
Investigate changing shadow root mode based on env variable

### ISSUE THREAD

**Issue by hannajones** [mozilla/sumo#1263]
Ideally we want to use a closed shadow root in the `<form-wizard>` element for maximum encapsulation. This presents some difficulties for testing as a closed shadow root would prevent us from easily accessing information about the currently visible form step. It may be possible to change the shadow root mode based on an environment variable - either `process.env.NODE_ENV` or some tbd variable we can set either in the different `.env` files or using [webpack.EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values).

**Comment by mikeconley** [comment]
I think this is probably not worth doing at this point, honestly. The encapsulation of a closed shadow root can be very nice, but considering that SUMO is the only user of the wizard (and likely will be for the forseeable future), I think we can get away with keeping things simple and not using a closed root unless we really hit a need for it. I'm going to close this as WONTFIX.
