### ISSUE TITLE
Make sure FxA production server can accept metrics flow parameter requests from SUMO

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1265]
This is something that the FxA side of the house needs to do, but we don't have the JIRA bot hooked up to that repo (as far as I'm aware), so this ticket is to track the work in https://github.com/mozilla/fxa/issues/15265 to make sure it happens.

**Comment by emilghittasv** [comment]
Hey @mikeconley 

I've noticed that the corresponding jira ticket for this one was closed. (https://mozilla-hub.atlassian.net/browse/FIDEFE-3640)

Should we close this SUMO ticket as well?

**Comment by mikeconley** [comment]
Yep!
