### ISSUE TITLE
Replace "Wizard header" text in form-wizard.js with the actual copy

### ISSUE THREAD

**Issue by hannajones** [mozilla/sumo#1271]
The "Wizard header" text [here](https://github.com/mozilla/kitsune/blob/main/kitsune/sumo/static/sumo/js/form-wizard.js#L18) matches the current designs, but is only intended as a placeholder. When we have the final copy this needs to be updated.

**Comment by mikeconley** [comment]
This was done in https://github.com/mozilla/kitsune/pull/5501.
