### ISSUE TITLE
Implement disqualified state + message for the <form-wizard>

### ISSUE THREAD

**Issue by hannajones** [mozilla/sumo#1274]
If the user opens the device migration page from a non-Firefox browser, we will still display the wizard, but it won't be usable. We need to add an overlay to make it impossible to interact with the wizard, and to explain why/tell the user to switch their browser. Figma mockups can be found [here](https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=3426-38855&t=p4b5DtLxKdLEjMHN-0).

**Comment by mikeconley** [comment]
Fixed in https://github.com/mozilla/kitsune/pull/5499.
