### ISSUE TITLE
add FXA_ROOT to dev, stage, and prod k8s configmaps

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1275]
We need to add `FXA_ROOT` to our Kubernetes `ConfigMap` for dev, stage, and prod.

**Comment by akatsoulas** [comment]
@escattone is this done?

**Comment by akatsoulas** [comment]
Also can we use the `FXA_SET_ISSUER` instead in order to avoid duplication?

**Comment by escattone** [comment]
Yes, this was done [about 3 weeks ago](https://github.com/mozilla-it/webservices-infra/pull/501). I can create an issue to use `FXA_SET_ISSUER` instead in order to avoid duplication.

**Comment by escattone** [comment]
I created https://github.com/mozilla/sumo/issues/1327.
