### ISSUE TITLE
Implement the <configure-sync> form step

### ISSUE THREAD

**Issue by hannajones** [mozilla/sumo#1285]
This step is responsible for directing the user to about:preferences so they can either turn on FxA sync, or change which data they want to sync.

Spec is here: https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=3362-38070&t=T6tOSjgWKQuaxfFB-4

This will probably just encompass the markup and functionality of the different buttons.

**Comment by mikeconley** [comment]
This was fixed in mozilla/kitsune#5486.
