### ISSUE TITLE
Articles are not displayed under search results

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1287]
**Steps to reproduce**
1. Search for any article using the searchbar

**Expected behavior**
Articles are successfully displayed.

**Actual behavior**
Articles are not displayed.

**Screenshots/Screencasts**
![image](https://github.com/mozilla/sumo/assets/28087895/e56b0d0e-c2e3-4286-89d0-d78932f7c384)

**Desktop:**
- OS: Windows 10
- Firefox

**Additional context**
I believe that this may have been introduced by the changes performed in https://github.com/mozilla/sumo/issues/1286

**Comment by akatsoulas** [comment]
Fixed here: https://github.com/mozilla/kitsune/pull/5482

**Comment by emilghittasv** [comment]
Thanks for the quick fix, Tasos!

Verified that this issue is no longer reproducible and the search results are successfully displayed again.

I've extended my search to cover different search entry points like: Homepage, Product pages, forums, Contributors support, top-navbar,etc

Tested on: Chrome, Firefox (both desktop & mobile) and Safari.

Marking this as ready for release
