### ISSUE TITLE
The "Switching-devices" article is also displayed inside the "tabbed menu" list

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1288]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Observe the "Tabbed menu" list.

**Expected behavior**
* The current article "Switching-devices" is not displayed inside the "tabbed menu" list since it's the current article in focus and it doesn't really make sense to redirect the user to the same article.

**Actual behavior**
* The "tabbed menu" list displays articles present inside the "Sync and save" topic. The current Switching-devices article lives inside that topic and hence it get displayed inside that list.

**Screencast**
![tabbed menu list](https://github.com/mozilla/sumo/assets/28087895/f22aa177-f2ca-4fcd-b9c8-9653882a2b3a)

**Desktop**
- OS: Windows 10 
- Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5483/

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed on stage. The"Switching-devices" article is not displayed inside the "tabbed menu" list.

Tested on Firefox, Chrome & Safari

Moving this ticket inside the "Ready for release" column
