### ISSUE TITLE
Consider adding pagination to the "tabbed menu" list

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1289]
**Describe the bug**
The "View All" section of the "tabbed menu" (present inside the "Switching Devices" article) can become a bit too large to scroll if there are a couple of articles that fall into our "Save and Sync" topic.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Scroll through the list of articles displayed inside the "tabbed menu".

**Expected behavior**
If the list contains a large number of elements, we could consider adding pagination for those items so that the user doesn't have to scroll too much through that list.

**Actual behavior**
The user has to scroll quite a lot through that list & also it has the ability of affecting mobile users the most.

**Screencast**
![pagination](https://github.com/mozilla/sumo/assets/28087895/c660f290-aa03-426a-b3fc-847348646034)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
This is not ready for implementation. Just a placeholder to discuss with the Content Team.

**Comment by akatsoulas** [comment]
We don't have many articles at the moment and there's not a need for this. Closing for now and we can re-open if needed
