### ISSUE TITLE
create custom funnel for device-migration wizard in Google Analytics for stage and prod

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1295]
Create a custom funnel in Google Analytics for the stage and production environments to support the Firefox device-migration project by tracking the flow of users starting at the switching-devices landing pages(s) and working through the steps of the UI wizard on that(those) page(s).

**Comment by escattone** [comment]
This has been completed for the stage (`support.allizom.org`) and prod (`support.mozilla.org`) GA360 views, and is ready for review.

**Comment by akatsoulas** [comment]
@escattone can we verify this in staging?

**Comment by escattone** [comment]
The stage and prod funnels appear to be working. We're seeing state reports for every stage in each funnel.

## Stage Funnel
<img width="1265" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/4ad2ee07-376e-4042-bd3f-ecb2285c340d">

## Prod Funnel
<img width="1395" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/c143010b-ec2e-4a67-8031-ac5cfdf0b994">
