### ISSUE TITLE
Figure out what to do if UITour can't be properly communicated with

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1299]
It's possible, either via user preferences or a corrupted permissions database, that UITour will not be working for some users. If that's the case, most of the `SwitchingDevicesWizardManager` / `<form-wizard>` isn't going to be very useful. We might want to consider showing an alternative message for users in that boat, or hiding the wizard altogether.

It'd also be worth collecting a GA event in that scenario to measure how many users might be impacted by something like this.

**Comment by mikeconley** [comment]
Fixed in https://github.com/mozilla/kitsune/pull/5508.

**Comment by emilghittasv** [comment]
This is verified fixed on stage.

The appropriate message is displayed if UI tour is disabled.
