### ISSUE TITLE
Converge on the right colour for the "Off" state for syncing in the switching devices wizard

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1300]
In https://github.com/mozilla/kitsune/pull/5486, I'm landing patches that set the colour of the "Off" syncing state indicator to be `--color-error`, since this is a colour that's part of the swatches that we can choose from. The colour from the spec, #E22850, is not part of the colour set available to us (unless we hardcode it in).

This ticket is for figuring out if there's a better existing colour to use here, or if we should add #E22850 to the set of colours on SUMO in its set of colour swatches.

**Comment by hannajones** [comment]
Complete with the landing of https://github.com/mozilla/kitsune/pull/5497
