### ISSUE TITLE
The request to https://accounts.stage.mozaws.net/ made after clicking the Sign in form button is missing the utm_campaign param

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1307]
**Preconditions**
* Firefox is configured to use FxA stage.
* UI tours is enabled for stage env.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Type an email address inside the Email field and click on the Sign In button.
3. Inspect the network requests.

**Expected behavior**
A request is made to accounts.stage.mozaws.net containing the following params:
`service`,`action`,`context`,`flow_id`,`flow_begin_time`,`utm_source`,`utm_medium`,`utm_campaign`,`entrypoint`,`redirect_immediately` and `redirect_to`

**Actual behavior**
The request made to accounts.stage.mozaws.net is missing the following params:
`utm_campaign`

Also we are missing the `flow_id` and `flow_begin_time` but this is a known issue for stage env:  https://github.com/mozilla/sumo/issues/1253#issuecomment-1549613472

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/41ca37fe-d003-4597-a8dc-2fba9c36abbe)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by mikeconley** [comment]
Fixed in the landing of mozilla/kitsune#5498.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed on stage.

We are now also sending the `utm_campaign` param.

![image](https://github.com/mozilla/sumo/assets/28087895/b74b2443-8b26-49b1-ad29-3fe818040792)
