### ISSUE TITLE
The request made to accounts.stage.mozaws.net after clicking on the "Sign up" button from the "Don't have an account?" section is missing the service and action params

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1308]
**Preconditions**
* Firefox is configured to use FxA stage.
* UI tours is enabled for stage env.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Click on the "Sign up" option from the "Don't have an account?" section.
3. Inspect the network requests.

**Expected behavior**
A request is made to accounts.stage.mozaws.net/ containing the following params:
`service`,`action`,`context`,`flow_id`,`flow_begin_time`,`utm_source`,`utm_medium`,`utm_campaign`,`entrypoint`,`redirect_immediately`,`redirect_to`

**Actual behavior**
The request made to accounts.stage.mozaws.net/ is missing the following params:
`service` and `action`.

The request is also missing the `flow_id` and `flow_begin_time` params but this is a known issue on stage env: https://github.com/mozilla/sumo/issues/1253#issuecomment-1549613472

We are also missing the `redirect_immediately` param but this is tracked in https://github.com/mozilla/sumo/issues/1297 

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/6b22ad26-8bd1-4f75-a9e9-119e187743c6)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by mikeconley** [comment]
Fixed in the landing of mozilla/kitsune#5498.

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed on stage.

We are now sending the `service` and `action` params as well:

![image](https://github.com/mozilla/sumo/assets/28087895/e1b7034d-baad-46d1-a0aa-d57db3efa391)
