### ISSUE TITLE
The wizard's step 1 doesn't change to "Sign in to your account" if user is already logged in to SUMO

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1316]
**Describe the bug**
As described inside the "SUMO Content 5.18.23" section from [figma](https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=3277-39189&t=dcWcXj53apX5UIlz-0), when the user is Signed in inside the SUMO page we need to display the "Sign in" button and the Step 1 from the wizard needs to update to "Sign in to your account"

**Preconditions**
User is not connected to sync in Firefox.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Sign in using your FxA account inside the SUMO page.
3. Observe the Wizard.

**Expected behavior**
- The Step 1 from the wizard updates from "Create an account" to "Sign in to your account".

**Actual behavior**
- The Step 1 from the wizard displays "Create an account".

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by hannajones** [comment]
Hey @emilghittasv I haven't been able to replicate this, but I've recorded a video to make sure I'm following the steps you outlined. Let me know if I'm missing something!


https://github.com/mozilla/sumo/assets/15138046/90266779-8e72-4267-bf17-c6350d009926

**Comment by mikeconley** [comment]
I _think_ I know what @emilghittasv was noticing - it's in the step indicator. The first step should be "Sign in to your account", and it's still "Create an account" when signed in to SUMO:

![image](https://github.com/mozilla/sumo/assets/195042/7f549af3-bb62-4d90-af8e-782d8c455bc6)

**Comment by emilghittasv** [comment]
Hey @hannajones, exactly what Mike mentioned ^

The text from the Step 1 doesn't transition from "Create an account" to "Sign in to your account" if the user is signed in to SUMO.

![CreateAnAccount](https://github.com/mozilla/sumo/assets/28087895/66d292ad-c35b-4d6e-97cb-8ff8c1f31d09)

Sorry for the confusion!

**Comment by mikeconley** [comment]
This was fixed in https://github.com/mozilla/kitsune/pull/5518.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed on stage.

If the user is connected to SUMO, the Step 1 changes from "Create an account" to "Sign in to your account".  The "Sign in to your account" persists through the entire flow (until the user reaches step 3).

Disconnecting from SUMO changes the Step 1 from "Sign in to your account" to "Create an account" even if the user is already at step > 2.
