### ISSUE TITLE
The "key banner" is displayed inside the wizard even if the user is logged in inside SUMO

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1317]
**Describe the bug**
As shown inside the "SUMO Content 5.18.23" from [figma](https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=3277-39189&t=dcWcXj53apX5UIlz-0), if the user is already logged in inside the SUMO page, the "key banner" is no longer displayed.

**Preconditions**
User is not connected to sync in Firefox.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Sign in using your FxA account inside the SUMO page.
3. Observe the wizard.

**Expected behavior**
The "key banner" is not displayed.

**Actual behavior**
The "key banner" is displayed.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by mikeconley** [comment]
Fixed by https://github.com/mozilla/kitsune/pull/5512.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on stage.

* The "recovery key warning messages" is displayed if the user is not signed in to SUMO
* The "recovery key warning message" is no longer displayed if the user is signed in to SUMO
