### ISSUE TITLE
Search results filter highlight is broken when navigating via keyboard-only

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1319]
**Describe the bug**
https://github.com/mozilla/sumo/issues/1310 re-introduced the highlight for tabbed menu items inside the Switching devices article but seems to have caused a regression inside the search results section.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Type something inside the search bar which returns some results.
3. Hit the "tab" keyboard button in order to navigate through the "View All", "Help Articles Only" and "Community Discussions Only" options.

**Expected behavior**
No ui issues are encountered.

**Actual behavior**
The border highlight seems to be broken.

**Screencasts**
![SearchResults](https://github.com/mozilla/sumo/assets/28087895/83dea962-0db4-4256-9fbc-de5340ef3c7b)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
- This seems to be a regression (probably caused by https://github.com/mozilla/sumo/issues/1310)
- Reproducible only in stage environment. Prod is not affected

**Comment by emilghittasv** [comment]
This is still reproducible and now prod is also affected. It seems that https://github.com/mozilla/sumo/issues/1310 did not cause this regression to occur.

Moving this ticket back to the "In progress" column

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5598

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on stage using Firefox and Chrome browsers on Windows 10 and macOS 11.

The highlight applied on the search results filter is no longer broken. Moving this ticket inside the "Release" column.
