### ISSUE TITLE
Cannot initiate the Sign up or Sign in flow via the Switching Devices Wizard

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1320]
**Preconditions**
* Enable UiTour
* Configure Firefox to connect to FxA stage.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Click on the "Sign in" link
3. Enter the email address inside the Email field and click on the "Sign up" button.

**Expected behavior**
Step 2: The FxA sign in flow is initiated.
Step3: The FxA sign up flow is initiated.

**Actual behavior**
Step 2 & Step 3: The SUMO page refreshes

**Screencasts**
![Sign in Flow](https://github.com/mozilla/sumo/assets/28087895/41ad0e83-ec5c-4d3b-a2d0-44af17b1fffc)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* Yesterday it was working just fine. 
* Reproducible using the https://stage.sumo.nonprod.webservices.mozgcp.net as well.

**Comment by mikeconley** [comment]
I think this is now fixed on staging @emilghittasv, right? Can we close this out?

**Comment by emilghittasv** [comment]
Yes! This is working as expected now.

Forgot to close this one. My bad.
