### ISSUE TITLE
The Wizard is not available while using Private Browsing mode

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1322]
**Steps to reproduce**
1. Open a new private browsing window in Firefox.
2. Access the following link: https://support.mozilla.org/en-US/kb/switching-devices

**Expected behavior**
The Wizard is functional.

**Actual behavior**
The "setup assistant is currently unavailable" message is displayed.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 113.0.1 and 114.0b8

**Additional context**
This issue is not reproducible on stage env.

**Comment by mikeconley** [comment]
This appears to be a UITour bug. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1835105.

**Comment by mikeconley** [comment]
A patch for this has been posted in https://phabricator.services.mozilla.com/D179233.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed using Firefox 116.0a1 (BuildId:20230607214358) on Windows 10 64bit and macOS 11

The Wizard is available and can be successfully interacted with while using Private Browsing Mode.

Since this was a Firefox side fix, I'm moving this ticket directly inside the "Done" column.
