### ISSUE TITLE
[Mobile] The "Important: once you have completed step two.." yellow section is displayed even if the wizard is disabled

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1325]
**Describe the bug**
With https://github.com/mozilla/kitsune/pull/5523 applied, mobile users will have the Wizard disabled and a custom warning message displayed. Since the next "yellow section" ("Important: Once you have completed step two") is not part of the Wizard, it is still displayed.

**Preconditions**
Build Kitsune locally with the https://github.com/mozilla/kitsune/pull/5523 changes applied.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Observe the content around the Wizard.

**Expected behavior**
The "Important: Once you have completed step two.." yellow section is no longer displayed since that part is related to the Wizard which is disabled on mobile and could generate user confusion.

**Actual behavior**
The "Important: Once you have completed step two.." is displayed.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/9b828618-35fc-4c54-a8a2-f2fd13fc43ae)

**Smartphone:**
 - Device: Pixel 6 Pro (emulator)
 - Browser: Firefox 114

**Comment by mikeconley** [comment]
Hey @emilghittasv - I think with the latest changes to the SUMO page, this is no longer an issue (at least, I can't reproduce it). Can you confirm?

**Comment by emilghittasv** [comment]
I can also confirm that this issue is no longer reproducible on mobile (used Firefox browser on a Huawei P40 pro device).
