### ISSUE TITLE
Use FXA_SET_ISSUER instead of FXA_ROOT in order to avoid duplication

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1327]
Use `FXA_SET_ISSUER` instead of `FXA_ROOT` in order to avoid duplication.

**Comment by emilghittasv** [comment]
I can confirm that no regressions were introduced at Switching Devices wizard functionality level.

* Verified that the `fxa_root` attribute is set to `https://accounts.stage.mozaws.net`.
* Verified that the same attribute value is set after creating several revisions and approving them for the switching-devices article.
* Verified that the user can successfully sign in with their FxA account via the wizard. 
* Verified that the user can successfully create a new FxA account via the wizard.
* Verified that the wizard is successfully listening and updates based on the changes performed at the FxA sync preferences.
* Verified that the user can navigate to the about:preferences#sync page directly via the wizard.
* Verified that the wizard is not available and an appropriate message is displayed when accessing the switching-devices article via a non-Firefox browser or via a mobile device.

I'm marking this ticket as ready for release.
