### ISSUE TITLE
Items from a disabled wizard can still be accessed via keyboard-only 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1328]
**Preconditions**
Use a non-Firefox browser or disable UiTour in Firefox and reload the Switching Devices page.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Navigate to the Wizard using keyboard-only actions.
3. Try interacting with the elements from the Wizard by pressing the "Enter" keyboard button.

**Expected behavior**
2 & 3: If the Wizard is disabled because the user is using a non-Firefox browser or the UiTour is disabled, the elements from the Wizard cannot be highlighted & interacted with.

**Actual behavior**
2: The Wizard elements can be keyboard focused.
3: Pressing the "Enter" keyboard button on a highlighted wizard option will interact with that element ( bringing a 404 page into view)

**Screencasts**
![keyboard-only](https://github.com/mozilla/sumo/assets/28087895/fc0d83cc-9ba5-484d-be9d-76dea7d57ca9)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox & Chrome

**Additional context**
Reproducible in both stage & production.

**Comment by hannajones** [comment]
@emilghittasv  this should be fixed now that https://github.com/mozilla/kitsune/pull/5531 was merged

**Comment by emilghittasv** [comment]
I can confirm that this issue is fixed on stage.

I am no longer able to interact with the elements from the disabled Wizard via keyboard-only actions. 

Tested on Firefox (by disabling the UiTour), Chrome, Edge & Safari.

Moving this ticket inside the "Ready for release" column.

**Comment by escattone** [comment]
This was released earlier today around 8:30am Pacific.
