### ISSUE TITLE
Step counters in <form-wizard> aren't localizable

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1331]
I noticed this while looking at translations for the switching devices article. This is the Italian translation: https://support.mozilla.org/it/kb/backup-dati-firefox-trasferire-su-altro-dispositivo

Notice that the step counter still says "Step 1", "Step 2", "Step 3":

![image](https://github.com/mozilla/sumo/assets/195042/7ed6df4a-9e44-41ee-93c1-90a0c32bfa9a)

This is because the string is hard-coded into `form-wizard.js` here: https://github.com/mozilla/kitsune/blob/28f3d8bb1bbb64148f13de8a261bc2574506ae9a/kitsune/sumo/static/sumo/js/form-wizard.js#L205

**Comment by escattone** [comment]
This was resolved with https://github.com/mozilla/kitsune/pull/5536, andreleased earlier today around 8:30am Pacific.
