### ISSUE TITLE
KB content with {for fx 113} tags displays for Firefox 112 and below

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1333]
**Describe the bug**
This issue was initially filled in https://bugzilla.mozilla.org/show_bug.cgi?id=1836594

**Steps to reproduce**
1. Go to:
https://support.mozilla.org/en-US/kb/import-bookmarks-internet-explorer-or-microsoft-edge
https://support.mozilla.org/en-US/kb/import-data-another-browser
https://support.mozilla.org/en-US/kb/import-bookmarks-google-chrome
2. View the article in an older version of Firefox < 113 or toggle the "Customize this article" version to a version < 113

**Expected behavior**
The content marked `{for fx113}` is not displayed for Firefox versions < 113.

**Actual behavior**
The content marked `{for fx113}` is displayed for Firefox versions < 113.

**Desktop:**
 - OS: Windows 10 
 - Browser: Firefox 112

**Additional context**
As mentioned by the original reporter:
- This issue is only reproducible for content marked `{for fx113}`. The `{for fx114}` content is not shown for previous versions. (https://support.mozilla.org/en-US/kb/import-bookmarks-google-chrome)

**Comment by smithellis** [comment]
It looks like the versions in admin were not set up properly - mobile was labeled fx113 and desktop was labeled m113. I changed these, and everything appears to be working as expected now.
