### ISSUE TITLE
replace raw SQL in update_question_vote_chunk

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1341]
Replace raw SQL [here](https://github.com/mozilla/kitsune/blob/041d00a42c13994cbd1246fe8528a3fe8f06b883/kitsune/questions/tasks.py#L40) and [here](https://github.com/mozilla/kitsune/blob/041d00a42c13994cbd1246fe8528a3fe8f06b883/kitsune/questions/management/commands/fix_weekly_votes.py#L17) with its Django ORM equivalent in order to avoid dependency on MySQL date functions that don't exist in Postgres.

**Comment by escattone** [comment]
## QA Notes
1. Go to https://support.allizom.org/en-US/questions/firefox and check the `<N> votes this week` for one of the questions (for example [Just a test question bio](https://support.allizom.org/en-US/questions/1207473))

![Image](https://github.com/mozilla/sumo/assets/3743693/da0e5418-e458-4a36-a83f-13d699d13993)

2. Go to the [Just a test question bio](https://support.allizom.org/en-US/questions/1207473) question and click on the `I have this problem, too` button (to vote)
3. Return to https://support.allizom.org/en-US/questions/firefox and verify that the number of `votes this week` has increased by one.

**Comment by emilghittasv** [comment]
I can confirm that no regressions were introduced by this ticket.

The number of "votes this week" is incrementing successfully if users are interacting with the "I have this problem, too" option.

Tested using a couple of questions from different product forums such as:

- Firefox Support forum
- Firefox for Android support forum
- Firefox for iOS support forum
- Firefox Focus support forum
- Firefox ESR support forum
- Thunderbird support forum

Also verified that the number increments while interacting with the "I have this problem, too" option for questions displayed in all categories (All, Attention needed, Responded and Done) 

Moving this ticket inside the release column.
