### ISSUE TITLE
replace raw SQL in forums view with Django ORM equivalent

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1342]
Replace the raw SQL [here](https://github.com/mozilla/kitsune/blob/041d00a42c13994cbd1246fe8528a3fe8f06b883/kitsune/forums/views.py#L35) with its Django ORM equivalent.

**Comment by escattone** [comment]
## QA Notes
- Go to https://support.allizom.org/en-US/forums/ and note that each forum has a "thread count" under the `Threads` column (see below). The code that generate that "thread_count" is what has been changed.
<img width="894" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/a933c048-0105-4a26-a436-1185b802afdf">
- Choose one of the forums -- let's pick the [test forum](https://support.allizom.org/en-US/forums/test/) -- note its current "thread count", and then go to that forum and create a new thread.
<img width="796" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/98f1952a-0124-4388-9aaf-f98332b3b3e1">
- After creating a new thread, return to https://support.allizom.org/en-US/forums/ and ensure that the "thread count" for the `test` forum has been incremented by one.

**Comment by emilghittasv** [comment]
I can confirm that no regressions were introduced. 

Tested:
- That the threads count increments when creating a new thread under a certain forum.
- That the threads count decrements when deleting an existing thread.
- That the threads count increments and decrements successfully when moving a thread from one forum to another.
- The thread count is not affected by modifying a threads title, locking/unlocking or sticking/un-sticking a thread.

Moving this ticket inside the "Release" column.
