### ISSUE TITLE
replace raw SQL in helpful_replies property of questions

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1344]
Replace the following raw SQL with its Django ORM equivalent:

https://github.com/mozilla/kitsune/blob/041d00a42c13994cbd1246fe8528a3fe8f06b883/kitsune/questions/models.py#L332

**Comment by escattone** [comment]
## QA Notes
For this one, you'll have to go to a question (for example, https://support.allizom.org/en-US/questions/1207474), create some replies, login as a different user and vote for one or more of the replies, and then verify that the 👍 votes have been incremented for each of the replies you voted for.

**Comment by emilghittasv** [comment]
I can confirm that no regressions were introduced by this patch. I have used the https://support.allizom.org/en-US/questions/1207474 and a newly created question (https://support.allizom.org/en-US/questions/1207347) for testing.

I can confirm that the votes (both thumbs up and thumbs down) are working as expected and their numbers are successfully incremented.

Moving this ticket inside the release column.
