### ISSUE TITLE
Zendesk form for Firefox Accounts - logged in version

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1380]
Allow users to get support through Zendesk

**Comment by smithellis** [comment]
This will just be enabling standard product form from what I understand. Swapping this to backlog while I wrap up login-less form.

**Comment by emilghittasv** [comment]
I can confirm that the logged in Zendesk form version for the Mozilla Accounts product is successfully displayed & functional (Tickets can be successfully sent to Zendesk).

Moving this ticket inside the "Release" column
