### ISSUE TITLE
Allow kb articles to have "foldout" sections

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1383]
We'll need this for the FAQ section in [this Figma spec](https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=4791-43714&mode=design&t=u6YCETZHgJAtxnet-4).

@escattone mentioned that this could be probably be done with some minor wiki parser changes.

**Comment by mikeconley** [comment]
Hey @escattone! So it looks like mediawiki syntax [supports this sort of thing](https://en.wikipedia.org/wiki/Template:FAQ). Their syntax is like this:

```
{{FAQ row
|index=1
|q=<!-- This is some question text... -->
|a=<!-- This is some answer text... -->
}}
```

Does it make sense to add similar syntax / support to the parser?

**Comment by mikeconley** [comment]
That looks like exactly what we want! I'll reach out to Tati to see if we're still interested in the styling in Figma, or if the component as-is is fine.

Thanks so much @escattone. Are the 6 lines something you'd be willing to get into the tree? Like, are you willing to take this ticket over the line?

**Comment by mikeconley** [comment]
Thanks so much!

**Comment by mikeconley** [comment]
I spoke to Tati, and she said the default styling from Protocol is fine, meaning we're not going to need any custom styling. \o/

**Comment by escattone** [comment]
Awesome! Thanks @mikeconley!
