### ISSUE TITLE
Add illustrations to the switching-devices form-wizard in a way that can be A/B tested

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1385]
[The Figma spec here](https://www.figma.com/file/qe9yX8x51jjbt6DJYgayg2/Device-Migration?type=design&node-id=4818-52898&mode=design&t=u6YCETZHgJAtxnet-4) shows how we'd like some illustrations to be displayed for each step of the wizard.

Ideally, we'd like to make it possible to use the Google Analytics tooling to A/B test whether or not these illustrations appear, and to measure any difference between those two branches.

**Comment by hannajones** [comment]
This should be complete with the landing of https://github.com/mozilla/kitsune/pull/5601, but could definitely use some testing

**Comment by emilghittasv** [comment]
This was already QA tested and the results were posted in https://github.com/mozilla/kitsune/pull/5601#issuecomment-1680125863. 

Moving this ticket inside the "Release" column.
