### ISSUE TITLE
Add the ability to have articles hidden

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1387]
We need the ability to add KB articles in SuMo only accessible and visible to a group of people (eg staff or a specific group). This can be helpful when we want to have articles published at a specific time (eg embargoed content).

**Comment by emilghittasv** [comment]
Testing activities in `stage` are done for this ticket.

Apart from a regression testing session mostly focusing on the general health of our KB article functionalities & dashboards, the following verifications were performed:
* Verified that the kb restricted visibility functionality/field is only available to `staff` level accounts.
* Verified that KB articles can be successfully created while restricting the visibility to both a single or to multiple groups or by not restricting the visibility to any groups. 
* Verified that users which are not signed in to SUMO are not able to access articles which are live and restricted.
* Verified that users belonging to other groups (non-whitelisted) are not able to access and view the restricted article (404 page is returned).
* Verified that both users belonging to the whitelisted groups and staff level accounts are able to access/view the restricted article.
* Verified that restricted kb articles are not returned in search results regardless of the signed in user privileges or group membership.
* Verified that no information referring to the restricted visibility kb article is leaked to non-whitelisted users inside the "Media Gallery" section for images attached to the restricted article.
* Verified that the restricted visibility kb article is displayed inside the "What Links Here" section for an image (inside the Media Gallery section) attached to the restricted article only for whitelisted users & staff accounts.
* Verified that linking a different (non restricted visibility kb article) inside the restricted visibility kb article will not leak the restricted visibility article inside the "What Links Here" page of the non-restricted one while signed in with a non-whitelisted account. (The link to the restricted visibility article is only available to staff accounts and whitelisted users).
* Verified that the restricted visibility kb article is displayed inside the "Recent Revisions" page only for whitelisted & staff accounts.
* Verified that the restricted visibility articles are displayed in product topics page only for whitelisted users & staff accounts.
* Verified that the restricted visibility articles are visible inside the article discussion threads only for whitelisted users & staff accounts.
* Verified that the restricted visibility template articles are displayed inside the Templates list only for whitelisted users & staff accounts.
* Verified that the restricted visibility articles are displayed inside the KB dashboards only for whitelisted users & staff accounts.
* Verified that the restricted visibility articles are displayed inside the Localization dashboards only for whitelisted users & staff accounts.
* Verified that the restricted visibility articles are not displayed inside the https://support.allizom.org/en-US/kb/category/ page.
* Verified that e-mail notifications are not sent to non-whitelisted users for restricted visibility kb articles.

Also, as requested, tested the following API calls:
* https://support.allizom.org/api/1/kb/{restricted_kb_article_slug}
* https://support.mozilla.org/api/1/kb/
* https://support.mozilla.org/api/1/products/firefox/topic/%7Bkb_article_topic%7D

^ Can confirm that the restrictions are working as expected and the restricted visibility information is returned only if setting the `session_id` cookie which belongs to a whitelisted user.

For all the above cases, the scenarios of dynamically restricting the visibility of an already live article via the "Edit Article Metadata" option & removing the restrictions were covered ensuring that after adding the restriction the article is no longer leaked throughout SUMO for non-whitelisted and non admin accounts and removing the restriction will unveil the article throughout SUMO (dashboards, threads, receiving e-mail notifications, search results,etc)

During the verification of this ticket, the following issues were encountered/reported:
* https://github.com/mozilla/sumo/issues/1658 - Restricted visibility kb articles are returned in search results (Fixed)
* https://github.com/mozilla/sumo/issues/1660 - Restricted visibility kb articles are displayed inside the "What Links Here" page even for non-whitelisted users (Fixed).
* https://github.com/mozilla/sumo/issues/1662 - Restricted visibility kb articles are displayed inside Article discussions page even for non-whitelisted users (Fixed)
* https://github.com/mozilla/sumo/issues/1663 - Restricted visibility kb articles are displayed inside the contributor users profile page even for non-whitelisted users (Fixed).
* https://github.com/mozilla/sumo/issues/1664 - E-mail notifications coming from restricted visibility kb articles are received even by non-whitelisted users (Partially fixed. See the next issue listed below). 
* https://github.com/mozilla/sumo/issues/1667 - E-mail notifications coming from restricted visibility kb articles are received by non-whitelisted users belonging to a group which was removed from the whitelisted group list (Not Fixed)
* https://github.com/mozilla/sumo/issues/1661 - Restricted KB articles can be linked in other (non-restricted) kb articles and the link is available for all users (We have decided to close this ticket as not planned for now/wontfix).

Moving this ticket inside the `release` column.
