### ISSUE TITLE
The "Access denied" page is displayed when trying to edit the article metadata even after promoting the user to staff level

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1401]
**Describe the bug**
Editing an article's metadata can be done only by a staff-level account. Promoting a non-staff user account to the staff level and trying to perform the metadata edit will still redirect the newly promoted account to the "Access denied" page.

**Preconditions**
Sign in with a non-staff level account.

**Steps to reproduce**
1. Promote the user to a staff-level account.
2. Access any article and click on the "Edit Article Metadata" option.

**Expected behavior**
The user is redirected to the "Editing Description for" form.

**Actual behavior**
The user access is restricted to editing the article metadata (the "Access denied" page is displayed).

**Screencasts**
![staffStatusEditMetadata](https://github.com/mozilla/sumo/assets/28087895/99170d7b-cbc9-4137-93d2-5c6c91d4dac1)

**Desktop:**
 - OS: Windows 10 64bit
 - Browser: Firefox

**Comment by escattone** [comment]
@emilghittasv Hey Emil! I think this can be closed, or you could re-test after giving your user "edit" permission as well, because the user has to be staff AND have "edit" permission (see https://github.com/mozilla/kitsune/blob/4f2a3ea69a420cb11f9dcc0ec8c336cca3e172d8/kitsune/wiki/views.py#L481).

**Comment by emilghittasv** [comment]
Hey @escattone. You are correct, promoting the user to staff-level account and giving the "wiki | document| Can change document" permission will allow that user to change the article metadata.

Sorry for the confusion and headache, I was not aware that both staff-level & edit permissions were needed in order to edit the article metadata. 

I'm closing this ticket and will update my tests accordingly.
