### ISSUE TITLE
Slugs from "Create a new KB article" are generating a false "A document with this slug already exists in this locale" error when auto-generating for the first time

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1402]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/kb/new page
2. Add a random title which should auto-generate a slug that has no duplicate and click somewhere else in order to remove the focus from the slug input field.

**Expected behavior**
The slug is successfully generated and no page error message is displayed

**Actual behavior**
The "A document with this slug already exists in this locale" page error message is displayed.  Clicking on the "Submit for Review" button will submit the article successfully (meaning that in fact there were no duplicate slugs found). Deleting a character from the title field and placing the same character back will auto-generate the slug as it was before but now the page error message is not displayed.

**Screencasts**
![SlugError](https://github.com/mozilla/sumo/assets/28087895/f3ec2f63-4381-42dc-adcf-d5f6b718487c)

**Desktop:**
 - OS: Windows 10 64bit
 - Browsers: Chrome & Safari.

**Additional context**
This issue is reproducible only on stage environment (prod is not affected).

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5593

Order of inits in wiki.js causing a check to happen in the wrong order.  Thanks @escattone for the sanity check.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed on stage.

Slugs are no longer generating a false "A document with this slug already exists in this locale" error when auto-generating the slug for the first time on kb article creation.

I'm moving this ticket inside the Release column. Thanks!
