### ISSUE TITLE
Typing the second character in the SUMO search field causes the focus to be removed, so that the second and subsequent characters cannot be entered in the search field

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1404]
**Describe the bug**
Initially filled in https://bugzilla.mozilla.org/show_bug.cgi?id=1847125

**Steps to reproduce**
1. Open https://support.mozilla.org/en-US/kb/firefox-subprocessor-list.
2. Press [Tab] key several times so that Search field(Find help...) gets focus. (Do not use mouse to focus it.)
3. Type something. e.g. `addon`

**Expected behavior**
The search field should continue focus. And subsequent characters should be able to be entered normally.

**Actual behavior**
Only first letter appears in search filed. And the search field loses focus and subsequent characters are not displayed.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox and Chrome

**Comment by smithellis** [comment]
[1404 - Search focus issue with instant search](https://github.com/mozilla/kitsune/pull/5621)

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on `stage`. 

The focus is no longer removed from the search field.

Moving this ticket inside the "Release" column.
