### ISSUE TITLE
Consider hiding the "Edit Article Metadata" option from the "Editing Tools" section if the user dosen't meet both staff level account and kb editing permissions stats

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1406]
**Preconditions**
Sign in to SUMO with a staff level account which doesn't have kb article editing permissions.

**Steps to reproduce**
1. Go to a random article. Example: https://support.allizom.org/en-US/kb/update-firefox-latest-version
2. Click on the "Edit Article Metadata"

**Expected behavior**
Since the user doesn't meet all the required permissions to edit the article metadata, the "Edit Article Metadata" option is not displayed.

**Actual behavior**
The user is redirected to the "Access denied" page which is an expected outcome but I think that we could improve this by just hiding the "Edit Article Metadata" option if the user doesn't meet both staff level account & kb article editing permissions.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox & Chrome.

**Comment by akatsoulas** [comment]
After talking with Abby, we are going to revert this functionality and re-approach this section.

**Comment by emilghittasv** [comment]
This was tracked and fixed in https://github.com/mozilla/sumo/issues/1424
