### ISSUE TITLE
Check add_tag permissions in questions API

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1413]
https://bugzilla.mozilla.org/show_bug.cgi?id=1846733

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5606

**Comment by emilghittasv** [comment]
I'm unable to reproduce this in `stage`.

Burp Suite's Repeater response while using the `session_id` and `csrf token` of a user which doesn't have the necessary permissions to add question tags:

`HTTP/2 403 Forbidden`
`{"detail":"You do not have permission to perform this action."}`

Moving this ticket inside the `release`column.
