### ISSUE TITLE
Archived questions are displayed inside the "Attention needed" questions list

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1415]
**Steps to reproduce**
1. Access an archived question that was posted a couple of months back and has at least 1 reply to it.
2. Edit the posted reply.
3. Access the product support for that question (example: https://support.allizom.org/en-US/questions/firefox?show=needs-attention) 

**Expected behavior**
The questions is not displayed inside the "Attention needed" list since it was archived.

**Actual behavior**
The question is displayed inside the "Attention needed" list.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/4453df4c-c892-4b90-9c1d-80ec352b2875)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5607
