### ISSUE TITLE
Remove the limitation to edit KB metadata only for staff members

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1423]
PR https://github.com/mozilla/kitsune/pull/5613

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed on stage.

* The "Edit Article Metadata" option is not displayed/available if the user has no article edit permissions.
* The "Edit Article Metadata" option is not displayed/available if the user has a "staff" account only (without permissions to edit the articles).
* The "Edit Article Metadata" option is available if the user has `wiki | document | Can change document` permission applied (regardless if he has "staff" level account or not).
* Navigating to `/edit/metadata` while the user has no article edit permissions redirects the user to the "Access denied" page.
* The "Edit Article Metadata" form is no longer accessible if the `wiki | document | Can change document` permission was removed from the user.
* The "Edit Article Metadata" option is available/functional if the user is a "superuser"
* No regressions were encountered while verifying the functionality of the "Edit Article Metadata" form options.


Please note that while testing this ticket I've noticed that https://github.com/mozilla/sumo/issues/1405 is still reproducible.

I'm moving this ticket inside the "Release" column.
