### ISSUE TITLE
[Postgres][Dev] Sometimes? Signing in to SUMO fails and redirects the user to the "An Error Occured" page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1431]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org
2. Sing in to SUMO

**Expected behavior**
* The user is successfully signed in to SUMO.

**Actual behavior**
* Sometimes, the user is redirected to the "An Error Occurred" page.
* The user is not signed in.
* The `SUMO-NONPROD-DEV-1X - IntegrityError: duplicate key value violates unique constraint "auth_user_pkey"` is fired by sentry when reproducing this.

**Screencasts**
![SignIn](https://github.com/mozilla/sumo/assets/28087895/284015a4-35fb-4a9a-ae72-49f868c8ef47)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional notes**
* This issue is reproducible only in dev env (Stage is not affected).
* I'm still looking for some more reliable steps. Will update the description once I find them!

**Comment by escattone** [comment]
@emilghittasv I looked into this today, and I'm nearly certain that this issue was due to the problem we had prior to August 17 where the Postgres sequences were not properly reset after the database migration. Can you test logins again?
