### ISSUE TITLE
Edit article metadata is not available/displayed in archived kb articles (even if the user has permissions to edit)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1433]
**Preconditions**
Sign in to SUMO with an account that has article edit permissions.

**Steps to reproduce**
1. Go to an archived article. Example: https://support.allizom.org/en-US/kb/search-based-content
2. Navigate to https://support.allizom.org/en-US/kb/search-based-content/edit/metadata

**Expected behavior**
The "Edit Article Metadata" option is available inside the "Editing Tools" so users with the necessary permissions are able to unarchive the article.

**Actual behavior**
The "Edit Article Metadata" option is not available inside the "Editing Tools". Navigating manually to /edit/metadata will successfully display that section.

**Screencasts**
![archived](https://github.com/mozilla/sumo/assets/28087895/21443daa-6e12-48ba-8e57-4c5bcceb1b3b)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by AliceWyman** [comment]
I opened a SUMO bug report, https://bugzilla.mozilla.org/show_bug.cgi?id=1849668

**Comment by AliceWyman** [comment]
For the record, reviewers were able to edit the Description for an archived article before, by using the instructions shown in the video here: https://support.mozilla.org/en-US/kb/edit-knowledge-base-article/discuss/8123 (click Show History under Editing Tools, click the Revision date and click Edit article based on this revision.  You can then access the Edit Description section of the article.)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5760

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

- The "Edit Article Metadata" option is successfully displayed inside the "Editing Tools" menu for archived marked KB articles (only for users which have the necessary permissions to edit an article's metadata). 
- Users which have the necessary permissions to edit the article's metadata can successfully mark or un-mark an article as archived via the "Edit Article Metadata" option.
- The "Edit Article Metadata" option remains inaccessible for users which don't have the necessary permissions to edit the article's metadata (Manually navigating to edit/metadata returns the access denied page and the "Edit Article Metadata" option is not available/displayed inside the Editing Tools menu).


Moving this ticket inside the `Release` column.
