### ISSUE TITLE
[Postgres][Dev] Cannot report a user if leaving all radio buttons unchecked 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1435]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access another users page. Example: https://support-dev.allizom.org/en-US/user/emilgtesting/
2. Click on the "Report Abuse" option.
3. Click on the "Submit" button without checking any radio button or entering any text inside the textarea field.

**Expected behavior**
The report is successfully submitted (same as in stage)

**Actual behavior**
* The "There was an error. Please try again in a moment." message is displayed
* The following sentry error is fired: https://mozilla.sentry.io/issues/4401326676/?project=4504326788808704&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Screencasts**
![ReportAbuseError](https://github.com/mozilla/sumo/assets/28087895/eace994c-5692-4420-92b0-af1d7b921acc)

**Desktop:**
- OS: Windows 10
- Browser: Firefox

**Additional context**
This issue is reproducible only on dev env (Can't reproduce on stage).

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5618
