### ISSUE TITLE
[Postgres][Dev] Accessing the kb dashboard redirects the user to "An Error Occurred" page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1437]
**Steps to reproduce**
1. Access the https://support-dev.allizom.org/en-US/contribute/kb page and click on the "Explore the Knowledge Base Dashboard" option from the "How you can contribute" section or navigate directly to the https://support-dev.allizom.org/en-US/contributors/kb-overview page.

**Expected behavior**
The KB Overview page is successfully displayed.

**Actual behavior**
The "An Error Occurred" page is displayed and sentry fires the https://mozilla.sentry.io/issues/4402531423/?project=4504326788808704&query=is%3Aunresolved&referrer=issue-stream&stream_index=0 error

**Screencasts**
![kb-overview](https://github.com/mozilla/sumo/assets/28087895/2dbb0f2a-98e4-4e3f-9fe9-262740f8dbe2)

**Desktop:**
 - OS: Windows 10.
 - Browser: Firefox

**Additional context**
Reproducible only on Dev end. Stage is not affected.

**Comment by escattone** [comment]
[Fix](https://github.com/mozilla/kitsune/pull/5609/commits/48282551b7d97a3f4b724321ddf1f5b8fa72cef1) coming for this.

**Comment by emilghittasv** [comment]
Same applies if having different products as query parameters. Example: /contributors/kb-overview?product=ios

This is just a note for myself to extend my verification when the fix for this issue lands.

**Comment by emilghittasv** [comment]
@escattone Since https://github.com/mozilla/kitsune/pull/5609/commits/48282551b7d97a3f4b724321ddf1f5b8fa72cef1 is still open/not landed yet, I'm moving this ticket inside the "in progress" column. Once the fix for this lands feel free to move it back inside QA !

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `dev` env. The Knowledge Base Overview dashboard is successfully displayed. 

Closing this ticket.
