### ISSUE TITLE
[Postgres][Dev] Unable to submit tickets to Zendesk for premium products

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1438]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access a contact support form for one of the premium products (example: https://support-dev.allizom.org/en-US/questions/new/mdn-plus/form)
2. Fill the form with valid data and click on the "Submit" button.

**Expected behavior**
A new ticket is successfully submitted to Zendesk.

**Actual behavior**
The "An Error Occurred" page is displayed and sentry fires the https://mozilla.sentry.io/issues/4404345321/?project=4504326788808704&query=is%3Aunresolved&referrer=issue-stream&stream_index=0 error

**Screencasts**
![Zendesk](https://github.com/mozilla/sumo/assets/28087895/46e3ba6d-5607-470d-ac9f-9962bc44970f)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible only on dev env (Stage is not affected).

**Comment by escattone** [comment]
@emilghittasv This is because the `dev` environment wasn't configured with the proper Zendesk settings. Can you try again?

**Comment by emilghittasv** [comment]
I can confirm that I'm able to submit tickets to Zendesk from `dev` successfully now! 

Moving this ticket inside the Done column.
