### ISSUE TITLE
[Postgres][Dev] Signing in to an FxA account in order to post a reply redirects the user to the SUMO homepage instead of redirecting back to the question

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1446]
**Preconditions**
Ensure that you are not connected to SUMO.

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/questions/1419356 (Or any other question).
2. Click on the "log in to your account" from the "You must log in to your account to reply to posts" section.
3. Sign in with a valid user account.

**Expected behavior**
The user is redirected back to the question.

**Actual behavior**
The user is redirected to the homepage.

**Screencasts**
![redirecttohomepage](https://github.com/mozilla/sumo/assets/28087895/01ca3a8e-8181-44ad-8153-94efbe6a8892)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* This issue is reproducible only in Dev. Stage and Prod are not affected.

**Comment by escattone** [comment]
@emilghittasv This should be fixed on `dev`. Can you verify the fix? The problem was very simple. I had forgot to adjust the site domain we store in the database. It was `support.mozilla.org`, but should have been modified to `support-dev.allizom.org`.

**Comment by emilghittasv** [comment]
Thanks Ryan! 

I can confirm that this issue is no longer reproducible on `dev`. Signing in to SUMO redirects the user back to the previous page instead of redirecting to the homepage.

Closing this ticket.
