### ISSUE TITLE
Create a survey CTA banner

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1463]
We need a CTA banner for a survey on all of our products. The requirements are:

* The banner will be shown to the Firefox product landing page to 10% of the received traffic. 
  * It won't be shown in the KB pages for Firefox.
* The banner will be shown to all KB pages for all other products to all visitors
* The banner will be behind feature flags

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5635

**Comment by emilghittasv** [comment]
I can confirm that:
* I've managed to enter inside the 10% user pool which are going to receive the CTA banner inside the Firefox product landing page so I can confirm that the targeted percentage rule is working and the CTA banner for the Firefox product landing page is successfully displayed for that pool of users. 
* The CTA banner is successfully displayed for the Firefox product landing page if the `dwf_product-cta-survey-banner` cookie is set to `True`. 
* The CTA banner is not displayed for the Firefox product landing page if the `dwf_product-cta-survey-banner` cookie is set to `False`.
* The CTA banner is successfully displayed for non-Firefox kb articles at all times.
* The CTA banner is not displayed for other products (other than Firefox) landing pages regardless of the `dwf_product-cta-survey-banner` cookie value.
* Clicking on the "Get Started" button for the Firefox landing page and non-Firefox kb articles CTA banner redirects the user to the form page successfully.
* Closing the CTA banner will no longer display the banner for that browser session (for both the CTA banner displayed inside the Firefox landing page & the CTA banner displayed in the non-Firefox kb articles)
* I can confirm that the CTA panel is successfully displayed on both macOS & Windows 10 devices while using: Chrome and Firefox browsers. 
* I can confirm that the CTA panel successfully responds to browsers window shrink & high contrast modes enabled.
* I can confirm that the CTA panel is successfully displayed on both Android & iOS mobile devices.

Moving this ticket inside the Release column.
