### ISSUE TITLE
CTA for Firefox Accounts Product Page

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1475]
Changes needed for Mozilla Account to show up in AAQ flow, present the correct CTA banners

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5646

**Comment by emilghittasv** [comment]
Testing activities are finalized for this ticket.

I can confirm that: 
* The CTA banner is successfully displayed on the Mozilla Account support page.
* Clicking on the CTA button from the Mozilla Account support page redirects the user to the Mozilla Account Solutions page and the CTA is successfully displayed on the right side of the page.
* Clicking on the CTA button displayed on the Mozilla Account Solutions page redirects the user to the login interstitial (if not signed in) or to the contact form (if signed in).
* Verified that the CTA is successfully displayed for the list of KB articles mentioned inside the figma file and, on click, it successfully redirects the user to the login interstitial or to the contact form.

Moving this ticket inside the "Release" column.

**Comment by yehiamohamedyehia281** [comment]
Thank you
