### ISSUE TITLE
[Postgres][Dev] The 0 search results page is not returned if searching for a non existing article or question

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1485]
**Steps to reproduce**
1. Navigate to https://support-dev.allizom.org/en-US/
2. Inside the searchbar type in something that should return 0 results (example: gewgwegwe)

**Expected behavior**
The page updates displaying the `Sorry! 0 results found for ‘gewgwegwe’ for ‘All Products’ ` message.

**Actual behavior**
The page does not update.

**Screencasts**
![NoResultsPage](https://github.com/mozilla/sumo/assets/28087895/e45df977-645c-4ce8-84ef-bb870c3306bb)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome & Firefox

**Additional context**
This issue is reproducible on `dev` environment only. `Stage` is not affected.

**Comment by emilghittasv** [comment]
Same thing is encountered when entering, inside the search field, a search term which is available only in one particular category (Help Articles or Community Discussions). 

When trying to change the filter to a category which doesn't contain that search result, the Sorry! 0 results page is not displayed.

Attaching a screencast:

![SearchFiltersa](https://github.com/mozilla/sumo/assets/28087895/65722c26-e0b4-44c9-9496-c7163ed22b48)

**Comment by escattone** [comment]
This appears to be due to [this query](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/wiki/facets.py#L115) which takes over 30 seconds in Postgres while in MySQL it's nearly instantaneous. I think the main factor is that Postgres does a full scan of the `wiki_helpfulvote` table (the second largest table with over 50 million rows) because it fails to use the index on the `created` column for the `>` operator (MySQL does use the index).

For example, with the simple query below, Postgres doesn't use the index when the `>` operator is used:

```sql
sumo_dev=> explain select * from wiki_helpfulvote where created > '2023-08-28 07:44:08.695289+00';
                                   QUERY PLAN
---------------------------------------------------------------------------------
 Seq Scan on wiki_helpfulvote  (cost=0.00..1811033.95 rows=18614372 width=635)
   Filter: (created > '2023-08-28 07:44:08.695289+00'::timestamp with time zone)
(2 rows)
```

but does when the `=` operator is used:

```sql
sumo_dev=> explain select * from wiki_helpfulvote where created = '2023-08-28 07:44:08.695289+00';
                                                      QUERY PLAN
----------------------------------------------------------------------------------------------------
 Index Scan using wiki_helpfulvote_created_06b8907e on wiki_helpfulvote  (cost=0.56..1008054.84 rows=279216 width=635)
   Index Cond: (created = '2023-08-28 07:44:08.695289+00'::timestamp with time zone)
(2 rows)
```

Below is more detail on the indexes, and specifically for the index on the `created` column:

```sql
sumo_dev=> \d wiki_helpfulvote
                                  Table "public.wiki_helpfulvote"
    Column    |           Type           | Collation | Nullable |             Default
--------------+--------------------------+-----------+----------+----------------------------------
 id           | integer                  |           | not null | generated by default as identity
 helpful      | boolean                  |           | not null |
 created      | timestamp with time zone |           | not null |
 anonymous_id | character varying(40)    |           | not null |
 user_agent   | character varying(1000)  |           | not null |
 creator_id   | integer                  |           |          |
 revision_id  | integer                  |           | not null |
Indexes:
    "wiki_helpfulvote_pkey" PRIMARY KEY, btree (id)
    "ryan_idx" brin (created)
    "wiki_helpfulvote_anonymous_id_e8881879" btree (anonymous_id)
    "wiki_helpfulvote_anonymous_id_e8881879_like" btree (anonymous_id varchar_pattern_ops)
    "wiki_helpfulvote_created_06b8907e" btree (created)
    "wiki_helpfulvote_creator_id_6cf03e69" btree (creator_id)
    "wiki_helpfulvote_revision_id_0684225e" btree (revision_id)
Foreign-key constraints:
    "wiki_helpfulvote_creator_id_6cf03e69_fk_auth_user_id" FOREIGN KEY (creator_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    "wiki_helpfulvote_revision_id_0684225e_fk_wiki_revision_id" FOREIGN KEY (revision_id) REFERENCES wiki_revision(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "wiki_helpfulvotemetadata" CONSTRAINT "wiki_helpfulvotemeta_vote_id_f64239b1_fk_wiki_help" FOREIGN KEY (vote_id) REFERENCES wiki_helpfulvote(id) DEFERRABLE INITIALLY DEFERRED
```
```sql
sumo_dev=> \d wiki_helpfulvote_created_06b8907e
    Index "public.wiki_helpfulvote_created_06b8907e"
 Column  |           Type           | Key? | Definition
---------+--------------------------+------+------------
 created | timestamp with time zone | yes  | created
btree, for table "public.wiki_helpfulvote"
```

**Comment by escattone** [comment]
Thanks to @jwhitlock for finding the solution to this by suggesting https://stackoverflow.com/questions/16639462/postgres-optimizing-querying-by-datetime, which worked like a charm. In terms of the Django ORM, the part of the query that did the filtering on the `created` field changed from:

```python
HelpfulVote.objects.filter(created__gt=datetime.now() - timedelta(days=30))
```

to:

```python
from django.db.models.functions import Now
...
HelpfulVote.objects.filter(created__range=(datetime.now() - timedelta(days=30), Now()))
```

**Comment by escattone** [comment]
@emilghittasv I fixed this in https://github.com/mozilla/kitsune/pull/5609 and pushed that branch to the `dev` environment. I checked and it seems to be fixed! Could you please confirm that when you have a chance?

**Comment by escattone** [comment]
This issue has revealed that we need to check for other places in our code where we're relying on an index for a timestamp range query, and make sure we make the same update to each of those places. I'm going to create a new issue for that.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `dev`.

All of my failing test cases due to this are green now.

Thanks Ryan for the fix!! 

Closing this ticket.
