### ISSUE TITLE
Popular searches are not working

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1486]
**Steps to reproduce**
1. Go to https://support.mozilla.org/en-US/
2. Click on one of the available popular searches.

**Expected behavior**
The search is performed for that particular popular search option.

**Actual behavior**
The search is not performed.

**Screencasts**
![PopularSearchess](https://github.com/mozilla/sumo/assets/28087895/e834bef8-eeff-4d5c-9ce9-cd521322f873)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox & Chrome.

**Additional context**
This issue is reproducible in both `stage` and `prod` envs.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on `stage`. Popular Searches are working again!

Verified on:
OS: Windows 10 & macOS11
Browsers: Firefox, Chrome & Safari

Also performed an additional exploratory testing and no regressions were encountered.

Moving this ticket inside the "Release" column.

**Comment by escattone** [comment]
Released!
