### ISSUE TITLE
SuMO Login interstitial banner 

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1491]
We need to add a banner to the login interstitial page on SuMO starting November 1st that will inform users that Firefox accounts have been renamed to Mozilla Accounts. The banner should also link to a SuMO KB article in another tab that offers more detail on the renaming. 

The banner should contain the following copy: 

"Firefox accounts is now Mozilla accounts.
You'll still sign in with the same username and password, and there are no other changes to the products that you use. Learn More" (https://support.mozilla.org/kb/firefox-accounts-renamed-mozilla-accounts)

The "Learn More" should link to the above URL in a new tab. We don't want to interrupt users login flow.

![interstitial_banner](https://github.com/mozilla/sumo/assets/87725469/ada6c663-d50e-4f44-9865-b5e776c198b6)

**Comment by akatsoulas** [comment]
this should be the relevant PR https://github.com/mozilla/kitsune/pull/5714

**Comment by emilghittasv** [comment]
Testing is done for this ticket.

* The banner is successfully displayed on the login interstitial page.
* The "Learn More" option redirects the user to the `firefox-accounts-renamed-mozilla-accounts` kb article in a new tab.
* The banner can be successfully closed via the X button.
* The banner is successfully displayed on mobile devices as well.

Moving this ticket inside the `release` column
