### ISSUE TITLE
[Postgres] adjust all timestamp range queries to ensure use of DB index

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1492]
Issue mozilla/sumo#1485 revealed that Postgres will not use an index for a timestamp range query unless `__range` is used rather than `__gt`, `__gte`, `__lt`, or `__lte`. We need to check all places where we're making range queries on indexed `DateTimeField` fields, and ensure we're using `__range` rather than things like `__gt`.

**Comment by escattone** [comment]
## Fields to Check

- [ ] `announcements.Announcement` -- [`show_after`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/announcements/models.py#L19)
- [ ] `announcements.Announcement` -- [`show_until`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/announcements/models.py#L25)
- [ ] `flagit.FlaggedObject` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/flagit/models.py#L47)
- [ ] `flagit.FlaggedObject` -- [`handled`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/flagit/models.py#L49)
- [ ] `forums.Thread` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/forums/models.py#L99)
- [ ] `forums.Post` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/forums/models.py#L183C4-L183C4)
- [ ] `forums.Post` -- [`updated`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/forums/models.py#L184)
- [ ] `gallery.Image` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/gallery/models.py#L16)
- [ ] `gallery.Image` -- [`updated`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/gallery/models.py#L17)
- [ ] `kbforums.Thread` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/kbforums/models.py#L36)
- [ ] `kbforums.Post` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/kbforums/models.py#L86)
- [ ] `kbforums.Post` -- [`updated`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/kbforums/models.py#L87)
- [ ] `messages.InboxMessage` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/messages/models.py#L39)
- [ ] `messages.OutboxMessage` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/messages/models.py#L63)
- [ ] `questions.QuestionVote` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L53)
- [ ] `questions.AnswerVote` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L53)
- [ ] `questions.Question` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L64)
- [ ] `questions.Question` -- [`updated`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L65)
- [ ] `questions.Answer` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L64)
- [ ] `questions.Answer` -- [`updated`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/questions/models.py#L65)
- [ ] `wiki.HelpfulVote` -- [`created`](https://github.com/mozilla/kitsune/blob/46cb36cc0c1655ac0c7c77275ced3b1c95c52fb6/kitsune/wiki/models.py#L1013)

**Comment by escattone** [comment]
## QA Notes

Test the following endpoints:

- https://support-dev.allizom.org/api/v1/kpi/kb-votes?locale=de&product=firefox returns data -- this is an expensive query that is cached for 3 hours
- https://support-dev.allizom.org/api/v1/kpi/questions?locale=de&product=firefox returns data -- this is an expensive query
- https://support-dev.allizom.org/api/v1/kpi/votes returns data -- this one fails in `prod` because it's such an expensive query, so i think it'll fail for `dev` as well
- https://support-dev.allizom.org/en-US/questions/firefox?filter=recently-unanswered&show=all
- https://support-dev.allizom.org/en-US/questions/firefox?filter=new&show=needs-attention
- https://support-dev.allizom.org/en-US/questions/firefox?filter=unhelpful-answers&show=needs-attention
- https://support-dev.allizom.org/en-US/questions/firefox?show=needs-attention
- https://support-dev.allizom.org/en-US/community/
- https://support-dev.allizom.org/en-US/community/top-contributors/questions
- https://support-dev.allizom.org/en-US/community/top-contributors/kb
- https://support-dev.allizom.org/en-US/community/top-contributors/l10n
- https://support-dev.allizom.org/api/2/user/weekly-solutions
- https://support-dev.allizom.org/en-US/kb/locales/en-US/
- https://support-dev.allizom.org/en-US/kb/locales/de/
- https://support-dev.allizom.org/en-US/kb/bookmarks-firefox/get-votes-async

**Comment by emilghittasv** [comment]
@escattone Here are the results of calling those endpoints:

**502 Bad Gateway**:
https://support-dev.allizom.org/api/v1/kpi/kb-votes?locale=de&product=firefox (works on `stage` & `prod`. Fails on `dev`)
https://support-dev.allizom.org/api/v1/kpi/votes (works on `stage` & `prod` if the call is performed again. It doesn't work in `dev`)
https://support-dev.allizom.org/en-US/kb/bookmarks-firefox/get-votes-async (works on `stage` & `prod`. Fails on `dev`)

**200 Ok**:

https://support-dev.allizom.org/api/v1/kpi/questions?locale=de&product=firefox
https://support-dev.allizom.org/en-US/questions/firefox?filter=recently-unanswered&show=all
https://support-dev.allizom.org/en-US/questions/firefox?filter=new&show=needs-attention
https://support-dev.allizom.org/en-US/questions/firefox?filter=unhelpful-answers&show=needs-attention
https://support-dev.allizom.org/en-US/questions/firefox?show=needs-attention
https://support-dev.allizom.org/en-US/community/
https://support-dev.allizom.org/en-US/community/top-contributors/questions
https://support-dev.allizom.org/en-US/community/top-contributors/kb
https://support-dev.allizom.org/en-US/community/top-contributors/l10n
https://support-dev.allizom.org/api/2/user/weekly-solutions
https://support-dev.allizom.org/en-US/kb/locales/en-US/
https://support-dev.allizom.org/en-US/kb/locales/de/

**Comment by escattone** [comment]
@emilghittasv Thank you! I looked at the code in detail again (for example, doing `explain`s and comparing between MySQL and Postgres) for the first failure you listed (https://support-dev.allizom.org/api/v1/kpi/kb-votes?locale=de&product=firefox), and couldn't find anything amiss. I then realized that the `dev` database instance had 8 times **less** CPU and memory! When I increased the power of the `dev` instance to equal the power of `prod`, the first and third of your three listed failures immediately worked! 🎉 However, I'm still getting a 502 error with https://support-dev.allizom.org/api/v1/kpi/votes, so I'll continue to look into that one tomorrow.

**Comment by escattone** [comment]
So one issue remains, a `502` error when requesting https://support-dev.allizom.org/api/v1/kpi/votes.

**Comment by escattone** [comment]
@emilghittasv I've made a change to the `switch-to-postgres` branch, and re-based the `dev` branch on `switch-to-postgres`, so that change is available in the `dev` environment. Could you please confirm at least that the following endpoints work (i.e., don't timeout), but feel free to test all of the endpoints listed above if you'd prefer. However, since most of these endpoints are cached, could you let me know right before you want to run your tests, and I'll clear the cache.
- https://support-dev.allizom.org/api/v1/kpi/votes
- https://support-dev.allizom.org/api/v1/kpi/kb-votes
- https://support-dev.allizom.org/api/v1/kpi/questions

**Comment by emilghittasv** [comment]
@escattone I can confirm that all of the endpoints mentioned in this ticket are successfully loading without timeouts.
