### ISSUE TITLE
Consider hiding the "Sign In/Up" option from the footer section if the user is already signed in to SUMO

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1495]
**Preconditions**
Sign in to SUMO.

**Steps to reproduce**
1. Click on the "Sign in/up" from the "Firefox Accounts" section displayed inside the footer section.

**Expected behavior**
The "Sign in/up" option from the "Firefox Accounts" section displayed inside the footer section is not displayed if the user is already signed in to SUMO.

**Actual behavior**
The "Sign in/up" option from the "Firefox Accounts" section is displayed even if the user is already signed in to SUMO and clicking on the option refreshes the SUMO page.

**Screencasts**
![footersigninandup](https://github.com/mozilla/sumo/assets/28087895/a8c3eb48-b419-495d-9f6c-aeac9b9043a4)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5719

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed.

The "Sign In/Up" option from the footer section is successfully displayed if the user is not signed in/signs out & the option is successfully hidden if the user signs in.

Moving this ticket inside the `release` column
