### ISSUE TITLE
Trying to access the "View Profile" and "My Questions" pages while signed in with accounts that contain special characters (+)  inside the username leads to "Page not Found"

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1496]
**Describe the bug**
This has been caught by our Selenium automated scripts and I can confirm that this is a valid issue:

![image](https://github.com/mozilla/sumo/assets/28087895/8e3088ef-a200-444b-986a-792e4caec4db)

**Preconditions**
Sign in with an account that contains a special (but accepted) character inside the username. (Example: testMozilla+14)

**Steps to reproduce**
1. Mouseover the "Username" inside top-navbar and click on the "View Profile" or "My Questions" options.

**Expected behavior**
The "View Profile" or "My Questions" pages are successfully displayed.

**Actual behavior**
It can be noticed that, the URL gets constructed wrong when clicking on those options: https://support.allizom.org/en-US/en-US/user/testMozilla%2014/ (notice the duplicity of the locale). This leads to a "Page Not Found"

**Screencasts**
![pagenotfoundlocale](https://github.com/mozilla/sumo/assets/28087895/0f28299d-071d-439e-868d-b45664cbef76)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage`. `prod` is not affected.

**Comment by emilghittasv** [comment]
This issue is verified fixed (manually) + I've re-triggered the Selenium Workflow and tests are green again!

Moving inside the "Release" column.

**Comment by escattone** [comment]
Released!
