### ISSUE TITLE
fix  `wiki.get_fallback_locale()`

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1499]
I noticed two problems with `wiki.get_fallback_locale()`:

- We're using a [custom `parse_accept_lang_header`](https://github.com/mozilla/kitsune/blob/36561c542a0ccc6dfe8807d4cff14abeaa267ece/kitsune/wiki/views.py#L1718) when we should be using Django's (`from django.utils.translation.trans_real import parse_accept_lang_header`).
- Within [`wiki.get_fallback_locale()`](https://github.com/mozilla/kitsune/blob/36561c542a0ccc6dfe8807d4cff14abeaa267ece/kitsune/wiki/views.py#L1675), we don't ensure that we're comparing strings of the same case when we compare locales from `all_accepted_locales` to those in `translated_locales`, which means that we may fail to use the proper fallback depending on the case used for the locales in the `Accept-Language` header. For example, if we have `SV;q=0.9,pt-br;q=0.8,fr;q=0.7` for the `Accept-Language` header, we'll never use `SV` or `pt-br` since `sv` and `pt-BR` have to be specified in order to fallback to Swedish or Brazilian Portugese.

**Comment by escattone** [comment]
## QA Notes
- [ ] Create a test article in English (let's give it the slug `test-fix-1499`), and 3 translations for it (`pt-BR`, `sv`, and `nl`).
- [ ] Request https:/support.allizom.org/fr/kb/test-fix-1499 using an `Accept-Language` header of `pt-br,fr;q=0.8,en-us;q=0.7` (case matters!). It should redirect to https:/support.allizom.org/pt-BR/kb/test-fix-1499.
- [ ] Request https:/support.allizom.org/fr/kb/test-fix-1499 using an `Accept-Language` header of `sv-se,fr;q=0.8,en-us;q=0.7` (case matters!). It should redirect to https:/support.allizom.org/sv/kb/test-fix-1499.
- [ ] Request https:/support.allizom.org/fr/kb/test-fix-1499 using an `Accept-Language` header of `fy-nl,fr;q=0.8,en-us;q=0.7` (case matters!). It should redirect to https:/support.allizom.org/nl/kb/test-fix-1499.

**Comment by emilghittasv** [comment]
I can confirm that hitting those enpoints with the mentioned `Accept-Language` headers will retrieve the correct kb article. The title & content of the kb articles are in the `pt-BR`, `sv` and `nl` version.

Moving this ticket inside the "Release" column.

**Comment by escattone** [comment]
Released!
