### ISSUE TITLE
article caching problems when using a fallback locale

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1500]
While working on https://github.com/mozilla/sumo/issues/1499 I realized that we have an article caching problem when we have a locale fallback situation for an article request. For example,

- An article, say `/fr/kb/some-article` is requested.
- There's no `fr` translation for `some-article`.
- We fallback to a locale in the request's `Accept-Language` header for which we have a translation.
- We return the response with the document title and content from the fallback locale. Let's say it's `de`.
- If the cache entry for `doc_html:fr:some-article` (the cache key) is empty, we cache the response with the content from the `de` document.
- The next user that requests `/fr/kb/some-article` with an `Accept-Language` header that doesn't include `de`, will be surprised to find that they get the cached response that includes the `de` article's content.

So we have two related problems:
1. We're not varying the document cache key based on the fallback language, if there is one.
2. We're not setting the [`Vary` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) appropriately. We should be doing something like `patch_vary_headers(response, ("Accept-Language",))` when we return a response using a fallback locale we've selected from the request's `Accept-Language` header.

It might be the right time to consider if we want to continue supporting this fallback mechanism. [Bugzilla bug #800880](https://bugzilla.mozilla.org/show_bug.cgi?id=800880) is a good reference for understanding its origin.

**Comment by escattone** [comment]
## QA Notes

Sorry for the delay on these notes @emilghittasv! This one is going to be really tricky to QA. Since we don't cache on stage or dev, we'll have to QA on production before we release to confirm the bug exists, and then after release, confirm that it no longer exists.

Here are the conditions to trigger the bug:
- Create a test KB article and translate it into at least one language, for this example `ro`.
- Modify the `Accept-Language` header that you'll use for your request to only include a non-English language for which the KB article has a translation, for this example `ro`, so for example `Accept-Language: ro;q=1.0`. Do not include English in the header.
- Request the KB article (using the English slug) in a locale for which it does NOT have a translation -- for example, `/yo/kb/test-article-slug`. This locale must not have been requested before.
- Check that the language of the article content (not the "chrome", like the menu items, etc.) is actually Romanian.
- Modify the `Accept-Language` header that you'll use for your next request to exclude Romanian. The easiest thing would be to only allow English.
- Request the KB article again using `/yo/kb/test-article-slug`.
- If you still see the article content in Romanian, the bug has occurred.
- If instead you see the article content in English, or whatever language you allowed in your `Accept-Language` header, then the bug is NOT present. In this case, you should also see the string `Accept-Language` (case insensitive) in the value of the `Vary` header of the response.

It may also be helpful to reference the unit test that walks through this process: https://github.com/mozilla/kitsune/blob/a61d27366b479a0dee613539da728cbc8f7f0607/kitsune/wiki/tests/test_views.py#L2365.

**Comment by emilghittasv** [comment]
Thank you for the awesome QA steps, Ryan!!!

I was able to reproduce this in `prod`
