### ISSUE TITLE
Navigating to a product page while leaving out the locale and having a trailing slash applied returns a 404 (example: https://support.mozilla.org/products/firefox/)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1501]
**Describe the bug**
A contributor mentioned that navigating to https://support.mozilla.org/products/firefox/ (with a trailing slash applied and no locale mentioned) returns a 404 page. This occurs with other products as well.

**Steps to reproduce**
1. Go to https://support.mozilla.org/products/firefox/ (or any other product)

**Expected behavior**
The user is redirected to https://support.mozilla.org/en-US/products/firefox

**Actual behavior**
A 404 page is returned.

**Desktop:**
- OS: Windows & macOS.
- Browser: Chrome & Firefox.

**Additional Notes**
* This might be related to the work performed in https://github.com/mozilla/sumo/issues/1469. I've built SUMO locally and I can't reproduce without the i18n changes applied.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The user gets redirected to the correct page locale:

* If navigating to `https://support.allizom.org/products/firefox-private-network-vpn/` , SUMO will automatically redirect to `https://support.allizom.org/en-US/products/firefox-private-network-vpn`. If the preferred language at profile level is set to something else rather than `en-US` it will redirect successfully to that locale. 

Same occurs with kb article endpoints (Navigating to `https://support.allizom.org/kb/how-save-web-page-testd/` will successfully redirect the user to that particular kb article in the correct locale).

* Verified this using the `Accepted-Language` header while not signed in to SUMO (no preferred language set/applied) and it successfully redirects to the value/locale specified inside the `Accepted-Language` header

* Verified this while using the `lang` parameter applied. Navigating to `https://support.allizom.org/products/firefox/?lang=it` will automatically redirect to `https://support.allizom.org/it/products/firefox`

Moving this ticket inside the Release column.

**Comment by escattone** [comment]
Released!
