### ISSUE TITLE
Sitewide Banner explaining ongoing work for Mozilla Account renaming.

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1502]
Can we please add a site-wide banner that will help mitigate questions regarding articles verbiage updates regarding renaming Firefox Accounts to Mozilla Accounts. Copy is as follows: 

**Firefox accounts will be renamed Mozilla accounts on Nov 1**
You'll still sign in with the same username and password, and there are no other changes to the products that you use. You may see updated help articles that refer to Mozilla accounts before Nov 1. Learn more(https://mzl.la/461jUjP) 

Learn more link will link out to article: https://support.mozilla.org/kb/firefox-accounts-renamed-mozilla-accounts

This banner should remain up until November 2, 2023.

**Comment by escattone** [comment]
✅  Done!
