### ISSUE TITLE
Switching devices wizard should update all references of Firefox accounts to Mozilla accounts.

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1506]
This is part of the broader FxA rebranding effort underway, and we'd best do our part here.

**Comment by emilghittasv** [comment]
I can confirm that the "You are now signed in to your Firefox account" has changed to "You are now signed in to your Mozilla account" inside the step 2 of the Wizard.

I'm moving this ticket from the closed column inside the "Release" column (until we push this to `prod`). Also assigning Mike to this ticket and moving inside the current sprint.
