### ISSUE TITLE
Knowledge Base Dashboard subscriptions cannot be modified

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1509]
**Describe the bug**
A user has mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1859181 that the subscribe panel from the Knowledge Base Dashboard page is broken (notification settings cannot be updated)

**Preconditions**
Sign in to SUMO.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/contributors
2. Click on the "Subscribe" button.
3. Check or uncheck the boxes. 
4. Refresh the page and click on the "Subscribe" button again.

**Expected behavior**
The checkboxes can be successfully modified (once checked they can be unchecked again). And after refreshing the SUMO page and accessing the "Subscribe" panel again, the previously checked checkboxes status should be saved and displayed accordingly.

**Actual behavior**
Once the checkoxes are checked they cannot be unchecked (they become greyed out). 
If the user checks a checkbox, refreshes the page and clicks on the "Subscribe" button it can be noticed that the previously checked checkboxes are not displayed as checked.

**Screencasts**
![kbsubscribe](https://github.com/mozilla/sumo/assets/28087895/6478c09d-e628-4c6d-b04e-0031a1a15fcb)

**Desktop:**
 - OS: Window 10
 - Browser: Firefox

**Additional context**
Reproducible on both `stage` and `prod`

**Comment by plwt** [comment]
To clarify, it was reported by a Mozilla contributor, not a user.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5780

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Subscription options/checkboxes can be successfully modified and the checkboxes states are preserved after a page refresh or after the user logs out/back in to SUMO.

As of our current messaging system state in `stage` & `prod` it's quite hard to test if the subscription options are successfully applied and if the e-mail notifications are successfully sent or no longer sent (depending on the checkboxes state) to a particular user. 

I'm moving this ticket inside the `release` column and will verify the e-mail notification in `prod`.
