### ISSUE TITLE
Mozilla Account top-navbar options are not arranged per the Figma design

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1510]
**Steps to reproduce**
1. Mouse-over the "Get Help" top-navbar menu option.

**Expected behavior**
As per the [figma design](https://www.figma.com/file/JIZmAskexNygAajEIvHEv1/Login-less-Account-Support-Journey?type=design&node-id=458-4935&mode=design&t=GScmznvNpAFZVy9G-0), the "Mozilla Account" section has the items arranged similar to the following screenshot:
![image](https://github.com/mozilla/sumo/assets/28087895/08c396ed-b0f9-4cdb-a2df-098a60a4e883)

On the first column the "What Is It?", "Reset My Password" and "Sync My Data" options.
On the second column only the "Get Help" option

**Actual behavior**
The "Mozilla Account" options are placed:
On the first column we have the "What is it?" and "Sync My Data" options
On the second column we have the "Reset Password" and "Get Help" options

See the attached screencast (ignore the greyed out screenshot aspect).
![image](https://github.com/mozilla/sumo/assets/28087895/3fa797bf-e697-4e18-9e29-c1b4fa74175a)

**Desktop:**
 - OS: Windows 10, macOS 11
 - Browser: Firefox, Chrome

**Comment by emilghittasv** [comment]
@smithellis I'm wondering if, somehow, the design has changed and the Figma doc was not updated.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5707

**Comment by emilghittasv** [comment]
I can confirm that the top-navbar elements under the "Mozilla Account" section are ordered into two columns (left column has 3 elements and right column has 1 element).

During the verification of this ticket I've noticed that the elements from the left column are not ordered as per the Figma design doc. Filled under -> https://github.com/mozilla/sumo/issues/1542

I'm moving this ticket inside the `release` column. Let's keep track of the follow-up issue separately.
