### ISSUE TITLE
The "Get Help" footer option redirects the user to the /products/mozilla-accounts instead of products/mozilla-account

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1511]
**Describe the bug**
I've noticed that the "Get Help" option from the footer section redirects the user to the `/products/mozilla-accounts` page (which is invalid since I suppose we are going to apply the `mozilla-account` slug to the new Mozilla Account product page).

**Steps to reproduce**
1. Click on the "Get Help" option from the footer section.

**Expected behavior**
The user is redirected to the `products/mozilla-account` page.

**Actual behavior**
The user is redirected to the `/products/mozilla-accounts` page (which is invalid).

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
There is currently a discrepancy between the "Get Help" option from the top-navbar which redirects to the `mozilla-account` product slug -> https://github.com/mozilla/kitsune/pull/5644/commits/a080456c8eca72d30acc8967a4892e65934f9c20 and the "Get Help" option from the footer section which redirects to the `mozilla-accounts` product slug -> https://github.com/mozilla/kitsune/blob/18b1137c669f128e5ad2595676bbaf1f3a90e116/kitsune/sumo/jinja2/base.html#L261

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5678

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The "Get Help" option from the footer section redirects to the `products/mozilla-account` product slug now.

Moving this ticket inside the "Release" column.
