### ISSUE TITLE
Some "Mozilla Account" subpanel links are wrong

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1513]
**Steps to reproduce**
1. Mouseover the "Get Help" top-navbar option.
2. Click on the "Mozilla Account" top-navbar `h4` element.
3. Redo step 1 and click on the "What is it?" option.

**Expected behavior**
* Step 2: The user gets redirected to the `mozilla-account` product page. (not entirely sure about this one because I couldn't find the documentation for this element)
* Step 3: The user is redirected to the https://support.mozilla.org/en-US/kb/access-mozilla-services-firefox-account kb article.

**Actual behavior**
* Step 2: The user is redirected to the `products/` page.
* Step 3: The user is redirected to the https://www.mozilla.org/en-US/firefox/accounts/ page.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5683

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`. 

The "Mozilla Account" top-navbar header redirects the user to the `mozilla-account` product page & the "What is it?" option redirects the user to the "Access Mozilla services with a Mozilla account" kb article.

Moving this ticked inside the `release` column.
