### ISSUE TITLE
Generated ICS file from switching devices reminder dialog is not an all-day event for Outlook

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1514]
iCal seems to interpret what we're generating now as an all-day event, but the Outlook calendar application does not.

We need to change the format of the VEVENT to something like this (for a Nov 2 event):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Mozilla.org/NONSGML support.mozilla.org switching devices wizard V1.0//EN
BEGIN:VEVENT
UID:20231101T000000Z0.13464522250091393
DTSTAMP:20231018T000000Z
DTSTART:20231101
DTEND:20231102
SUMMARY: [see copy doc]
DESCRIPTION: [see copy doc]
END:VEVENT
END:VCALENDAR
```

**Comment by emilghittasv** [comment]
I can confirm that an all day event is successfully created when selecting the "Outlook.com" option or after opening the downloaded .ics file locally in Outlook.

Moving this ticket inside the "Release" column.
