### ISSUE TITLE
Localization newsletter produces wrong links pointing to KB

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1517]
Eg https://support.mozilla.org/fr/fr/kb/portail-captif/history

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5688

**Comment by AliceWyman** [comment]
Similar issue with "[Reviews Pending: en-US] SUMO needs your help!'' emails to reviewers.  All of the listed article links are bad, with double en-US in the URL.  For example, here's one ofthe KB article links from the email I got this morning: https://support.mozilla.org/en-US/en-US/kb/dns-over-https-doh-faqs/history (I also posted about this in the SUMO room on Matrix).

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The KB article links are working again (no duplicate locale inside the URL).

Moving this ticket inside the `release` column.
