### ISSUE TITLE
The legal footer information has a different font size inside the contribute page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1518]
**Steps to reproduce**
1. Access the SUMO homepage and notice the font size of the legal information from the footer section.
2. Access the Contribute page and notice the font size of the legal information from the footer section.

**Expected behavior**
The legal information has the same font size on both pages.

**Actual behavior**
The font size for the legal information inside the Contribute page is `1rem` making it bigger.

**Screencasts**
![contributefooterfont](https://github.com/mozilla/sumo/assets/28087895/0c4e5702-000a-4080-82d0-2ea30a4ce000)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Reproducible in both `stage` and `prod`

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5779

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on `stage`.

Tested on:
Windows 10: Firefox & Chrome
Huawei P40Pro: Firefox 
iPhone 12: Safari.

Moving this ticket inside the `release` column.
