### ISSUE TITLE
The "Mozilla Account" top-navbar menu contains "Mozilla Account" instead of "Mozilla account" inside the description section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1519]
**Steps to reproduce**
1. Mouseover the "Get Help" top-navbar option.
2. Observe the "Mozilla Account" section.

**Expected behavior**
The "Find help for common issues and learn about the benefits a Mozilla account provides" text is displayed (with the "Account" in lower case). As per the https://www.figma.com/file/JIZmAskexNygAajEIvHEv1/Login-less-Account-Support-Journey?node-id=458%3A4935&mode=dev

**Actual behavior**
"Find help for common issues and learn about the benefits a Mozilla Account provides" text is displayed

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Reproducible on `stage`

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5707

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The "Find help for common issues and learn about the benefits a `Mozilla Account` provides" changed to "Find help for common issues and learn about the benefits a `Mozilla account` provides".

Moving this ticket inside the `release` column
