### ISSUE TITLE
Dupee badge for KB 

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#153]
Go to https://support.mozilla.org/en-US/badges/. There are 2 badges for KB badge. The [2021 badge ](https://support.mozilla.org/en-US/badges/badge/2021-kb-badge)should be removed from the list due to the wrong year.

**Comment by emilghittasv** [comment]
Hey @kelimuttu !

It seems that this issue is no longer reproducible. 

Please feel free to re-open this ticket if this is still reproducible for you!
