### ISSUE TITLE
Unable to submit Zendesk tickets (500 Internal Server Error)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1533]
**Preconditions**
Sign in to SUMO on stage

**Steps to reproduce**
1. Access the Contact Support form for any premium product.
2. Fill out the form and click on the "Submit" button.

**Expected behavior**
The ticket is successfully submitted to Zendesk.

**Actual behavior**
The ticket is not submitted to Zendesk and the "Internal Server Error (500)" page is displayed.

**Screencasts**
![ZendeskSubmit](https://github.com/mozilla/sumo/assets/28087895/f64c64cc-1935-4585-b009-c8fb7b41e22d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Occurs with the following premium products: Mozilla Account (logged in form), Hubs, MDN Plus, Pocket, Relay, Mozilla VPN

Reproducible on `stage`. `prod` is not affected.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5701

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed now.

Zendesk tickets can be successfully sent for all premium products while signed in to SUMO.

Moving this ticket inside the "Release" column.
