### ISSUE TITLE
CTA's from the "Mozilla Account Solutions" & "Featured Topics List" pages are redirecting directly to the loginless form

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1535]
**Describe the bug**
The CTA's from the "Explore Solutions" & "Featured Topics List" pages, as per the figma file, should redirect to the login interstitial (if the user is not signed in to SUMO).

**Preconditions**
Ensure that you are not signed in to SUMO

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/questions/new/mozilla-account or the https://support.allizom.org/en-US/products/mozilla-account/troubleshoot-accounts page and click on the "Contact Support" button from the CTA.

**Expected behavior**
The user is redirected to the login interstitial.

**Actual behavior**
The user is redirected directly to the loginless form.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5710

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed.

The not logged in user is successfully redirected to the login interstitial page if interacting with the CTA's from the "Mozilla Account Solutions" & "Featured Topics List" pages. 

If they are interacting with the CTA from those specific KB articles, they are redirected directly to the loginless form.

Also verified that no regressions are encountered when interacting with all the mentioned CTA's while the user is logged in (the normal user form is displayed in all cases).

Moving this ticket inside the `release` column.
