### ISSUE TITLE
Progress bars on Localization dashboard are not displayed

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1538]
More info: https://bugzilla.mozilla.org/show_bug.cgi?id=1861628

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5737

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5744

**Comment by emilghittasv** [comment]
I can confirm that the progress bars are successfully displayed inside the localization dashboards for both the "Localization" & "Review" tables:



![Image](https://github.com/mozilla/sumo/assets/28087895/6de7defe-e920-429e-a483-117fdef1fa0e)

![Image](https://github.com/mozilla/sumo/assets/28087895/3bb02179-7301-41d0-9c76-0d702c4a7f94)

The progress bars are also successfully displayed inisde the https://support.allizom.org/ro/localization/unreviewed & https://support.allizom.org/ro/localization/most-visited-translations pages.



![Image](https://github.com/mozilla/sumo/assets/28087895/ac951922-eef8-416b-b8c3-33ddfaf30f28)
![Image](https://github.com/mozilla/sumo/assets/28087895/f4b5b8c2-c36d-41b7-bd8e-50f8cf630631)


Testing was performed on:
Windows 10: Chrome & Firefox browsers
macOS 11: Safari & Firefox browsers
Huawei P40Pro: Firefox
iPhone 13Pro: Safari

Moving this ticket inside the release column.
