### ISSUE TITLE
Wrong order of elements displayed inside the "Mozilla Account" top-navbar section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1542]
**Steps to reproduce**
1. Mouseover the "Get Help" top-navbar option.
2. Observe the "Mozilla Account" section.

**Expected behavior**
As per the [figma file](https://www.figma.com/file/JIZmAskexNygAajEIvHEv1/Login-less-Account-Support-Journey?type=design&node-id=458-4935&mode=design&t=g4cSHMifPZ0YOBxo-0), the left column elements should be ordered by: `What Is It?`, `Reset Password` and `Sync My Data`

**Actual behavior**
The left column elements are ordered by: `What Is It?`, `Sync My Data` and `Reset Password`

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5718

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The order for the left column elements has changed to: `What is it?`, `Reset Password`, `Sync Your Data`

Moving this ticket inside the `release` column.
