### ISSUE TITLE
The "Learn More" option from the interstitial banner is opening the link to the KB article inside the same tab

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1546]
**Describe the bug**
As JC mentioned in https://github.com/mozilla/sumo/issues/1491, `The "Learn More" should link to the above URL in a new tab. We don't want to interrupt users login flow.`

**Preconditions**
Ensure that you are not signed in to SUMO.

**Steps to reproduce**
1. Access the login interstitial.
2. Click on the "Learn More" option from the banner.

**Expected behavior**
The `firefox-accounts-renamed-mozilla-accounts` kb article gets open in a new tab.

**Actual behavior**
The `firefox-accounts-renamed-mozilla-accounts` kb article gets open inside the same tab.

**Desktop:**
 - OS: Windows 10 
 - Browser: Firefox & Chrome

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5730

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The `firefox-accounts-renamed-mozilla-accounts` kb article is opened inside a new tab after clicking on the "Learn More" option from the login interstitial banner. 

Moving this ticket inside the `release` column
