### ISSUE TITLE
Mozilla Account popular searches change to singular

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1555]

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5741

I think there was some regression from:
https://github.com/mozilla/kitsune/pull/5687

I only updated visible text, not comments.

Reference for spec is here:
https://www.figma.com/file/7nsOBSt3VTeCimDqavQT9J/Mozilla-Accounts-Content-Guidelines?type=design&node-id=1903%3A134&mode=design&t=2bBGEK22py8bVsKf-1

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The `Mozilla accounts` popular search has changed to `Mozilla account` and the popular searches are functional.

Tested on both Firefox & Chrome browsers. 

Moving this ticket inside the `release` column.
