### ISSUE TITLE
Copy update - update first_l10n.html email template

### ISSUE THREAD

**Issue by ghostinhershell** [mozilla/sumo#1558]
**Describe the bug**
We would like to update the copy of our contributor first l10 email that we sent when a user signed up in order to update old links and overall improve the email copy.
https://github.com/mozilla/kitsune/blob/a709f49525aabd16be84aa8c344524b39d4b4b5a/kitsune/community/jinja2/community/email/first_l10n.html

**The current email copy should be replaced with the following text:**

{# This does not need translated, since it is being sent to localizers. #}
{% extends 'email/base.html' %}

{% block content %}
  <p>
    Thank you for your first contribution to our Knowledge Base in your
    language! You can consider yourself an Open Web rockstar on the rise.
    :-) Your contribution will now undergo review by our awesome community
    members and will be published after it is reviewed.
  </p>

  <p>
    SUMO has millions of visitors each month and more than 60% of them view
    pages in languages other than English. You may think that you
    translated just one page, but for all the users who speak your language
    it makes a <strong>huge</strong> difference.
  </p>

  <p><strong>Team up</strong></p>
  <p>
    It’s always a good idea to get in touch with your Locale Leaders.
    <a href="https://support.mozilla.org/en-US/kb/locales">
        You can find them clicking your language’s name in this list
    </a>.
    Send them a Private Message - they are there to help you help others
    through your localizing skills!
  </p>

  <p>
    If you want to get in touch with other people localizing SUMO in your
    language,
    <a href="https://support.mozilla.org/en-US/forums/l10n-forum/">
      go to our l10n forums
    </a>.
    You can also find people hanging out on IRC at
    <a href="https://chat.mozilla.org/#/room/#SUMO:mozilla.org">
      #sumo.
    </a>
  </p>

  <p><strong>Stay in touch</strong></p>
  <p>
    Finally, if you want to follow all news related to SUMO, don’t forget about
    <a href="https://support.mozilla.org/en-US/questions/">
      our community forums
    </a>,
    <a href="https://blog.mozilla.org/sumo/">
      official blog
    </a>
    and
    <a href="https://twitter.com/sumo_mozilla">
      Twitter account
    </a>.
    We also
    <a href="https://wiki.mozilla.org/Support/Weekly_Meetings">
      meet once a month during our Community Calls
    </a>
    - you can join us there.
  </p>

  <p><strong>Keep rocking</strong></p>
  <p>
    So, now that you know how easy it is to improve our community-powered
    support wiki in your language, why not
    <a href="/localization">
      localize another article
    </a>?
  </p>

  <p>
    Thank you once more. We are looking forward to seeing you more often
    around SUMO!
  </p>
{% endblock %}

**Comment by kelimuttu** [comment]
**Updated copy with HTML markup included & updated URLs:**

`{# This does not need translated, since it is being sent to localizers. #}`
`{% extends 'email/base.html' %}`

`{% block content %}`
  `<p>`
    `Thank you for your first contribution to our Knowledge Base in your language! You can consider yourself an Open Web rockstar on the rise. :-) Your contribution will now undergo review by our awesome community members and should be published soon.`
  `</p>`

  `<p>`
    `SUMO has millions of visitors each month, and more than 60% of them view pages in languages other than English. You may think that you translated just one page, but for all the users who speak your language, it makes a <strong>huge</strong> difference.`
  `</p>`


  `<p><strong>Team up</strong></p>`
  `<p>`
    `It’s always a good idea to get in touch with your Locale Leaders. You can find them by clicking on your language’s name in <a href="/locales">this list</a>. Send them a Private Message - they are there to help you help others through your localizing skills!`
  `</p>`

  `<p>`
    `If you want to get in touch with other people localizing SUMO in your language, go to our <a href="/forums/l10n-forum/">l10n forum</a>. You can also find people hanging out on Matrix at <a href="https://chat.mozilla.org/#/room/#SUMO:mozilla.org">#sumo channel</a>.`
  `</p>`

  `<p><strong>{{ _('Stay in touch') }}</strong></p>`
  `<p>`
      `Finally, if you want to follow all news related to SUMO, don’t forget about our <a href="/forums/contributors">community forums</a>, <a href="https://blog.mozilla.org/sumo/">official blog</a>, and <a href="https://twitter.com/sumo_mozilla">Twitter account</a>. We also <a href="https://wiki.mozilla.org/Support/Weekly_Meetings">meet every month </a> - and you can <a href="/kb/how-participate-sumo-contributor-meetings">join us</a>.`
  `</p>`

  `<p><strong>Keep rocking</strong></p>`
  `<p>`
    `So, now that you know how to improve our community-powered support wiki in your language, why not <a href="/localization">localize another article</a>?`
  `</p>`

  `<p>`
    `Thank you once more. We are looking forward to seeing you more often around SUMO!`
  `</p>`
`{% endblock %}`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5756

**Comment by kelimuttu** [comment]
Same here. I'd like to be review the email when we test this. @emilghittasv

**Comment by emilghittasv** [comment]
@kelimuttu I've sent you the `first_l10n` e-mail. Please let us know if everything looks in order so we can close this ticket! 

Thank you!

**Comment by kelimuttu** [comment]
Actually, this was not on my updated copy above. But can you change the link from `/locale` to `/kb/locales` from the **Team up** section? 

Recently, I just found out that `/locale` takes people to a localized homepage instead of the locale team page (which is the page that we intended in the first place).

**Comment by akatsoulas** [comment]
@emilghittasv is this verified?

**Comment by emilghittasv** [comment]
@akatsoulas I've sent the e-mail to @kelimuttu for another confirmation as requested.

The link now successfully points out to /kb/locales.

Kiki, are we good to close this ticket?

**Comment by kelimuttu** [comment]
All good! Sorry for being slow-res today.
