### ISSUE TITLE
Copy Update: Update first_answer.html email template

### ISSUE THREAD

**Issue by ghostinhershell** [mozilla/sumo#1559]
### Describe the bug
We would like to update the copy of our contributor first answer email that is sent when a user answers their first question in order to update old links and overall improve the email copy.
https://github.com/mozilla/kitsune/blob/a709f49525aabd16be84aa8c344524b39d4b4b5a/kitsune/community/jinja2/community/email/first_answer.html

### The current email copy should be replaced with the following text:

{% extends 'email/base.html' %}

{% block content %}
  <p>
    {% trans %}
      Thank you for your first contribution to the Mozilla support
      forums! You just made somebody's day!
    {% endtrans %}
  </p>

  <p>
    {% trans %}
      Mozilla support is fully powered by our volunteer community that is
      helping hundreds of users everyday. This community is formed by
      passionate Firefox and Thunderbird users who take some of their
      spare time to help others. We couldn't do it without your passion
      and enthusiasm. Your contribution, as minor as it might seem, has
      tremendous value. Solving one issue in the support forums can help
      up to 1000 users a day!
    {% endtrans %}
  </p>

  <p><strong>{{ _('Tell us about yourself!') }}</strong></p>

  <p>
    {% trans intro_url='/forums/contributors', irc_url='https://chat.mozilla.org/#/room/#SUMO:mozilla.org&channel=#sumo' %}
      We are always very happy to hear from new people who like helping
      on the forums so if you haven’t met our community yet
      <a href=""https://support.mozilla.org/en-US/questions/>
        please take a minute to look through the community
      </a>.
      If you want to stay low-profile, that’s also ok :). You can also
      find us all hanging out on IRC, on the
      <a href="https://chat.mozilla.org/#/room/#SUMO:mozilla.org">
        Matrix
      </a>.
    {% endtrans %}
  </p>

  <p><strong>{{ _('Learn new things') }}</strong></p>

  <p>
    {% trans training_url='/kb/introduction-contributor-quality-training?utm_source=training&utm_medium=1intro&utm_term=cqt&utm_campaign=Contributorqualitytraining' %}
      If you are interested in learning more about how this whole support
      thing works, check out our
      <a href="https://support.mozilla.org/en-US/kb/mozilla-support-rules-guidelines">
        Mozilla Support rules and guidelines
      </a>.
      This includes some cool troubleshooting info, guidelines, how-to
      questions, and info about where to find more help if stuck.
    {% endtrans %}
  </p>

  <p><strong>{{ _('Stay in touch') }}</strong></p>

  <p>
    {% trans forums_url='/forums/contributors', blog_url='https://blog.mozilla.org/sumo/', twitter_url='https://twitter.com/sumo_mozilla', meetings_url='https://wiki.mozilla.org/Support/Weekly_Meetings' %}
      Finally, if you want to follow all news related to SUMO, don’t
      forget about our
      <a href="https://support.mozilla.org/en-US/questions/">community forums</a>,
      <a href="https://blog.mozilla.org/sumo/">official blog</a> and
      <a href="https://twitter.com/i/flow/login?redirect_after_login=%2Fmoz_sumo">Twitter account</a>.
      We also
      <a href="(https://wiki.mozilla.org/Support:Community_Calls)">
        meet every month
      </a> - you can join us there.
    {% endtrans %}
  </p>

  <p>
    {% trans %}
      Thank you once more. We are looking forward to seeing you more often
      around SUMO! Keep rocking!
    {% endtrans %}
  </p>
{% endblock %}

**Comment by kelimuttu** [comment]
**Updated copy with HTML markup included & updated URLs:** 

`{% extends 'email/base.html' %}`

`{% block content %}`
  `<p>`
    `{% trans %}`
      `Thank you for your first contribution to the Mozilla support forums! You just made somebody's day!`
    `{% endtrans %}`
  `</p>`

  `<p>`
    `{% trans %}`
      `Mozilla support forum is fully powered by our volunteer community that helps hundreds of users every day. This community is formed by passionate Firefox and Thunderbird users who take some of their spare time to help others. We couldn't do it without your passion and enthusiasm. Your contribution, as minor as it might seem, has tremendous value. Solving one issue in the support forums can help up to 1000 users a day!`
    `{% endtrans %}`
  `</p>`

  `<p><strong>{{ _('Tell us about yourself!') }}</strong></p>`

  `<p>`
    `{% trans intro_url='/forums/contributors', matrix_url='https://chat.mozilla.org/#/room/#SUMO:mozilla.org' %}`
      `We are always very happy to hear from new people who like helping on the forums so if you haven’t met our community yet, <a href="{{ intro_url }}">please take a minute to introduce yourself</a>. If you want to stay low-profile, that’s also ok :). You can also find us all hanging out on Matrix, on the<a href="{{ matrix_url }}">#sumo channel</a>.`
    `{% endtrans %}`
  `</p>`

  `<p><strong>{{ _('Learn new things') }}</strong></p>`

  `<p>`
    `{% trans onboarding_url='/kb/how-contribute-support-forum?utm_source=onboardingemail&utm_medium=1intro&utm_term=cqt&utm_campaign=ContribOnboarding' %}`
      `If you are interested in learning more about how this whole support thing works, check out our <a href="{{ onboarding_url }}">contributor guidelines</a>. This includes some cool troubleshooting info, how-to questions, and info about where to find more help if stuck.`
    `{% endtrans %}`
  `</p>`

  `<p><strong>{{ _('Stay in touch') }}</strong></p>`

  `<p>`
    `{% trans forums_url='/forums/contributors', blog_url='https://blog.mozilla.org/sumo/', twitter_url='https://twitter.com/sumo_mozilla', meetings_url='https://wiki.mozilla.org/Support/Weekly_Meetings', participate_url='/kb/how-participate-sumo-contributor-meetings' %}`
      `Finally, if you want to follow all news related to SUMO, don’t forget about our <a href="{{ forums_url }}">community forums</a>, <a href="{{ blog_url }}">official blog</a> and <a href="{{ twitter_url }}">Twitter account</a>. We also <a href="{{ meetings_url }}">meet every month </a> - and you can <a href="{{ participate_url }}">join us</a>.`
    `{% endtrans %}`
  `</p>`

  `<p>`
    `{% trans %}`
      `Thank you, once more. We are looking forward to seeing you more often around SUMO! Keep rocking!`
    `{% endtrans %}`
  `</p>`
`{% endblock %}`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5755

**Comment by kelimuttu** [comment]
@emilghittasv can you please forward the email to me when you test this?

**Comment by emilghittasv** [comment]
@kelimuttu I've sent you the e-mail.

I've also noticed some differences between the implementation and the proposed copy. Filled under https://github.com/mozilla/sumo/issues/1577.

**Comment by emilghittasv** [comment]
I can confirm that the `first_answer` e-mail has the correct content now. (Also confirmed with @kelimuttu on slack).


Moving this ticket inside the `release` column.
