### ISSUE TITLE
Dashboards are taking too long to load (~40 seconds to 1 minute) and sometimes return 502 Server Error

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1560]
**Steps to reproduce**
1. Access the following links:
* https://support.allizom.org/en-US/contributors
* https://support.allizom.org/en-US/kb/locales/en-US/
* https://support.allizom.org/en-US/kb/revisions?locale=en-US
* https://support.allizom.org/de/localization
* https://support.allizom.org/de/kb/locales/de/
* https://support.allizom.org/de/kb/revisions?locale=de

**Expected behavior**
The above pages are loading quite fast (similar to the load time we have in `prod`)

**Actual behavior**
The above pages take too long to load (~40 to 1 minute) and sometimes return 502 Server Error.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* I suspect that the changes performed in https://github.com/mozilla/kitsune/pull/5737 caused this issue to occur.
* This issue is reproducible in `stage`. `prod` is not affected.

**Comment by akatsoulas** [comment]
That should be an interim infra problem. The nonce related PR adds a bit of CSS and a nonce directive to the screen.css file that I cannot see how it can cause the slowness

**Comment by akatsoulas** [comment]
Today staging performs great in all the urls that I tested.

**Comment by emilghittasv** [comment]
@akatsoulas  I've just hit 502 when trying to access https://support.allizom.org/en-US/contributors :(

**Comment by akatsoulas** [comment]
That looks like it was a problem with the lib updates and the staging deployments. Closing for now and we can reopen if needed
