### ISSUE TITLE
Consider opening the "Learn More" link from the step 3 of the Wizard in a new tab

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1561]
**Describe the bug**
The "Learn more" link from the step 3 of the wizard opens the https://www.mozilla.org/en-US/privacy/websites/#campaigns page inside the same tab which might disrupt the user flow. If he decides to navigate back to the switching-devices page, the wizard's state is on step 2 instead of 3 (where he left off).

I think that we should consider opening the "Learn more" link in a new tab so that the user's wizard flow is not interrupted.

**Preconditions**
Enable UI tour on `dev`

**Steps to reproduce**
1. Access the https://support-dev.allizom.org/en-US/kb/switching-devices
2. Reach the step 3 of the wizard.
3. Click on the "Learn more" link from the `The intended recipient of the email must have consented.` section.

**Expected behavior**
The https://www.mozilla.org/en-US/privacy/websites/#campaigns page opens in a new tab.

**Actual behavior**
The https://www.mozilla.org/en-US/privacy/websites/#campaigns page opens in the same tab.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
This project milestone is complete and there is no active development.
