### ISSUE TITLE
 Localization dashboard minor UI errors

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1563]
More info https://bugzilla.mozilla.org/show_bug.cgi?id=1688165

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5748

**Comment by emilghittasv** [comment]
@akatsoulas 

This ticket is linked with the https://bugzilla.mozilla.org/show_bug.cgi?id=1688165 and which describes some UI issues which are still reproducible in `stage`. 

I've broke them down into 3 different tickets which can be considered as a dependency for this ticket completion:
https://github.com/mozilla/sumo/issues/1569
https://github.com/mozilla/sumo/issues/1571
https://github.com/mozilla/sumo/issues/1524

I'm moving this ticket back inside the "In Progress" column.

Tasos, please let me know if I've missed something

**Comment by emilghittasv** [comment]
All the dependency tickets were fixed & verified a while back.

I'm going to close this ticket since all the localization dashboard UI issues were fixed.
