### ISSUE TITLE
The "Ok" td status from the localization dashboard has no visible text

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1567]
**Steps to reproduce**
1. Go to https://support.allizom.org/ro/localization/most-visited-translations. Or go to https://support.allizom.org/de/localization/most-visited-translations (it seems that `de` locale has more articles with this status)
2. Notice the `Cum imi personalizez bara de instrumente?` article.

**Expected behavior**
The `Cum imi personalizez bara de instrumente?` article, which has the `<span class="ok"></span>` applied (since no other localization actions are required) has an appropriate text displayed inside the status `td`

**Actual behavior**
No text is displayed inside the status `td`.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/d5caa04c-23fb-471f-925f-8699c31b2edc)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Latest Nighlty

**Additional Notes**
* Both `stage` and `prod` are affected.

**Comment by akatsoulas** [comment]
It turns out that it was working as expected. There was no text for articles that were updated. Because that behavior is confusing I did the following:

* Added the text `Updated`
* Reset the mouse pointer
* Remove any styling on :visited and :hover selectors

PR https://github.com/mozilla/kitsune/pull/5759

**Comment by emilghittasv** [comment]
I can confirm that the "Updated" text has been added to the "OK" status inside the localization dashboard.



![Image](https://github.com/mozilla/sumo/assets/28087895/9d887e70-7e4f-4015-83d6-e152e33459ff)

Moving this ticket inside the `release` column.
