### ISSUE TITLE
Percentage belonging to the first row of the overview table from the localization dashboard is placed in a separate row

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1569]
**Steps to reproduce**
1. Access the https://support.allizom.org/ro/localization page and observe the overview table.

**Expected behavior**
Nu UI issues are displayed.

**Actual behavior**
The percentage which belongs to the first `tr` is placed in a separate `tr`

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/a2d21cb9-2cce-40dd-8326-1b0285048761)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
I've noticed that the HTML structure is different for the first `tr` of the table. The percentage lives in a different `tr`.

```
<tr class="most-visited-row">
            <td class="row-title">
              Top 100 de articole
              <div>Acesta este topul celor 100 cele mai vizitate articole din ultimele 30 de zile, care reprezintă peste 99% din traficul din Baza de cunoștințe.</div>
            </td>
            <td colspan="2">
              4 din 100
            </td>
          </tr>
<tr>
            <td colspan="3">
              <div class="percent-graph">
                <span>4%</span>
                <div style="" class="bad"></div>
              </div>
            </td>
          </tr>
```

If the HTML structure is modified (to be similar to the other `tr` elements) as such should probably fix this issue:

```
<tr class="most-visited-row">
            <td class="row-title">
              Top 100 de articole
              <div>Acesta este topul celor 100 cele mai vizitate articole din ultimele 30 de zile, care reprezintă peste 99% din traficul din Baza de cunoștințe.</div>
            </td>
            <td>4
            <small>din 100</small></td>
          <td>4%<div class="percent-graph">
                <div style="" class="bad"></div>
              </div></td>
  </tr>
```

screenshot with the modified (fix) version:
![image](https://github.com/mozilla/sumo/assets/28087895/2449c002-5fe1-4c61-8bb4-9786f4840a45)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5753

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Tested on:
- Windows 10: Firefox & Chrome
- macOS 11: Firefox & Safari
- Huawei P40Pro: Firefox.

Moving this ticket inside the `release` column.
