### ISSUE TITLE
The items from the localization dashboard "review menu" are displayed as simple text instead of buttons or links

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1571]
**Steps to reproduce**
1. Go to https://support.allizom.org/el/localization and observe the `Μετάφραση` and `Αξιολόγηση`

**Expected behavior**
As mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1688165 the `Μετάφραση` and `Αξιολόγηση` should be displayed to the user as links/clickable items.

**Actual behavior**
The `Μετάφραση` and `Αξιολόγηση` are displayed to the user as text which is not that intuitive that those items are actually clickable and performing an event.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5777

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The `Μετάφραση` and `Αξιολόγηση` are displayed as links now. Also no regressions found functionality wise (the correct table is displayed each time when switching from `Μετάφραση` to `Αξιολόγηση`)

Tested on:
Windows 10: Firefox & Chrome
Huawei P40Pro: Firefox
iPhone 12: Safari.

Moving this ticket inside the `release` column.
