### ISSUE TITLE
investigate possible deployment workflow issue(s)

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1572]
Deployments to stage (and maybe other environments) sometimes do not seem to work properly (e.g., missing CSS changes, etc.).

**Comment by escattone** [comment]
@ahoneiser discovered that it seems to be related to one of our package updates, but we have yet to discover which one.

**Comment by escattone** [comment]
@ahoneiser identified the updated `newrelic` package as the culprit. I did some research, and we've been successfully using `newrelic` v8.7.0 since Feb. 21, 2023 (since https://github.com/mozilla/kitsune/pull/5405 was merged), so it seems that some version of `newrelic` between v8.7.0 and v8.11.0, which was the version we tried to jump to, is not playing well within our world.

**Comment by akatsoulas** [comment]
Closing this in favor of #1565. We are going to update the libraries without NR. If everything works great we will focus on NR. New issues will be opened if the need arises.
