### ISSUE TITLE
The e-mail address is not preserved if the user signed in via the "Already have an account?" option from the Wizard's step 1

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1574]
**Preconditions**
Ensure that you are not signed in to FxA.

**Steps to reproduce**
1. Access the https://support-dev.allizom.org/en-US/kb/switching-devices page.
2. Click on the "Sign in" button from the "Already have an account?" section.
3. Proceed with the sign in flow and navigate back to the Wizard.
4. Reach the Wizard's step 3.

**Expected behavior**
The e-mail used in step 2 is saved in session storage under the `switching-devices-email` key and the e-mail is pre-filled in the Wizard's step 3.

**Actual behavior**
The e-mail address is not saved & pre-filled in the Wizard's step 3.

**Screencasts**
![e-mail](https://github.com/mozilla/sumo/assets/28087895/023d3719-9e66-4f9d-a306-c4f0a75d3a2d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
- Reproducible in `dev`
- The e-mail address is successfully saved & pre-filled inside the Wizard's step 3 if the user signed in to FxA via the "Enter your email" field.

**Comment by akatsoulas** [comment]
This project milestone is complete and there is no active development.
