### ISSUE TITLE
Firefox becomes unresponsive and the "Are you sure you want to sign in to Sync" popup opens multiple times after signing out and signing back in with a different FxA user via the Wizard's step 1 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1575]
**Preconditions**
Ensure that you are not signed in to FxA

**Steps to reproduce**
1. Access the https://support.mozilla.org/en-US/kb/switching-devices page.
2. Complete the FxA sign in flow via the "Enter your email" field from the Wizard's step 1.
3. Sign out from the FxA account connected in step 2.
4. Complete the FxA sign in flow again via the "Enter your email' field from the Wizard's step 1 but now by using a different account. 

**Expected behavior**
No issues are encountered and the user can successfully sign in with the second account via the Wizard.

**Actual behavior**
Firefox becomes unresponsive and the "Are you sure you want to sign in to Sync" pop-up is opened multiple times.

**Screencasts**
![anotherAccountSpam](https://github.com/mozilla/sumo/assets/28087895/1b8e059b-2d93-4a8b-a60f-773ef0ec9be0)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue affects both `prod` and `stage`

**Comment by mikeconley** [comment]
Whoa, this is brutal. Almost certainly this isn't a SUMO bug though, but rather a bug in the Firefox Sync / accounts client code. Would you mind refiling this in Bugzilla under Firefox :: Firefox Accounts?

**Comment by emilghittasv** [comment]
Thanks @mikeconley!.

Filled under https://bugzilla.mozilla.org/show_bug.cgi?id=1863894

**Comment by akatsoulas** [comment]
This is tracked in Bugzilla. Closing
