### ISSUE TITLE
Consider removing the link from the "Updated" status inside the localization dashboard

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1576]
**Steps to reproduce**
1. Access the https://support.allizom.org/ro/localization/most-visited-translations page.
2. Click on the `Updated` option.

**Expected behavior**
We should consider removing the link attached to the `Updated` option since it redirects the user to the same page.

**Actual behavior**
The user is redirected to the https://support.allizom.org/ro/localization/most-visited-translations page (which actually refreshes the page on which the user is currently on). 

**Screencasts**
![updated](https://github.com/mozilla/sumo/assets/28087895/a6ee3307-0e2a-4703-a2e5-7a04058f7eaa)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5762

**Comment by emilghittasv** [comment]
This issue is verified fixed.

The link attached to the "Updated" status inside the localization dashboard has been removed.

Moving this ticket inside the `release` column.
