### ISSUE TITLE
Differences between the proposed copy and the actual implementation of the "Thank you for your contributions to Mozilla Support" (first_answer) e-mail

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1577]
**Preconditions**
Create a new SUMO account and sign in.

**Steps to reproduce**
1. Leave a comment to one of the user posted questions.
2. Check your e-mail addressed attached to the account from the preconditions.

**Expected behavior: Kiki's copy (https://github.com/mozilla/sumo/issues/1559#issuecomment-1801099411)**
1.  `Mozilla support forum` is fully powered by our volunteer community that helps hundreds of users every day. This community is formed by passionate Firefox and Thunderbird users who take some of their spare time to help others. We couldn't do it without your passion and enthusiasm. Your contribution, as minor as it might seem, has tremendous value. Solving one issue in the support forums can help up to 1000 users a day!

2. We are always very happy to hear from new people who like helping on the forums so if you haven’t met our community yet`,` please take a minute to introduce yourself`.` If you want to stay low-profile, that’s also ok :). You can also find us all hanging out on Matrix, on the #sumo channel`.`

3. If you are interested in learning more about how this whole support thing works, check out our contributor guidelines`.` This includes some cool troubleshooting info, how-to questions, and info about where to find more help if stuck.

4. Finally, if you want to follow all news related to SUMO, don’t forget about our community forums, official blog and Twitter account. We also meet `every` month - and you can join us.

5. Thank you`,` once more. We are looking forward to seeing you more often around SUMO! Keep rocking!

**Actual implementation**
1. `Mozilla support` is fully powered by our volunteer community that helps hundreds of users every day. This community is formed by passionate Firefox and Thunderbird users who take some of their spare time to help others. We couldn't do it without your passion and enthusiasm. Your contribution, as minor as it might seem, has tremendous value. Solving one issue in the support forums can help up to 1000 users a day!

**Note**: `Mozilla support` instead of `Mozilla support forum`

2. We are always very happy to hear from new people who like helping on the forums so if you haven’t met our community `yet please` take a minute to introduce yourself `.` If you want to stay low-profile, that’s also ok :). You can also find us all hanging out on Matrix, on the #sumo channel `.` 

**Note**: There is no `,` between yet and please. Space can be noticed before the `.`

3. If you are interested in learning more about how this whole support thing works, check out our contributor guidelines . This includes some cool troubleshooting info, how-to questions, and info about where to find more help if stuck.

**Note**: Space can be noticed before the `.`

4. Finally, if you want to follow all news related to SUMO, don’t forget about our community forums, official blog and Twitter account. We also meet `almost every` Monday - and you can join us.

**Note**: `almost every` instead of `every`

5. Thank `you once` more. We are looking forward to seeing you more often around SUMO! Keep rocking!

**Note**: Missing `,`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5761

**Comment by emilghittasv** [comment]
This is verified fixed now.

Moving this ticket inside the `release` column.

![Image](https://github.com/mozilla/sumo/assets/28087895/6a250bbb-3dff-4497-8197-bd23468daf2c)
