### ISSUE TITLE
update elasticsearch index on stage

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1580]
Update the Elasticsearch index on stage, since it has been updated with new test data.

**Comment by escattone** [comment]
I increased the size of our stage Elasticsearch instance to accommodate the larger set of data, scaled-up our celery pods from 1 to 5 in stage, and kicked-off a full re-index with `./manage.py es_reindex`.

**Comment by akatsoulas** [comment]
The reindex should be done - closing this as QA-
