### ISSUE TITLE
The localization dashboard progress bar dissapears when the page is fully loaded

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1582]
**Steps to reproduce**
1. Go to the https://support.allizom.org/ro/localization page **or** https://support.allizom.org/ro/localization/most-visited-translations **or** https://support.allizom.org/ro/localization/unreviewed

**Expected behavior**
The progress bar is displayed all the times.

**Actual behavior**
After the page fully loads, the progress bar disappears.

**Screencasts**
![progress_bar](https://github.com/mozilla/sumo/assets/28087895/e6c3631f-5e40-4e10-925f-dc9fbc9c4683)

**Desktop:**
 - OS: Windows 10 
 - Browser: Firefox & Chrome

**Additional context**
* This issue is reproducible in `stage`. `prod` is not affected.
* The progress bar re-appears and stays displayed if the user interacts with the filters ("Ultimele 7 zile", "Ultimele 30 de zile",etc)

**Comment by escattone** [comment]
This issue has actually exposed a separate bug. We were not accommodating the approach that Postgres uses to order `null` values, which is the reverse of MySQL, in raw SQL queries like the ones in `readouts.py`. I created #1585 to track that.

This issue remains for this case where we're not setting the "visits" bar width when clicking between the "modes" (i.e., 7-day, 30-day, etc.).

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The localization dashboard progress bar is successfully displayed and no longer dissapears on page load.

Tested on:
Windows 10: Firefox & Chrome
macOS 11: Firefox
Huawei P40Pro and iPhone 12: Firefox

Moving this ticket inside the `release` column.
