### ISSUE TITLE
The "Avoid support scams" scam alert is displayed for admin users as well 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1586]
**Preconditions**
Sign in with an admin account.

**Steps to reproduce**
1. Navigate to any posted question (example: https://support.allizom.org/en-US/questions/1430387)

**Expected behavior**
The "Avoid support scams" scam alert is not displayed while signed in with admin accounts.

**Actual behavior**
The "Avoid support scams" scam alert is displayed.

**Desktop :**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Reproducible in `stage`. `prod` is not affected.

**Comment by escattone** [comment]
As far as I can tell, the visibility of the scam alert banner is only controlled by the `id_scam_alert.closed` Local Storage key. The scam alert banner shows-up when I reset that key's value to `false`.

<img width="1314" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/3c0142e9-6a61-4542-ae48-d9cb9754c14f">

**Comment by akatsoulas** [comment]
Tested this with a private session and it's working fine. It's controlled by locale storage. If you clear everything it should be displayed.
