### ISSUE TITLE
Lists in forums are not properly indented 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1587]
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1641565

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5785

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in stage -> https://support.allizom.org/en-US/questions/1430412#answer-1616811

Tested on: Firefox & Chrome browsers

Moving this ticket inside the release column.
