### ISSUE TITLE
Tickets are not sent to Zendesk if the "Tell us more" field is left empty and the ratelimit can be reached even though no tickets were submitted (for loginless ones)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1595]
**Preconditions**
Ensure that you are not signed in to sumo.

**Steps to reproduce**
1. Access the loginless form.
2. Add valid data to each field but leave the `Tell us more` field empty.
3. Redo steps 1-2 for 4 times.

**Expected behavior**
The ticket is successfully sent to Zendesk and the ratelimit is reached after trying to submit more than 3 tickets.

**Actual behavior**
The "That didn't work. Please try again" red banner is displayed and no tickets are sent to Zendesk each time. Also the ratelimit is reached even though no tickets were submitted.

**Screencasts**
![NotWorking](https://github.com/mozilla/sumo/assets/28087895/55785d17-1adc-4b3d-b2c4-812c2bb1fe67)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Reproducible in `stage`. Not reproducible in `prod`

**Comment by emilghittasv** [comment]
@smithellis This also affects the logged in form for all premium products. Tickets are not submitted if the "Tell us more" field is left empty.
![NotWorking2](https://github.com/mozilla/sumo/assets/28087895/819349a9-e94e-4141-ba95-e4a781fae289)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5798

This should fix things. The _lazy was never being called on NO_RESPONSE, so calling it with str(NO_RESPONSE) fixed it.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Tickets are successfully sent to Zendesk if the "Tell us more" field is left empty.

Moving this ticket inside the `release` column.
