### ISSUE TITLE
The "Nobody has translated this article yet" banner is displayed even though the kb article contains a translation which is pending review & clicking on the "start to translate now" redirects to Access Denied page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1596]
**Describe the bug**
This is similar to the issue mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1866797

**Preconditions**
Sign in to SUMO using two different accounts (A and B) in two different browsers (A in Firefox and B in Chrome). Please also make sure that account B doesn't have the `wiki | revision | Can review a revision` permission

**Steps to reproduce**
1. Go to any KB article that is not translated yet in a particular locale on both profiles (A and B). (Example: https://support.allizom.org/ro/kb/end-support-firefox-reality)
2. With account A click on the `începe să traduci de acum` and submit the translation.
3. With account B refresh the page and click o the `începe să traduci de acum`

**Expected behavior**
After a page refresh the banner updates to the one which informs the user that `Our volunteers are working at this article translation` (`Voluntarii noștri lucrează la traducerea acestui articol`)

**Actual behavior**
After a page refresh the `începe să traduci de acum` is still displayed and clicking on the `începe să traduci de acum` option redirects the user to the "Access Denied" page.

**Screencasts**
![AccessDenied](https://github.com/mozilla/sumo/assets/28087895/ea112457-a918-42e8-bda0-c42f2af84ee8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Probably we should update the banner to `Our volunteers are working at this article translation` when a translation for that article locale is already submitted for revision regardless if the user has the `wiki | revision | Can review a revision` permission or not in order to avoid confusion like the ones mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1866797

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5799

**Comment by emilghittasv** [comment]
Hey @smithellis hmm.. I'm still able to reproduce this issue in `stage`. 

Moving this ticket back inside the in progress column.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

* Trying to access an article which is pending translation review in a particular locale (by manually adding the link inside the URL bar) with a user that lacks the `wiki | revision | Can review a revision` permission will return a page not found. (for article translations which have different slugs from their parent article).
* Trying to access an article which is pending translation review in a particular locale with an account that has the `wiki | revision | Can review a revision` permission will display the pending article translation successfully (For both article translation which have the same slug as their parent article and for article translations which have different slugs from their parent article)
* Trying to access an article which is pending translation review in a particular locale (which has the same or different slug as the parent article) with an account that lacks the `wiki | revision | Can review a revision` will show the correct banner (`Our volunteers are working on translating this article. Until it's ready, maybe you'll find the English version helpful. If you want to help us translate articles like this, click here.` instead of `No one has helped translate this article into Vietnamese yet :( We look forward to receiving your contributions. If you already know how to translate articles for SUMO, start translating now. If you want to learn how to translate articles for SUMO, start here.`)
* If there isn't a translation pending review for a particular article the `No one has helped translate this article into Vietnamese yet :( We look forward to receiving your contributions. If you already know how to translate articles for SUMO, start translating now. If you want to learn how to translate articles for SUMO, start here.` banner is displayed and clicking on the `start translating now` option will redirect the user to the article `/translate` page.

Moving this ticket inside the `release` column.
