### ISSUE TITLE
Update questions API with ordering=-last_answer does not work after switching to PostgreSQL

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1599]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1867146

**Comment by escattone** [comment]
## QA Notes
GET the following endpoints and ensure that the first few results do **not** contain a null value for their `last_answer` field:
- https://support.allizom.org/api/2/question/?locale=en-US&product=firefox&ordering=-last_answer
- https://support.allizom.org/api/2/question/?product=firefox-enterprise&ordering=-last_answer

**Comment by emilghittasv** [comment]
Thanks Ryan!

I can confirm that no `null` values are received for the `last_answer` field for the above endpoints while GET requesting them.

Moving this ticket inside the `release` column.

**Comment by escattone** [comment]
This was completed with the release this morning, and I've already resolved the bugzilla ticket.
