### ISSUE TITLE
Offer to let users sign-in or sign-up for a Mozilla account using a pre-existing Google / Apple account

### ISSUE THREAD

**Issue by mikeconley** [mozilla/sumo#1601]
For the switching devices wizard, we don't currently offer the ability to let users provide a verified email address via Google / Apple. This is something that Pocket is able to do at https://getpocket.com/login/, and according to Ben Bangert, we should be able to do this too.

We should offer that. Users would still need to set up or provide a password to finish creating an account or logging in, but this allows us to skip the email verification step.

**Comment by akatsoulas** [comment]
This project milestone is complete and there is no active development.
