### ISSUE TITLE
update Django to latest 4.2

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1603]
Now that we've moved to Postgres, we can update to Django 4.2.

**Comment by escattone** [comment]
## QA Notes
@emilghittasv I can't think of any specific QA plan for this issue. Stage is running fine with this package update, so if you just want to change the status of this to `release`, feel free to do that.

**Comment by emilghittasv** [comment]
I've also performed a general smoke testing session and nothing came up. 

I'm moving this ticket inside the `release` column.
