### ISSUE TITLE
Internal Server Error when trying to submit a Zendesk ticket for any premium product if logged in to SUMO with an e-mail address used previously to submit a longiless ticket (Anonymous user)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1604]
**Preconditions**
Ensure that you are not signed in to SUMO.

**Steps to reproduce**
1. Submit a loginless ticket to Zendesk.
2. Create a SUMO account using the same e-mail address used in step 1. 
3. Submit a Zendesk ticket to any premium product.

**Expected behavior**
The ticket is successfully submitted to Zendesk.

**Actual behavior**
The ticket is not submitted to Zendesk and the "Internal Server Error" page is displayed.

**Screencasts**
![ZendeskInternalServerError](https://github.com/mozilla/sumo/assets/28087895/039f703c-6f76-4e63-8bac-32258df89078)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional Notes**:
This issue is reproducible in `stage`. `prod` is not affected.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5803

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

New users are able to submit tickets to Zendesk while using the same e-mail address used previously in sending loginless forms (anonymous users).

Zendesk also successfully updates the username from "Anonymous user" to the actual username.

Moving this ticket inside the `release` column.
