### ISSUE TITLE
Display in the KB page whether it's linkd to an inproduct link

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1607]
We should display to a specific group of people somewhere at the right of the page where the edit menu is, whether the KB article is connected to an inproduct link

**Comment by kelimuttu** [comment]
This is super cool. Thanks for working on this, you guys!

**Comment by emilghittasv** [comment]
This ticket is verified in `stage`

* The inproduct indicator is displayed for KB articles which are linked.
* The inproduct indicator is not displayed for KB articles which are not linked (or for which the inproduct link was removed).
* The inproduct indicator is displayed only for `Staff` group members.
* The inproduct indicator is no longer displayed if the user was removed from the `Staff` group.
* The inproduct link is displayed without any UI issues on both Desktop (Windows 10- Firefox & Chrome) and Mobile (Huawei P40 Pro - Firefox)

Moving this ticket inside the `release` column.

**Comment by AliceWyman** [comment]
I don't see why the group of people able to view the KB article in-product indicator should be limited to Staff.  I filed [bug 1915731](https://bugzilla.mozilla.org/show_bug.cgi?id=1915731) to propose that the group be expanded to include KB article reviewers.
