### ISSUE TITLE
No-break spaces in subtitles of articles show &nbsp; in TOC

### ISSUE THREAD

**Issue by YD-89** [mozilla/sumo#1609]
**Describe the bug**
When a subtitle of an article contains a no-break space, it is rendered as &amp;nbsp; (in the HTML of the page &amp;amp\;&amp;nbsp;). The no-break space is mandatory in French before a question mark for instance.

**Steps to reproduce**
1. Go to https://support.mozilla.org/fr/kb/reparer-firefox-reinitialiser-modules-parametres
2. Scroll down to the TOC
4. See error at the end of the TOC lines finishing with a question mark or a colon

**Expected behavior**
It's a new behavior. The no break spaces should appear just like spaces.

**Comment by emilghittasv** [comment]
Hi @YD-89 ! 👋 

I'm no longer reproducing this issue. I'm wondering if this is still occurring on your end or if you are still able to reproduce.

**Comment by YD-89** [comment]
Hi!

It seems to be fixed. That's OK.

**Comment by emilghittasv** [comment]
Thank you for the confirmation!
