### ISSUE TITLE
Update Thunderbird logo

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1610]
More info https://bugzilla.mozilla.org/show_bug.cgi?id=1868623

**Comment by smithellis** [comment]
Check this in production I guess? It was an admin change.

**Comment by smithellis** [comment]
Logo from [here](https://design.thunderbird.net/resources/logo)

**Comment by emilghittasv** [comment]
I can confirm that the new logo for Thunderbird is displayed in `prod`.

Verified while going through different pages of the AAQ, KB article, forum flows. 

Since this is already live in `prod` we can close this ticket directly.
