### ISSUE TITLE
Login interstitial copy changes

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1611]
**Briefly describe the Initiative.**
Update text copy on the login interstitial page on SuMO

**Describe the milestones if any**

Specific copy on the card should be changed to the following:

Card Title: Continue with a Mozilla account
Card sub copy: Sign in or sign up to ask questions in our forums and contact support agents.
Card CTA button: Continue
Card footer: "I can't sign in to my Mozilla account" 

**Add any related issues**
N/A

**What is the requested timeline for completion?**
Release with standard cadence

**Who is the audience**
Improvement to existing functionality

**Additional context**
![Login_interstitial_copy_update_12 7 23](https://github.com/mozilla/sumo/assets/87725469/5f5f40b2-4e1a-41b3-9b15-898ccdde0e19)

**Applicable resources**
Project brief, JIRA, Bugzilla or GitHub, any documentation, use cases.
https://www.figma.com/file/JIZmAskexNygAajEIvHEv1/Login-less-Account-Support-Journey?type=design&node-id=1244-16&mode=design&t=mkWPfhuKtOVtBHgc-0

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5810

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5811

**Comment by emilghittasv** [comment]
I can confirm that the  changes performed to the login interstitial in `stage` aligns with the newly proposed copy.

Screenshot:
![Image](https://github.com/mozilla/sumo/assets/28087895/3fe89114-704f-482a-a369-e9099f83e63b)

Verification performed on Windows 10: Firefox & Chrome and Huawei P40Pro (Firefox)

Moving this ticket inside the `release` column.
