### ISSUE TITLE
Remove ""I have another sign in issue" from the contact reason selection of the account support loginless ticket form

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1612]
**Briefly describe the Initiative.**
Recent data suggests that the contact reason "I have another sign in issue" is being used inappropriately. This means users are primarily selecting this contact reason for issues not relating to sign in failure or different Mozilla products all together. No unique sign in issues have been discovered in the past 30 days and other issues can be related to existing contact reasons. As a result, we would like to have it removed.

**Describe the milestones if any**
The "What do you need help with?" field should only have 4 contact reasons. The fifth contact reason of "I have another sign in issue" should be removed from the list. 

**Add any related issues**
N/A

**What is the requested timeline for completion?**
Released with normal cadence

**Who is the audience**
Improvement to existing functionality

**Additional context**
N/A

**Applicable resources**
N/A

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5808

**Comment by emilghittasv** [comment]
I can confirm that the `I have another sign in issue` option is no longer available inside the `What do you need help with?` dropdown menu for the loginless form. 

The dropdown menu now contains 4 options (besides the default `Select a reason for contacting` one): 
1. `I forgot my password`
2. `I can't recover my account using email`
3. `I'm having issues signing in with my Google or Apple ID`
4. `My security code isn't working or is lost`

I can also confirm that the above options are working as expected and loginless Zendesk tickets can be successfully sent by having any of the dropdown menu option selected (besides the default one of course).

Moving this ticket inside the `release` column.
