### ISSUE TITLE
Setup Zendesk Contact Flow for Monitor

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1615]
**Briefly describe the Initiative.**
Monitor Plus will be going live on January 17th. To support this premium offering we will need to setup a Zendesk ticket flow for the Monitor product on SuMO similar to how we have setup to Relay, VPN, MDN Plus, Hubs, etc. Additionally icons on SuMO will need to be updated to reflect the new branding

**Describe the milestones if any**
Setup Zendesk ticket flow for Monitor product using the existing slug monitor. We can use the same implementation that Relay uses. 
Update icons to reflect new branding

**Add any related issues**
https://app.asana.com/0/1205126718386140/1205643051851893/f

**What is the requested timeline for completion?**
We'd like to test and confirm setup by January 8th for a Go-Live of January 17th. 

**Who is the audience**
External ticket flow for Monitor users

**Additional context**

**Applicable resources**
Engagement doc: https://docs.google.com/document/d/1emwLtQiv_WwlT4v-BJyPnl7r3T9W4Bl0ZEYHRynemc8/edit#heading=h.37j1ol27ooro
Icons: https://drive.google.com/drive/folders/1sQLOlnxPXNEfDpM6jpdH4qTR_Cgqj3l_

**Comment by smithellis** [comment]
Need a little more information from JR about branding - he'll get back to me soon. Primary question is "Mozilla Monitor" vs. "Monitor".
Otherwise, this implementation should be straight forward.
https://github.com/mozilla/kitsune/compare/main...smithellis:kitsune:monitor-enable-support

**Comment by smithellis** [comment]
Update - still need branding answers.  Main question is the graphic provided has "Mozilla Monitor" text, while most of our other product graphics do not have text. Also, the branding guidelines reference the product as "Monitor" not "Mozilla Monitor" - so I need brand clarity there.

**Comment by smithellis** [comment]
Have the following: Leave image as is, name as Monitor, description text is "Stay informed and take back control of your exposed data"

https://github.com/mozilla/kitsune/pull/5830

**Comment by emilghittasv** [comment]
I can confirm that this is working as expected in `stage`.

* The original Monitor image was kept.
* The "Stay informed and take back control of your exposed data" Monitor card's description text is displayed.
* Zendesk tickets can be successfully sent from SUMO, are tagged correctly and added to the "Monitor" product in Zendesk.

During the verification of this ticket I've also performed a regression testing session targeting other premium products Zendesk ticket submissions. No regressions found.

I'm moving this ticket inside the `release` column.

**Comment by JC-Support** [comment]
New launch date 2/6/13.

**Comment by JC-Support** [comment]
Confirmed the official name of the product is "Mozilla Monitor"
