### ISSUE TITLE
"Valid email required" error message displayed after signing out from sync

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1617]
**Preconditions**
Sign in to Firefox Sync.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Click on the "Continue" button and continue the sign in process.

**Expected behavior**
* The "Valid email required" error message is not displayed and the e-mail field is focused.

**Actual behavior**
* The "Valid email required" error message is displayed immediately after the wizard automatically switches from step 2 to step 1 and the email field is not focused.

**Screencasts**
![switching_devices_autofocus_sign_out](https://github.com/mozilla/sumo/assets/28087895/70b60bd6-8dfa-4338-9c61-117563cdae05)

**Desktop:**
- OS: Windows 10
- Firefox

**Additional context**
This issue is reproducible in `stage`. `prod` is not affected.

**Comment by emilghittasv** [comment]
This issue is also reproducible while the email field was previously populated as the consequence of signing in to SUMO. 

Steps:
1. Sign in to SUMO.
2. Navigate to the https://support.allizom.org/en-US/kb/switching-devices page.
3. Sign in to Firefox Sync.
4. Sign out from the Firefox Sync.

Actual behavior: The e-mail field is prepopulated, the "Valid email required" error message is displayed and the filed is not focused.

![image](https://github.com/mozilla/sumo/assets/28087895/12305b65-f546-4818-84fb-48e28b513a41)

**Comment by mikeconley** [comment]
This was closed by https://github.com/mozilla/kitsune/pull/5816.
