### ISSUE TITLE
The ability for staff to send PM to groups

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1619]
**Briefly describe the Initiative.**
We don't have an easy way to send broadcast comms to contributors from a certain segment (for example: forum contributors only, Japanese locale group only, etc). We can post an announcement on the contributor forum, but that doesn't guarantee all contributors will see it because they need to subscribe to the forum first. At the moment, we rely on manual process such as exporting the data from BQ and then email them manually, or sending PM to each individual that we want to reach out which takes more time than the former. This is a request to have the ability for staff members to send private PM to groups so we can easily broadcast announcements, messages, or community requests, without having to go through a time-consuming manual process. 

**Describe the milestones if any**
An ability for staff members to send PM to groups & locale groups (for example [nl](https://support.mozilla.org/kb/locales/nl/)). 

**Add any related issues**
-

**What is the requested timeline for completion?**
Q1 2024

**Who is the audience**
Staff members

**Additional context**
-

**Applicable resources**
-

**Comment by kelimuttu** [comment]
Hi @akatsoulas, can we get a clarification on whether we can squeeze this work in Q1 or not? Thanks.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5957

**Comment by emilghittasv** [comment]
The QA work is finalized for this ticket. 

I can confirm that:
* Users belonging to the `staff` group are able to send messages to a single or multiple groups.
* Users which do not belong to the `staff` group are not able to send messages to groups.
* Group messages are successfully received by all targeted group members.
* If a user belongs in two targeted groups the message is sent only once to that particular user.
* If a staff user sends a message to a group & to an individual user (which is also part of that group), the targeted user/recipient will only receive 1 message.
* Group messages cannot be sent to profileless groups.
* The UI for both inbox & outbox has been updated and `staff` accounts are able to visualize to which recipient groups the message was sent.
* No regressions encountered while sending a message to an individual user or to multiple users.

Moving this ticket inside the `release` column.
