### ISSUE TITLE
Update the top level navigation menu to point to KB, Forums, AAQ and Contribute

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1621]
See [Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=380-2097&mode=design&t=ed7FyS3IELLCGw1l-4)

**Comment by akatsoulas** [comment]
- [ ] Updates the top-level menu according to the design
- [ ] Removes the `Explore Our Help Articles` from the submenu
- [ ] Removes the one column from the `Ask A Question` sub-menu
- [ ] Removes links from submenus
- [ ] All top level links are available to all users.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5848

**Comment by emilghittasv** [comment]
I can confirm that the top level navigation menu was updated as per the proposed figma design.

The verification was performed in `dev`. Leaving this ticket inside `qa` until this is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
