### ISSUE TITLE
Add the ability to Explore by popular topics

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1622]
We need to add new functionality which will return all the articles under a specific topic. The articles will be filterable by product.

**Comment by akatsoulas** [comment]
Currently the top-level navigation is not linked to this functionality. Moreover the All Topics menu is missing along with the breadcrumbs. Everything listed in this comment will be tracked in a different PR/issue. This will be used as MVP to validate the functionality and the designs.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6015

**Comment by emilghittasv** [comment]
I can confirm that:
* Users can explore/filter through articles based on the listed topics available inside the `Explore Help Articles` > `Explore by topic` section.
* When selecting a certain topic from the Top-navbar section, the user is successfully redirected to the `Explore by topic` page where all articles belonging to that particular topic are listed. The filter, by default, is applied to display articles from that particular topic for `All Products`.
* Users can successfully filter through the different products which have that particular topic via the `Filter by product` dropdown menu.
* Users can successfully navigate to different topics which are listed inside the `All Topics` side navbar.
* Articles which are archived are not displayed inside the `Explore by topic` page for users which lack the necessary permissions (same applies for restricted visibility kb articles)
* Changing the topic of a particular article is going to be successfully resembled inside the `Explore by topic` page.

Moving this ticket inside the `release` column.
