### ISSUE TITLE
Update the forums drop-down menu 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1624]
See [Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=ed7FyS3IELLCGw1l-4)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5855

**Comment by akatsoulas** [comment]
The links in `Browse all forum threads by topic` are just a placeholder for now until we build the back-end functionality

**Comment by emilghittasv** [comment]
I can confirm that the "Community Forums" drop-down menu has been updated to match the figma designs.

This verification was performed in `dev`. Leaving this ticket inside the `qa` column until this work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well:
* Users can successfully filter AAQ questions based on the topics listed inside the `Community Forums` > `Browse all forum threads by topic` section.

Moving this ticket inside the `release` column.
