### ISSUE TITLE
Update the contribute drop-down menu

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1625]
Update the drop-down menu according to the [Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=ed7FyS3IELLCGw1l-4)

- Will the menu be visible only to logged-in users and only when they will have the contributor flag?

**Comment by emilghittasv** [comment]
As Josh confirmed in slack, the sub-menu for the `Contribute` top-navbar option should be available only for logged in contributors. 

If the user is logged out or logged in with a non-contributor account, the `Contribute` should act as a link pointing out to the `/contribute` page (similar to what is currently implemented in `stage` or `prod`).

**Comment by emilghittasv** [comment]
I can confirm that this is verified in `dev`.

The "Contribute" top-navbar menu has been updated to contain the desired options (as per the figma file). 

With a note that the "Moderate forum content" is displayed only for users which have the necessary permissions to moderate content (as expected).

During the verification of this ticket I've noticed that the `Community discussions` option needs to be renamed to `Contributor discussions` & the ordering of the the elements under that section is not as per the figma design -> https://github.com/mozilla/sumo/issues/1714

Leaving this ticket under `qa` until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this is verified in `stage` as well.

During the verification of this ticket I've noticed a slight deviation from the Figma design. The `Templates` option is displayed inside the `Cotnribute > Contributor Tools` dropdown menu (and it shouldn't be). 

I'm going to move this ticket inside the `release` column and track the above mentioned issue in https://github.com/mozilla/sumo/issues/1827
