### ISSUE TITLE
Improve Recent Revisions page

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1627]
Relevant [figma link](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=ed7FyS3IELLCGw1l-4)

**Comment by emilghittasv** [comment]
I can confirm that the "Recent Revisions" page has been updated to match the figma design & the slack conversations.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
