### ISSUE TITLE
Update top-level AAQ menu

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1628]
[figma](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=386-2799&mode=design&t=svlClS8097icxNKf-4)

**Comment by emilghittasv** [comment]
I can confirm that the Ask a Question (AAQ) top-navbar menu contains the correct set of elements (as per the figma design) in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
