### ISSUE TITLE
Update copy in Explore Solutions

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1629]
[figma](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=ed7FyS3IELLCGw1l-4)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5834

**Comment by akatsoulas** [comment]
From Josh in slack:

Widget States:
```html
Product has ticketing support (user authenticated)
<h2>Ask a Question</h2>
<p>Still need help? Continue to contact our support team.</p>
Product has ticketing support (user is not authenticated)
<h2>Ask a Question</h2>
<p>Still need help? Sign in to contact our support team.</p>
Product has forum support (user is authenticated)
<h2>Ask a Question</h2>
<p>Still need help? Continue to ask your question on our forums.</p>
Product has forum support (user is not authenticated)
<h3>Ask a Question</h2>
<p>Still need help? Sign in to ask your question on our forums.</p>
```

**Comment by emilghittasv** [comment]
I can confirm that the correct AAQ widget is displayed inside the Explore Solutions pages for all premium & freemium products for both signed in & signed out states.

Verification was performed in `dev`. Leaving this ticket inside `qa` until it gets pushed & verified inside `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
