### ISSUE TITLE
archive translations of two Firefox suggest articles

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1632]
The following was requested by the content team and approved by the community team:

- Bulk archive the translations of [How to Customize Firefox Suggest Settings](https://support.mozilla.org/en-US/kb/firefox-suggest) and [Firefox Suggest FAQ](https://support.mozilla.org/en-US/kb/firefox-suggest-faq), leaving only the English articles.
- Generate a list of contributors involved in the archived translations so @kelimuttu can explain the context and communicate this change.

**Comment by escattone** [comment]
## All contributors to the translations of [How to Customize Firefox Suggest Settings](https://support.mozilla.org/en-US/kb/firefox-suggest)
- [Artist](https://support.mozilla.org/en-US/user/Artist)
- [Goudron](https://support.mozilla.org/en-US/user/Goudron)
- [Manuela.Silva](https://support.mozilla.org/en-US/user/Manuela.Silva)
- [Mozinet](https://support.mozilla.org/en-US/user/Mozinet)
- [TyDraniu](https://support.mozilla.org/en-US/user/TyDraniu)
- [Y.D.](https://support.mozilla.org/en-US/user/Y.D.)
- [and.cza553](https://support.mozilla.org/en-US/user/and.cza553)
- [d.spentzos](https://support.mozilla.org/en-US/user/d.spentzos)
- [digfleur](https://support.mozilla.org/en-US/user/digfleur)
- [erling.rosag](https://support.mozilla.org/en-US/user/erling.rosag)
- [graba](https://support.mozilla.org/en-US/user/graba)
- [hcasellato](https://support.mozilla.org/en-US/user/hcasellato)
- [ihor_ck](https://support.mozilla.org/en-US/user/ihor_ck)
- [marcelo.ghelman](https://support.mozilla.org/en-US/user/marcelo.ghelman)
- [markh2](https://support.mozilla.org/en-US/user/markh2)
- [michro](https://support.mozilla.org/en-US/user/michro)
- [noelonassis](https://support.mozilla.org/en-US/user/noelonassis)
- [norhorn](https://support.mozilla.org/en-US/user/norhorn)
- [pascalchevrel](https://support.mozilla.org/en-US/user/pascalchevrel)
- [smalltv233](https://support.mozilla.org/en-US/user/smalltv233)
- [soucet](https://support.mozilla.org/en-US/user/soucet)
- [user4000717](https://support.mozilla.org/en-US/user/user4000717)
- [wxie2016](https://support.mozilla.org/en-US/user/wxie2016)
- [xumeng](https://support.mozilla.org/en-US/user/xumeng)
- [zupe](https://support.mozilla.org/en-US/user/zupe)


## All contributors to the translations of [Firefox Suggest FAQ](https://support.mozilla.org/en-US/kb/firefox-suggest-faq)
- [Artist](https://support.mozilla.org/en-US/user/Artist)
- [Edjy](https://support.mozilla.org/en-US/user/Edjy)
- [Goudron](https://support.mozilla.org/en-US/user/Goudron)
- [JUM](https://support.mozilla.org/en-US/user/JUM)
- [Manuela.Silva](https://support.mozilla.org/en-US/user/Manuela.Silva)
- [Mozinet](https://support.mozilla.org/en-US/user/Mozinet)
- [TyDraniu](https://support.mozilla.org/en-US/user/TyDraniu)
- [Y.D.](https://support.mozilla.org/en-US/user/Y.D.)
- [ZoeMeow](https://support.mozilla.org/en-US/user/ZoeMeow)
- [bingchuanjuzi](https://support.mozilla.org/en-US/user/bingchuanjuzi)
- [d.spentzos](https://support.mozilla.org/en-US/user/d.spentzos)
- [goofy_sumo](https://support.mozilla.org/en-US/user/goofy_sumo)
- [graba](https://support.mozilla.org/en-US/user/graba)
- [markh2](https://support.mozilla.org/en-US/user/markh2)
- [michro](https://support.mozilla.org/en-US/user/michro)
- [norhorn](https://support.mozilla.org/en-US/user/norhorn)
- [smalltv233](https://support.mozilla.org/en-US/user/smalltv233)
- [soucet](https://support.mozilla.org/en-US/user/soucet)
- [uribetxebarria](https://support.mozilla.org/en-US/user/uribetxebarria)
- [wxie2016](https://support.mozilla.org/en-US/user/wxie2016)

**Comment by kelimuttu** [comment]
@escattone Do you have a hard deadline to archive the translation in bulk? I want to make sure that we're aligned with the timeline.

**Comment by escattone** [comment]
@kelimuttu No, I don't have a hard deadline, but the content team may have one, I'm not sure.

**Comment by escattone** [comment]
@kelimuttu is proposing an alternative solution that seems to be a better approach, and would eliminate the need for this task. Closing this, and we can open again if needed.

**Comment by kelimuttu** [comment]
Just for documentation purposes, we agree to ask contributors to remove the localized content and leave only the disclaimer section. We have added the localization note to the articles and communicated to the contributors whose work is impacted by this.

The only action item here is to document that process on the content side, so we'll use this as standard practice for articles that don't need to be translated in the future.

**Comment by AliceWyman** [comment]
Related bug: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1871473 Archive localized versions of the How to Customize Firefox Suggest Settings and Firefox Suggest FAQ articles [off-train request]
