### ISSUE TITLE
Remove obsolete accounts

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1635]
We should remove old accounts that are deactivated or not used any more. Specifically:

- [ ] Drop all accounts that are not migrated to FxA
- [ ] Drop the `is_fxa_migrated` flag from the code-base
- [ ] Investigate what's the cascade effect that the deletion will trigger and figure out ways to mitigate it

**Comment by escattone** [comment]
From production on January 11, 2024:
```python
In [1]: User.objects.filter(profile__is_fxa_migrated=False).count()
Out[1]: 1226059

In [2]: User.objects.filter(is_active=False, profile__is_fxa_migrated=False).count()
Out[2]: 70484

In [3]: User.objects.filter(profile__isnull=True).count()
Out[3]: 262
```

**Comment by akatsoulas** [comment]
A few ideas on how to manage users going forward:

- Automatically drop users that don't have any content posted in the platform and haven't login for a year.
- Delete the account on user prompt if there's no content
- If there's content posted, deactivate and fully anonymize the account.
   - When the content becomes archived (after 6 months) drop it if it belongs to a deactivated user
   - When the content becomes archived, drop the deactivate user

**Comment by smithellis** [comment]
Some more discovery:
Using `NestedObjects` from `django.contrib.admin.utils` you can create a collection of objects that are related to an object you pass in. 
There is also a method `get_deleted_objects` that will produce a nested list of objects that would be deleted given the parent object, a request, and the admin_site - it's not super friendly to casual requests, though.
I think the `NestedObjects` class is a useful inspection tool for this effort in terms of finding out what objects will cascade from a deletion of a User.
`User._meta.get_fields()` is also interesting, as it will give you back related models/fields, and their relationship.

**Comment by akatsoulas** [comment]
This is currently blocked - pending documented requirements for approval by the team

**Comment by akatsoulas** [comment]
Depends on #1679

**Comment by akatsoulas** [comment]
This ticket should be replaced by a series of tickets to implement the plan as defined in #1679

**Comment by smithellis** [comment]
I've opened a series of tickets to handle User Maintenance.
