### ISSUE TITLE
Zendesk form page for Monitor fails to load (ERR_TOO_MANY_REDIRECTS)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1636]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/questions/new/monitor page.
2. Click on the "Contact Support" option from the "Still need help?" widget.

**Expected behavior**
The user is redirected to the Zendesk contact form.

**Actual behavior**
`ERR_TOO_MANY_REDIRECTS` page is displayed.

**Screencasts**
![MonitorZendeskRedirect](https://github.com/mozilla/sumo/assets/28087895/ba625413-7e5f-4ae8-9812-213eb86e90ff)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome & Firefoxx

**Notes**
- Other premium products Zendesk form pages load as expected.

**Comment by akatsoulas** [comment]
This is a configuration change in the admin interface. We need to enable the locale for this product in the AAQ.
