### ISSUE TITLE
Remove the login interstitial banner

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1639]
Joe C mentioned that we have green light in removing the banner from the login interstitial page.

![image](https://github.com/mozilla/sumo/assets/28087895/a163bd92-4450-4f30-a2b2-78554ac12879)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5846

**Comment by emilghittasv** [comment]
I can confirm that the login interstitial banner is no longer displayed in `stage`.

Moving this ticket inside the `release` column.
