### ISSUE TITLE
Update Explore Solutions searchbar placeholder

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1647]
**Describe the bug**

As per the [figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=279-2838&mode=design&t=5RHCZYUqRBHhccJ3-0) the new placeholder for the searchbar inside the product solutions page should be: `Search questions, articles, or topics (example: saving passwords in Firefox)`

![image](https://github.com/mozilla/sumo/assets/28087895/172c0bab-e94c-49c1-91a8-3ef386426845)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5853

**Comment by emilghittasv** [comment]
I can confirm that the search placeholder has changed from `Find Help...` to `Search questions, articles, or topics (example: saving passwords in Firefox)` inside the Homepage, Explore Help Articles products page, product support pages and product solutions page.

Verification was performed in `dev`. Leaving this ticket inside `qa` until this work is pushed & verified in `stage`.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
