### ISSUE TITLE
The top-level menu panel overlaps the top-level menu options

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1648]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/questions/new
2. Sign in to SUMO.
3. Scroll down a bit. 
4. Mouse-over the top level elements.

**Expected behavior**
No UI issues are encountered.

**Actual behavior**
The top-level menu panel overlaps the top-level menu elements.

**Screencasts**
![top_navbar_overlap](https://github.com/mozilla/sumo/assets/28087895/bc0a87d1-4ab7-428e-9eb3-26ce3fdbf4e6)

**Additional context**
This issue is not reproducible if the user is not signed in to SUMO.

**Comment by emilghittasv** [comment]
@smithellis This issue is partially fixed in `dev`.

The top-level menu panel still overlaps the top-level menu options when the browser window width is reduced.

![Image](https://github.com/mozilla/sumo/assets/28087895/0e2bf44d-8341-4058-aac6-2a3222180a8e)


I'm moving this ticket back inside the in progress column.

**Comment by emilghittasv** [comment]
Disregard the above. This is a different issue because it's reproducible in `stage` & `prod` as well. 

So we can consider this ticket as verified fixed in `dev`. I'm going to leave this ticket inside the `release` column until the IA work is pushed & verified in `stage` as well.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5939

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

Leaving this ticket inside the `QA` column until the IA work is pushed and verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
