### ISSUE TITLE
unable to vote on the helpfulness of an article

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1649]
Users are often unable to vote on the helpfulness of an article. It works or at least worked sometimes, but the conditions are unknown. Trying to vote yields an endless spinner.

![image](https://github.com/mozilla/sumo/assets/3743693/4865cdf0-41bc-463a-9ab5-3e470a8db03e)

For example:

<img width="1368" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/656fc0ff-552c-4a01-947b-100d71b4bfc0">

One user reported the following:

![image](https://github.com/mozilla/sumo/assets/3743693/013ac31a-2d62-4f0a-9e3b-2d16b955c91e)

and experienced the problem on Firefox, Firefox Android, Chromium and Edge, and also reported that Chrome throws different errors than Firefox.

**Comment by escattone** [comment]
Documenting the following here from comments I made earlier in the week in Slack:

> I noticed that on `dev` and `stage`, the CSRF token embedded in the voting form on an article page changes with every request, as you'd expect, but that it doesn't in production, so it's an article caching problem. On `dev`, `stage`, and usually locally, we set `DEV=True` which disables caching, but in production, of course, we enable caching. All of our articles are cached for 5 minutes with the CSRF token embedded, so only an anonynous user who gets a fresh, un-cached article will be able to vote successfully. Everyone else will get a 403 due to a CSRF token mismatch.

**Comment by emilghittasv** [comment]
This issue was not reproducible previously in `stage`, also pointed out in https://github.com/mozilla/sumo/issues/1649#issuecomment-1924601122

I've performed a small regression testing session around article voting and no new issues were encountered.

Moving this ticket inside the `release` column.

Once this is released in `prod` I will extend my verification there and post a follow-up report here.

**Comment by emilghittasv** [comment]
Confirmed that I am unable to reproduce this in `prod`
