### ISSUE TITLE
Query error in Looker when trying to build a dashboard with Community Support data

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1653]
**Describe the bug**
I get an error when trying to use the Answers dimension from Kitsune Question explore. 

**Preconditions**
Looker access

**Steps to reproduce**
1. Go to `Explore` section in Looker and look for `SUMO`
2. Choose `Community Support: Questions `
3. Try to use `Answers` dimension

**Expected behavior**
The query will run, and I will be able to see the result in the data section 

**Actual behavior**
I get an error, saying that 
```
The Google BigQuery Standard SQL database encountered an error while running this query.
Query execution failed: - Name answers not found inside kitsune_questions at [2:23]
```

**Screenshots/Screencasts**
-

**Additional context**
-

**Comment by smithellis** [comment]
@emilghittasv Can I get some further information? Is this in https://mozilla.cloud.looker.com or https://lookerstudio.google.com ? I assume the first one, as it is the only one that gives me the `Explore` nav item. That said, if I search for SUMO, I don't find anything.
Maybe we can touch base on this in the morning.

**Comment by kelimuttu** [comment]
@smithellis You're right that it's the first one. Here's a screenshot of how the Explore selection looks from my end. 

![gambar](https://github.com/mozilla/sumo/assets/4922388/901a2c73-a744-493c-8c91-0c462cebf345)

**Comment by emilghittasv** [comment]
@smithellis tbh, I have not used Looker for SUMO before. I've just tried looking around for the SUMO options but the explorer searchbar returns nothing related to "SUMO" for me. 

![image](https://github.com/mozilla/sumo/assets/28087895/01f137b4-5a5d-48cc-bd04-e46aa3166945)

@kelimuttu I'm wondering, do our accounts need some extra permissions to see those?

**Comment by kelimuttu** [comment]
Eh? I'm not entirely sure, tbh. Looking at [this page](https://mozilla-hub.atlassian.net/wiki/spaces/SRE/pages/27920436/Looker), though, I don't think we necessarily have different permission on Looker. Perhaps, different database connection? Can you try to go to your profile and look at what OAuth connection credentials you have?

**Comment by smithellis** [comment]
Spoke with @kelimuttu and have request in to get matching permissions in Looker.

**Comment by smithellis** [comment]
Ok, I now have permissions and can replicate the issue. The table that supplies the `kitsune_questions` data doesn't have a column for `answers`. 

This is true in BQ as well. 

We need a different datasource, one that include `kitsune_answers` data. I've asked for support in the `#data-help` channel.

**Comment by smithellis** [comment]
@kelimuttu I don't know what changed this view (if it was changed, or if it ever worked). I found "Kitsune Q and A (sumo)" which appears to be fully functional and correctly put together. If you can access this, and it works for you, let me know. Otherwise I'll need to get more assistance on creating a new set-up.

**Comment by kelimuttu** [comment]
I was actually using another dataset `Community Support: Questions`, but now that you mention `Kitsune Q and A (sumo)`, I tried, and it appears that it's working fine for me too. 

I will need to re-create my current dashboard with this dataset, but otherwise, feel free to consider this as resolved for now. 

Thanks a lot for looking into this, @smithellis

**Comment by smithellis** [comment]
Great!
