### ISSUE TITLE
turn off Sentry events from the `request.summary` logger

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1656]
We can sometimes get a large quantity of events from the `request.summary` logger in Sentry, and these events are typically not interesting anyway, since they're generated from **already-handled** exceptions that are logged. For example, when calling Django's `get_object_or_404()`, if no instance of the given model exists, an `Http404` exception is raised and handled by Django, but the exception message is logged -- e.g., `No Topic matches the given query.` when calling [`get_object_or_404(Topic, slug=subtopic_slug, product=product, parent=topic)`](https://github.com/mozilla/kitsune/blob/2576d1f41f15a17c179dc040f809b423cca954cc/kitsune/products/views.py#L81).

**Comment by akatsoulas** [comment]
Closing per comment in the PR
