### ISSUE TITLE
Restricted visibility kb articles are returned in search results

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1658]
**Describe the bug**
@escattone mentioned in slack that search should never return any restricted document (no matter who the user is) since only unrestricted documents will be added to the search index.

**Preconditions**
Sign in to SUMO with an admin account.

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/kb/new page.
2. Add a particular group inside the Restrict Visibility field.
3. Submit the new kb article.
4. Approve the articles revision in order for it to go live. 
5. Wait a couple of minutes ( ~ 1-2 ).
6. Search for the article title inside the SUMO search bar. 
7. Redo step 6 with any user (regardless if he belongs to the group added in step 2) and while not signed in to SUMO.

**Expected behavior**
The restricted visibility article is not returned inside search results.

**Actual behavior**
The restricted visibility article is returned in search results.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by akatsoulas** [comment]
What's the desired behavior here? Completely remove the restricted articles from the index or filter our the results for users that don't have the permissions to see those articles?

**Comment by emilghittasv** [comment]
@akatsoulas Ryan mentioned that the expected behavior here is to completely remove the restricted articles from the search index. So, regardless who the user is, restricted articles should not show up in search results.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Restricted visibility kb articles are no longer returned in search results regardless of the user (whitelisted, non-whitelisted or staff). 

Tested while restricting the kb visibility on kb creation, on the fly (by editing the article metadata for an article which is already live) and translated articles. I can also confirm that removing the visibility restriction will bring the article back in search results after a couple of minutes (~ 1-2)

Moving this ticket inside the `release` column.
