### ISSUE TITLE
The restricted kb article is displayed inside the "What Links Here" page even for non-whitelisted group of users

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1660]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/kb/new page.
2. Restrict the visibility to a certain group.
3. Fill valid data inside all of the required fields.
4. Inside the body field insert a link target pointing to an existing KB article. (Example: `[[Using Pontoon to Localize SUMO]]` )
5. Submit the article and approve the revision for it to go live.
6. With an account that doesn't belong to the whitelisted group from step 2 (or while not signed in to SUMO) access the `/links` (by clicking on the `What Link Here` option from the `Editing Tools` section) page for the article which was linked in step 4.

**Expected behavior**
The link which points out to the kb article which has restricted visibility is not displayed for users which don't belong to a whitelisted group or for non-admin accounts.

**Actual behavior**
The link which points out to the kb article which has restricted visibility is displayed for all users (even for users which are no signed in and users which don't belong to a whitelisted group).

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox.

**Comment by escattone** [comment]
@emilghittasv Based on the Slack group conversation earlier today, I think this also would no longer be considered a `bug`?

**Comment by akatsoulas** [comment]
Closing per last comment. Linking a restricted article in a published one will just trigger a 404 which is the desired behavior

**Comment by emilghittasv** [comment]
@akatsoulas 

I had a conversation with Ryan yesterday over slack. This ticket refers to the situation in which non-restricted kb articles are linked inside a restricted one (linking other non-restricted kb articles inside a restricted one for reference could be a practice).

This ticket describes what's going to happen in this situation (the restricted visibility article will get displayed inside the "What Links Here" page of the unrestricted one thus exposing it to non-whitelisted users). 

@escattone mentioned that after further investigating this, the removal of the restricted articles from that page should be an easy fix and would bring consistency to what we currently did for different areas through SUMO (hide the restricted visibility article for non-whitelisted users).

**Comment by akatsoulas** [comment]
After re-reading the comments, this makes a lot of sense. Agreed, the desired functionality would be to remove the article from the list of `What's links here`

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The restricted kb articles are no longer displayed inside the "What Links Here" page for non-whitlisted users (only whitelisted users are able to see and interact with the restricted visibility kb article link inside the 'What Links Here' page).

I can also confirm that the same behavior is encountered while testing this using kb article translations.

Moving this ticket inside the `release` column.
