### ISSUE TITLE
Restricted KB articles can be linked in other (non-restricted) kb articles and the link is available for all users

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1661]
**Preconditions**
Sign in to SUMO and create a restricted visibility article.

**Steps to reproduce**
1. Access any non-restricted kb article.
2. Click on the "Edit Article" option from the "Editing Tools" section.
3. Click on the "Insert a link..." option from the "Content" section.
4. Type the restricted visibility article title inside the "Support article:" field.
5. Select the article and submit the kb article edit.
6. Approve the revision and access the article with other (non-whitlisted users)

**Expected behavior**
Step 4: The restricted visibility article is not returned inside the "Insert a link..." modal.
Step 6: Links pointing out to restricted articles are not available/displayed for non-whitelisted users.

**Actual behavior**
Step 4: The restricted visibility article is returned inside the "Insert a link..." modal.
Step 6: Links pointing out to restricted articles are available/visible for non-whitelisted users. The user is redirected to the page not found page after clicking on the link.

**Screenshots/Screencasts**
Step 4:
![image](https://github.com/mozilla/sumo/assets/28087895/56b7f456-05bf-430e-b9c4-f6ff467b198b)

Step 6: 
![restricted_linked](https://github.com/mozilla/sumo/assets/28087895/aae598c4-42bc-4761-9994-7f6e47279844)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
@emilghittasv Based on the Slack group conversation earlier today, I think this would no longer be considered a `bug`?

**Comment by emilghittasv** [comment]
Yes! We can close this one and consider re-opening it if necessary.
