### ISSUE TITLE
Rename Monitor Support to Mozilla Monitor Support

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1665]
We should rename to Mozilla Monitor under:
- [ ] The product listing page (through admin)
- [x] In the AAQ

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5877

**Comment by emilghittasv** [comment]
I can confirm that the `Monitor` was renamed to `Mozilla Monitor` in:
- https://support.allizom.org/en-US/questions/new (Contact Support page)
- https://support.allizom.org/en-US/questions/new/monitor (Mozilla Monitor Solutions page)
- https://support.allizom.org/en-US/questions/new/monitor/form (Mozilla Monitor contact support form)

As part of this testing session I've also submitted a couple of tickets to Zendesk (for Mozilla Monitor product). No regressions encountered.

Moving this ticket inside the `release` column.
