### ISSUE TITLE
SUMO content breaks with get() returned more than one Image -- it returned 2! (Sentry error)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1672]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org
2. Currently `stage` has two similar images in naming: https://support.allizom.org/en-US/gallery/image/50190 (named **Test Image**) and https://support.allizom.org/en-US/gallery/image/50186 (named **Test image**).
3. This breaks everywhere so you can reproduce by adding [[Image:test image]] while editing an article, article thread, simple thread, AAQ question or sending a SUMO message to someone.

**Expected behavior**
SUMO doesn't break.

**Actual behavior**
SUMO breaks displaying the following page: 

```
An Error Occurred

Oh, no! It looks like an unexpected error occurred. We've already notified the site administrators. Please try again now, or in a few minutes.
```

**Screencasts**
![breakage](https://github.com/mozilla/sumo/assets/28087895/9c595ab0-1c77-4345-a25c-0809b281e4b5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Reproducible in `stage` only.

I suspect https://github.com/mozilla/kitsune/pull/5887 causing this to occur.
Sentry error: https://mozilla.sentry.io/issues/4980178836/?alert_rule_id=13095090&alert_timestamp=1708001493249&alert_type=email&environment=us-west1&notification_uuid=5da0098b-08a8-4196-b2b6-eae5b15d356a&project=4504326797197312&referrer=alert_email

* Sending a private message with the tag from step 3 breaks the entire "Sent Messages" for the sender (he is unable to access that particular page anymore).  The receiver user is unable to open the inbox section because the "An Error Occurred" page is displayed.
* Adding the tag from step 3 to a Question makes the question no longer accessible by users.
* Adding the tag from step 3 to a revision makes the revision inaccessible for other users to see.

**Comment by escattone** [comment]
This issue was discovered and created after merging https://github.com/mozilla/kitsune/pull/5887, which was the root cause. However, that PR was reverted by https://github.com/mozilla/kitsune/pull/5888, so this issue no longer exists.
