### ISSUE TITLE
404 page is returned for locale leaders when trying to review the first revision from an article translation

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1680]
**Describe the bug**
A locale leader has pointed out in Element that he is unable to review a submitted revision (receiving a 404 page when clicking on the "review" option).

After further investigating this issue I've noticed that it has the same flavor as https://github.com/mozilla/sumo/issues/1674#issuecomment-1952001956 but with some differences:

**Preconditions**
Sign in to SUMO with an admin account.

**Steps to reproduce**
1. Navigate to the https://support.allizom.org/en-US/kb/new page.
2. Submit/Create the article.
3. Approve the article's revision & mark the revision as ready for localization.
4. Navigate to the https://support.allizom.org/ro/localization/template-translations page.
5. Click on the "Necesită traducere" (Translation Needed) and submit a new translation for review (do not approve it) for the article created in step 2.
6. Navigate to the https://support.allizom.org/en-US/kb/locales/ro/ page and add a different user (let's call him user B) as a locale leader.
7. Sign in with the locale leader added in step 6.
8. Navigate to the https://support.allizom.org/ro/localization/template-translations page.
9. Click on the "Necesită revizuire" (Needs review) for the article translation performed in step 5.
10. Click on the "Revizuiește" link for the unreviewed revision.

**Expected behavior**
The locale leader is able to review even the first revisions.

**Actual behavior**
The 404 page is displayed because (my feeling is that) the locale leaders group doesn't have the `wiki| revision | Can review a revision |` permission. 

**Screencasts**
I've managed to reach the performance of having >10mb for the screen recording. If you wish to see this issue in action, please access -> https://drive.google.com/file/d/11l5lxByRasqEorCKBNiy9DstrajaY9gS/view?usp=sharing (or ping me in slack and I can share it there directly).

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
What's interesting is that adding a locale leader via UI is different than manually adding a user to the SUMO Locale Leaders & Romanian Localization groups via admin directly. If the user is added directly via admin (instead of adding him via UI as in step 6) to those groups, he will not be able to reach the /history endpoint for that article translation (SUMO will yield a 404 page). 

If the user is added as a locale leader via UI he is then able to access the /history page for that particular article translation but still not able to review the revision (will receive the 404 page when clicking on the 'review' option for that particular revision). (but he can interact with the "pencil" button to edit the article based on that revision).

**Comment by Timmaks** [comment]
A other reviewer, not a locale leader, was the creator of the translation and he can review the article without issues.

**Comment by Mozinet-fr** [comment]
I met this problem with [this article](https://support.mozilla.org/fr/kb/firefox-android-visualiser-fichiers-pdf/history) too.

**Comment by kelimuttu** [comment]
Please note that both Tim and Pierre are locale leaders for nl and fr

**Comment by escattone** [comment]
This will be fixed in our next release, which we expect will be tomorrow (Thursday, Feb. 29).

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`

Locale leaders & Locale reviewers are able to review the first revision for a translated KB article.

Moving this ticket inside the `release` column.

**Comment by Timmaks** [comment]
It is fixed for me, thanks
