### ISSUE TITLE
Replace the use of is_staff by checking for membership in the Staff group

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1683]
We should be consistent and stop using the `is_staff` flag for staff members. Instead the `Staff` group should be used.

**Comment by emilghittasv** [comment]
I can confirm that this is working as expected in `stage`.

Apart from the verification performed in https://github.com/mozilla/sumo/issues/1738 I can confirm that users belonging to the `Staff group` are able to view & create restricted visibility KB articles.

Moving this ticket inside the `release` column.
