### ISSUE TITLE
Add Shutdown Banner to Hubs section of SuMO

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1684]
**Briefly describe the Initiative.**
Mozilla Hubs is being sunset as of May 31,2024. To inform users and direct them to relevant information, we need a banner on SuMO.

**Describe the milestones if any**
We need a banner visible across all Hubs surfaces on SuMO with the below text. Content for the sunset went live after 3/1, so we need this banner ASAP.

"Mozilla Hubs will shut down on May 31, 2024. For more information about the shutdown and how you can support Hubs' life beyond Mozilla, please read [this article](https://hubs.mozilla.com/labs/sunset/)."

**Add any related issues**
Add the issues this project is tracked by
https://app.asana.com/0/1203460865189761/1206674609317329/f

**What is the requested timeline for completion?**
Ideal timeline for this project proposal.

**Who is the audience**
Audience of this project. Internal or external, feature request or improvement.
External users

**Additional context**

**Applicable resources**
Project brief, JIRA, Bugzilla or GitHub, any documentation, use cases.
https://docs.google.com/document/d/1q7CE4u1kIvFqRxBcaV32GsvdcQUzKxHjf7URrsHuDwY/edit

**Comment by emilghittasv** [comment]
I can confirm that the Hubs shutdown banner is successfully displayed in `stage` for the Hub's product support page, topics page and inside the kb articles belonging under one of Hub's topic. Also the "article at Mozilla Hubs Creator Labs" link successfully redirects the user to the 
https://hubs.mozilla.com/labs/sunset/ page.

Testing was performed on:
* Windows 10: Firefox & Chrome.
* Huawei P40Pro: Firefox.

Moving this ticket inside the `release` column.
