### ISSUE TITLE
The top-level menu panel overlaps the top-level menu options when the browser window width is reduced

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1686]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/
2. Scroll down a bit.
3. Reduce the browser window width and mouse-over the top-navbar options.

**Expected behavior**
No UI issues are encountered.

**Actual behavior**
 The top-level menu panel overlaps the top-level menu elements.

**Screencasts**
**Stage**
![stage shrink](https://github.com/mozilla/sumo/assets/28087895/efc1889b-3216-43e6-b43c-14465d050810)

**Dev**
![shrink](https://github.com/mozilla/sumo/assets/28087895/cf888012-b720-4849-b4f7-1365483ee39c)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Affects both `stage` and `prod`. `dev` is also affected (where the current IA work lives) and it looks & feels a bit worse.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5939

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

The top-level menu panel no longer overlaps the top-level menu options when the browser window width is reduced.

I'm leaving this ticket inside the `QA` column until this patch is pushed to `stage` and verified there as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
