### ISSUE TITLE
The "Firefox browser" option from the Community Forums > Browse by product top-navbar section redirects to the Firefox Support page instead of Firefox Support forum

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1687]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over the "Community Forums" top-navbar option.
3. Click on the "Firefox browser" option from the "Browse by product" section.

**Expected behavior**
The user is redirected to the Firefox Support Forum page -> https://support-dev.allizom.org/en-US/questions/firefox

**Actual behavior**
The user is redirected to the FIrefox Support page -> https://support-dev.allizom.org/en-US/products/firefox

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `dev`.

Leaving this ticket inside the `QA` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
