### ISSUE TITLE
[GA4] The dmw_report_state event with the sign-into-fxa param is sent when signing out from fxa

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1693]
**Preconditions**
* Sign in to FxA sync.

**Steps to reproduce**
1. Navigate to the https://support.allizom.org/en-US/kb/switching-devices page
2. Sign out from the FxA sync.

**Expected behavior**
The `dmw_report_state` event contains a parameter which resembles better the sign out action.

**Actual behavior**
The `dmw_repost_state` event contains the `sign-into-fxa` param which describes the exact opposite of the action performed.

**Screencasts**
![GA4SignOut](https://github.com/mozilla/sumo/assets/28087895/029e2048-294f-489a-90d9-2c9b4eefac1e)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
I don't think this is a bug, but a natural outcome of a state change. When signing-out of FxA Sync, the state returns to its initial state of `sign-into-fxa`.

**Comment by emilghittasv** [comment]
Thanks Ryan!

I'm closing this issue.
