### ISSUE TITLE
[GA4] The dmw_click with the copy-link-to-clipboard-button param is not sent

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1695]
**Preconditions**
Sign in to FxA sync

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Reach the step 3 of the Wizard.
3. Click on the "Add to calendar" button.
4. Click on the "Copy link" button.

**Expected behavior**
The `dmw_click` event with the `copy-link-to-cliboard-button` param is successfully sent.

**Actual behavior**
The `dmw_click` event with the `copy-link-to-cliboard-button` param is not sent.

**Screencasts**
![GA4CopyLink](https://github.com/mozilla/sumo/assets/28087895/e6544b7e-bad3-420c-88f8-4eb198d35f9d)

**Desktop:**
 - OS: Windows 10.
 - Browser: Firefox.

**Comment by escattone** [comment]
Closing since this is not necessary to resolve, at least for now.
