### ISSUE TITLE
[GA4] The dmw_click event with the create-calendar-event param is not sent

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1696]
**Preconditions**
Sign in to FxA sync.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Reach the step 3 of the wizard.
3. Click on the "Add to calendar" button.
4. Click on the "Save" button.

**Expected behavior**
The `dmw_click` event with the `create-calendar-event` param is successfully sent.

**Actual behavior**
The `dmw_click` event with the `create-calendar-event` param is not sent.

**Screencasts**
![GA4SaveButton](https://github.com/mozilla/sumo/assets/28087895/440e636b-0eae-4d0e-a564-208e3783d236)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
Closing since this is not necessary to resolve, at least for now.
