### ISSUE TITLE
[GA4] undefined event & param sent instead of dmw_click event with send-email-reminder param

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1697]
**Preconditions**
Sign in to FxA sync

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Navigate to the Wizard's step 3.
3. Fill out the e-mail field and click on the "Send link" button.
4. Remove the e-mail entry.
5. Re-add the e-mail entry inside the e-mail field and click on the "Send link" button again.

**Expected behavior**
The `dmw_click` event with the `send-email-reminder` param is successfully sent for both steps 3 & 5.

**Actual behavior**
The `dmw_click` event with the `send-email-reminder` param is successfully send for step 3 but the `undefined` event with `undefined` param is sent for step 5

**Screencasts**
![GA4SendReminder](https://github.com/mozilla/sumo/assets/28087895/7df2e12c-dc63-4910-9488-732d80587bea)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
Closing since this is not necessary to resolve, at least for now.
