### ISSUE TITLE
Banner/Annoucement/Alert SOP for SUMO

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1699]
We need a SOP for how we define, use and implement Alerts, Banners and Announcements.

**Comment by smithellis** [comment]
[SOP](https://docs.google.com/document/d/1vlbAZQyQktBzgDvR7Lm3sCD_T6p8HEf9Buf3SXTusRY/edit?usp=sharing) is having a round of edits. There is a Platform meeting to discuss more details on Thursday - 3/28/2024 .

**Comment by smithellis** [comment]
https://docs.google.com/document/d/1hyNEkythr3tydPlbZudmfTMdjfCp9NXvL1BpJfEb88U/edit?usp=sharing

This needs some internal review; it's a smaller, cleaner, clearer document. But I'd like to be sure we have covered what we intended to cover.

**Comment by smithellis** [comment]
https://docs.google.com/document/d/1hyNEkythr3tydPlbZudmfTMdjfCp9NXvL1BpJfEb88U/edit?usp=sharing

**Comment by akatsoulas** [comment]
@smithellis what needs review here?

**Comment by smithellis** [comment]
Closing.
