### ISSUE TITLE
Extra space in article links causes the link to break

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1710]
**Describe the bug**
Initially described in https://support.mozilla.org/en-US/forums/contributors/716898?utm_campaign=forums-thread&utm_source=notification&utm_medium=email

**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Access a random KB article.
2. Click on the "Edit Article" option from the "Editing Tools" sidebar menu.
3. Inside the content section add a link pointing out to a different kb article & add space right after . Example: [[How to troubleshoot time related errors on secure websites |Test]] 
4. Save the article changes and click on the newly added link.

**Expected behavior**
The extra empty space is ignored and the link redirects the user to the correct article.

**Actual behavior**
The link breaks redirecting the user to the https://support.allizom.org/en-US/kb/new?title=How+to+troubleshoot+time+related+errors+on+secure+websites+ page.

**Screencasts**
![extraspacecreatenew](https://github.com/mozilla/sumo/assets/28087895/3aa679b5-4f04-40a6-850c-61cdff2895a1)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by AliceWyman** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1867499#c1

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6269

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket under the `release` column.
