### ISSUE TITLE
[Mobile] Extra space between the AAQ "Add a tag" and "Question Details" sections

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1712]
**Describe the bug**
Initially filled in https://bugzilla.mozilla.org/show_bug.cgi?id=1623788

**Preconditions**
Sign in to SUMO.

**Steps to reproduce**
1. Go to any posted AAQ question.
2. Expand the "Question Tools" top-navbar.
3. Scroll down a bit.

**Expected behavior**
The space between the "Add a tag" & "Question Details" sections is reduced.

**Actual behavior**
There is a bigger than needed space between the "Add a tag" & "Question Details* sections.

**Screenshots**
![screenshot_20240403_112834_org mozilla firefox](https://github.com/mozilla/sumo/assets/28087895/7dc777ab-12d4-4e7b-b88e-6a28f1dec1da)

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6270

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
