### ISSUE TITLE
[Mobile] Layout issues with the Ask a Question top-navbar options

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1713]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org
2. Tap on the "Ask a Question" top-navbar option.

**Expected behavior**
No layout issues are encountered.

**Actual behavior**
![screenshot_20240403_132305_org mozilla firefox](https://github.com/mozilla/sumo/assets/28087895/9055ac04-5748-4c7c-8548-52146335f92e)

**Smartphone:**
 - Device: Huawei P40Pro (Firefox), OnePlus 7T (Chrome)
 
 **Additional Notes**
 This issue is reproducible in `dev` only and is part of the IA navigation changes.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5938

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

Confirmed using Huawei P40Pro (Firefox), OnePlus 7t (Chrome) and iPhone 13Pro (Safari).

![Image](https://github.com/mozilla/sumo/assets/28087895/494910c3-cf49-4590-8595-9d587cee457b)

Leaving this ticket inside the `QA` column until the IA navigation work is pushed and verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is not reproducible in `stage`.

Moving this ticket inside the `release` column.
