### ISSUE TITLE
The ordering of the Contribute > Contributor discussions top-navbar menu options is different from the design specs

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1714]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over the "Contribute" top-navbar option.

**Expected behavior**
The order of the options displayed inside the "Contributor discussions" respects the [figma ](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=jKgi5mdTiyLKFgNq-0) doc

**Actual behavior**
The order is different from the figma specs.

**Screenshots**
`Dev`:
![image](https://github.com/mozilla/sumo/assets/28087895/0a578a8a-3a04-4809-b495-d09f20e6a12a)

`Figma`:
![image](https://github.com/mozilla/sumo/assets/28087895/c13a888e-c8f1-49d5-a1ad-7483043cad45)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* This issue is reproducible only in `dev` and is part of the IA project.

**Comment by emilghittasv** [comment]
@akatsoulas Also, the `Community discussions` section should (as per the figma doc) be renamed to `Contributor discussions`. 

Would you like me to file a different ticket for this case? Or can we track this inside this SUMO ticket as well?

**Comment by akatsoulas** [comment]
The order is different only when the option `Moderate Forum Content` is missing. When all the options are there the order is the same as in figma. I am closing this but feel free to reopen if there's a regression

**Comment by emilghittasv** [comment]
@akatsoulas I was referring to the `Contributor discussions` section. The elements from that particular section are not ordered as per the figma doc. This order is displayed as such regardless if the `Moderate Forum Content` option is available/displayed or not.

`Dev`
![image](https://github.com/mozilla/sumo/assets/28087895/4662b4b0-c298-44a1-9dd4-fae4d9ca5a4b)

`Figma`
![image](https://github.com/mozilla/sumo/assets/28087895/9515ce37-a282-4ce0-a840-45c6c0afe905)

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `dev`.

Leaving this ticket under the `qa` column until the IA work is pushed and verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is fixed in `stage`.

Moving this ticket inside the `release` column.
