### ISSUE TITLE
[GA4] Better search term data for "instant" search events

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1717]
I've been thinking about "instant" searches -- all searches made from any page other than the search landing page of `/{locale}/search/` -- and how they're done [every 200ms after a change to the search input box](https://github.com/mozilla/kitsune/blob/9b1fc5bab0f3a8f59595321f423609b1336ed0c0/kitsune/sumo/static/sumo/js/instant_search.js#L192). The GA event is sent the same way, so GA is littered with partial search terms like `f` --> `fi` --> `fir` --> ... --> `firefox`. I'm thinking we'd get much better search term data in GA4, as well as much better efficiency, if we only started searching after a pause in the user's typing -- maybe 500ms or something like that.

**Comment by escattone** [comment]
This vanilla JS code snippet might provide a nice starting point:
```js
function debounce(callback, wait) {
  let timeout;
  return (...args) => {
      clearTimeout(timeout);
      timeout = setTimeout(function () { callback.apply(this, args); }, wait);
  };
}

window.addEventListener('keyup', debounce( () => {
    // code you would like to run 1000ms after the keyup event has stopped firing
    // further keyup events reset the timer, as expected
}, 1000))
```

**Comment by escattone** [comment]
After looking at the [instant_search.js code](https://github.com/mozilla/kitsune/blob/9b1fc5bab0f3a8f59595321f423609b1336ed0c0/kitsune/sumo/static/sumo/js/instant_search.js) in more detail, I see it's already being "debounced". The "debounce" threshold simply needs to be increased.

**Comment by emilghittasv** [comment]
I can confirm that the `search` event is sent to GA4 containing the correct `search_term` data after a 600ms typing pause. 

Moving this ticket inside the `release` column.
