### ISSUE TITLE
502 Server Error when trying to send a message to a big user group

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1720]
**Preconditions**
Sign in to SUMO with a user that is part of the Staff group

**Steps to reproduce**
1. Navigate to the `/messages/new` page.
2. Type the name of a big group inside the `to` field (example: `Contributors`) or add multiple big groups inside the `to` field.
3. Add a message inside the `Message` field and send it out.

**Expected behavior**
The user is redirected to the `Sent Messages` page and the sent message to the group/groups is displayed inside the table.

**Actual behavior**
SUMO fails to redirect to the `Sent Messages` page and the `Error: Server Error` page is displayed. 

Please note that the actual message to the group members is sent successfully.

**Screencasts**
![ServerErrorGroupMessage](https://github.com/mozilla/sumo/assets/28087895/d4cb4298-ab4d-4ea5-b77f-ba8d2fb8b40d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5957

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The 502 error is no longer encounter when sending a message to big groups. Tested while sending a multi group message to all the groups listed in `/groups/`.

I've also verified that the message was received by some users belonging to the targeted groups.

Moving this ticket inside the `release` column.
