### ISSUE TITLE
Layout issues inside the Sent Messages page after submitting a message to multiple groups

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1721]
**Preconditions**
Sign in to SUMO with a Staff group member user and have a couple of sent messages to users only or to single groups.

**Steps to reproduce**
1. Go to /messages/new and send a message to multiple groups.

**Expected behavior**
No layout issues displayed inside the  "Sent Messages" page.

**Actual behavior**
The `To Groups` information shifts the `Message` information to the right.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/3b48eb13-0a21-457b-ab90-18c1fa5f42cd)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5976

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
