### ISSUE TITLE
Consider removing the avatar from the "Sent Messages" and "Read Sent Message" pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1724]
**Describe the bug**
As discussed in slack, there is no real benefit of having the user avatar displayed inside both the `Sent Messages` & `Read Sent Message` pages if we have that information displayed already inside the `To` field. 

Also the way that the recipient avatar is currently displayed seems to be a bit off (and this issues is also reproducible in `prod`). Having a message sent for more than 1 recipient will show the avatar for the sender instead of the recipient/recipients.

**Sent Messages page:**
![image](https://github.com/mozilla/sumo/assets/28087895/93ad86fa-0c36-45dc-bba4-3cc135f38df7)

**Read Sent Message page:**
![image](https://github.com/mozilla/sumo/assets/28087895/baeaf107-7aff-456c-af53-34dc446e738f)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5957

**Comment by emilghittasv** [comment]
I can confirm that the user avatar is no longer displayed inside the "sent messages" and "read sent message" pages. 

Moving this ticket under the `release` column.
