### ISSUE TITLE
Sent message content preview is displayed as bolded if the message was sent to only one recipient

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1726]
**Preconditions**
Sign in to SUMO.

**Steps to reproduce**
1. Go to `/messages/new`
2. Send out a message to a single user without applying the bold style.
3. Navigate to the "Read Sent Message" page for the sent message.

**Expected behavior**
The sent message is displayed in the exact format as it was sent.

**Actual behavior**
The bold style is automatically applied to the displayed text.

**Screencasts**
![BoldSentMessage](https://github.com/mozilla/sumo/assets/28087895/4ce53bce-bbb6-4c66-bbf5-bbda3e2f6601)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome & Firefox
 
 **Additional Information**
 * This issue is reproducible only in `stage`. `prod` is not affected.
 * Please note that received message is not displayed in bold for the recipient user.
 * This issue is not reproducible if sending the message to multiple users or to groups

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5957

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. Moving this ticket under the `release` column
