### ISSUE TITLE
Priviledge escalation - Non-staff users can send messages to Groups by editing the request body

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1727]
**Preconditions**
- Sign in with a non-staff account.
- Have the network tab open.

**Steps to reproduce**
1. Go to `/messages/new` and submit a message to a user.
2. Edit the sent request body by replacing the `to={usernameFromStep1}` with `to=TestGroup1` (or any other target group).
3. Resent the modified request.

**Expected behavior**
The non-staff level user should not be able to send messages to groups.

**Actual behavior**
The message is successfully sent to the group.

**Screencasts**
![Vul](https://github.com/mozilla/sumo/assets/28087895/3c0602cb-2257-4270-aef6-a2017d1e5da4)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5957

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket under the `release` column.
