### ISSUE TITLE
Layout issues inside the inbox section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1729]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to /en-US/messages/new
2. Send a message to user b by adding a bigger chunk of text inside the message body (example: 
`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`)
3. Sign in with the recipient user and verify the inbox section.

**Expected behavior**
No layout issues are displayed.

**Actual behavior**
Layout issues are visible. Comparison between `stage` and `prod`

`stage`
![image](https://github.com/mozilla/sumo/assets/28087895/ab2ad527-6456-4070-8073-e26bd9e67754)

`prod` 
![image](https://github.com/mozilla/sumo/assets/28087895/72dd779a-6939-4389-8e89-9b6b45ade72d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by emilghittasv** [comment]
@smithellis I think that we should revert the layout for the inbox back to it's original state (to what we have in `prod`)^

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5976

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
