### ISSUE TITLE
Messages can be sent to profileless groups

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1732]
**Preconditions**
Sign in to SUMO with an account belonging to the Staff group

**Steps to reproduce**
1. Go to the `/messages/new` page
2. Type the name of a group which doesn't have a profile inside the "To" field (example: `TestGroupNoProfile`).
3. Sent the message.

**Expected behavior**
The profileless groups are not returned as a search result inside the `To` field/messages cannot be sent to those groups.

**Actual behavior**
Profileless groups are returned inside the "To" field and messages can be sent to those groups.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5971 Contains the fix for this.

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Users belonging to the `staff` group are not able to send messages to profileless groups (The profileless group is not returned inside the "To" search results). 

Also verified that the group is successfully returned inside the "To" search results if a profile was created for that group and no longer returned if the profile was deleted.

Moving this ticked inside the `release` column.
