### ISSUE TITLE
Layout issues displayed inside the Kb Team page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1737]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/locales/en-US/

**Expected behavior**
No layout issues displayed.

**Actual behavior**
Layout issues are displayed for the locale leaders, reviewers and editors. The members name & private message options are shifted to the right

**Screenshots**
`Stage`
![image](https://github.com/mozilla/sumo/assets/28087895/533fd99b-166b-4afe-8b2c-140ebc160852)

`Prod`
![image](https://github.com/mozilla/sumo/assets/28087895/c91caa30-1646-443c-a939-159bc899a32e)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage`. `prod` is not affected.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5976 -- I believe this fixes the regression.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The mentioned UI issues are no longer displayed inside the KB Team page.

Moving this ticket inside the `release` column.
