### ISSUE TITLE
Messages sent to a single user cannot be previewed or deleted Sentry fires: 'kitsune.messages.models.OutboxMessage object' has no attribute 'recipients'

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1741]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to /en-US/messages/new
2. Send a message to only one user.
3. Click on the sent message from the "Sent Messages" page or try to delete it.

**Expected behavior**
The sender is able to view and/or delete the sent message.

**Actual behavior**
The `Oh, no! It looks like an unexpected error occurred. We've already notified the site administrators. Please try again now, or in a few minutes.` page is displayed and sentry fires: `UndefinedError kitsune.messages.models.OutboxMessage object has no attribute 'recipients'

**Screencasts**
![SentMessages](https://github.com/mozilla/sumo/assets/28087895/dd757752-d684-44b0-a512-94bb6442c759)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
- Please note that this issue is not reproducible if the message is sent to multiple recipients ( >1) or to groups.
- The recipient is able to view and/or delete the received message from the inbox.
- Sentry error: https://mozilla.sentry.io/issues/5236296452/?project=4504326797197312&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5970

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
