### ISSUE TITLE
If a username is identical to a group name, the message is sent to both the group and username which shares the same name

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1742]
**Preconditions**
Create a SUMO account with a name identical to a group name (example: TestGroup1) & make sure it doesn't belong to that group.

**Steps to reproduce**
1. Sign in to SUMO with a user belonging to the `staff` group.
2. Access the /messages/new page and inside the `To` field add the `TestGroup1` **group**
3. Send the message.

**Expected behavior**
The message is sent only to the members belonging to the `TestGroup1` **group**.

**Actual behavior**
The message is sent to both all members of the `TestGroup1` **group** **and** to the `TestGroup1` **user**.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by emilghittasv** [comment]
@smithellis 

Also, trying to send a message with a non-staff user to the user which has the same name as the group name will fail with the `You can't send messages to groups. Please select only users`.

![TestGroup1](https://github.com/mozilla/sumo/assets/28087895/1892f838-d6f2-496d-be23-08155de748ab)

**Comment by emilghittasv** [comment]
Also, when sending a message with a `Staff` user to the username which has the same name as the group name will send the message to both the user & the group.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5971

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

* Sending a message to the `group` will not send the same message to the `user` which has the name similar to that group (and is not part of that group)
* Sending a message to the `user` will not send the same message to the `group` which has the name similar to that user.
* The message can be successfully send to both the `user` and `group` which shares the same names if both are added inside the "To" field while using an account that is part of the `staff` group.
* The `group` is not returned inside the "To" field for users which are not part of the `staff` group (only the user which has the same name as the group).

Moving this ticket inside the `release` column.
