### ISSUE TITLE
do not send GreenletExit exceptions to Sentry

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1743]
With the deployment of https://github.com/mozilla/kitsune/pull/5960 to stage, we're seeing a huge increase in `GreenletExit` exceptions being reported to Sentry. These exceptions come from the underlying `gevent` package, and are [a normal part of its operation](https://www.gevent.org/api/gevent.greenlet.html#gevent.GreenletExit), so should be ignored.

NOTE: Bedrock is also ignoring them: https://github.com/mozilla/bedrock/pull/14486

**Comment by akatsoulas** [comment]
Before disabling Sentry exceptions for this event, we should figure out why we have a big increase on the number of these events after the upgrade of Gunicorn

**Comment by escattone** [comment]
I found the root cause. In Sentry, the errors are coming from the `gunicorn.error` logger, and the error message is `Error handling request (no URI read)`:

<img width="866" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/cb38b632-310d-40da-be15-a7edbce02284">

The root cause is a logging line added at line 255 in the `gunicorn/workers/base.py` file sometime between the release of 20.1.0 and 22.0.0.

- Go to https://github.com/benoitc/gunicorn/compare/20.1.0...22.0.0
- Click on the `Files changed` tab
- Search for `gunicorn/workers/base.py` file
- See the added logging at lines 254-255.

So we can safely ignore these `GreenletExit` exceptions, since they're not errors, and the reason we're seeing such an increase is due to additional logging in `gunicorn`.

**Comment by akatsoulas** [comment]
That's great find @escattone! I opened PR https://github.com/mozilla/kitsune/pull/5983 to ignore these errors.
