### ISSUE TITLE
New Contributors forum is still listed in the Contributertools menu while it is Retired

### ISSUE THREAD

**Issue by Timmaks** [mozilla/sumo#1746]
**Describe the bug**
New Contributors forum is still listed in the Contributertools menu while it is Retired

**Steps to reproduce**
1. Go to Contributer Tools
2. Click on New Contributers
3. link to [Retired] New Contributors

**Expected behavior**
Not showing up in the menu

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5974

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The "New Contributors" option is no longer displayed inside the "Contributor Tools" top-navbar menu and inside the "For Contributors" side navbar.

Moving this ticket inside the `release` column.
