### ISSUE TITLE
Elastic search synonym set request (bookmarks bar)

### ISSUE THREAD

**Issue by jscher2000** [mozilla/sumo#1747]
**Issue:** A search for _bookmarks bar_ does not turn up [the main article for the Bookmarks Toolbar](https://support.mozilla.org/kb/bookmarks-toolbar-display-favorite-websites) in the top results. 

This is a problem because users coming from Chrome and its sister browsers may not realize that there is a different naming convention between those browsers and Firefox, and will end up going down a rabbit hole or losing confidence in SUMO. 

**Possible Resolution:** Could this problem be resolved by adding a new synonym set in Elastic search? For example:

`bookmarks bar, bookmarks toolbar`

(I don't know whether the more general `bar, toolbar` would be too all encompassing.)

If that is not an option, what would be the preferred method to ensure that the desired KB article comes up prominently in search results?

**Comment by emilghittasv** [comment]
The main problem of not having the https://support.allizom.org/en-US/kb/bookmarks-toolbar-display-favorite-websites kb article returned in the top results is still occurring.

While searching for `bookmarks bar` and `bookmark bar` that article is displayed on the second page of search results. (if filtering for Help Articles Only ) and on the 8'th search result page if the filter is set to View All

While searching for `bookmarks toolbar` and `bookmark toolbar` that article is displayed in the first search result page as the second listed item.

I'm tracking this ticket for the current sprint & moving it back inside the `in progress` field.

**Comment by smithellis** [comment]
I need to figure out how I can login to Elastic to upload and revise the extension. I apparently don't have access.

**Comment by smithellis** [comment]
This should be fixed up now.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The https://support.allizom.org/en-US/kb/bookmarks-toolbar-display-favorite-websites article is returned into the top search results when searching for `bookmarks bar`, `bookmark bar`, `bookmarks toolbar` and `bookmark toolbar`.

Moving this ticket inside the `release` column.
