### ISSUE TITLE
Use GA4 events for the new nav

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1748]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6078

**Comment by emilghittasv** [comment]
I can confirm that the newly added GA4 events for the nav items are successfully sent. 

During the verification of this ticket I've noticed that we are not sending GA4 events for the `Contribute` > `Contributor discussions` and `Contributor tools` options. (filled and keeping track under https://github.com/mozilla/sumo/issues/1860)

I'm moving this ticket inside the `release` column.
