### ISSUE TITLE
Update the sidenav contributor tools menu

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1749]
[Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=549-13633&mode=design&t=2kcJFHmX725YPomq-0)

**Comment by emilghittasv** [comment]
I can confirm that the `Contributor tools` sidenav matches the figma & slack changes.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
