### ISSUE TITLE
Make the "Contribute" sub-menu available only for logged in contributors

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1750]
**Describe the bug**
As @cajinajr pointed out in slack, the sub-menu for the `Contribute` top-navbar option should be available only for signed in contributors.

If the user is logged out or logged in with a non-contributor account, the `Contribute` should act as a link pointing out to the `/contribute` page (similar to what is currently implemented in `stage` or `prod`).

**Comment by emilghittasv** [comment]
This is partially fixed.

I can confirm that the `Contribute` sub-menu is available only when logged in.

If the user is logged out, the sub-menu is not available and clicking on the `Contribute` top-navbar option will redirect the user to the `/contribute` page.

@akatsoulas This is partially fixed because I believe that the desired behavior here is that only logged in contributors should be able to see that sub-menu. If I'm logged in with a non-contributor account I'm still able to see it.

I'm going to move this ticket back inside the `in progress` column until we decide how to proceed further.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6010

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `dev`.

* If the user is not signed or signed in with a non-contributor account, the "Contribute" sub-menu is not displayed and the "Contribute" option acts as a link pointing out to the /contribute page.
* If the user is signed in with a contributor account, the "Contribute" sub-menu is successfully displayed.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
