### ISSUE TITLE
"Social Support Discussions" option is displayed twice inside the "Contributor Discussions" sidebar

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1751]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/forums/contributors/

**Expected behavior**
No duplicated options are displayed inside the "Contributor Discussions" side navbar.

**Actual behavior**
The Social Support Discussions option is displayed twice.

**Screencasts**
![image](https://github.com/mozilla/sumo/assets/28087895/1ef47edb-2114-4fad-8744-a6f12b785581)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5977

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

The "Social Support Discussions" is no longer duplicated inside the "Contributor Discussions" sidebar.

I'm leaving this ticket inside the `QA` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage` as well.

Moving this ticket inside the `release` column.
