### ISSUE TITLE
Consider highlighting the current user location inside the "Contributor discussions" side navbar

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1752]
**Describe the bug**
As described inside the [IA mockup](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design&t=UDKjgL48JWntHVTf-0), the list items from the "Contributor discussions" side navbar should be highlighted if the user is located on that particular page. 

I believe that this can be done by adding the `selected` class to those respective `li` options. 

Example:
![image](https://github.com/mozilla/sumo/assets/28087895/46a44a4e-9335-47db-bbe0-1e03ec3fcdbb)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6062

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
