### ISSUE TITLE
The "Forum Moderator Discussions" option from the "Contributor Discussions" side-navbar is displayed for non-forum moderators

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1753]
**Preconditions**
Sign in to SUMO with a non-forum moderator account.

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/forums/.
2. Click on the "Forum Moderator Discussions" option.

**Expected behavior**
Since the "Forum Moderator" forum is a private forum (only available for forum moderators) it shouldn't be displayed for non-forum moderator users.

**Actual behavior**
The "Forum Moderator Discussions" option is displayed and once clicked will redirect the user to the 404 page.

**Screencasts**
![ForumModerators](https://github.com/mozilla/sumo/assets/28087895/916043be-dff5-4b3c-a833-5978c42c7314)

**Desktop (please complete the following information):**
 - OS: macOS 13.6
 - Browser: Firefox

**Additional context**
* This issue is reproducible only in `dev` as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5989

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

* The `Forum Moderator Discussions` option is available while signed in with a forum moderator.
* The `Forum Moderator Discussions` option is not available while signed in with a non-forum moderator account.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage` as well.

Moving this ticket inside the `release` column.
