### ISSUE TITLE
Rename the "Community discussions" to "Contributor discussions" inside the Contribute top-navbar sub-panel

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1754]
**Describe the bug**
As pointed out in [figma](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=380-2166&mode=design&t=RuTmMMF4QSJLqy2h-0) the "Community discussions" should be renamed to "Contributor dicussions" inside the "Contribute" top-navbar panel.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5982

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `dev`. 

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage`.

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
