### ISSUE TITLE
Update the contributor tools sidenav in Locales

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1756]
[Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-7319&mode=design&t=Wo0SI3HQ9VIdBhea-4l)

**Comment by emilghittasv** [comment]
@akatsoulas QA is currently blocked in testing this ticket due to https://github.com/mozilla/sumo/issues/1777

**Comment by emilghittasv** [comment]
I can confirm that the `Contributor tools` side nav from the Locales page matches the Figma design in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
