### ISSUE TITLE
Update the contributor tools in KB Dashboard

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1757]
[Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-7561&mode=design&t=Wo0SI3HQ9VIdBhea-4)

- [x] Similar update should be performed on the Moderate Forum Content page

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5990

**Comment by emilghittasv** [comment]
I can confirm that the `Contributor tools` sidenav from the KB dashboard matches the Figma design in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
