### ISSUE TITLE
Update the contributor tools sidenav in media gallery

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1758]
[Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-7397&mode=design&t=Wo0SI3HQ9VIdBhea-4)

**Comment by emilghittasv** [comment]
I can confirm that the Media Gallery page has been updated as per the figma design & based on the conversations we had on slack.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
