### ISSUE TITLE
[GA4 data API conversion] Article page views of non-English locales with English slug

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1768]
This issue was discovered during QA for mozilla/sumo#1705.

We're not really counting page views properly for a localized URL that's using the same slug as its English parent, and the localized article doesn't exist. In that specific case, we display the English article at the non-English locale (a "fallback" to the English content), so the page view should probably be attributed to the English article.

The problem is that we've been making that decision -- deciding that a "fallback" occurred -- when we retrieve the GA data  -- which is a guess -- rather than at the moment it happens by sending a "fallback" indicator with the GA event itself.

The GA3 code would make an "considered guess" at the time that the GA data was retrieved, and attribute the page views to the English article.

The new GA4 code is different, and probably too strict in that it doesn't attempt to retroactively "guess", so it doesn't attribute this "fallback" case to the English article.

**Comment by escattone** [comment]
After discussing this with some team members, we're considering resolving this in a strict manner, by sending an additional parameter for `page_view` events when the `content_group` is `kb-article`. The additional parameter would indicate whether or not a "fallback" to the English content did indeed actually occur. Then, when retrieving the GA data later, we could use that additional parameter to perfectly attribute those events without guessing.

**Comment by escattone** [comment]
## Planned Steps for Resolution
- [x] Add new GA4 event parameter `article_locale` that's sent with every KB article pageview.
- [x] Create custom dimension for `article_locale` in GA4 for the stage and production properties.
- [x] Use the new dimension to accurately attribute all KB article pageviews to the proper article when gathering pageview information from GA4.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
