### ISSUE TITLE
Rename "Firefox of iOS" to "Firefox for iOS" inside the "Community Forums" top-navbar menu

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1770]
**Describe the bug**
As described inside the [Figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-6337&mode=design&t=3lA2odrPyjVaAEjZ-0) the `Firefox for iOS` option is displayed inside the `Browse by product` section.

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over the `Community Forums` top-navbar.

**Expected behavior**
The `Firefox for iOS` option is listed inside the `Browse by product` section.

**Actual behavior**
The `Firefox of iOS` option is listed inside the `Browse by product` section.

**Screenshots**
`Dev`
![image](https://github.com/mozilla/sumo/assets/28087895/891795af-79a6-490c-af16-b9581c56e861)

`Figma proposal`
![image](https://github.com/mozilla/sumo/assets/28087895/715017a6-65ac-457b-b6c3-ed9fcd99aa81)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible only in `dev` and is part of the IA changes.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
