### ISSUE TITLE
UI issues inside the "Contributor tools" top-navbar section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1772]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Navigate to the https://support-dev.allizom.org/en-US/ page.
2. Mouse-over the "Contribute" top-navbar option.

**Expected behavior**
The "Contribute" sub-panel matches the [Figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-6479&mode=design&t=3lA2odrPyjVaAEjZ-0).

**Actual behavior**
* UI issues.
* It seems that some unwanted options were added inside the sub-panel like: Locales, Aggregated Metrics and Locale Metrics.

![image](https://github.com/mozilla/sumo/assets/28087895/bb31c2ad-f629-45d4-a2ff-a25d355ab4ce)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible only in `dev` and is part of the IA changes.

**Comment by akatsoulas** [comment]
This is no longer reproducible. Moving it to QA for final verification.

**Comment by emilghittasv** [comment]
Yep, I can confirm that this issue is no longer reproducible in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
