### ISSUE TITLE
Username is not automatically prefilled inside the To field when trying to submit a message from the profile or community pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1774]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/community/top-contributors/l10n
2. Click on the "Private Message" option.
3. Navigate to a user page (example: https://support.allizom.org/en-US/user/fasttest/)
4. Click on the "Private Message" button

**Expected behavior**
The user is redirected to the New Message page and the username is automatically prefilled inside the "To" field. (same as in `prod`)

**Actual behavior**
The user is redirected to the New Message page but the username is not automatically prefilled inside the "To" field.

**Screencasts**
![preFilled](https://github.com/mozilla/sumo/assets/28087895/cf7faaa5-1a61-4424-92e3-e0de40d1b85a)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only. `prod` is not affected.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5998

Proposed fix.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
