### ISSUE TITLE
Support Forum Discussions option redirects the user to the /questions/ page instead of /forums/support-forum-contributors/

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1775]
**Describe the bug**
As proposed inside the [IA Figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design) the `Support forum discussions` (from the `Contribute` top-navbar and from the `Contributor Discussions` sidebar) should redirect the user to the /forums/support-forum-contributors/ page.

**Preconditions**
Sign in to SUMO dev

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over the `Contribute` top-navbar option.
3. Click on the `Support Forum Discussions` option.
4. Navigate to the https://support-dev.allizom.org/en-US/forums/ page.
5. Click on the `Support Forum Discussions` option from the `Contributor Discussions` sidebar.

**Expected behavior**
Step 3 and 5: The user is redirected to the https://support-dev.allizom.org/en-US/forums/support-forum-contributors/ page.

**Actual behavior**
Step 3 and 5: The user is redirected to the https://support-dev.allizom.org/en-US/questions/ page.

**Screencasts**
![dev-support-forum](https://github.com/mozilla/sumo/assets/28087895/5ade8dc2-87b5-4234-bec7-5b89448828e1)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
