### ISSUE TITLE
The Templates option is missing from the Contributor Tools sidenav

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1776]
**Describe the bug**
As described inside the [IA figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design) the `Contributor tools` sidebar menu should contain the following options:
* Moderate Forum Content (if the signed in user has the necessary perms)
* Recent Revisions
* Guides
* Templates
* Community Hub
* Locales
* Knowledge Base Dashboards
* Locale Metrics
* Aggregated Metrics
* Media Gallery

**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Navigate to the https://support-dev.allizom.org/en-US/kb/revisions page.
2. Observe the `Contributor Tools` side navbar.

**Expected behavior**
All the proposed sidebar menu links/options are available.

**Actual behavior**
The `Templates` option is missing from the sidebar.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified in `stage` as well.

Moving this ticket inside the `release` column.
