### ISSUE TITLE
Capitalization mismatch in some top-navbar options

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1779]
**Describe the bug**
[IA figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design)

**Preconditions**
Sign in to SUMO dev

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over all the available top-navbar options.

**Expected behavior**
**Explore Help Articles > Explore by product**:
* Firefox `browser`

**Ask a Question > Get help with**:
* Firefox `browser`
* Firefox for `Enterprise`
* Firefox `Focus`
* Firefox `Relay`
* Mozilla `Account`

**Contribute > Contributor discussions**:
* Sumo `community discussions`
* Support `forum discussions`
* Social `support discussions`
* Localization `discussions`
* Article `discussions`
* View all `discussions`

**Contribute > Contributor tools**:
* Recent `revisions`
* Media `gallery`
* Community `hub`

**Actual behavior**
**Explore Help Articles > Explore by product**:
* Firefox `Browser`

**Ask a Question > Get help with**:
* Firefox `Browser`
* Firefox for `enterprise`
* Firefox `focus`
* Firefox `relay`
* Mozilla `account`

**Contribute > Contributor discussions**:
* Sumo `Community Discussions`
* Support `Forum Discussions`
* Social `Support Discussions`
* Localization `Discussions`
* Article `Discussions`
* View all `Discussions`

**Contribute > Contributor tools**:
* Recent `Revisions`
* Media `Gallery`
* Community `Hub`

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6004

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
