### ISSUE TITLE
Replace Firefox Focus with Thunderbird in Explore by product top-navbar section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1780]
**Describe the bug**
[IA figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=389-3194&mode=design)

**Preconditions**
Sign in to SUMO dev

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Mouse-over the `Explore Help Articles` top-navbar option.

**Expected behavior**
The `Thunderbird` option is displayed inside the `Explore by product` top-navbar section.

**Actual behavior**
The `Firefox Focus` option is displayed instead.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This is in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6003

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `stage`.

Moving this ticket inside the `release` column.
