### ISSUE TITLE
Both "Show More" and the original expandable menu are displayed inside the Recent Revisions page on mobile devices

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1782]
**Describe the bug**
As mentioned inside the [IA Figma doc](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-4989&mode=design&t=jsamXIYg2Ybn4Z7t-0) the `Show More` expandable menu should be only implemented for Desktop devices.

**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/kb/revisions

**Expected behavior**
From a slack discussion with @cajinajr:
* On mobile devices we want to keep the original expandable menu but the name should be changed to `Contributor Tools`.
* The items from the original expandable menu are going to change as per the dev handoff documentation.

**Actual behavior**
Both the `Show More` and `Contributor Tools` expandable menus are displayed.

**Screencasts**
https://github.com/mozilla/sumo/assets/28087895/1f2a2bc6-9233-4da4-b566-18ab07dc2177

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6007

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage` as well.

Moving this ticket inside the `release` column.
