### ISSUE TITLE
Some non-US articles are displayed inside the Featured Articles list on the en-US SUMO version

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1784]
**Describe the bug**
This was caught by a recent playwright test run

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/
2. Refresh the page a couple of times until the `ಸಾಮಾನ್ಯವಾಗಿ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು` and `Сжатие папок` articles are displayed inside the `Featured Articles` section.
3. Click on both articles.

**Expected behavior**
Non en-US articles (in this case `kn` and `ru`) are not visible on the en-US SUMO version.

**Actual behavior**
The non-US articles are displayed and redirect to a 404 page when clicked.

**Screencasts**
![featured-articles-different-locale](https://github.com/mozilla/sumo/assets/28087895/59fd5f1f-94e3-4b44-b7e3-6a69ca5e4823)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`. `prod` is not affected.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6002

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
