### ISSUE TITLE
Users are not UI notified when a new message was received or if there are any unread messages in the inbox

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1785]
**Preconditions**
Sign in to SUMO with account a

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/messages/new
2. Send a message to account b.
3. Sign in to SUMO with account b.

**Expected behavior**
Users are notified at UI level that they have received a new unread message.

**Actual behavior**
Users are not notified at UI level that a new message was received.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Both `stage` and `prod` are affected.

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by kelimuttu** [comment]
Oh, this is cool! I remember we used to have this functionality in the past (without the message counter), so this is an improvement worth celebrating. 

@emilghittasv could you please notify me when this is up in the release pipeline? Thanks!

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

* Users are now visually notified when they have at least 1 unread message inside the SUMO inbox.  This applies for all types of messages (messages sent by other users or messages coming from a group-wide message).
* A mouse-over the SUMO username inside the top-navbar will display the unread message counter next to the "Inbox" option if a user has at least 1 unread message.
* The counter successfully decrements if the user reads, deletes or marks the unread message as read.
* The counter successfully increments when the user receives a new message.

Top-navbar visual notification:
![Image](https://github.com/user-attachments/assets/59534164-85e9-49cf-ac22-2268511adede)

Top-navbar counter visual notification:
![Image](https://github.com/user-attachments/assets/e3f84115-09ca-4bf7-bba5-73ebe123342c)

Moving this ticket inside the `release` column.

@kelimuttu This is now fixed/available in `stage` if you want to take a look! I've approved this to ride to prod with our next release.

**Comment by kelimuttu** [comment]
@emilghittasv I just tried this on staging. It's pretty neat! One thing I notice, though. There's no indication, in your inbox page, which message you've read and which one you haven't. Is that feature coming up next?

**Comment by escattone** [comment]
@kelimuttu There is an indication -- a difference in the background shading of read messages vs unread messages -- but in my view it's so slight that it's difficult to notice. I think we need to create a stronger indicator of read vs unread.

**Comment by emilghittasv** [comment]
Hm, I agree! Let me file a new ticket to track that.

**Comment by kelimuttu** [comment]
I didn't notice that! I was almost certain there may be an indication that I couldn't tell, though. Because there's a button to mark all selected messages as read.

But yes, a more prominent differentiator would be much more appreciated!

**Comment by emilghittasv** [comment]
https://github.com/mozilla/sumo/issues/1929
