### ISSUE TITLE
Footer UI issues in both inbox and outbox pages on mobile devices

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1788]
**Preconditions**
Sign in to SUMO and have at least 1 received and 1 sent message.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/messages/sent
2. Scroll down to the footer section.
3. Go to https://support.allizom.org/en-US/messages/
4. Scroll down to the footer section.

**Expected behavior**
No UI issues displayed.

**Actual behavior**
The footer section looks broken

**Screencasts**
https://github.com/mozilla/sumo/assets/28087895/a1b72051-f380-472b-9b2a-eb0a872879b1

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6008

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
