### ISSUE TITLE
Unable to send out messages to groups

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1789]
**Preconditions**
Sign in with a user belonging to the staff group

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/messages/new
2. Add a group inside the "To" field.
3. Fill out the message body and click on the "Send" button.

**Expected behavior**
The message is successfully sent out to the group.

**Actual behavior**
The message cannot be sent and an error message stating that the entered recipient is not a valid username (example: `TestGroup2 is not a valid username.`) is displayed.

**Screencasts**
![NoMessageToGroup](https://github.com/mozilla/sumo/assets/28087895/60a97b57-1f76-432c-9778-1e1b47cb6371)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by emilghittasv** [comment]
@akatsoulas 

Same occurs when trying to send the message out via the "Private message group members" from the groups page. 

The group is automatically populated inside the to field but same error occurs when trying to send the message out.

![notAValidUsernam](https://github.com/mozilla/sumo/assets/28087895/3f25ca6c-abcc-4613-a3a0-fbb401343ecf)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6006

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Also, I can confirm that the `Private message group members` button was removed from the groups profile for both `staff` and `non-staff` users.

Moving this ticket inside the `release` column.
