### ISSUE TITLE
Consider sticking the Upload a New Media File modal in the center of the users screen

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1791]
**Describe the bug**
This issue is reproducible in all environments (`dev`, `stage` and `prod`) but has a higher impact in `dev` with the new IA design in place.

**Preconditions**
Sign in to SUMO dev

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/gallery/images
2. Scroll down a bit until the "Upload a New Media File" button is displayed at the top of the users screen.
3. Click on the "Upload a New Media File" button.

**Expected behavior**
The "Upload a New Media File" modal sticks on the center of the users screen.

**Actual behavior**
The "Upload a New Media File" is displayed on top of the page. This can generate user confusion since the user might not know from the start what happened or where the modal was opened (he has to scroll up in order to find it)

**Screencasts**
**Desktop**:
![Upload a new media file](https://github.com/mozilla/sumo/assets/28087895/40ce991b-0155-4362-9b7d-448c20a5f4e8)

**Mobile**:
https://github.com/mozilla/sumo/assets/28087895/2b5e9415-ced6-4bb7-abdf-e506eb909040

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6011

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.

I'm going to remove the IA tag from this ticket since this is not strictly related to the IA project and it will get release sooner.

**Comment by emilghittasv** [comment]
@escattone The changes performed in https://github.com/mozilla/kitsune/pull/6159 are making this issue reproducible again.

I'm reopening this ticket and adding it into the current sprint.

**Comment by akatsoulas** [comment]
That's probably happening b/c the code that calculated the aspect ratio was removed.

**Comment by emilghittasv** [comment]
@escattone Unfortunately I'm still able to reproduce this issue in `stage`.

I'm moving this ticket back inside the `in progress` column.

**Comment by emilghittasv** [comment]
@escattone This is actually fixed (sorry for this!)

The media upload modal is actually brought into view regardless of the user position when the modal open action was performed.

I'm moving this ticket inside the `release` column.
