### ISSUE TITLE
Several UI issues displayed on the Media Gallery page for some non-US locales on mobile devices 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1792]
**Preconditions**
Sign in to SUMO dev

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/de/gallery/images
2. Observe the "Upload a New Media File" button.

**Expected behavior**
No UI issues are encountered.

**Actual behavior**
* The "Upload a New Media File" button text is cut off. 
* The "Search Gallery" placeholder text is cut off.
* The "Search Galley" search field is not aligned with the "Show Media for:" field

**Screenshots**
**DE locale**:
![Screenshot_20240515_151109_org mozilla firefox](https://github.com/mozilla/sumo/assets/28087895/cf65478c-5f57-43ee-82dd-20fc23a56e9b)

**en-US locale**:
![Screenshot_20240515_152156_org mozilla firefox](https://github.com/mozilla/sumo/assets/28087895/c1cd98da-eabc-44b3-9e3e-bb758a443677)

**Smartphone (please complete the following information):**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Additional context**
* The "Upload a New Media File" button issue is reproducible in `dev` only (as part of the IA changes).
* A misalignment for the "Show media for" and "Show" fields is also present in `stage` and `prod`

**Comment by emilghittasv** [comment]
Hi @escattone !

I can confirm the fix for the Upload media button on mobile devices. This ticket makes reference to two more issues:
* The "Search Gallery" placeholder text is cut off.
* The "Search Galley" search field is not aligned with the "Show Media for:" field

Would you like to keep this ticket until the above issues are also fixed or would you like them filled in separate tickets?

**Comment by escattone** [comment]
@emilghittasv Thank you! If you don't mind, I'd prefer that the remaining two issues are filed as separate tickets.

**Comment by emilghittasv** [comment]
Thanks @escattone !

I've filled https://github.com/mozilla/sumo/issues/1961 and https://github.com/mozilla/sumo/issues/1962 for the remaining cases.

I'm going to close this ticket since the fix for the media button text is already in `prod`.
