### ISSUE TITLE
Unable to sign in/sign out on SUMO dev

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1793]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/
2. Try signing in or out.

**Expected behavior**
Users can successfully sign in or out

**Actual behavior**
404 page not found is displayed.

**Screencasts**
![SignInOrOut](https://github.com/mozilla/sumo/assets/28087895/57d08c3e-607c-46fe-b165-f623085bbfd7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6013

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is not reproducible in `stage`.

Moving this ticket inside the `release` column.
