### ISSUE TITLE
Remove Hubs Sunset Banner on 5/31

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1797]
**Briefly describe the Initiative.**
Mozilla Hubs is being sunset on 5/31/2024. Presently, there has been a banner displayed on Hubs pages on SuMO announcing this sunset. We need to take this banner down on 5/31/2024. 

**Describe the milestones if any**
On 5/31/2024, the Banner announcing Hubs sunset needs to be disabled. It will not longer be needed. A new KB article will be used instead to detail the end of support.

**Add any related issues**
N/A

**What is the requested timeline for completion?**
Turn off the banner on 5/31/2024

**Who is the audience**
External

**Additional context**
N/A

**Applicable resources**
(https://app.asana.com/0/1203460865189761/1206776558121955/f)

**Comment by emilghittasv** [comment]
I can confirm that the Hubs sunset announcement banner was successfully removed in `stage` from the hubs support page, topic pages and kb articles.

Moving this ticket inside the `release` column.
