### ISSUE TITLE
Localization Team user details information is shifted to the right

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1800]
**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/kb/locales/ro ( or any other locale team page from the https://support-dev.allizom.org/en-US/kb/locales list)

**Expected behavior**
No UI issues displayed.

**Actual behavior**
The Name & Private message option for each locale member is shifted to the right.

**Screenshots**
`Dev`
![image](https://github.com/mozilla/sumo/assets/28087895/420a9339-3b90-4b56-a356-420ba15d5c9f)

`Stage`
![image](https://github.com/mozilla/sumo/assets/28087895/11f58fcb-72bb-4daa-83a2-0d71676502fa)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
@akatsoulas This issue is still reproducible in `dev`.

I'm moving this ticket back inside the `in progress` column.

**Comment by akatsoulas** [comment]
We had some changes in the css class that affects this. Once merged in staging this bug will go away. I am moving it under the QA column and we can verify once the PR targeting staging is merged

**Comment by emilghittasv** [comment]
I can confirm that this issue is not reproducible in `stage`.

Moving this ticket inside the `release` column.
