### ISSUE TITLE
Unable to edit locale team members

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1801]
**Preconditions**
Sign in to SUMO dev with an admin account.

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/kb/locales/ro
2. Click on the `Edit locale leaders`, `Edit locale reviewers` or `Edit locale editors` options.

**Expected behavior**
onClick, the `id="add-leader-form"` form is displayed and the user is able to edit the locale members.

**Actual behavior**
It seems that there is no event attached to the edit elements and onClick the `id="add-leader-form"` form is not displayed.

**Screencasts**
![EditLocaleTeam](https://github.com/mozilla/sumo/assets/28087895/abbb022f-4e26-4cbb-881f-93a9855e7618)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `dev` only as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6030

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
