### ISSUE TITLE
Redirect to step 2 of the AAQ in the question listing page of a product

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1803]
If a user navigates to the question listing page of a product, the `Ask the Community` button should redirect to step 2 of the AAQ instead of the grid. If the page displays question for multiple products, it should redirect to the product selection step (step 1).

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6027

**Comment by emilghittasv** [comment]
I can confirm that the `Ask the Community` button from the question listing page redirects the user to step 2 of the AAQ in `dev`. 

If the user clicks on the `Ask the Community` while on the question listing page for multiple products it will redirect the user to the product selection step (step 1).

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment]
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.
