### ISSUE TITLE
Unable to close large image previews

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1804]
**Describe the bug**
Also mentioned in https://support.mozilla.org/en-US/forums/contributors/716979?last=87615

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/1449378 and click on the second attached image.
2. Try closing the image (try finding the "x' button by scrolling up or hit the "escape" keyboard button).

**Expected behavior**
Users are able to close the image preview via the "x" button and  by hitting the "escape" keyword button.

**Actual behavior**
Users are unable to bring the "x" button into view or by hitting the "escape" button (The escape button is an old issue which was already filled in https://github.com/mozilla/sumo/issues/1204)

**Screencasts**
![closeImage](https://github.com/mozilla/sumo/assets/28087895/e1c2d5ac-b3a2-4155-b3cf-550e164d2fab)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Smartphone:**
 - Device: Huawei P40pro
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`

**Comment by emilghittasv** [comment]
@akatsoulas I'm wondering if this is a regression caused by https://github.com/mozilla/kitsune/pull/6011

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6033

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Image preview can be successfully closed by:
1. Clicking outside of the image preview.
2. Clicking on the "x" button.
3. Pressing the "escape" keyboard button.

Moving this ticket inside the `release` column.
