### ISSUE TITLE
Identify and resolve data duplication when exporting helpfulness survey data from the `KB Helpfulness` Looker dashboard

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1809]
Users are seeing duplication in the KB article helpfulness vote data when exported from the `KB Helpfulness` Looker dashboard. Identify the root cause and resolve.

**Comment by escattone** [comment]
I've discovered a fundamental problem -- which also might explain the duplication.
- The KB Helpfulness Looker dashboard uses the `metrics_unhelpful_surveys_with_document_ids` BQ table as a data source
- The `metrics_unhelpful_surveys_with_document_ids` BQ table -- in turn -- queries the `metrics_wiki_unhelpfulsurveys` BQ table
- The `metrics_wiki_unhelpfulsurveys` BQ table is populated by a daily scheduled query that has been failing since April 3, 2024, and which was querying the old MySQL database, which has been frozen since the end of November 2023
- I attempted to update the scheduled query for `metrics_wiki_unhelpfulsurveys` to use the new Postgres connection instead, but discovered that the Postgres connection -- which ultimately uses the `bq_ro` Postgres user -- does not have access to the `wiki_helpfulvotemetadata` table within our production Postgres instance.
```SQL
sumo_prod=> \z wiki_helpfulvote
                                  Access privileges
 Schema |       Name       | Type  | Access privileges | Column privileges | Policies
--------+------------------+-------+-------------------+-------------------+----------
 public | wiki_helpfulvote | table | sumo=arwdDxt/sumo+|                   |
        |                  |       | bq_ro=r/sumo      |                   |
(1 row)

sumo_prod=> \z wiki_helpfulvotemetadata
                                      Access privileges
 Schema |           Name           | Type  | Access privileges | Column privileges | Policies
--------+--------------------------+-------+-------------------+-------------------+----------
 public | wiki_helpfulvotemetadata | table |                   |                   |
(1 row)
```
- I've confirmed with the SRE's , that the `bq_ro` user was granted permission to select tables manually.

**Comment by escattone** [comment]
This should be resolved, but needs to be confirmed. I did the following:
- [x] Logged into our production Postgres instance and manually granted our `bq_ro` user `SELECT` access to the `wiki_helpfulvotemetadata` table.

```sql
sumo_prod=> \z wiki_helpfulvotemetadata
                                      Access privileges
 Schema |           Name           | Type  | Access privileges | Column privileges | Policies
--------+--------------------------+-------+-------------------+-------------------+----------
 public | wiki_helpfulvotemetadata | table |                   |                   |
(1 row)

sumo_prod=> grant SELECT on table wiki_helpfulvotemetadata to bq_ro;
GRANT
sumo_prod=> \z wiki_helpfulvotemetadata
                                      Access privileges
 Schema |           Name           | Type  | Access privileges | Column privileges | Policies
--------+--------------------------+-------+-------------------+-------------------+----------
 public | wiki_helpfulvotemetadata | table | sumo=arwdDxt/sumo+|                   |
        |                          |       | bq_ro=r/sumo      |                   |
(1 row)
```

- [x] Updated the `metrics_wiki_unhelpfulsurveys` scheduled query to use the new Postgres connection (see image below), and successfully re-ran the scheduled query.

<img width="1317" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/1abe1f96-1d8b-4ac6-b298-b6a8c390c0b0">

**Comment by akatsoulas** [comment]
Closing this as done. Thanks @escattone !
