### ISSUE TITLE
"Last updated" KB article metadata is displayed as empty for newly created kb articles which are not live yet

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1812]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
**For a newly created kb article**:
1. Go to https://support.allizom.org/en-US/kb/new
2. Create and submit the kb article for revision.
3. Observe the KB article metadata information.

**For newly created kb article translation**:
1. Access a random KB live kb article.
2. Click on the "Translate Article" option from the "Editing Tools" section.
3. Perform the translation and send it out for review.
4. Click on the "Article" option from the translated version.
5. Observe the KB article metadata information.

**Expected behavior**
Since the first revision is not yet approved, the `Last updated` is not displayed **OR** fallback to `Created` date (as Josh pointed out)

**Actual behavior**
The `Last updated` is displayed as empty.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/7edd9d57-7c95-4fb6-972a-13ca2a39985d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6042

I'm choosing to not display the date meta for these.

**Comment by emilghittasv** [comment]
I can confirm that the `Created` or `Last updated` Kb metadata information is not displayed in `stage` for newly created kb articles, translations or templates which don't have the first revision approved.

I'm moving this ticket inside the `release` column.
