### ISSUE TITLE
Product metadata information overlaps the topics dropdown menu items on mobile devices

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1813]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/firefox/fix-problems
2. Tap on the "More" dropdown menu.

**Expected behavior**
No UI issues are displayed.

**Actual behavior**
The KB metadata product overlaps the dropdown menu.

**Screencasts**
https://github.com/mozilla/sumo/assets/28087895/07833e41-740a-4da6-8480-3b36b1760f2c

**Smartphone:**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6034

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
