### ISSUE TITLE
The "Created" status is not displayed inside the KB article metadata info

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1815]
**Describe the bug**
As described inside the Figma doc (https://www.figma.com/design/5bdwOFssObTuqUxlJOa7We/Article-Experience-Redesign?node-id=221-2075&t=HyJZVJgUyR745P6v-0) the `Created` information should be displayed when an article is created but doesn't have any other revisions approved (apart from the first one)

**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/new
2. Create the article and submit it for review.
3. Approve the first revision.

**Expected behavior**
The KB metadata is `Created: {timestamp}`

**Actual behavior**
The KB metadata is `Last updated: {timestamp}`

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6044

**Comment by emilghittasv** [comment]
I can confirm that the `Created` status is successfully displayed inside the KB article metadata info & inside the product topics listing page for newly created articles (which have the first revision approved).

Moving this ticket inside the `release` column.
