### ISSUE TITLE
The KB article metadata timestamp is not displayed in calendar format (m/d/y)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1816]
**Describe the bug**
As described inside the Figma doc -> https://www.figma.com/design/5bdwOFssObTuqUxlJOa7We/Article-Experience-Redesign?node-id=221-2223&t=HyJZVJgUyR745P6v-0 if the timestamp is over a month, the timestamp should be displayed in a calendar format.

**Steps to reproduce**
1. Access a KB article for which the `Last Update` or `Creation` was performed >1 month from now (or access https://support.allizom.org/en-US/kb/firefox-password-authentification-prompt directly)

**Expected behavior**
The timestamp is displayed in a calendar format.

**Actual behavior**
The timestamp is displayed in relative timestamp

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/8ffa0469-f424-40b3-bfbe-95dd214a45ba)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6043

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The KB article metadata timestamp is displayed in calendar format (m/d/y) for articles created or updated > 1 month from the current date.

Moving this ticket inside the `release` column.
