### ISSUE TITLE
Wrong articles listed inside the KB dashboard

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1818]
**Steps to reproduce**
1. Go to https://support.mozilla.org/en-US/contributors
2. Click through the `Last 7 days`, `Last 30 days` and `Last 90 days` 
3. Observe the listed articles.

**Expected behavior**
* The listed articles respect the chosen filter.

**Actual behavior**
* Some of the listed articles are older than the chosen filter.

**Screencasts**
![kbdashboardfilter](https://github.com/mozilla/sumo/assets/28087895/d76c046a-d038-49f8-9ae9-052406b43ac4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
Both `stage` and `prod` are affected.

**Comment by escattone** [comment]
@emilghittasv From what I can tell, this is working as intended. The four periods shown in the tabs -- `Last 7 days`, `Last 30 days`, `Last 90 days`, and `Last Year` -- do not mean the time period within which the KB articles were last updated, but instead the time period over which to count the number of visits (page views) for each article, which in turn are used to select the top 10 most-visited articles within that time period.

**Comment by emilghittasv** [comment]
Oh, sorry for the misunderstanding. 

You are correct. The listed articles are filtered based on the number of visits within the chosen filter. 

I'm going to close this ticket.
