### ISSUE TITLE
zh-Hant fallbacks to zh-CN instead of zh-TW

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1820]
**Describe the bug**
As described in https://github.com/mozilla/kitsune/blob/63ec0cad074724d9ae4b15975524ce40ff421641/kitsune/settings.py#L205, the `zh-Hant` should fallback to the `zh-TW` locale.

**Steps to reproduce**
1. Go to https://support.allizom.org/zh-Hant/

**Expected behavior**
The user is redirected to https://support.allizom.org/zh-TW/

**Actual behavior**
The user is redirected to https://support.allizom.org/zh-CN/

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This is reproducible in both `stage` and `prod`

**Comment by escattone** [comment]
Django is returning `zh-cn` from the `translation.get_language_from_path()` call, which in turn, is because `translation.get_supported_language_variant("zh-Hant")` returns `zh-cn`, which, in turn, is because we're not using "strict" mode and `zh-cn` is always the first match for the `zh-` check.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

`zh-Hant` locale successfully fallbacks to `zh-TW`.

Moving this ticket inside the `release` column.
