### ISSUE TITLE
[Mobile] Unable to upload files to Media Gallery

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1822]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/gallery/images
2. Tap on the `Upload a New Media File` button.
3. Tap on the `Browse` button and add an image to upload.

**Expected behavior**
The full modal is displayed.

**Actual behavior**
The modal is not fully displayed and the `Upload file` and `Cancel` buttons are not visible

**Screencasts**
https://github.com/mozilla/sumo/assets/28087895/8695a385-2f75-40f2-8def-97abc6e00f2c

**Smartphone (please complete the following information):**
 - Device: Huawei P40Pro
 - Browser: Firefox

**Additional context**
* This issue is reproducible on both `stage` and `prod`.
* On Desktop the modal expands to the bottom but it's fully visible and the upload can be successfully performed or canceled.
![UploadMediaModal](https://github.com/mozilla/sumo/assets/28087895/803df134-7483-46c0-901a-d5e7ce45a989)

**Comment by AliceWyman** [comment]
This is not limited to mobile devices.  It also affects my Windows 10 laptop computer.  Screenshot: https://support.mozilla.org/en-US/gallery/image/52417

I added a comment to a related bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1724648

**Comment by AliceWyman** [comment]
I filed a new bugzilla report for this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1905372 Unable to upload files to the media gallery due to missing Upload file button

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
