### ISSUE TITLE
Incorrect "Last updated" time displayed inside the product topics listing page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1825]
**Preconditions**
Sign in to SUMO and have two browsers side by side.

**Steps to reproduce**
1. Access the https://support.allizom.org/en-US/products/firefox/basic-browsing-firefox/bookmarks page (or any other product topic listing page).
2. Click on an article which has the `Created` Kb article metadata status.
3. Submit a new revision for it & approve it.
4. Navigate back to the product listing page from step 1 using a different browser or inside the private browsing session.

**Expected behavior**
The `Last Updated` indicates the correct time.

**Actual behavior**
The `Created` transitions successfully to the `Last Updated` but the `Last Updated` displays the `Created` date for the next ~ 4 minutes until it updates successfully.

**Screencasts**
![lastUpdatedProductTopics](https://github.com/mozilla/sumo/assets/28087895/516120de-c250-440b-bcef-e5d1392c6aaa)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by emilghittasv** [comment]
After further investigating this issue I've noticed that this is the general behavior of the topics listing page. The article listing page seems to have a delay of ~ 4 minutes until the new article updates are displayed (modifying the title, search summary, relevancy or in this case creating & approving a new article revision).

The transition from the `Created` to `Last updated` state is instant though which generates this confusion.

**Comment by smithellis** [comment]
@emilghittasv This feels like caching - I'll take a look.

**Comment by akatsoulas** [comment]
This small delay is b/c of caching. Closing this
