### ISSUE TITLE
The "Templates" option is displayed inside the Contribute > Contributor tools top-navbar section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1827]
**Describe the bug**
[Figma design](https://www.figma.com/design/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?node-id=749-6479&t=m5hU1BtalgumdlLM-0)

**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Mouse-over the `Contribute` top-navbar.

**Expected behavior**
All elements displayed inside the `Contribute` top-navbar section are as pe the Figma design.

**Actual behavior**
The "Templates" option is displayed inside the `Contributor tools` section which is not as per figma design.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/83ec54aa-1134-4f1f-8618-e8fba6ed955d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6054

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
