### ISSUE TITLE
Rename {Product} Community Forums to {Product} Community Forum

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1828]
**Describe the bug**
[Figma design](https://www.figma.com/design/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?node-id=749-8739&t=m5hU1BtalgumdlLM-0)

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/firefox (or any other product community forum)

**Expected behavior**
The forum page title is {Product} Community **Forum**

**Actual behavior**
The forum page title is {Product} Community **Forums**

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/4df496ec-f065-4490-abee-eafe1b016f04)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6049

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
