### ISSUE TITLE
Rename the {Product} Support Forum to {Product} Community Forum inside the Community Forums page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1829]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/

**Expected behavior**
Since the `Support Forum` was renamed to `Community Forum`, the products listed inside the `Community Forums` page should also be named `{Product} Community Forum`.

**Actual behavior**
The products listed inside the `Community Forums` page are named `{Product} Support Forum`.

**Screenshots**
![image](https://github.com/mozilla/sumo/assets/28087895/5c350161-41cd-439f-8b48-8ee4e5c95a45)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6055

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
