### ISSUE TITLE
404 is returned when clicking on the All, Attention needed, Responded and Done filters when browsing all forum threads by topic

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1837]
**Steps to reproduce**
1. Mouse-over the `Community Forums` top-navbar and click on one of the listed options from the `Browse all forum threads by topic` section.
2. Click on the `All`, `Attention needed`, `Responded` and `Done` filters.

**Expected behavior**
The filter is successfully applied.

**Actual behavior**
The url updates to `/questions/None?show=all`, `/questions/None?show=needs-attention`, `/questions/None?show=responded` and `/questions/None?show=done` which returns a 404 page.

**Screencasts**
![CommunityForums](https://github.com/mozilla/sumo/assets/28087895/9ab83231-b12a-490e-aa37-0e366ea3db91)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` as part of the IA work.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6060

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
