### ISSUE TITLE
Change AAQ topic values to match with the newly proposesd topic slugs

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1841]
**Describe the bug**
Currently, the values for the topics listed inside the `Which topic best describes your question?` AAQ dropdown field are hardcoded. If we update the slugs & the user tries to submit an AAQ question by selecting that particular topic from the `Which topic best describes your question?` dropdown menu it will fail with `Topic.DoesNotExist`

**Preconditions**
Sign in to admin and change the slug for a topic (example: Change the `install-and-update-firefox-ios` slug to `install-and-update`

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/new/ios/form and submit a question by choosing the `Install and Update` option from the `Which topic best describes your question?` dropdown menu.

**Expected behavior**
The question can be successfully submitted and the submission is performed agains the new slug `install-and-update`

**Actual behavior**
Since the values are hardcoded inside the dropdown menu, the question submission will fail with [Topic.DoesNotExist](https://mozilla.sentry.io/issues/5481711613/?alert_rule_id=13095090&alert_timestamp=1718193050852&alert_type=email&environment=us-west1&notification_uuid=a2e5c8eb-ff53-43e9-a800-f1dab7cf117b&project=4504326797197312&referrer=alert_email) error because the value is pointing out to the old slug (`install-and-update-firefox-ios`)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only as part of the IA work.

**Comment by akatsoulas** [comment]
This is blocked until we have the final list of slugs that we are going to rename

**Comment by akatsoulas** [comment]
Depends on https://github.com/mozilla/sumo/issues/1850

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6077

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
