### ISSUE TITLE
Unable to filter through different subtopics

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1842]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/firefox/protect-your-privacy or any other topic listing page.
2. Click on the `Cookies and cache` subtopic filter (or any other subtopic)
3. All the listed articles are belonging to the `Cookies and cache` subtopic.

**Expected behavior**
The `Cookies and cache` is highlighted and the listed products belong to the `Cookies and cache` subtopic.

**Actual behavior**
The `Cookies and cache` is not highlighted and some of the listed products don't belong to the `Cookies and cache` subtopic. (basically all topics belonging to the parent topic are listed).

**Screencasts**
![UnableToFilter](https://github.com/mozilla/sumo/assets/28087895/d318c623-a913-4981-a9ad-6802344cf0c6)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
Somehow in the [redirects pr](https://github.com/mozilla/kitsune/commit/ddb315fa2ec30a7f9ab7964ebcd6d90394c52ba4) the URL names got changed. [Reverting back](https://github.com/mozilla/kitsune/pull/6063) fixes this issue.

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
