### ISSUE TITLE
Help Solve it! link can redirect the user to an empty list on the Browse all forum threads by topic page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1845]
**Preconditions**
Sign in to SUMO and submit an AAQ question.

**Steps to reproduce**
1. Mouse-over the `Community Forums` top-navbar option and click on one of the available options from the `Browse all forum threads by topic page` section which is a different topic from the posted question topic.
2. Click on the `Help solve it!` option from the `1 question in the last 24 hours has no reply.` section.

**Expected behavior**
The question which needs to be solved is successfully listed.

**Actual behavior**
The posted question is not listed since the filter is applied to the topic page selected in step 1 and the posted question belongs in a separate topic.

**Screencasts**
![HelpSolveIt](https://github.com/mozilla/sumo/assets/28087895/b1d8746a-799d-4547-abc0-f1a28474fa04)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6065

**Comment by akatsoulas** [comment]
The solution hides the line with the number of questions in the last 24 hours when navigating per topic. During topic navigation we cannot know which product has the unanswered question and redirect the request properly.

**Comment by emilghittasv** [comment]
I can confirm that the "Help Solve" it section is hidden when browsing forum threads by topic. 

The "Help Solve" section is working as expected when browsing the forum threads by product.

Moving this ticket inside the `release` column.
