### ISSUE TITLE
Inconsistencies inside the product topic listing pages for the Ask a Question card 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1846]
**Steps to reproduce**
Steps to reproduce the behavior for **freemium products**:
1. Ensure that you are not signed in to SUMO
2. Navigate to the https://support.allizom.org/en-US/products/firefox/troubleshooting page and note the "Ask a Question" text.
3. Click on the "Continue" button and notice the redirect.
4. Navigate to the https://support.allizom.org/en-US/topics/troubleshooting/firefox page and note the "Ask a Question" text.
5. Click on the "Continue" button and notice the redirect.
6. Redo the above steps while signed in.

Steps to reproduce the behavior for **premium products**:
1. Ensure that you are not signed in to SUMO
2. Navigate to the https://support.allizom.org/en-US/products/mdn-plus/getting-started page and note the "Ask a Question" text.
3. Click on the "Continue" button and notice the redirect.
4. Navigate to the https://support.allizom.org/en-US/topics/troubleshooting/relay page and note the "Ask a question" text.
5. Click on the "Continue" button and notice the redirect.
6. Redo the above steps while signed in.

**Expected behavior**
The AAQ "Continue" button redirect and the AAQ text should be consistent.

**Actual behavior**
For **signed out on freemium products topic pages**:
* The Ask a Question card text on https://support.allizom.org/en-US/products/firefox/troubleshooting is: `Still need help? Sign in to ask your question on our forums` while on the https://support.allizom.org/en-US/topics/troubleshooting/firefox page, the Ask a Question card text is `Still need help? Continue to ask your question and get help.`
* The `Continue` button on https://support.allizom.org/en-US/products/firefox/troubleshooting redirects the user to the [`Get community support`](https://support.allizom.org/en-US/kb/get-community-support?exit_aaq=1) kb article while the `Continue` button on https://support.allizom.org/en-US/topics/troubleshooting/firefox redirects the user to the https://support.allizom.org/en-US/questions/new page.

For **signed in on freemium products topic pages**
* The Ask a Question card text on https://support.allizom.org/en-US/products/firefox/troubleshooting is: `Still need help? Sign in to ask your question on our forums` while on the https://support.allizom.org/en-US/topics/troubleshooting/firefox page, the Ask a Question card text is `Still need help? Continue to ask your question and get help.`
* The `Continue` button on https://support.allizom.org/en-US/products/firefox/troubleshooting redirects the user to the [`Get community support`](https://support.allizom.org/en-US/kb/get-community-support?exit_aaq=1) kb article while the `Continue` button on https://support.allizom.org/en-US/topics/troubleshooting/firefox redirects the user to the https://support.allizom.org/en-US/questions/new page.

For **signed out on premium products topic pages**:
* The Ask a Question card text on https://support.allizom.org/en-US/products/mdn-plus/getting-started is `Still need help? Sign in to contact our support team.` while the Ask a Question card text on https://support.allizom.org/en-US/topics/troubleshooting/relay is `Still need help? Continue to ask your question and get help.`
* The `Continue` button on https://support.allizom.org/en-US/products/mdn-plus/getting-started redirects the user to the `Continue with a Mozilla account` page while the `Continue` button on https://support.allizom.org/en-US/topics/troubleshooting/relay redirects the user to the https://support.allizom.org/en-US/questions/new page

For **signed in on premium products topic pages**:
* The Ask a Question card text on https://support.allizom.org/en-US/products/mdn-plus/getting-started is `Still need help? Continue to contact our support team.` while the Ask a Question card text on https://support.allizom.org/en-US/topics/troubleshooting/relay is `Still need help? Continue to ask your question and get help.`
* The `Continue` button on https://support.allizom.org/en-US/products/mdn-plus/getting-started redirects the user to the `Premium product contact support form page` page while the `Continue` button on https://support.allizom.org/en-US/topics/troubleshooting/relay redirects the user to the https://support.allizom.org/en-US/questions/new page

**Screencasts**
**Signed out freemium & premium** products:
![freemiumAAQtopics](https://github.com/mozilla/sumo/assets/28087895/024d67f3-78c8-44e1-ba79-bb82acc7e6a9)

**Signed in freemium & premium** products:
![premiumAAQtopics](https://github.com/mozilla/sumo/assets/28087895/c4399282-8b46-488d-8bf3-992c667d5287)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by emilghittasv** [comment]
As mentioned in slack, we could show the correct text or redirect the user via the `Continue` button to the correct AAQ form based on the product filter chosen for the browse by topic page. (example `/topics/troubleshooting/ios` or `/topics/troubleshooting/relay` could redirect the user to the correct AAQ form page).

For the `/topics/troubleshooting` which displays all products it makes more sense to display a more general text and have the `Continue` button redirect to the `/questions/new` page so that users can choose a product for which they require help

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6076

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

The same `Ask a Question` widget message is displayed on both explore by product and explore by topic page (if a product is chosen from the dropdown menu) & the `Continue` button redirects to the same destination:

**Freemium products signed out:**
`Still need help? Sign in to ask your question on our forums.` & the continue button redirects to the auth page. After completing the sign in flow in the newly displayed page, the user is redirected to that particular product form page.

**Premium products signed out:**
`Still need help? Sign in to contact our support team.` & the continue button redirects to the auth page. After completing the sign in flow in the newly displayed page, the user is redirected to that particular product form page.

**Freemium products signed in:**
`Still need help? Continue to ask your question on our forums.` & the continue button redirects to that particular product contact form.

**Premium products signed in:**
`Still need help? Continue to contact our support team.` & the continue button redirects to that particular product contact form.

If the user is on the browse by topic listing page and has no product selected inside the `Filter by product` dropdown menu the `Still need help? Continue to ask your question and get help.` is displayed & the continue button redirects to `/questions/new` for both signed in and signed out states.

Moving this ticket inside the `release` column.
