### ISSUE TITLE
Normalize Topic slugs 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1850]
We need to update the slug of specific topics to facilitate the new navigation, normalize the URLs, stop spilling product information into topic URLs and ease the migration to the new taxonomy. Redirects will take place for each rename to avoid 404s.The final list of topics that we should keep is:

## Staging
- Update to **Install and Update** with slug **install-and-update**:
  - [x] *Firefox*:
    - [x] `Install and Update` and `install-and-update-firefox`
    - [x]  `Download, install and migration` and `download-and-install`
  - [x] *Firefox for iOS*
    - [x]  `Install and Update` and `install-and-update-firefox-ios`
  - [x] *Firefox for Android*
    - [x] `Download, install and migration` and `download-and-install`
  - [x] *Mozilla VPN*
    - [x]  `Download & Setup` and `download-setup`
  - [x] *Firefox for Enterprise*
    - [x] `Deploy` and `deploy-firefox-for-enterprise`
    - [x] `Installation` and `installation-enterprise` 
    - [x] `Mac` and `deploy-firefox-enterprise-mac`
    - [x] `Linux` and `deploy-firefox-enterprise-linux`
    - [x] `Windows` and `deploy-firefox-enterprise-windows`
  - [x] *Thunderbird*
    - [x]  `Install, Migrate and Update` and `install-migrate-and-update`
    - [x] `Download, Install and migration` and `download-install-and-migrataion`
  - [x] *Firefox Lockwise*
    - [x] `Install and setup` and `install-lockwise`

- Update to **Troubleshooting** with slug **troubleshooting**:
  - [x] *Firefox*
    - [x] `Troubleshooting` and `troubleshooting`
    - [x] `Fix problems` and `fix-problems-firefox`
  - [x] *Firefox for Android*
    - [x] `Fix problems` and `fix-problems`
  - [x] *Firefox for iOS*
    - [x] `Troubleshooting` and `troubleshooting`
    - [x] `Crashes, errors and other issues` and `crashes-errors-and-other-issues`
      - [x] `Firefox for iOS is not working as expected` and `firefox-ios-not-working-expected`
  - [x] *Mozilla VPN*
    - [x] `Troubleshooting` and `troubleshooting`
  - [x] *Firefox Relay*
    - [x] `Troubleshooting` and `troubleshooting`
  - [x] *Thunderbird*
    - [x] `Fix slowness, crashing, error messages and other problems` and `fix-slowness-crashing-error-messages-and-other-problems`
  - [x] *Mozilla Account*
    - [x] `Troubleshoot` and `troubleshoot`
    - [x] `Troubleshoot issues` and `troubleshoot-issues` -- This is a subtopic of `Passwords & recovery`.
  - [x] *Firefox Lockwise*
    - [x] `Fix problems` and `fix-problems-lockwise`
  - [x] *Firefox Reality*
    - [x] `Troubleshooting` and `troubleshooting-reality`

- Update to **Protect your privacy** with slug **protect-your-privacy**:
  - [x] *Firefox*
    - [x] `Protect your privacy` and `protect-your-privacy`
    - [x] `Stay private and secure` and `stay-private-and-secure` -- This is a subtopic of `Firefox for families`
    - [x] `Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?] **Decision: It belongs here.** ✅
  - [x] *Firefox for Android*
    - [x] `Protect your privacy` and `protect-your-privacy`
    - [x] `Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?] **Decision: It belongs here.** ✅
  - [x] *Firefox for iOS*
    - [x] `Protect your privacy` and `protect-your-privacy`
  - [x] *Thunderbird*
    - [x] `Privacy and security settings` and `privacy-and-security-settings`
    - [x] `Passwords, forms and search` and `passwords-forms-and-search` -- This is a subtopic of `Privacy and security settings`
  - [x] *Mozilla Account*
    - [x] `Protect your privacy` and `protect-your-privacy`
    - [x] `Security & privacy` and `security-privacy`
    
- Update to **Emails** with slug **emails**: 
  -  [x] *Thunderbird*
     - [x]  `Emails`  and `emails-thunderbird`
     - [x] `Set up email` and `set-up-email-thunderbird`
  
- Update to **Customize settings and preferences** with slug **customize-settings-and-preferences**:
  - [x] *Firefox*
    - [x] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
    - [x] `Firefox settings` and `firefox-settings`
    - [x] `Personalize Firefox` and `personalize-firefox`
    - [x] `Personalize Firefox` and `personalize-firefox-settings`
    - [x] `Customize controls, options and add-ons` and `customize`
      - [x] `Firefox controls and buttons` and `controls`
      - [x] `Tab settings` and `tab-settings`
      - [x] `Firefox options, preferences and settings` and `firefox-options-preferences-and-settings`
      - [x] `Bookmark options` and `bookmark-options`
    - [x] `Personalize your experience` and `personalize-your-experience` -- This is a subtopic under `Firefox for families`. Does it belong here? [Josh?] **Decision: It belongs here.** ✅
  - [x] *Firefox for Android*
    - [x] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
    - [x] `Changing your settings` and `firefox-android-settings`
    - [x] `Firefox Sync settings` and `sync` -- This is a subtopic of `Sync and save`
    - [x] `Customize controls, options and add-ons` and `customize`
      - [ ] `Firefox controls and buttons` and `controls`
  - [x] *Firefox for iOS*
    - [x] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
  - [x] *Firefox for Enterprise*
    - [x] `Customization of Firefox in an enterprise environment` and `customization-firefox-enterprise-environment`
    - [x] `Manage updates, policies & customization` and `policies-customization-enterprise`
      - [x] `Manage certificates` and `manage-certificates-firefox-enterprise`
      - [x] `Policies overview` and `policies-overview-enterprise`
      - [x] `Manage settings via policy` and `manage-settings-policy`
    - [x] `Autoconfiguration` and `autoconfiguration-enterprise` [Josh?] **Decision: It belongs here.** ✅
  - [x] *Hubs*
    - [x] `Permissions & settings` and `hubs-permissions-settings` -- This is a subtopic of `Moderators and hosts`
  - [x] *Thunderbird*
    - [x] `Customize controls, options and add-ons`
      - [x] `Thunderbird controls and buttons` and `thunderbird-controls-and-buttons`
      - [x] `Tab settings` and `tab-settings`
      - [x] `Thunderbird options, preferences and settings ` and `thunderbird-options-preferences-and-settings`
    - [ ] ~~`Passwords, forms and search` and `passwords-forms-and-search` -- This is a subtopic of `Privacy and security settings` [Josh?]~~ **Decision: Move to `Protect your privacy`** ✅
  - [x] *Mozilla Account*
    - [x] `Update account settings` and `update-account-settings` -- This is a subtopic of `Security & privacy` [Josh?] **Decision: It belongs here.** ✅

- Update to **Install and manage add-ons** with slug **install-and-manage-add-ons**:
  - [x] *Firefox*
    - [x] `Install and manage add-ons` and `install-and-manage-add-ons-firefox`
    - [x] `Use extensions and add-ons` and `use-extensions-and-add-ons` -- This is a subtopic of `Firefox for families`
    - [x] `Manage add-ons` and `install-and-manage-add-ons` -- This is a subtopic of `Customize settings and preferences`
    - [x] `Customize Firefox with add-ons, plugins, and extensions` and `add-ons` -- This is a subtopic of `Customize controls, options and add-ons`
  - [x] *Firefox for Android*
    - [x] `Customize Firefox with add-ons, plugins, and extensions` and `add-ons` -- This is a subtopic of `Customize controls, options and add-ons`. Perhaps this should be moved to `Customize settings and preference` instead? [Josh?] **Decision: It belongs here.** ✅
  - [x] *Firefox for Enterprise*
    - [x] `Manage add-ons` and `manage-add-ons-enterprise`
  - [x] *Thunderbird*
    - [x] `Customize Thunderbird with add-ons, plugins, and extensions` and `customize-thunderbird-add-ons-plugins-and-extensions` -- This is a subtopic of `Customize controls, options and add-ons`

## Production
- Update to **Install and Update** with slug **install-and-update**:
  - [ ] *Firefox*:
    - [ ] `Install and Update` and `install-and-update-firefox`
    - [ ]  `Download, install and migration` and `download-and-install`
  - [ ] *Firefox for iOS*
    - [ ]  `Install and Update` and `install-and-update-firefox-ios`
  - [ ] *Firefox for Android*
    - [ ] `Download, install and migration` and `download-and-install`
  - [ ] *Mozilla VPN*
    - [ ]  `Download & Setup` and `download-setup`
  - [ ] *Firefox for Enterprise*
    - [ ] `Deploy` and `deploy-firefox-for-enterprise`
    - [ ] `Installation` and `installation-enterprise` 
    - [ ] `Mac` and `deploy-firefox-enterprise-mac`
    - [ ] `Linux` and `deploy-firefox-enterprise-linux`
    - [ ] `Windows` and `deploy-firefox-enterprise-windows`
  - [ ] *Thunderbird*
    - [ ]  `Install, Migrate and Update` and `install-migrate-and-update`
    - [ ] `Download, Install and migration` and `download-install-and-migrataion`
  - [ ] *Firefox Lockwise*
    - [ ] `Install and setup` and `install-lockwise`

- Update to **Troubleshooting** with slug **troubleshooting**:
  - [ ] *Firefox*
    - [ ] `Troubleshooting` and `troubleshooting`
    - [ ] `Fix problems` and `fix-problems-firefox`
  - [ ] *Firefox for Android*
    - [ ] `Fix problems` and `fix-problems`
  - [ ] *Firefox for iOS*
    - [ ] `Troubleshooting` and `troubleshooting`
    - [ ] `Crashes, errors and other issues` and `crashes-errors-and-other-issues`
      - [ ] `Firefox for iOS is not working as expected` and `firefox-ios-not-working-expected`
  - [ ] *Mozilla VPN*
    - [ ] `Troubleshooting` and `troubleshooting`
  - [ ] *Firefox Relay*
    - [ ] `Troubleshooting` and `troubleshooting`
  - [ ] *Thunderbird*
    - [ ] `Fix slowness, crashing, error messages and other problems` and `fix-slowness-crashing-error-messages-and-other-problems`
  - [ ] *Mozilla Account*
    - [ ] `Troubleshoot` and `troubleshoot`
    - [ ] `Troubleshoot issues` and `troubleshoot-issues` -- This is a subtopic of `Passwords & recovery`.
  - [ ] *Firefox Lockwise*
    - [ ] `Fix problems` and `fix-problems-lockwise`
  - [ ] *Firefox Reality*
    - [ ] `Troubleshooting` and `troubleshooting-reality`

- Update to **Protect your privacy** with slug **protect-your-privacy**:
  - [ ] *Firefox*
    - [ ] `Protect your privacy` and `protect-your-privacy`
    - [ ] `Stay private and secure` and `stay-private-and-secure` -- This is a subtopic of `Firefox for families`
    - [ ] `Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?] **Decision: It belongs here.** ✅
  - [ ] *Firefox for Android*
    - [ ] `Protect your privacy` and `protect-your-privacy`
    - [ ] `Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?] **Decision: It belongs here.** ✅
  - [ ] *Firefox for iOS*
    - [ ] `Protect your privacy` and `protect-your-privacy`
  - [ ] *Thunderbird*
    - [ ] `Privacy and security settings` and `privacy-and-security-settings`
    - [ ] `Passwords, forms and search` and `passwords-forms-and-search` -- This is a subtopic of `Privacy and security settings`
  - [ ] *Mozilla Account*
    - [ ] `Protect your privacy` and `protect-your-privacy`
    - [ ] `Security & privacy` and `security-privacy`
    
- Update to **Emails** with slug **emails**: 
  -  [ ] *Thunderbird*
     - [ ]  `Emails`  and `emails-thunderbird`
     - [ ] `Set up email` and `set-up-email-thunderbird`
  
- Update to **Customize settings and preferences** with slug **customize-settings-and-preferences**:
  - [ ] *Firefox*
    - [ ] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
    - [ ] `Firefox settings` and `firefox-settings`
    - [ ] `Personalize Firefox` and `personalize-firefox`
    - [ ] `Personalize Firefox` and `personalize-firefox-settings`
    - [ ] `Customize controls, options and add-ons` and `customize`
      - [ ] `Firefox controls and buttons` and `controls`
      - [ ] `Tab settings` and `tab-settings`
      - [ ] `Firefox options, preferences and settings` and `firefox-options-preferences-and-settings`
      - [ ] `Bookmark options` and `bookmark-options`
    - [ ] `Personalize your experience` and `personalize-your-experience` -- This is a subtopic under `Firefox for families`. Does it belong here? [Josh?] **Decision: It belongs here.** ✅
  - [ ] *Firefox for Android*
    - [ ] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
    - [ ] `Changing your settings` and `firefox-android-settings`
    - [ ] `Firefox Sync settings` and `sync` -- This is a subtopic of `Sync and save`
    - [ ] `Customize controls, options and add-ons` and `customize`
      - [ ] `Firefox controls and buttons` and `controls`
  - [ ] *Firefox for iOS*
    - [ ] `Customize settings and preferences` and `manage-preferences-and-add-ons-firefox`
  - [ ] *Firefox for Enterprise*
    - [ ] `Customization of Firefox in an enterprise environment` and `customization-firefox-enterprise-environment`
    - [ ] `Manage updates, policies & customization` and `policies-customization-enterprise`
      - [ ] `Manage certificates` and `manage-certificates-firefox-enterprise`
      - [ ] `Policies overview` and `policies-overview-enterprise`
      - [ ] `Manage settings via policy` and `manage-settings-policy`
    - [ ] `Autoconfiguration` and `autoconfiguration-enterprise` [Josh?] **Decision: It belongs here.** ✅
  - [ ] *Hubs*
    - [ ] `Permissions & settings` and `hubs-permissions-settings` -- This is a subtopic of `Moderators and hosts`
  - [ ] *Thunderbird*
    - [ ] `Customize controls, options and add-ons`
      - [ ] `Thunderbird controls and buttons` and `thunderbird-controls-and-buttons`
      - [ ] `Tab settings` and `tab-settings`
      - [ ] `Thunderbird options, preferences and settings ` and `thunderbird-options-preferences-and-settings`
    - [ ] ~~`Passwords, forms and search` and `passwords-forms-and-search` -- This is a subtopic of `Privacy and security settings` [Josh?]~~ **Decision: Move to `Protect your privacy`** ✅
  - [ ] *Mozilla Account*
    - [ ] `Update account settings` and `update-account-settings` -- This is a subtopic of `Security & privacy` [Josh?] **Decision: It belongs here.** ✅

- Update to **Install and manage add-ons** with slug **install-and-manage-add-ons**:
  - [ ] *Firefox*
    - [ ] `Install and manage add-ons` and `install-and-manage-add-ons-firefox`
    - [ ] `Use extensions and add-ons` and `use-extensions-and-add-ons` -- This is a subtopic of `Firefox for families`
    - [ ] `Manage add-ons` and `install-and-manage-add-ons` -- This is a subtopic of `Customize settings and preferences`
    - [ ] `Customize Firefox with add-ons, plugins, and extensions` and `add-ons` -- This is a subtopic of `Customize controls, options and add-ons`
  - [ ] *Firefox for Android*
    - [ ] `Customize Firefox with add-ons, plugins, and extensions` and `add-ons` -- This is a subtopic of `Customize controls, options and add-ons`. Perhaps this should be moved to `Customize settings and preference` instead? [Josh?] **Decision: It belongs here.** ✅
  - [ ] *Firefox for Enterprise*
    - [ ] `Manage add-ons` and `manage-add-ons-enterprise`
  - [ ] *Thunderbird*
    - [ ] `Customize Thunderbird with add-ons, plugins, and extensions` and `customize-thunderbird-add-ons-plugins-and-extensions` -- This is a subtopic of `Customize controls, options and add-ons`

**Comment by cajinajr** [comment]
_Firefox_
`Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?] 

**Yes, I think `protect-your-privacy` is the best place for it**

_Firefox for Android_
`Privacy and security settings` and `privacy-and-security` -- Does this belong here or under `Customize settings and preferences`? [Josh?]

**Yes, I think `protect-your-privacy` is the best place for it**

_Firefox_
`Personalize your experience` and `personalize-your-experience` -- This is a subtopic under `Firefox for families`. Does it belong here? [Josh?]

**Yes, I think `customize-settings-and-preferences` is the best place for it**

_Firefox for Enterprise_
`Autoconfiguration `and `autoconfiguration-enterprise` [Josh?]

**I checked out the topic in Kitsune Admin and the documents I found for it were both stubs. Not entirely sure what "Autoconfiguration" is with regard to Fx Enterprise, but I suppose `customize-settings-and-preferences` is a good enough home for it.**

_Thunderbird_
`Passwords, forms and search` and `passwords-forms-and-search` -- This is a subtopic of `Privacy and security settings` [Josh?]

**I think a better home for this would be `protect-your-privacy` since a lot of the articles in that subtopic have to do with passwords.**

_Mozilla Accounts_
`Update account settings` and `update-account-settings` -- This is a subtopic of `Security & privacy` [Josh?]

**Yes, I think `customize-settings-and-preferences` is the best place for it**

_Firefox for Android_
`Customize Firefox with add-ons, plugins, and extensions` and `add-ons` -- This is a subtopic of `Customize controls, options and add-ons`. Perhaps this should be moved to `Customize settings and preferences` instead? [Josh?]

**Since the focus of this subtopic seems to be add-ons and extensions, I think housing it under `install-and-manage-add-ons` makes sense.**

**Comment by akatsoulas** [comment]
This list feels complete and we have a data migration to apply the normalization to Documents and Questions. I am moving this under the QA column until we hear back from the content team. If this is approved we can move it to the release column.

**Comment by akatsoulas** [comment]
All topics have been applied to prod too.

**Comment by AliceWyman** [comment]
Reopen?  See [Bug 1907029 - Link returned in Google search 404s](https://bugzilla.mozilla.org/show_bug.cgi?id=1907029)  reporting a failed redirect for the "manage-add-ons-enterprise" subtopic. 

A google search for "firefox enterprise policies add-ons" comes up with page titled _Manage add-ons for Firefox for Enterprise_ with the URL, https://support.mozilla.org/en-US/products/firefox-enterprise/policies-customization-enterprise/manage-add-ons-enterprise ... which redirects to https://support.mozilla.org/en-US/products/firefox-enterprise/customize-settings-and-preferences/manage-add-ons-enterprise (a 404 Page Not Found)

Note that https://support.mozilla.org/en-US/products/firefox-enterprise/manage-add-ons-enterprise redirects to 
https://support.mozilla.org/en-US/topics/install-and-manage-add-ons/firefox-enterprise

**Comment by AliceWyman** [comment]
New issue opened: https://github.com/mozilla/sumo/issues/1873 Subtopics with redirects are returning 404
