### ISSUE TITLE
The "All topics" list is empty inside the /topics/install-and-manage-add-ons and /topics/emails pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1854]
**Steps to reproduce**
1. Mouse over the `Explore Help Articles` top-navbar option and click on the `Install and manage add-ons` & `Emails` options from the `Explore by topic section`.

**Expected behavior**
The `All Topics` section is populated.

**Actual behavior**
The `All Topics` section is empty.

**Screencasts**
![emptyAllTopics](https://github.com/mozilla/sumo/assets/28087895/c9ec4fd8-3dbd-4e34-91c4-5dba0481d46f)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6084

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
