### ISSUE TITLE
500 Error (NoReverseMatch) when trying to access /questions/mobile, /questions/firefox-enterprise and /questions/thunderbird pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1855]
**Steps to reproduce**
1. Access the following links: https://support.allizom.org/en-US/questions/mobile, https://support.allizom.org/en-US/questions/firefox-enterprise and https://support.allizom.org/en-US/questions/thunderbird 

**Expected behavior**
The Community Forums for those products is successfully displayed.

**Actual behavior**
500 Error. Sentry fires -> https://mozilla.sentry.io/issues/5539096328/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox.

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6084

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
