### ISSUE TITLE
500 error (Topic.DoesNotExist) when trying to submit an iOS AAQ question by choosing the Private Browsing mode from the topics dropdown

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1858]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/new/ios/form
2. Select the `Private Browsing mode` from the topics dropdown.
3. Submit the question.

**Expected behavior**
The question is successfully submitted.

**Actual behavior**
500 error message displayed and sentry fires https://mozilla.sentry.io/issues/5481711613/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Screencasts**
![500iOSAAQ](https://github.com/mozilla/sumo/assets/28087895/4a607a71-3eb6-4cd2-9d9d-5afdde431e71)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6091

**Comment by akatsoulas** [comment]
Nice catch!

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
