### ISSUE TITLE
Duplicate items displayed in the "Topic" dropdown menu inside the "Browse all forum threads by topic" page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1859]
**Steps to reproduce**
1. Mouse-over the `Community Forums` top-navbar.
2. Click on one option from the `Browse all forum threads by topic` section.
3. Click on the `Topic` dropdown.

**Expected behavior**
No duplicated items displayed.

**Actual behavior**
Several duplicates displayed.

**Screencasts**
![topicsduplication](https://github.com/mozilla/sumo/assets/28087895/7289ded8-b3e4-41cf-8660-2b6a6f199875)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 
**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6095

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
