### ISSUE TITLE
Cannot filter by "All Topics" inside the "Browse all forum threads by topic" page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1862]
**Steps to reproduce**
1. Mouse-over the `Community Forums` top-navbar option.
2. Click on one of the listed options from the `Browse all forum threads by topic` section.
3. Select the `All Topics` option from the `Topic` dropdown menu.

**Expected behavior**
The listed questions are filtered against all topics.

**Actual behavior**
The listed questions are filtered agains the option selected in step 2 (notice that the URL does not change when the `All Topics` option is selected).

**Screencasts**
![AllTopics](https://github.com/mozilla/sumo/assets/28087895/334034e1-0f50-4cff-a521-72a2320e4b7c)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6099

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
