### ISSUE TITLE
Marking a product or topic as archived will remove the item from the admin/product/product or admin/product/topic tables

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1863]
**Steps to reproduce**
1. Sign in to admin.
2. Mark a product or topic as archived.

**Expected behavior**
The product or topic is displayed inside the table and has the `is_archived` checkbox checked.

**Actual behavior**
The product or topic which was archived in step 2 is no longer displayed inside the table.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6098

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6100

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
