### ISSUE TITLE
Unable to swtich form "Install and update" topic filter to "All Topics"

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1864]
**Steps to reproduce**
1. Mouse-over the `Community Forums` top-navbar section.
2. Click on any of the displayed options under the `Browse all forum threads by topic` section.
3. Click on the `Install and update` option from the `Topic` dropdown section.
4. Click on the `All Topics` option from the `Topic` dropdown section.

**Expected behavior**
Step 3: The `Install and update` option is selected as the filtered topic inside the `Topic` section.
Step 4: The page filters the displayed questions based on `All Topics`

**Actual behavior**
Step 3: The `All Topics` option is displayed inside the `Topic` dropdown.
Step 4: The page is filtered based on `Install and update`

**Screencasts**
![Fitertoall](https://github.com/mozilla/sumo/assets/28087895/faebfda6-d304-42af-a693-cb301d64159e)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
This is not reproducible in my local env but I suspect that the culprit here is the topic comparison and the fact that we have different topics with the same slug. Since we are only interested in the slug in the topic navigation, I am ignoring the product FK.

PR https://github.com/mozilla/kitsune/pull/6101

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
