### ISSUE TITLE
Topic.DoesNotExist when submitting an AAQ question for the Firefox Enterprise product with topic Manage updates, policies & customization and Manage certificates

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1866]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/new/firefox-enterprise/form
2. Submit a question by choosing the `Manage updates, policies & customization` topic or `Manage Certificates` topic.

**Expected behavior**
The question is successfully posted.

**Actual behavior**
Unable to submit the question and sentry fires https://mozilla.sentry.io/issues/5583927885/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6107

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
