### ISSUE TITLE
Mozilla Account is not displayed inside the "Filter by product" dropdown

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1869]
**Steps to reproduce**
1. Go to https://support.mozilla.org/en-US/topics/troubleshooting
2. Click on the "Filter by product" dropdown.

**Expected behavior**
The `Mozilla Account` options is displayed.

**Actual behavior**
The `Mozilla Account` option is not displayed.

**Screenshot**
![image](https://github.com/mozilla/sumo/assets/28087895/56be349a-188f-4c6d-9742-08589321e37e)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `prod` only. `stage` is not affected.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6110

**Comment by emilghittasv** [comment]
I can confirm that non-visibile products are now successfully displayed inside the product filters.

Moving this ticket inside the `release` column.
