### ISSUE TITLE
Hide "Customize this article" when empty

### ISSUE THREAD

**Issue by janbrasna** [mozilla/sumo#1870]
KB articles that are not tied to a specific browser/OS/version still have the "Customize this article" shown in sidebar, with nothing there, and no indication what would be there otherwise — making the user feel like he's not seeing all the functionality. Could the heading be hidden too, when there is no form to show?

> ![Screen Shot 2024-07-01 at 19 27 20](https://github.com/mozilla/kitsune/assets/1784648/e0ca0a35-114a-432c-aa97-e82d6a1c1f92)

**Comment by janbrasna** [comment]
This gets even more prominent on smaller viewports, where it turns into expandable element, that has nothing more inside:

https://github.com/mozilla/kitsune/assets/1784648/bd776d38-451c-4cc8-9f72-282572df6de1

**Comment by akatsoulas** [comment]
Thanks @janbrasna for filing this issue. PR https://github.com/mozilla/kitsune/pull/6112 should address it

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
