### ISSUE TITLE
Firefox Private Network is visibile inside the AAQ /questions/new product listing page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1871]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/new
2. Click on Firefox Private Network product.

**Expected behavior**
1. The Firefox Private Network product is not displayed.

**Actual behavior**
1. The Firefox Private Network product is displayed.
2. The user is redirected to a 404 page.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6113

**Comment by emilghittasv** [comment]
I can confirm that Firefox Private Network, Hubs and Firefox Reality are successfully dropped from AAQ.

Moving this ticket inside the `release` column.
