### ISSUE TITLE
Consider hiding the Firefox Reality Community Forum from the /en-US/question/ page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1872]
**Describe the bug**
Since we have dropped Firefox Reality from AAQ in https://github.com/mozilla/kitsune/pull/6113 we should probably hide/remove the Firefox Reality Community Forum from the `/en-US/questions/` page as well.

**Comment by escattone** [comment]
This has been fixed in both stage and production by doing the following via the admin console:
- Removed the`Firefox Reality` product from the English question locale
