### ISSUE TITLE
The AAQ CTA for Firefox Reality & Hubs redirect to a 404 page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1875]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/firefox-reality/get-started and https://support.allizom.org/en-US/products/hubs/hubs-get-started
2. Click on the `Continue` button from the `Ask a Question` CTA.

**Expected behavior**
As in `prod` the user is redirected to the https://support.allizom.org/en-US/kb/get-community-support?exit_aaq=1 page. (Similar for the behavior of the Firefox Lockwise product https://support.allizom.org/en-US/products/firefox-lockwise/install-and-update)

**Actual behavior**
The user is redirected to https://support.allizom.org/en-US/questions/new/None/form which is not valid.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by escattone** [comment]
This has been fixed in both stage and production by doing the following via the admin console:
- Removed the `Hubs` and `Firefox Reality` products from the English question locale
- Removed Zenhub support for the `Hubs` product by removing its `codename` value.
