### ISSUE TITLE
non-navigable topic slug in topics page requests returns 500 error

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1876]
Requesting an existing topic that is not one of the defined [`kitsune.sumo.NAVIGATION_TOPICS`](https://github.com/mozilla/kitsune/blob/51e5dcbf8711f1f539efe9b43f06340575ee9f77/kitsune/sumo/__init__.py#L1) returns a 500 error, for example https://support.mozilla.org/en-US/topics/get-started. It should return a 404 instead.

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
