### ISSUE TITLE
Migrate current topics to the new taxonomy

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1877]
Existing topics should be migrated to the new [taxonomy map](https://docs.google.com/spreadsheets/d/1lBueJboMLNWeQU0-IL3b3-GcrVcPPzQvQ95JIay_Shg/edit?gid=1047509256#gid=1047509256) and satisfy the following requirements (draft - non exhaustive list):

- [x] Respect the two levels of hierarchy
- [x] Apply the same Topic to multiple products
- [x] Redirect old Topics to the new Topics
- [x] Migrate KB content to the new Topics
- [x] Create new KB articles with the new Topics

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6146

**Comment by emilghittasv** [comment]
QA activities are done for this ticket.

Moving inside the `release` column.
