### ISSUE TITLE
Wagtail: Document key implementation milestones

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1882]

**Comment by smithellis** [comment]
https://docs.google.com/document/d/1M2yu5xbNHSOncHcdrvq9JmNVhWzq_dZzA1KIS2f-EHs/edit?usp=sharing

**Comment by akatsoulas** [comment]
Work is paused on integrating Wagtail into the platform for the remainder of the year. New tickets will be opened when/if work is resumed.
