### ISSUE TITLE
Create the topics for the new taxonomy

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1885]
Create the list of topics and their relations (parent-child) for the new taxonomy

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6130

**Comment by emilghittasv** [comment]
I can confirm that: 
- The new parent topics and subtopics were successfully created & are successfully displayed in admin. 
- The relationship between the subtopics and parent topic is established.
- Each parent topic and subtopic description is successfully set.

Moving this ticket inside the release column.
