### ISSUE TITLE
Update wording in navigation menu

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1886]
Rename `Firefox browser` to `Firefox desktop`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6123

**Comment by emilghittasv** [comment]
I can confirm that the:
* `Firefox Desktop` has been modified to `Firefox desktop` inside the footer section.
* `Firefox browser` has been modified to `Firefox desktop` inside the `Explore by product` top-navbar section.
* `Firefox browser` has been modified to `Firefox desktop` inside the `Browse by product` top-navbar section.
* `Firefox browser` has been modified to `Firefox desktop` inside the `Get help with` top-navbar section.

Moving this ticket inside the `release` column.
