### ISSUE TITLE
[l10n] "Learn more" in banners not localised

### ISSUE THREAD

**Issue by janbrasna** [mozilla/sumo#1887]
**Describe the bug**

"Learn More" CTA in banners is not being translated, even when all the surrounding content is.

**Preconditions**

Some yellow notification banners being active somewhere around the site.

**Steps to reproduce**
1. Find any non-EN page with a banner, e.g. "avoid scams" at https://support.mozilla.org/de/questions/new/firefox-enterprise
2. Check the CTA
4. See it's in English, even on a German page. (Try different locales, it's the same. Pontoon shows no missing strings.)

**Expected behavior**

CTA wording matching the language.

**Actual behavior**

The are no untranslated strings missing for given locales, so that would suggest it is not being exposed to l10n. This is being observed throughout multiple callouts of the same format with varying content over the past months… and across multiple languages.

**Screenshots/Screencasts**

> ![Screen Shot 2024-07-18 at 02 53 34](https://github.com/user-attachments/assets/7f26b3a1-cf5a-4799-8148-eaeddfb8a3f7)

> ![Screen Shot 2024-07-14 at 15 02 00](https://github.com/user-attachments/assets/b20bc9c7-d077-4924-9c10-50c7810ffc98)

> ![Screen Shot 2024-07-18 at 03 01 13](https://github.com/user-attachments/assets/7bd0a6c4-0c29-4ba7-b216-392b0402bef6)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: FXDE, Chromium
 - Version: nightly

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
