### ISSUE TITLE
[l10n] "All products" dropdown default value not localised

### ISSUE THREAD

**Issue by janbrasna** [mozilla/sumo#1890]
**Describe the bug**

Troubleshooting sidebar "Filter by product" dropdown has default option "All Products" not exposed to l10n even though the string is available elsewhere.

**Steps to reproduce**

1. Visit https://support.mozilla.org/de/topics/troubleshooting or any language with no missing translations.
2. See english placeholder value in the first select option.

**Expected behavior**

Translated value being shown, given it's available in Pontoon.

**Actual behavior**

English placeholder is being shown.

**Screenshots/Screencasts**

![Screen Shot 2024-07-22 at 13 18 17](https://github.com/user-attachments/assets/25ec412f-09d4-44e5-9cf2-4a3a0c6e34b7)

**Desktop (please complete the following information):**

 - macOS Catalina
 - FXDE, chromium
 - nightly

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
