### ISSUE TITLE
Expose m2m product field in the Topic page in admin interface

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1892]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6142

**Comment by emilghittasv** [comment]
I can confirm the following in `stage`:
- The m2m field is successfully displayed for topics.
- The m2n relationship was successfully added & displayed for the new taxonomy topics.
- The products/topic page successfully filters `is_archived=not_archived` by default.
- Tested that many products can be added or remove from one topic.

Moving this ticket inside the `release` column.
