### ISSUE TITLE
Update codebase to utilize the m2m product relationship.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1893]
In the new taxonomy, we changed the product-topic relationship from a FK to a M2M. The code-base needs to be updated to utilize the m2m field

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6163

**Comment by akatsoulas** [comment]
I moved this to QA but maybe we should mark this as qa-? Basically the goal was to update the code-base to utilize the `products` field under Topic instead of `product`

**Comment by emilghittasv** [comment]
I agree. Let's move this ticket inside the `release` column since the QA for this ticket is going to be covered indirectly by the work performed for others + general regression testing.
