### ISSUE TITLE
Filter by product returns products with no articles and threads belonging to that topic category

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1901]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/topics/troubleshooting
2. From the `Filter by product` section select the `Firefox Reality` option.
3. Go to https://support.allizom.org/en-US/topics/customize-settings-and-preferences
4. From the `Filter by product` section select `Hubs` option.
5. Go to https://support.allizom.org/en-US/topics/install-and-update
6. From the `Filter by product` section select `Firefox for Android Beta`

**Expected behavior**
Since the options mentioned in steps 2, 4 and 6 are not returning any kb articles based on the chosen topics, those products are not displayed inside the `Filter by product` dropdown menu.

**Actual behavior**
Those products are displayed and selecting them will display an empty list of articles and threads.

**Screenshots**
![image](https://github.com/user-attachments/assets/8650b6aa-65af-44ee-80cd-736520779777)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`.

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6164

**Comment by emilghittasv** [comment]
Hmm, I'm still able to see this issue occurring with the following filters:
* https://support.allizom.org/en-US/topics/settings/mdn-plus
* https://support.allizom.org/en-US/topics/settings/hubs
* https://support.allizom.org/en-US/topics/settings/focus-firefox
* https://support.allizom.org/en-US/topics/installation-and-updates/firefox-preview

I'm going to move this ticket back inside the `in progress` column.

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
