### ISSUE TITLE
Update wording in topic side menu.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1904]
The side menu in the topic listing, when navigating by topic, has the title of `All Topics`. This should change to `Popular Topics` since the list displayed is not exhaustive but rather the topics listed under the main navigation.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6140

**Comment by emilghittasv** [comment]
This is confirmed in `stage`. 

Moving this ticket inside the `release` column.
