### ISSUE TITLE
Update navigation menu to point to the new taxonomy

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1909]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6148

**Comment by akatsoulas** [comment]
Until https://github.com/mozilla/kitsune/pull/6146 is merged, the main menu will probably return either empty pages or 404s

**Comment by emilghittasv** [comment]
I can confirm that both `Explore by topic` and `Browse all forum threads by topic` nav menus have been updated and now points out to the new taxonomy items.

Moving this ticket inside the `release` column.
