### ISSUE TITLE
Update the browse by product side menu to respect the new taxonomy

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1911]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6150

**Comment by emilghittasv** [comment]
I can confirm this in `stage`.

The listed products inside the `Filter by product` section are displayed accordingly to the m2m relationship between the newly added topics and products.

I'm moving this ticket inside the `release` column.
