### ISSUE TITLE
Make the KB and AAQ redirects permanent

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1916]
After the successful application of the new taxonomy, we need to make the slug redirects permanent.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6336

**Comment by emilghittasv** [comment]
I can confirm that:
* Navigating to the product topics listing page for old topic slugs (listed in `/admin/products/topicslughistory/`) are redirecting to the new slug permanently (301 instead of 302)

Moving this ticket inside the `release` column.
