### ISSUE TITLE
Several kb articles are returning 500 when accessed

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1917]
**Steps to reproduce**
1. Mouse-over the `Explore Help Articles` top-navbar option.
2. Click on one of the listed items from the `Explore by topic` section.
3. Click on several listed kb articles.

**Expected behavior**
The redirect to the article is successfully performed.

**Actual behavior**
The 500 error page is displayed.

Sentry fires multiple errors:
* https://mozilla.sentry.io/issues/5655256810/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
* https://mozilla.sentry.io/issues/3809794267/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=1

**Screencasts**
![500listedarticles](https://github.com/user-attachments/assets/acb41577-02fc-48c5-826e-708a0a8c1024)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**:
This issue is reproducible in `stage` only

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6153

**Comment by emilghittasv** [comment]
I can confirm that this issue is fixed in `stage` 

Moving this ticket inside the `release` column.
