### ISSUE TITLE
The /topics/privacy-and-security and questions/topic/privacy-and-security are not redirecting properly

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1918]
**Steps to reproduce**
1. Mouse-over the `Explore Help Articles` top-navbar.
2. Click on the `Privacy and security` option from the `Explore by topic` section.
3. Navigate to the https://support.allizom.org/en-US/questions/topic/privacy-and-security page

**Expected behavior**
The user is redirected to the /topics/privacy-and-security and /questions/topic/privacy-and-security pages successfully.

**Actual behavior**
The link isn't redirecting properly.

**Desktop:**
 - OS: Windows 10.
 - Browser: Firefox.

**Additional context**
This issue is reproducible in `stage` only.

**Comment by emilghittasv** [comment]
@akatsoulas I've morphed this ticket to include the faulty https://support.allizom.org/en-US/questions/topic/privacy-and-security link as well

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6157

The PR should prevent production to catch this bug. For staging I also manually deleted the redirect.

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
