### ISSUE TITLE
500 error when trying to navigate to several options from the Browse all forum threads by topic section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1920]
**Steps to reproduce**
1. Mouse over the `Community Forums` top navbar option.
2. Click on the `Installation and updates` and `Browse` options from the `Browse all forum threads by topic options` section.

**Expected behavior**
The user is successfully redirected.

**Actual behavior**
500 error message and sentry fires https://mozilla.sentry.io/issues/5655154181/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6156

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
