### ISSUE TITLE
500 error when trying to filer by product inside the Explore by Topic page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1921]
**Steps to reproduce**
1. Mouse-over the `Explore Help Articles` top-navbar option.
2. Click on an option from the `Explore by topic` section (example: `Settings`)
3. Select an option from the `Filter by product` dropdown.

**Expected behavior**
The listed articles are successfully filtered by the chosen product,

**Actual behavior**
500 error message and sentry fires https://mozilla.sentry.io/issues/5655249783/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
This should be fixed by https://github.com/mozilla/kitsune/pull/6153

**Comment by emilghittasv** [comment]
I can confirm that this issue is fixed in `stage`.

Moving this ticket inside the `release` column.
