### ISSUE TITLE
Several topics/ pages are not redirecting properly

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1925]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/topics/bookmarks
2. Go to https://support.allizom.org/en-US/topics/tracking-protection
3. Go to https://support.allizom.org/en-US/topics/calendar
4. Go to https://support.allizom.org/en-US/topics/accounts

**Expected behavior**
The user is successfully redirected.
**Actual behavior**
The user is no redirected properly.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`

**Comment by akatsoulas** [comment]
The fix in https://github.com/mozilla/kitsune/pull/6157 should be applied here too. Staging is already migrated to the new taxonomy so this fix will not be re-run. I am applying the fix manually by deleting the redirect entries for the topics in this issue manually.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.

Thank you for manually fixing this in `stage`!
