### ISSUE TITLE
The product topic listing page is not listing all topics for that product inside the side navbar

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1926]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/firefox/troubleshooting (or any product topic listing page)
2. Observe the side-navbar.

**Expected behavior**
As in `prod`, the product topic listing page is listing all the topics for that product.

**Actual behavior**
In `stage` only a few topics are listed and the side navbar menu is named `Popular Firefox Topics` instead of `All Firefox Topics`

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6163

**Comment by emilghittasv** [comment]
I believe that the fix for this ticket has caused https://github.com/mozilla/sumo/issues/1931

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
