### ISSUE TITLE
Research spacing around URLs in Notification Bar Announcements

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1927]
![Image](https://github.com/user-attachments/assets/9b015727-62db-4450-80d0-0ce88ee6a897)

There is awkward spacing around URLs in our announcement alerts. We should:

- [ ] Determine if this is in service to accessibility and if not
- [ ] Correct the spacing

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6271

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.

**Comment by janbrasna** [comment]
The underlying issue is actually a bug in Protocol itself: https://github.com/mozilla/protocol/issues/1000 — I'll try to ping you when a fix is released in case it would fit within your update path, so that you can get rid of this override at such point.

**Comment by janbrasna** [comment]
FYI the fix for this is included in [mozilla/protocol@`v21.0.0`](https://github.com/mozilla/protocol/releases/tag/v21.0.0) release so once updated, the override here can be dropped.
