### ISSUE TITLE
[L10n Project] Create an adapter for translatable Wiki text to/from a machine-translation service

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1932]
Create an adapter that "conceals" any Wiki syntax within HTML text that will be sent to a machine-translation service, and that also is able to "reveal" any previously "concealed" Wiki syntax after the text has been translated.

The following Wiki syntax elements need to be handled:
- [ ] Internal links -- The title needs to be protected from translation.
- [ ] Image and video links -- Protect entire construct from translation.
- [ ] `{note}` and `{/note}` -- Protect tags from translation, but not the content.
- [ ] `{warning}` and `{/warning}` -- Protect tags from translation, but not the content.
- [ ] `{pref ` and its closing `}` -- Protect tags from translation, but not the content.
- [ ] `{filepath ...}` -- Protect entire construct from translation.
- [ ] `{key ...}` --  Protect entire construct from translation.
- [ ] `{menu ` and `}` -- Protect tags from translation, but not the content.
- [ ] `{button ` and `}` -- Protect tags from translation, but not the content.
- [ ] `{for ...}` and `{/for}` -- Protect tags from translation, but not the content.
- [ ] Should all Wiki formatting commands that start a line be protected from translation, just to be safe?

**Comment by akatsoulas** [comment]
The project has slightly changed direction. I am closing this bug to reduce clutter until we have a better understanding on the implementation details
