### ISSUE TITLE
Add banner in support of CA Certificate change

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1939]
We have an upcoming [Root Certificate Expiration](https://bugzilla.mozilla.org/show_bug.cgi?id=1906487) which will cause issues for users on older versions of the browser. The last time we had a root certificate expire, the lack of proactive FX communication to users led to an apocalyptic incident with large volumes of user feedback. This time, we will be showing in-product messages leading up to this update. This in-product messaging will begin Sept 9.

Due to the sensitive nature of this update, Product also asked us about including a SUMO banner .

Add banners to 2 KB articles but we don’t need to configure banners based on Version/OS
Content will provide articles and banner copy for this work

**Comment by akatsoulas** [comment]
This is no longer needed
