### ISSUE TITLE
Navigating to the Switching Devices kb article returns a 404

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1940]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices

**Expected behavior**
The article is successfully displayed.

**Actual behavior**
404 is returned.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by emilghittasv** [comment]
@escattone Hmm, this issue is still reproducible in `stage`, the Switching Devices kb article returns a 404.

**Comment by escattone** [comment]
Oops, I missed something that @akatsoulas has addressed with https://github.com/mozilla/kitsune/pull/6173, so once that PR merges, this issue should be fixed.

**Comment by emilghittasv** [comment]
This issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
