### ISSUE TITLE
Product topic listing page is no filtering articles based on the chosen subtopic

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1942]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/firefox/troubleshooting
2. Switch between the available subtopics (https://support.allizom.org/en-US/products/firefox/troubleshooting/slowness-or-hanging and https://support.allizom.org/en-US/products/firefox/troubleshooting/procedures-diagnose-and-fix-problems)  

**Expected behavior**
The listed articles belong to the selected subtopic.

**Actual behavior**
The listed articles are the same with the ones displayed when filtering for `All articles and threads`.

For example the https://support.allizom.org/en-US/kb/Certificate-contains-the-same-serial-number-as-another-certificate kb article is displayed for all subtopics even if it belongs only to the `Troubleshooting` parent topic.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6175

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
