### ISSUE TITLE
The "Explore by topic" page is listing subtopic tabs which are redirecting the user from /topics/ to /products/ page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1943]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/topics/browse/firefox
2. Click on a subtopic tab option (example: "Bookmarks")

**Expected behavior**
The Explore by Topic page should display all articles belonging to that particular topic (similar to `prod`) and not list any subtopic tabs.

**Actual behavior**
Subtopic tabs are listed and if the user clicks on one of them he gets redirected from `topics/browse/firefox` to `/products/firefox/browse/bookmarks` which can be confusing since it looks like an unexpected redirect & the side menu options have changed significantly.

**Screencasts**
![explore_by_topic_subtopic](https://github.com/user-attachments/assets/f0484282-1884-468f-b031-d7989d4f9a1a)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6174

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
