### ISSUE TITLE
Wagtail: Create product templates for WT output

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1965]

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6217

- product_card_preview - the template for a product card
- product_wagtail - a single product template
- products_wagtail - a multiple products template

**Comment by akatsoulas** [comment]
Work is paused on integrating Wagtail into the platform for the remainder of the year. New tickets will be opened when/if work is resumed.
