### ISSUE TITLE
Wagtail: Create blocks for main product page

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1966]

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6216

- cta_block template
- featured_article_block - template for single article block
- featured_articles_block - template for all featured articles
- frequent_topics_block - template for all frequent topics for product
- product_snippet_block - allows viewing and selecting of product models once registered as snippets
- search_block - search block with parent page product context

**Comment by akatsoulas** [comment]
Work is paused on integrating Wagtail into the platform for the remainder of the year. New tickets will be opened when/if work is resumed.
