### ISSUE TITLE
KB articles can be created under an unwanted product + topic combination if the disabled fields are forcefully enabled at UI level

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1969]
**Preconditions**
* Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/new (or edit an existing article metadata).
2. Select a product from the "Select product(s)" section.
3. Force enable a disabled topic by removing the `disabled` HTML attribute from the checkbox.
4. Check the checkbox which was force enabled.
5. Fill all the other required form fields.
6. Submit the article for review.

**Expected behavior**
The user is unable to submit the article for review under the invalid product + topic combination.

**Actual behavior**
The article is successfully submitted for review under the invalid product + topic combination.

**Screencasts**
![validation](https://github.com/user-attachments/assets/cd6937f1-548b-4855-b2e1-524fcd1ce783)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage` only.
* This issue is reproducible even if forcefully enabling the disabled products.

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6240

**Comment by emilghittasv** [comment]
@akatsoulas 

This issue is partially fixed. While I can no longer force apply topics which are not relevant to the selected product, I can still force apply products that are not relevant to the selected topic.

Steps to reproduce:
1. Go to https://support.allizom.org/en-US/kb/new (or edit an existing article metadata).
2. Select a product from the "Select product(s)" section.
3. Select a topic which is valid for that product
4. Force enable a different (non-relevant) product and check the checkbox.
5. Fill all the other required form fields.
6. Submit the article for review.


![Image](https://github.com/user-attachments/assets/4456a075-a007-4c6f-989b-96dcd58bbab4)

I'm going to move this ticket inside the `in progress` field.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6253

**Comment by akatsoulas** [comment]
Related also PR https://github.com/mozilla/kitsune/pull/6261

**Comment by emilghittasv** [comment]
This is partially fixed in `stage` but we are going to keep track of the remaining issue in https://github.com/mozilla/sumo/issues/1989#issuecomment-2379062280

Moving this ticket inside the `release` column.
