### ISSUE TITLE
Product and Topic selections progress is lost if there is an error on kb submission

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1970]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/new
2. Fill all the required fields except the `Select product(s)` and `Select topic(s)` sections.
3. Choose a product/products from the `Select product(s)` section.
4. Submit the article for review without selecting a topic from the `Select topic(s)` section.
5. Choose a topic from the `Select topic(s)` section.
6. Submit the article for review without selecting a product from the `Select product(s)` section.

**Expected behavior**
**Step 4**: The `Please select at least one topic.` error message is displayed and the product/products chosen in step 3 are saved/checked.
**Step 6**: The `Please select at least one product.` error message is displayed and the topic/topics chosen in step 5 are saved/checked.

**Actual behavior**
**Step 4**: The `Please select at least one topic` error message is successfully displayed but the product/products selection in step 3 is/are lost.
**Step 6**: The `Please select at least one product.` error message is successfully displayed but the topic/topics selection in step 5 is/are lost.

**Screencasts**
![lostproducttopicselection](https://github.com/user-attachments/assets/621e31d6-a387-4cff-9fc8-9e6b4e11e732)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by akatsoulas** [comment]
This should be fixed by 
https://github.com/mozilla/kitsune/pull/6257 and https://github.com/mozilla/kitsune/pull/6260

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
