### ISSUE TITLE
Product selection progress is lost if there is an error on kb metadata edit submission

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1971]
**Preconditions**
Sign in to SUMO.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/testarticletest/edit/metadata
2. Choose the `Templates` option from the `Category` select box.
3. Click on the `Save` button to perform the changes.

**Expected behavior**
An error message is displayed and the `Select product(s)` selection is not lost.

**Actual behavior**
An error message is displayed but the product selections inside the `Select product(s)` section is lost.

**Screencasts**
![editmetadataproductselectionlost](https://github.com/user-attachments/assets/d55af998-0a6f-41c8-a160-8aba856254f3)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage` only.
* The topics selection from the `Select topic(s)` section is not lost.

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6257

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
