### ISSUE TITLE
Wagtail: Implement localization for new product index pages

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1975]
We will immediately require localization to be in place for Product index pages once we roll one/any live. We need to look at current localization options that can work seamlessly with our current Pontoon based workflow, or propose something different.

**Comment by smithellis** [comment]
Update:

We already had everything installed for [wagtail-localize](https://wagtail-localize.org/stable/).

What is missing is the process that can do bulk extraction and update. wagtail-localize appears to let you do in-admin localization, and download/upload one-off PO files. We need a more robust, scripted solution.

There is an additional app called [wagtail-localize-git](https://github.com/wagtail/wagtail-localize-git) that uses what wagtail-localize offers but can manage POs via a git repo - so very much how we do today.

Key questions I'm looking at still/now:

- [ ] Can we "bulk create" all our localized branches in Wagtail? Right now I have to go into the admin, choose a page for translation, create that translation, and that creates the new tree under that locale. This will need to be scripted somehow.
- [ ] I'm not 100% clear on integrating our current PO process with the automated process offered by wagtail-localize-git. I think it would make more sense to use whatever extraction method wagtail-localize-git is firing off (if it is?) and then update our current PO files, thus using the current process.

**Comment by akatsoulas** [comment]
This ticket is to general and doesn't capture the exact state of work. It needs to be replaced by tickets/issues with smaller scope that capture the exact state of work at any given moment.
