### ISSUE TITLE
No topics are listed under the "Change Topic" dropdown inside the moderator tool

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1983]
**Preconditions**
1. Report an AAQ question as "Miseplaced"
2. Sign in with an account that has the necessary permissions of moderating forum content & changing the question topic.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/flagged
2. Choose the "Misplaced bug report or support request" from the "Filter by reason" drodpown menu.
3. Click on the "Change Topic" dropdown.

**Expected behavior**
A list of topics belonging to that particular product is listed successfully.

**Actual behavior**
No items are returned inside the "Change Topic" dropdown.

**Screencasts**
![topicsChange](https://github.com/user-attachments/assets/6b72ffef-a064-4c56-b807-33ba965f577d)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6255

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
