### ISSUE TITLE
The /flagged page returns 500 if a question answer was flagged as "Misplaced bug report or support request"

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1984]
**Preconditions**
Sign in with an account that has the necessary permissions of moderating flagged content.

**Steps to reproduce**
1. Go to any posted AAQ question which has at least 1 reply.
2. Click on the 3 dotted menu for that particular reply.
3. Click on the "Report Abuse" option
4. Check the "Misplaced bug report or support request" radio button and submit the report.
5. Navigate to the https://support.allizom.org/en-US/flagged page.

**Expected behavior**
The "Misplaced bug report or support request" radio button should be available only for the flagged question and not for question replies.

**Actual behavior**
The "Misplaced bug report or support request" radio button is available for the question replies and navigating to /flagged page yields a 500 error.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.
Sentry fires: https://mozilla.sentry.io/issues/5905207712/?alert_rule_id=13095090&alert_timestamp=1727260767188&alert_type=email&environment=us-west1&notification_uuid=c58a21dc-4358-4f18-8976-4d083a0dea4c&project=4504326797197312&referrer=alert_email

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6254

**Comment by akatsoulas** [comment]
The radio button should be available on all instances like it is in production today. The Topic moderation should be only available to Question instances.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
