### ISSUE TITLE
The "Filter by reason" updates automatically to the "All reasons" option when the /flagged page is refreshed

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1986]
**Preconditions**
Sign in with an account that has the necessary permissions of moderating forum content.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/flagged
2. Choose an option from the "Filter by reason" dropdown (except the "All reasons" default option).
3. Perform an action (update the reported status) or refresh the page.

**Expected behavior**
The /flagged page filters the flagged content based on the option selected in step 2.

**Actual behavior**
The /flagged page filters the flagged content back to "All reasons" default option which could cause some frustration among our trusted contributors since they might want to handle multiple reports coming from only a particular reason.

**Screencasts**
![allreasons](https://github.com/user-attachments/assets/c3baf3c9-9c48-4fb4-a738-2e8a188474e6)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6258

**Comment by emilghittasv** [comment]
@akatsoulas This issue is partially fixed. 

The "Filter by reason" no longer switches to "All reasons" when refreshing the page via the browser refresh button. The "Filter by reason" still updates back to "All reasons" option when updating a flagged item via the "Update" button.

https://github.com/user-attachments/assets/5eeba5b5-22de-4709-a98c-49f6d8123c1d

I'm moving this ticket back inside the `in progress` column.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6263

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
