### ISSUE TITLE
Moderator tool: Choosing a different topic via the "Change Topic" dropdown enables the "Update" button from the "Update Status:" section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1987]
**Preconditions**
Have 1 flagged question as "Misplaced bug report or support request"

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/flagged and locate the question which was flagged inside the preconditions step.
2. Choose a different topic from the "Change Topic" dropdown menu.

**Expected behavior**
The "Update" button is not enabled since no option was selected from the "Update Status:" dropdown menu.

**Actual behavior**
The "Update" button becomes enabled which could mislead moderators into thinking that the they have to interact with the "Update" button in order to perform the topic change action (the topic change action occurs automatically when a new topic was selected from the "Change Topic" dropdown without the need of clicking the "Update" button).

**Screencasts**
![updateButton](https://github.com/user-attachments/assets/1bf592f1-4dee-4422-88b7-8418d3e08bb6)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
The proper behavior here would be to enable the button and select also the value that the topic is updated.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6258

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

The "Update" button is automatically enabled and the "Redirected support request" option from the "Update Status" is automatically selected.

Moving this ticket inside the `release` column.
