### ISSUE TITLE
Topics cannot be changed via the /flagged page for some flagged questions

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1988]
**Preconditions**
Have a couple of questions flagged as "Misplaced bug report or support request".

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/flagged
2. Choose a different topic from the "Change topic" drodpown

**Expected behavior**
The topic is successfully changed.

**Actual behavior**
Nothing happens,

**Screenshots/Screencasts**
![cantChangeTopic](https://github.com/user-attachments/assets/deaadfdd-9090-404a-a3d8-f40391b610c2)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage` only.
* This issue is reproducible only for some flagged questions. Not sure yet what is the exact cause.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6258

**Comment by emilghittasv** [comment]
I am no longer able to reproduce this issue in `stage`.

Moving this ticket inside the `release` column.
