### ISSUE TITLE
KB articles can be moved under an unwanted product + topic combination if the disabled product fields are forcefully enabled at UI level during the article metadata edit

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1989]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to an existing article and click on the "Edit Article Metadata" option from the "Editing Tools" section.
2. Force enable a disabled product by removing the `disabled` HTML attribute from the checkbox.
3. Check the checkbox which was force enabled.
4. Submit the metadata changes.

**Expected behavior**
The user is unable to submit the changes under the invalid product + topic combination.

**Actual behavior**
The changes can be successfully submitted under the invalid product + topic combination.

**Screenshots/Screencasts**
![forceontMetadataChange](https://github.com/user-attachments/assets/659cf6e6-215b-460f-b825-e62365a67030)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by emilghittasv** [comment]
@akatsoulas Unfortunately I can still reproduce this issue:

**Steps to reproduce**
1. Access the following kb article edit/metadata page: https://support.allizom.org/en-US/kb/fewfwefwef/edit/metadata or create a new kb article which has the "Firefox" product and the "Accessibility" topic applied.
2. Force enable the "Hubs" product and the "Billing and subscription" topic.
3. Click on the "Save" button.

**Expected Results**
* The disabled products and topics cannot be forcefully applied.

**Actual Result**
* The disabled products and topics can be forcefully enabled and applied to the article.

I'm going to move this ticket back inside the `in progress` field.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6267

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
