### ISSUE TITLE
The product(s) and topic(s) are not pre-selected on the metadata edit page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1990]
**Preconditions**
Create a KB article.

**Steps to reproduce**
1. Go to the article created inside the preconditions.
2. Click on the "Edit Article Metadata" option from the "Editing Tools" navbar.

**Expected behavior**
The topics and products applied during kb article creation are pre-selected on the metadata edit page.

**Actual behavior**
The topics and products applied during kb article creation phase are not pre-selected on the metadata edit page.

**Screencasts**
![noProductOrTopic](https://github.com/user-attachments/assets/f478bd57-c4a2-4c86-925f-7dbb0d4ec5d6)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.
I believe that this is a regression caused by the fix for https://github.com/mozilla/sumo/issues/1971

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6260

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
