### ISSUE TITLE
The "Update" button is not disabled back when choosing the "Please select..." option from the "Update Status:" section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1991]
**Preconditions**
Have a couple of questions flagged.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/flagged
2. Choose an option from the "Update Status:" dropdown menu. (different from the default "Please select..." one)
3. Choose the "Please select..." option from the "Update Status:" dropdown menu.

**Expected behavior**
The "Update" button is disabled again since the "Update Status:" must be different from the default "Please select...:" one in order to successfully resolve the flagged content.

**Actual behavior**
The "Update" button remains enabled when switching the "Update Status" back to the default "Please select..." value.

**Screencasts**
https://github.com/user-attachments/assets/6990f032-ca00-445d-9092-392ebad861c9

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6272

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
