### ISSUE TITLE
Default reason filter to spam in the moderation tool

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1997]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6280

**Comment by emilghittasv** [comment]
I can confirm that the default reason filter when accessing the /flagged page is `spam`

No regressions encountered while verifying this change.

Moving this ticket inside the `release` column.

**Comment by kelimuttu** [comment]
Hey folks, I'm glad to see that this work is underway. I just want to share what the moderators are saying in the forum, though. Would it be possible to default to all reasons except for the `Misplaced bug report or support request`? That way, the forum moderators don't need to change the filter one by one to get to what they need to see.

**Comment by akatsoulas** [comment]
My concern here is that if we default `All reasons` to display everything apart from a single choice, it's going to introduce a weird behavior which will add confusion in the future.

**Comment by akatsoulas** [comment]
This is already released in prod. Please open a new issue if you would like the functionality of the filter altered

**Comment by kelimuttu** [comment]
Cool. I filed https://github.com/mozilla/sumo/issues/2000 to capture this proposal.
