### ISSUE TITLE
Visually mark questions which were flagged as spam inside our AAQ fourms 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1998]
**Describe the bug**
If moderators are marking a question as spam and navigating back to the https://support.allizom.org/en-US/questions/all page, the flagged question is not highlighted in any way as being marked as spam which leads other moderators (or the same moderator) to not immediately spot that the question is indeed marked as spam or not (they have to navigate to the question in order to see the "marked as spam" ui notification). 

This could be a quality of life improvement by having our moderators easily spot questions which were already marked as spam.

**Preconditions**
Sign in with a moderator account.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/all and click on any of the listed questions.
2. Click on the "Mark as spam" option from the "Question Tools" section.
3. Navigate back to the https://support.allizom.org/en-US/questions/all page

**Expected behavior**
The question from step 2 has a visual representation of being marked as spam for easy identification.

**Actual behavior**
The question from step 2 has no visual representation of being marked as spam so moderators have to access it in order to find out this information.

**Screencasts**
![noRepresentation](https://github.com/user-attachments/assets/f067e673-846f-4568-ae25-35cb74722fa2)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`.

**Comment by cajinajr** [comment]
Excellent, yes! I noticed this too. Would this be low lift, engineering-wise? One option for a quick 1st iteration is to use the same visual marker (as seen in step two) but without the user and timestamp metadata. Using a shortened version that just says "Marked as spam" on the `/questions/all` page keeps the UI clean and avoids visual competition between the forum thread metadata and the spam marker metadata. If contributors want to see who marked the post as spam and when it was marked, they can still click into the thread and see the (existing) detailed spam marker with the user and timestamp metadata.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6289

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

* Questions which were marked as spam by moderators are now visually marked (for moderators) inside community forums.
* Removing a question from the "marked as spam list" also removes the "Marked as spam" visual indicator from the community forums.

![Image](https://github.com/user-attachments/assets/f422c12c-93e4-4e70-a2b5-25cf5c9ce076)


Moving this ticket inside the `release` column.
