### ISSUE TITLE
KB API does not return any results

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1999]
Visiting `api/1/kb/` returns zero results. Similarly there's not way to retrieve a document through the API. It looks like the culprit is the locale. Django is returning a locale in the form of `en_us` but `Document` objects have a locale in the form of `en_US`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6282

**Comment by emilghittasv** [comment]
I can confirm that the api/1/kb/ is functional and retrieves the kb data on GET request.

Moving this ticket inside the `release` column.
