### ISSUE TITLE
Default moderation list to include everything except for 'Misplaced bug report or support request'

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#2000]
**Describe the bug**
There are 5 filtering reasons on the moderation tool right now. Four of them are mostly used by the forum moderators, and only one (`Misplaced bug report or support request`) is intended for the agents. 

The default filter is currently 'spam'. Though this helps the forum moderators from not seeing the stuff that's intended for the agents, they still have to manually select the filter to moderate conversations flagged due to other reasons. This place a huge risk, especially if we missed a report about abusive content due to the default state set to only show spam reports. 

**Preconditions**
Sign in with a forum moderator account.

**Steps to reproduce**
1. Go to http://support.mozilla.org/flagged. The default filtering is spam
2. As a forum moderators, you can moderate the conversations flagged as spam from this page
3. Click on filter by reason control menu and select `Inappropriate language/dialog`
4. Moderate the conversations flagged due to their language
5. Click on filter by reason control menu and select `Abusive content`
6. Moderate the conversations flagged as abusive content
7. Click on filter by reason control menu and select `Other`
8. Moderate the conversations flagged due to other reasons

**Expected behavior**
Forum moderators should be able to see all conversations that need their immediate attention, without having to select the filtering reasons one by one. 

**Actual behavior**
Forum moderators have to go through step 3-8 to get to all the conversations that need their attention. 

**Screenshots/Screencasts**

**Desktop:**
 - OS: MacOS Sonoma 14.5
 - Browser: Firefox
 - Version: 131

**Additional context**
The team may need to change the filtering control from a dropdown to multi-select, so the indication is clear.

**Comment by akatsoulas** [comment]
The only way to introduce this functionality would be by changing the widget to something that would allow multiple selects like checkboxes. Although it would achieve what's being proposed here, I am not sure this is a solution to the actual problem which is focused on the value and impact that the addition of the AAQ topic flags adds to the queue. 

The filtering works correctly and until we find a good solution to the problem, I added the following tickets which will be released soon.

* [Controlling the creation of the flags through waffle](https://github.com/mozilla/sumo/issues/2001). This will basically disable the automatic creation of new flags when a new question is submitted. It can be enabled back on the fly through the admin interface without requiring any changes, if/when required. 
* [Change back the default option in the filtering](https://github.com/mozilla/sumo/issues/2002). Without any more flags automatically created from the Questions, the filtering should default to everything which was also the behavior even before the filtering was introduced.

**Comment by akatsoulas** [comment]
I would avoid making any more changes to the functionality, until we have a clearer path forward. I am closing this issue but feel free to re-open if you would like different filtered options regardless of the content they provide filtering upon.

**Comment by kelimuttu** [comment]
My initial intention with this proposal was to create a separation between agents and forum contributors. If there's one thing to learn from this situation, I think it'll be, mixing contributors and agents experience is not a good idea and will lead to frustration on both sides. 

But, I guess, your proposal above would help revert the old experience before we add the additional flag, so I'd be fine with that as long as we're pausing the automation. My only concern is that I don't want to mess around with the forum moderators workflow for now, since they're already frustrated with our spam volume.

**Comment by akatsoulas** [comment]
Also related issue
https://github.com/mozilla/sumo/issues/2003
The last issue should have cleared all the pending flags that were waiting for topic moderation.
