### ISSUE TITLE
Control the creation of flagged questions through waffle. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2001]
We should have a waffle flag/switch in order to dynamically control the creation of flags for questions.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6287

**Comment by emilghittasv** [comment]
I can confirm that the `flagit-spam-autoflag` waffle flag successfully controls if questions are added to the "Misplaced bug report or support request" flagged queue or not.

* If the `flagit-spam-autoflag` waffle flag is `active`, new questions are automatically flagged for review as "Misplaced bug report or support request".
* If the `flagit-spam-autoflag` waffle flag is not `active`, new questions are not automatically flagged for review.

Moving this ticket inside the `release` column.
