### ISSUE TITLE
Page views for the /localization page listed articles doesn't match the GA4 numbers

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2005]
**Steps to reproduce**
1. Go to https://support.allizom.org/ro/localization and compare the page view counts with the looker studio or GA4 numbers.

**Expected behavior**
The numbers should roughly match (respecting the filters applied inside the /localization page)

**Actual behavior**
The numbers seem to be way off.

For example the article with slug `cum-configurez-sincronizare` has 17 views listed inside the /localization page & the views count listed in looker studio for the same article is 1

**Desktop:**
 - OS: Windows 11.
 - Browser: Firefox

**Comment by escattone** [comment]
The pageview counts are for the English article (which is accurate), not the translation, and I suspect it's because the popularity of the English article is used to prioritize the translation work.
