### ISSUE TITLE
The "Ask the Community" button from the "Still need help?" CTA on the Contributors Support page returns 404

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2006]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/products/contributor
2. Click on the "Ask the Community" button.

**Expected behavior**
Since AAQ is not enabled for the "Contributors" product, the Still need help? is not available.

**Actual behavior**
The user is redirected to a 404 page.

**Screencasts**
![404ContributorsPage](https://github.com/user-attachments/assets/6621cb8f-0bc9-459b-9be1-1d2575904f9a)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`

**Comment by akatsoulas** [comment]
This is happening for all products that do not have an AAQConfig. For example
https://support.allizom.org/en-US/questions/new/firefox-os

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6292

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

* The CTA is successfully removed from the product landing page if the AAQ configuration doesn't exist or is set as inactive. 
* The CTA is successfully displayed inside the product landing page if the AAQ configuration is activated again or if a new AAQ configuration was added to that particular product (and marked as active).

Moving this ticket inside the `release` column.
