### ISSUE TITLE
Remove Wagtail from the code-base

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2008]

**Comment by akatsoulas** [comment]
This will require a series of PRs in order to complete the removal. 
1st PR https://github.com/mozilla/kitsune/pull/6291

**Comment by akatsoulas** [comment]
Other PRs will depend on merging https://github.com/mozilla/kitsune/pull/6291

**Comment by akatsoulas** [comment]
[PR to squash](https://github.com/mozilla/kitsune/pull/6295) migrations from `sumo` and `products` apps.

**Comment by akatsoulas** [comment]
~~PR to remove squashed migrations https://github.com/mozilla/kitsune/pull/6327~~

**Comment by akatsoulas** [comment]
PR to remove traces of Wagtail https://github.com/mozilla/kitsune/pull/6328

**Comment by emilghittasv** [comment]
General regression testing did not yield any issues caused by this change.

Moving this ticket inside the `release` column.
