### ISSUE TITLE
Ask the Community button (for Freemium products) and the "Continue" button from the "Ask a Question" CTA in topic listing page (for Premium products) returns a 404 if AAQ configuration is disabled

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2010]
**Describe the bug**
In https://github.com/mozilla/sumo/issues/2006 we have fixed a similar issue by removing the CTA from the product landing page when AAQ is not configured for that particular product but there are some other areas in which SUMO returns a 404.

**Steps to reproduce**
**Steps to reproduce the behavior for Freemium products**
1. Go to SUMO admin and disable an AAQ configuration for one of the listed `freemium` products (example: Firefox).
2. Navigate to the disabled product configuration forum page (example: https://support.allizom.org/en-US/questions/firefox)
3. Click on the `Ask the Community` button.

**Steps to reproduce the behavior for Premium products**
1. Go to SUMO admin and disable an AAQ configuration for one of the listed `premium` products (example: Pocket)
2. Navigate to the `/topics` page with the filter applied for that particular disabled product configuration (example: https://support.allizom.org/en-US/topics/settings/pocket)
3. Click on the `Continue` button from the AAQ CTA.
4. Navigate to the `/products/` topic listing page for that particular disabled product configuration (example: https://support.allizom.org/en-US/products/pocket/pocket-for-ios)
5. Click on the `Continue` button from the AAQ CTA

**Expected behavior**
**Freemium product**: The `Ask the Community` could redirect the user to the https://support.allizom.org/en-US/kb/get-community-support?exit_aaq=1 page or not be available at all in this case.
**Premium product**: the AAQ CTA is not available 

**Actual behavior**
**Freemium product**: The `Ask the Community` button returns a 404.
**Premium product**: The `Continue` button from the AAQ CTA returns a 404.

**Screencasts**
**Freemium product**:
![disabledFreemium404](https://github.com/user-attachments/assets/146483cc-014d-4fd6-80f5-5262df22824e)

**Premium product**
![disabledPremium404](https://github.com/user-attachments/assets/05286757-506d-4ac5-b3a3-b5cbc2a77311)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
For disabled freemium products, the `Continue` button from the AAQ CTA displayed inside the `/products/` topic listing page and `/topics/` page redirects the user to the https://support.allizom.org/en-US/kb/get-community-support?exit_aaq=1 kb article.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6297

**Comment by emilghittasv** [comment]
I suspect that the fix for this ticket has caused https://github.com/mozilla/sumo/issues/2022 and https://github.com/mozilla/sumo/issues/2023 to occur.

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `stage`.

* The AAQ CTA for premium products which have the AAQ configuration disabled in /products/ and /topics/ pages redirects the user to the https://support.allizom.org/en-US/questions/new page.
* The "Ask the Community" button from freemium products which has the AAQ configuration disabled redirects the user to the https://support.allizom.org/en-US/questions/new page.

I'm moving this ticket inside the `release` column.
