### ISSUE TITLE
Duplicate product tags in AAQ forums

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2012]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Submit an AAQ question for any freemium product
2. Navigate to the AAQ forum for the product in which the AAQ question was submitted in step 1.

**Expected results**:
* Only one product tag is displayed for the filled question

**Actual result**
The product tag is displayed twice:

- For the Firefox product: `Firefox` and `firefox`
- For the Android product: `Firefox for Android` and `mobile`
- For the Firefox for iOS product: `Firefox for iOS` and `ios`
- For the Firefox Focus product: `Firefox Focus` and `focus-firefox`
- For the Firefox for Enterprise product: `Firefox for Enterprise` and `firefox-enterprise`
- For the Thunderbird product: `Thunderbird` and `thunderbird`
- For the Thunderbird for Android product: `Thunderbird for Android` and `thunderbird-android`

**Screenshots/Screencasts**
![duplicateProductTags](https://github.com/user-attachments/assets/8a02602a-335f-4205-8c4f-c1152a1035e5)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6306

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Only the product tag (which acts as a tag) is displayed inside the AAQ freemium product forums.

Moving this ticket inside the `release` column.
