### ISSUE TITLE
Consider removing the "Avatar" field from admin

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2014]
**Describe the bug**
We are currently showing a custom user avatar in SUMO if it is set via Fxa and the default one if no Fxa avatar was set.

In admin we have the "Avatar" field which allows you to upload a custom image for the user but that image is never applied in SUMO.

(https://support.allizom.org/admin/users/profile/5582195/change/)

![image](https://github.com/user-attachments/assets/01a8a90f-641d-4691-b118-21f667d2a9a6)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6308

**Comment by emilghittasv** [comment]
I can confirm that the "Avatar" field was successfully removed from admin.

Moving this ticket inside the `release` column.
