### ISSUE TITLE
500 error message when accessing a user profile via admin

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2017]
**Preconditions**
Sign in with an admin account.

**Steps to reproduce**
1. Go to https://support.allizom.org/admin/users/profile/
2. Click on any of the listed profiles.

**Expected behavior**
The user profile is successfully displayed.

**Actual behavior**
500 error message.

**Screencasts**
![500ErrorAdminProfilePage](https://github.com/user-attachments/assets/eaebbcbd-e80b-4be9-8ceb-40d3c84fd03c)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional Notes**:
* Sentry fires https://mozilla.sentry.io/issues/6016896944/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6311

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Moving this ticket inside the `release` column.
