### ISSUE TITLE
Cannot filter based on the displayed name in /revisions page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2019]
**Preconditions**
Sign in to SUMO with a contributor account.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/revisions
2. Type "Smith" inside the "Users" filter.

**Expected behavior**
The revisions can be filtered for both username and display names

**Actual behavior**
The revisions are not filtered based on "Smith" which is the display name of the sellis1 username. The problem here is that contributors might try filtering via the value which is displayed inside the "Editor" column. 

If the username has a set display name, the display name will take priority and it will be displayed inside the "Editor" column instead of the username which makes it hard for users to figure out which is the actual username and based on what should they perform the search. 

**Screencasts**
![recentRevisionsFilter](https://github.com/user-attachments/assets/e0dd1d80-e600-4166-9d52-0be1b5a1e914)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible on both `stage` and `prod`.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6348

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6351

**Comment by emilghittasv** [comment]
@smithellis I'm still able to reproduce this issue in `stage`.

Trying to search (inside the /revisions page) for `Smith` in the `Users` field will not return only the search results containing the contributions made by your profile. Searching for the username `sellis1` will successfully return only your contributions. So searching for display name is still not working in this case.

I'm moving this ticket back inside the `in progress` column.

**Comment by emilghittasv** [comment]
@smithellis Now that the patch has landed in `stage` after the pod fix I've redone the verification.

Unfortunately (as it can be seen in the attached screencast for this comment) the recent revisions page is not filtering data based on the display name.

![Image](https://github.com/user-attachments/assets/29357341-ddbc-47ea-8d95-9c04845f92fe)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6361

This may be a speed/timing issue. This PR attempts to improve the speed and quality of the user lookup.

**Comment by emilghittasv** [comment]
I can confirm that the /revisions page can be filter by both displayed names & usernames in `stage`.

Moving this ticket inside the `release` column.
