### ISSUE TITLE
add GA4 events for the "unhelpful" survey

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#2020]
For the "unhelpful" survey, add GA4 events for the following:
- Submission of the survey
- Closing the survey prior to submission

**Comment by emilghittasv** [comment]
I can confirm that:
* The `article_unhelpful_survey_close` event is being sent if the unhelpful survey was closed.
* The `article_unhelpful_survey_submit` event is being sent if the unhelpful survey was successfully submitted.

Moving this ticket inside the `release` column.
