### ISSUE TITLE
500 error message if clicking the "Upload" button when changing a group avatar without having any image file selected for upload

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2021]
**Preconditions**
Sign in with an admin account.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/groups/
2. Select a random group from the list.
3. Click on the "Change" button under the default group avatar.
4. Upload an image.
5. Click on the "Change" option under the newly uploaded image.
6. Click on the "Upload" button.

**Expected behavior**
Nothing happens since no files were selected via the file picker (or the Upload button is disabled in this case).

**Actual behavior**
500 error with `FileNotFoundError`

**Screencasts**
![upload 500](https://github.com/user-attachments/assets/65bb108f-ddc5-492c-b5c9-4c7308209887)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
Sentry fires https://mozilla.sentry.io/issues/6029282387/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6342

**Comment by emilghittasv** [comment]
@smithellis 

This issue is still reproducible in `stage`.

Sentry fires the [same error](https://mozilla.sentry.io/issues/6029282387/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0)

I'm moving this ticket back inside the `in progress` field.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6355

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`.

Clicking on the "Upload" button without having an image attached will display the "You have not selected an image to upload." error message.

Moving this ticket inside the `release` column.
