### ISSUE TITLE
Frequent topics page for a product which has a disabled AAQ returns 404 and 500

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2022]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Disable an AAQ configuration for a product (example: Firefox).
2. Navigate to the https://support.allizom.org/en-US/products/firefox page
3. Click on the "Troubleshooting" frequent topic
4. Click on any other listed frequent topic.

**Expected behavior**
The frequent topics page is successfully displayed. 

**Actual behavior**
Step 3: 500 error message is returned and sentry fires: https://mozilla.sentry.io/issues/6030571427/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
Step 4: 404 is returned

**Screencasts**
![DisabledAAQFrequentTopics](https://github.com/user-attachments/assets/5af7e94a-34bc-4477-a073-1b0391e4367c)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6320

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6321

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
