### ISSUE TITLE
Unable to filter via a product with AAQ disabled in /topics/ page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2023]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Disable the AAQ configuration for one product (example: Firefox)
2. Navigate to a /topics/ listing page (example: https://support.allizom.org/en-US/topics/settings/firefox)
3. Choose the "Firefox" product from the "Filter by product" dropdown.

**Expected behavior**
The content is successfully filter by the "Firefox" product.

**Actual behavior**
The content is not filtered by the "Firefox" product and the "Filter by product" dropdown resets to "All Products"

**Screencasts**
![UnableToFilterByProducttopicspage](https://github.com/user-attachments/assets/532add47-dcfa-4f00-8b15-a05fab584878)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6320

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6321

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
