### ISSUE TITLE
Replace selectisize with an alternative.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2024]
We should replace selectisize with an alternative in order to remove the jQuery dependency. `tom-select` is a direct replacement which uses vanilla JS.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6323

**Comment by emilghittasv** [comment]
No regressions have been encountered during a general regression testing session.

During the verification of this ticket, a proposal of overriding/reverting the previous style of the "Clear All" button from the "Restrict Visibility" section was filled.

Moving this ticket inside the `release` column.
