### ISSUE TITLE
Disable the creation of new tags through the UI

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2025]
New tags should be added only through the admin interface for now. In the future, a form will be created for users to suggest new tags.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6326

**Comment by emilghittasv** [comment]
I can confirm that:
- New question tags cannot be created for posted AAQ questions via the "Apply a tag" section.
- Existing question tags can be successfully applied to questions.
- Unable to add an empty tag via the "Apply a tag" section.
- The "Add" button has changed to "Apply" for the "Apply a tag" section.
- New tags can be successfully created via Admin and then added inside the forum questions.
- Tags can be successfully deleted via Admin and the deleted tag cannot be added inside the forum questions anymore.

I'm moving this ticket inside the `release` column.
