### ISSUE TITLE
Templates are displayed inside the "Featured Articles" section

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2028]
**Steps to reproduce**
1. Go to https://support.mozilla.org/en-US/products/thunderbird-android
2. Observe the `Featured Articles` section.

**Expected behavior**
The `Featured Articles` section contains only KB articles (articles of type `template` should not be listed)

**Actual behavior**
Templates are displayed inside the `Featured Articles` section.

**Screenshots**
![image](https://github.com/user-attachments/assets/28c83ad9-59c6-494e-b408-ddd8370d730e)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6324/

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
