### ISSUE TITLE
UI issues displayed for the "Clear All" button from the "Restrict Visibility" section 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2029]
**Preconditions**
Sign in to SUMO with an account that has the proper permission of restricting the visibility of a KB article.

**Steps to reproduce**
1. Go to any kb article.
2. Click on the "Edit Article Metadata" option from the "Editing Tools" side navbar.
3. Add a group inside the "Restrict Visibility" section.
4. Observe the "Clear all" button.

**Expected behavior**
No UI issues displayed.

**Actual behavior**
The "Clear all" button is not properly displayed.

**Screencasts**
![ClearAll](https://github.com/user-attachments/assets/9ab693fa-6e2b-424a-b383-85723d91f6b9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
This is the default design of the library. We can add a ticket to override it but this is not a bug

https://tom-select.js.org/plugins/clear-button/

**Comment by emilghittasv** [comment]
Thanks! @akatsoulas 

I think that we should consider overriding it. Even if that's the default style. It looks broken & could generate user confusion.

Would you like me to morph this ticket? or do you prefer keeping track of the override somewhere else?

**Comment by akatsoulas** [comment]
Let's track this in a different issue. Since this is not considered a bug, it won't be part of this sprint
