### ISSUE TITLE
500 error returned when trying to access an option from the Browse all forum threads by topic top-navbar section while on a non-US locale

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2030]
**Steps to reproduce**
1. Go to https://support.mozilla.org/de/ (or any other locale for which the AAQ forum is not configured)
2. Mouse over the `Foren der Gemeinschaft` top-navbar option.
3. Click on one of the listed options from the `Themen im Forum nach Thema durchsuchen` section.

**Expected behavior**
The user is redirected to the product forum successfully. 

**Actual behavior**
500 error returned. Sentry fires https://mozilla.sentry.io/issues/6031206447/?project=4504326799753216&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Screencasts**
![500](https://github.com/user-attachments/assets/2f23decb-b381-40a1-a7e6-060ec06407c8)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
Reproducible in both `stage` and `prod`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6332

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
