### ISSUE TITLE
The /questions/all page returns 500 on non-US locales 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2032]
**Steps to reproduce**
1. Go to https://support.allizom.org/de/questions/all (or while on any locale for which an AAQ configuration is not set)

**Expected behavior**
The page is successfully returned.

**Actual behavior**
500 error message is returned. Sentry fires https://mozilla.sentry.io/issues/6041723467/?alert_rule_id=13095090&alert_timestamp=1730715806784&alert_type=email&environment=us-west1&notification_uuid=bc40e841-067f-49b7-aef0-bba5add8dd88&project=4504326797197312&referrer=alert_email

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6333

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
