### ISSUE TITLE
AAQ CTA from KB articles redirects the user to the kb/get-community-support article even though the AAQ configuration is enabled for that product/locale

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2033]
**Steps to reproduce**
1. Go to https://support.allizom.org/it/kb/utilizzare-schede-firefox-ios (this also occurs for the English version of that article: https://support.allizom.org/en-US/kb/use-tabs-firefox-ios)
2. Click on the `Continua` button form the AAQ CTA.

**Expected behavior**
Since the forum for that particular product (Firefox in this case) is enabled in that particular locale, the user is redirected to the `/questions/new/desktop/form` form or to the `/questions/new` if multiple products are linked to the article kb metadata.

**Actual behavior**
The user is redirected to the `kb/get-community-support` kb article.

**Screencasts**
![aaq_kb_article_redirect](https://github.com/user-attachments/assets/a99d1702-8897-470f-8696-bf7790f8c040)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6337

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

- Clicking on the AAQ CTA inside a KB article redirects the user correctly to the product AAQ form page. 

Please note that this issue was fixed only for KB articles which have a single product attached to it's metadata. For KB articles which have multiple products attached to the metadata I've filled a follow-up ticket in https://github.com/mozilla/sumo/issues/2046

Moving this ticket inside the `release` column.
