### ISSUE TITLE
Ask a Question buttons are pointing to Get Community Support page for premium products

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#2035]
**Describe the bug**
When clicking the "Ask a Question" button found on knowledge base articles, the page is redirecting to the community driven AAQ flow only (https://support.mozilla.org/en-US/kb/get-community-support?exit_aaq=1), instead of Zendesk ticket flow. I was able to reproduce this issue on desktop and Mobile using two different browsers.

**Preconditions**
None. Issue is present whether you are signed in or not.

**Steps to reproduce**

1. On Support.mozilla.org navigate to any support product for a premium product (i.e, VPN, Monitor, Relay)
2. Click the "Ask a question" button on the right hand side of the KB article. 

**Expected behavior**
User should be taken into the sign in flow to submit a Zendesk ticket.

**Actual behavior**
Observe that you are redirected to the Get Community support page for Firefox.

**Screenshots/Screencasts**
If applicable, add screenshots or screencasts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1
 - Browser: Firefox Nightly 
 - Version: 134.0a1

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android 13
 - Browser: Chrome
 - Version: 130.0.6

**Additional context**
Observed the issue with all premium products. 

https://github.com/user-attachments/assets/df030403-3b98-4be9-9f37-a2d9066e5bdb

ere.

**Comment by emilghittasv** [comment]
Similar with https://github.com/mozilla/sumo/issues/2033

**Comment by akatsoulas** [comment]
This is the same bug. Closing as duplicate. Thanks @JC-Support! A fix has been opened in #2033
