### ISSUE TITLE
AAQ CTA widget from a posted AAQ question redirects the user to the kb/get-community-support page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2036]
**Steps to reproduce**
1. Go to any posted forum questions (example: https://support.allizom.org/en-US/questions/1457825)
2. Click on the "Continue" button from the "AAQ" CTA.

**Expected behavior**
The user is redirected to that particular product AAQ new question form page.

**Actual behavior**
The user is redirected to the kb/get-community-support page page.

**Screencasts**
![AAQ_CTA_widget](https://github.com/user-attachments/assets/cba73897-c0e2-4ac3-9dce-091a2e0f3a0d)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in both `stage` and `prod`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6346

**Comment by emilghittasv** [comment]
This issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
