### ISSUE TITLE
Tags which were deleted via admin are not automatically removed from questions page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2038]
**Preconditions**
Sign in to SUMO with an admin account.

**Steps to reproduce**
1. Go to any question and apply a tag.
2. Go to admin and delete the tag applied in step 1.
3. Navigate back to the question from step 1 and refresh the page.

**Expected behavior**
The tag which was deleted via admin is automatically removed from the question.

**Actual behavior**
The deleted tag is still displayed on the question page.

**Screencasts**
![deleted_tags](https://github.com/user-attachments/assets/4cc2f772-0eab-473b-ab7b-4edc7dc8372d)

**Additional Notes** 
This issue is reproducible even after removing a tag from a question via admin from the `Tagged Items` section:
![tagRemovedFromQuestion](https://github.com/user-attachments/assets/3537bfd4-e719-4284-b952-6b2c2df6af7a)

**Comment by akatsoulas** [comment]
This is working correctly. When the entry is removed from the `Tagged Items`, the tag is removed from the associated object. In this example from the question. In order to complete remove the tag, you need to delete it from `/admin/taggit/tag/`

**Comment by emilghittasv** [comment]
The tags are not removed from the posted question UI immediately because the tag list is cached https://github.com/mozilla/kitsune/blob/main/kitsune/questions/models.py#L397
