### ISSUE TITLE
Reduce the list of existing tags

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2039]
Reduce the list of existing tags by:

- Deleting tags that are not used
- Deleting tags that are used *only* in archived questions
- Merging related tags by performing a fuzzy search

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6335

**Comment by emilghittasv** [comment]
Prior to merging this PR I've created a couple of test data tags to match each criteria.

I can confirm that:
- I had created a tag called `unusedTag` which was not used anywhere and it got successfully deleted.
- I had created a tag called `onlyUsedInArchive` which was used only in archived questions and the tag was successfully deleted.
- I had created a tag called `usedInLocked` which was used only in locked questions and the tag was not deleted.
- I had created a tag called `bothArchivedAndNonArchived` which was used in both archived and non archived question and the tag was not deleted.
- I had created a tag called `test` which was used in multiple questions (non-archived) and the tag was not deleted.

Please note that the fuzzy merge was removed from the PR.

Moving this ticket inside the `release` column.
