### ISSUE TITLE
Create Tier-3 of the taxonomy in Kitsune

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2044]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6362

**Comment by emilghittasv** [comment]
I can confirm the followings in `stage`:
* The tier 3 taxonomy topics are successfully added and matches the Taxonomy map doc.
* The tier 3 taxonomy topics are successfully displayed inside the /moderate tool.
* Tier 3 topics can be successfully applied to questions via the /moderate tool.

Moving this ticket inside the `release` column.
