### ISSUE TITLE
The AAQ CTA from the /topics listing page redirects the user to the /get-community-support?exit_aaq=1 while having the "All Products" filter selected

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2047]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/topics/settings
2. Ensure that the "All Products" option is chosen inside the "Filter by product" filter.
3. Click on the `Continue` button from the AAQ CTA.

**Expected behavior**
The user is redirected to the `/en-US/questions/new` (same as in `prod`)

**Actual behavior**
The user is redirected to the `/get-community-support?exit_aaq=1` kb article

**Screencasts**
![exit_aaq=1_topics_page](https://github.com/user-attachments/assets/4fe78dcc-84c7-434b-9147-2f41852ec4a7)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
* This issue is reproducible in `stage` only.
* This issue was caught by playwright in ` test_explore_by_topic_aaq_widget_redirect` test

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6349

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
