### ISSUE TITLE
Some taxonomy topics require updates

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2050]
As per the [Taxonomy map doc](https://docs.google.com/spreadsheets/d/1lBueJboMLNWeQU0-IL3b3-GcrVcPPzQvQ95JIay_Shg/edit?gid=921396354#gid=921396354)

**[Backup, recovery, and sync Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L95)**:
* Needs to be removed: `Relay`

**[Browse Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L121)**
* Needs to be added: `Focus` and `Firefox for Enterprise`

**[Links Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L151)**
* Needs to be added: `Focus` 

**[Performance and connectivity Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L159)**
* Needs to be added: `Firefox for Enterprise` and `Relay`

**[Crashing and slow performance Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L174)**
* Needs to be added: `Firefox for Enterprise`, `Relay` and `Thunderbird for Android` 

**[Site breakages Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L188)**
* Needs to be added: `Mozilla VPN`

**[Downloads Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L209)**
* Needs to be added: `MDN Plus`
* Needs to be removed: `Pocket`

**[Save content Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L215)**
* Needs to be added: `MDN Plus` 

**[Search, tag, and share Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L223)**
* Needs to be added: `Thunderbird for Android`

**[Search Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L229)**
* Needs to be added: `Thunderbird for Android`

**[Tags Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L235)**
* Needs to be added: `Thunderbird` and `Thunderbird for Android`
* Needs to be removed: `firefox`, `mobile`, `ios`

**[Settings Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L296)**
* Needs to be added: `Thunderbird for Android`

**[Import and export settings Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L315)**
* Needs to be added: `Thunderbird for Android`
* Needs to be removed: `mozilla-account`

**[Customization Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L330)**
* Needs to be added: `Thunderbird for Android` and `MDN Plus`
* Needs to be removed: `mozilla-account`

**[Autofill Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L346)**
* Needs to be added: `Thunderbird for Android`
* Needs to be removed: `firefox-private-network-vpn` and `mozilla-account`

**[Languages Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L361)**
* Needs to be added: `Thunderbird for Android`
* Needs to be removed: `mozilla-account`

**[Privacy and security Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L396)**
* Needs to be added: `Thunderbird for Android`

**[Tracking protection Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L414)**
* Needs to be added: `Firefox Relay` and `Pocket`
* Needs to be removed: `Thunderbird`

**[Masking Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L444)**
* Needs to be removed: `firefox`, `mobile` and `ios` 

**[Security Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L450C18-L450C26)**
Needs to be added: `Mozilla Monitor` and `Thunderbird for Android`

**[Passwords and sign in Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L468)**
* Needs to be added: `Pocket`

**[Save passwords Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L485)**
* Needs to be added: `Mozilla Monitor`

**[Reset passwords Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L498)**
* Needs to be added: `Pocket`

**[Accounts Tier 1](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L531)**
* Needs to be added: `MDN Plus`

**[Account management Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L561)**
* Needs to be added: `Firefox`, `Firefox for Android`, `Firefox for iOS` and `Thunderbird for Android`
* Needs to be removed: `Firefox for Enterprise`

**[Account recovery Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L573)**
* Needs to be added: `MDN Plus`
* Needs to be removed: `Firefox for Enterprise`

**[Manage billing Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L600)**
* Needs to be added: `Monitor`

**[Manage subscriptions Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L613)**
* Needs to be added: `Monitor`

**[Junk email and spam Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L640)**
* Needs to be added: `Thunderbird for Android`

**[Instant messaging Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L646)**
* Needs to be added `Firefox Relay`

**[Attachments Tier 2](https://github.com/mozilla/kitsune/blob/474d8a4bd1317216a39b90254f90e13e8db354e9/kitsune/products/migrations/0001_squashed_0020_remove_sumoplaceholderpage_page_ptr_and_more.py#L652)**
* Needs to be added: `Thunderbird for Android`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6350

**Comment by akatsoulas** [comment]
This should be considered done when the mentioned changes have been manually applied to prod.

**Comment by emilghittasv** [comment]
I've manually applied the changes in `prod`.

Moving this ticket inside the `release` column.
