### ISSUE TITLE
Expose tier-{2, 3} topics in the moderation tool

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2051]

**Comment by akatsoulas** [comment]
This is blocked pending the decision if we are going to limit the list of topics only to those available for the AAQ.

**Comment by akatsoulas** [comment]
Following up on this, we are going to expose Topics from all levels related to the product in question.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6352

**Comment by emilghittasv** [comment]
I can confirm that the tier 2 topics are now available inside the `Change Topic` dropdown list inside the moderation tool.

Let's move this ticket inside the `release` column after the tier 3 addition & verification is performed as well.

**Comment by emilghittasv** [comment]
Tier 3 topics have been added & I can confirm that they are successfully exposed inside the moderator tool.

Moving this ticket inside the `release` column.
