### ISSUE TITLE
Expose segmentation tags in the moderation tool

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2057]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6360

**Comment by emilghittasv** [comment]
The majority of the segmentation tags are exposed/returned inside the `Assign Tags:` section from the moderator tool.

It seems that the `ios` and the `VPN::Unsupported::No OS Named` tags are not returned inside the `Assign Tags:` section. Filled under https://github.com/mozilla/sumo/issues/2068.

I'm moving this ticket inside the `release` column.
