### ISSUE TITLE
Lock the editing of the topic and tags of the question if moderated 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2058]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6364

**Comment by emilghittasv** [comment]
I can confirm the following in `stage`.

* The `Question Details` section is enabled if the question was not moderated via the /moderate tool. 
* The `Question Details` is successfully removed if the question was moderated via the /moderate tool.

Moving this ticket inside the `release` column.
