### ISSUE TITLE
Introduce segmentation tags

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2059]
- Create segmentation tags according to the [taxonomy map](https://docs.google.com/spreadsheets/d/1lBueJboMLNWeQU0-IL3b3-GcrVcPPzQvQ95JIay_Shg/edit?gid=1370915403#gid=1370915403) document
- Introduce custom tag model in order to easily extend it with more attributes
- Migrate existing tags to the new model

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6358

**Comment by emilghittasv** [comment]
I can confirm that the newly added segmentation tags are aligned with the ones listed inside the taxonomy map document
