### ISSUE TITLE
500 is returned when selecting an AAQ configuration via admin or trying to sumbit an AAQ forum question to a freemium product

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2061]
**Steps to reproduce**

**AAQ Config**:
1. Go to /admin/questions/aaqconfig/
2. Select one of the listed configurations.

**AAQ questions submission**:
1. Try submitting a question to any freemium product form.

**Expected behavior**
The AAQ can be configured and AAQ questions can be successfully submitted to freemium products

**Actual behavior**
500 is returned and Sentry fires:https://mozilla.sentry.io/issues/6072616430/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0 (for AAQ configuration) and https://mozilla.sentry.io/issues/6072652949/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0 (when trying to submit a freemium product question)

**Screencasts**
![500](https://github.com/user-attachments/assets/497ba789-e8c6-40e2-8472-d531b325fa03)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.
This issue was also reported by Playwright

**Comment by akatsoulas** [comment]
This was happening b/c the migration did not run properly. Resolving this issue
