### ISSUE TITLE
Assign Tags dropdown menu is not entirely visible inside the /moderate tool

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2064]
**Preconditions**
Have at least 1 question flagged inside the /moderate tool

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/moderate
2. Click on the "Assign Tags" dropdown menu
3. Scroll down through the list.

**Expected behavior**
All elements are entirely visible.

**Actual behavior**
Not all elements are visible.

**Screencasts**
![AssignTags](https://github.com/user-attachments/assets/2b183b60-f874-4b6d-bf18-2858b24503f0)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6378

**Comment by emilghittasv** [comment]
I can confirm that the `Assign Tags` dropdown menu is no longer clipped.

Moving this ticket inside the `release` column.
