### ISSUE TITLE
Unable to dismiss a flagged content as "Content is appropiately categorized".

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2065]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/moderate
2. From the `Update Status` choose the `Content is appropriately categorized.` option.'
3. Click the `Update` button.

**Expected behavior**
Moderators are able to dismiss a ticket if no action is needed (change of topic or tag assignment)

**Actual behavior**
Moderators are not able to dismiss a ticket without performing a topic or tag update.

**Screencasts**
![forced](https://github.com/user-attachments/assets/4d5f3f04-f235-4282-aff0-2530e6001c9d)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6363

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
