### ISSUE TITLE
Tags assigned via the /moderate tool are visbile at question level only under certain conditions

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2066]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/moderate
2. Choose a tag from the "Assign Tags" dropdown.
3. Click on the "View" button for that ticket.
4. Navigate back to the /moderate tool and add a new tag inside the "Assign Tags" field
5. Click on the "View" button for that ticket.
6. Navigate back to the /moderate tool and remove one of the added tags.
7. Click on the "View" button for that ticket.

**Expected behavior**
Each new tag addition (performed in step 2 and 4) should be visible inside the question.

**Actual behavior**
Only after performing tag removal from the "Assign Tags" field, the remaining tag is successfully displayed inside the question.

On step 2 & 4 one POST request is performed to `add-tag-async` which returns "Tags updated successfully."
On step 6 (when removing a tag) 2 POST requests are being performed:
1. To `add-tag-async` with the "message": "Tags updated successfully."
2. To `remove-tag-async` returns {"message": "Tag 'Accounts::Change Email' removed successfully."} 

If the deletion is being performed while only one tag is displayed inside the "Assign Tags" field the following POST requests are being performed:
1. To `add-tag-async` which returns a 404 `{"error": "Some tags do not exist or are invalid"}`
2. To `remove-tag-async` which retruns a 200 `{"message": "Tag '3rdparty-redirect' removed successfully."}`

**Screencasts**
![add_tag_test](https://github.com/user-attachments/assets/617f5687-3bf9-4351-962b-84db497414f9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6377

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

* Adding a new tag via the moderation tool is immediately visible at question level (or after a page refresh if the question is already opened in a different tab).
* Removing a tag via the moderation tool is immediately visible at question level.
* Removing a segmentation tag at question level is immediately visible inside the moderation tool.
* The segmentation tag which was added from the question level (via the `Apply a tag` section) is immediately visible inside the moderation tool.

Moving this ticket inside the `release` column.
