### ISSUE TITLE
Add the ability to filter the moderation queue per product

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2067]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6380

**Comment by emilghittasv** [comment]
I can confirm that the moderation tool tickets can be successfully filtered by products.

During the verification of this ticket I've noticed & filled the following tickets:
* https://github.com/mozilla/sumo/issues/2082 - Performing a moderation tool ticket update resets the product filter to `All products`
* https://github.com/mozilla/sumo/issues/2081 - Enhancement to list only the products which have an active AAQ configuration.

Moving this ticket inside the `release` column.
