### ISSUE TITLE
Some segmentation tags are missing from the moderator tool

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2068]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/moderate
2. Type `ios` and `VPN::Unsupported::No OS Named` inside the `Assign Tags` section.

**Expected behavior**
The `ios` and `VPN::Unsupported::No OS Named` tags are returned inside the `Assign Tags` section.

**Actual behavior**
[ios ](https://github.com/mozilla/kitsune/pull/6358/files#diff-a7c603f0c771153cb1b7b5b736b310eaf6c1ca3a9974368c59d083797bc2a60dR74) and [VPN::Unsupported::No OS Named](https://github.com/mozilla/kitsune/pull/6358/files#diff-a7c603f0c771153cb1b7b5b736b310eaf6c1ca3a9974368c59d083797bc2a60dR177) are not returned inside the `Assign Tags` section. 

**Screencasts**
![someMissingTags](https://github.com/user-attachments/assets/22f62792-e957-4b4a-bc85-7415c1d29bcd)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`.

**Comment by akatsoulas** [comment]
There was a typo in the slug of the tag. PR https://github.com/mozilla/kitsune/pull/6374
