### ISSUE TITLE
Strucutre the topics hierarchically in topic dropdown in the moderation tool 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2071]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6368

**Comment by emilghittasv** [comment]
I can confirm that topics are hierarchically structured inside the moderator tool.

Tested on macOS 14, Huawei P40Pro, Iphone 13 mini.

Moving this ticket inside the `release` column.
