### ISSUE TITLE
Question product & topic tags are not automatically reflecting changes in question product & topic

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2074]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to a posted AAQ question.
2. Modify the product & topic via the `Question Details` section.

**Expected behavior**
The changes are also reflected inside the question tags.

**Actual behavior**
The question tags are not updated.

**Screencasts**
Uploading tagChange.mov…

**Desktop:**
 - OS: macOS 14.7
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6372

**Comment by emilghittasv** [comment]
I can confirm that changing the question product or topic via the `Question Details` section is successfully reflected in the applied tags.

Moving this ticket inside the `release` column.
