### ISSUE TITLE
Update the tag form in the question details with tom-select

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2075]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6376

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6381

**Comment by emilghittasv** [comment]
The tag form was successfully updated to tom-select. 

All elements are functional (addition or deletion of tags on both desktop & mobile devices).

During the verification of this ticket I've noticed that the tags no longer act as a community forum search filter (filled and tracked in https://github.com/mozilla/sumo/issues/2085)

Moving this ticket inside the `release` column.
