### ISSUE TITLE
Expose SumoTag in the admin interface

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2076]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6375

**Comment by emilghittasv** [comment]
I can confirm that:
* Segmentation tags are successfully displayed inside admin under the `Tags > Sumo tags` section.
* New segmentation tags can be successfully added via the "Add SUMO Tags" option.
* The newly added segmentation tag is available inside the moderation tool and inside the `Apply a tag:` dropdown from the question page.
* Segmentation tags can be successfully deleted via `admin` and the deleted segmentation tags are no longer available inside the moderation tool or inside the `Apply a tag` from the question page.
* Archiving a segmentation tag will successfully remove the tag from the segmentation tag list inside the moderation tool.

While testing this ticket I've noticed that the segmentation tags which were marked as `is_archived` are still returned inside the `Apply a tag` field from the AAQ question page. Filled under: https://github.com/mozilla/sumo/issues/2083

Moving this ticket inside the `release` column.
