### ISSUE TITLE
Create a new group to manage the moderation queue

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2080]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6388

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6391

**Comment by emilghittasv** [comment]
I can confirm that:
* Users which do not belong to the `Content Moderators` group are redirected to a 404 page while trying to access the `/moderate` page.
* Users which are not signed in to SUMO are redirected to a 404 page while trying to access the `/moderate` page.
* Users which belong to the `Content Moderators` group can access the `/moderate` page successfully.

Note: The `Content Moderators` group or the users from that group need to have the `flagit | flagged object| Can moderate flagged objects` and `questions| question| Can change question` permissions set.

Moving this ticket inside the `release` column.
