### ISSUE TITLE
Consider limiting the products listed under the `Filter by product` dropdown inside the moderation tool only to those which have an active AAQ configuration

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2081]
We should consider limiting the products displayed inside the `Filter by product` dropdown menu (from the https://support.allizom.org/en-US/moderate page) to the ones which have an active AAQ configuration.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6382

**Comment by emilghittasv** [comment]
I can confirm that the `Filter by product` dropdown menu from the moderation tool lists only the products with an active AAQ configuration.

Marking an existing AAQ configuration as inactive will successfully remove the product from the dropdown filter.

Moving this ticket inside the `release` column.
