### ISSUE TITLE
Performing a moderation tool ticket update resets the product filter to All products

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2082]
**Preconditions**
* Sign in to SUMO with an account that has the necessary perms of accessing the moderation tool.
* Have a couple of questions (filled under different products) flagged for moderation .

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/moderate
2. Choose a particular product from the `Filter by product` dropdown menu.
3. Perform an update to the question, select the appropriate update status and click the `Update` button.

**Expected behavior**
After the page refresh the user is kept with the product filter applied in step 2.

**Actual behavior**
After the page refresh the filter is switched to the default (`All products`).

**Screencasts**
![ModerationToolFilter](https://github.com/user-attachments/assets/9595a74f-66fc-4402-bbaf-793575f4de9b)

**Desktop:**
 - OS: Windeows 11
 - Browser: Firefox

**Additional context**
This is reproducible in `stage`.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6384

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
