### ISSUE TITLE
Archived segmentation tags are returned inside the Apply a Tag AAQ question field dropdown

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2083]
**Preconditions**
Sign in with an admin account.

**Steps to reproduce**
1. Go to `/admin/tags/sumotag/`
2. Click on one of the listed segmentation tags.
3. Check the `Is archived` checkbox and save the edit.
4. Navigate to a random AAQ question.
5. From the `Apply a tag` field search for the archived segmentation tag.

**Expected behavior**
The archived segmentation tag is not returned.

**Actual behavior**
The archived segmentation tag is returned.

**Screenshots/Screencasts**
![ArchivedSegTag](https://github.com/user-attachments/assets/36e759eb-1067-4290-bea2-620c8f0860df)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6383

**Comment by emilghittasv** [comment]
I can confirm that archived segmentation tags are no longer returned inside the `Apply a Tag` dropdown menu at question level.

Unarchiving the segmentation tag will bring the option back inside the `Apply a Tag` dropdown.

Moving this ticket inside the `release` column.
