### ISSUE TITLE
The tags displayed at question level no longer act as community forum search filters for users which have the permission of modifying the question tags

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2085]
**Preconditions**
Sign in to SUMO with an account that has permissions of modifying the question tags.

**Steps to reproduce**
1. Go to a posted forum question.
2. Click on any of the listed Tags.

**Expected behavior**
The tag acts as a filter and the user is redirected to the question product community forum while having the tag set as a search filter.

**Actual behavior**
Nothing happens.

**Screenshots/Screencasts**
![noTagFilter](https://github.com/user-attachments/assets/1cf8225d-e194-4c69-a0af-f7d08a86b142)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
* The tags still act as a community forum search filter if clicking on them while not signed in to SUMO or while signed in using an account that doesn't have the permissions of modifying the question tags.
* This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6392

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
