### ISSUE TITLE
Consider displaying all elements inside the tom-select Tags drodpown on the moderation tool and question page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2086]
Currently, the "Assign Tags" dropdown from the moderation tool and the "Tags" dropdown from the question page is only listing a subset of the full tags list. We should consider displaying all elements by using the `maxOptions`  setting.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6386

**Comment by emilghittasv** [comment]
@akatsoulas Can we do the same with the "Tags" dropdown inside the question page?

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6387

**Comment by emilghittasv** [comment]
I can confirm that the `Assign Tags` dropdown from the moderator tool and the `Tags` dropdown from the question page successfully lists all the available segmentation tags.

Moving this ticket inside the `release` column.
