### ISSUE TITLE
Remove only the edit details and not the question details section

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2087]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6389

**Comment by emilghittasv** [comment]
Moderating a question via the `/moderate` tool will automatically remove the `Edit details` option from the `Question Details` section inside the question page. All the other information regarding product, topic, locale and system details will still be available/visible.

Moving this ticket inside the `release` column.
