### ISSUE TITLE
Consider moving the questions reported as "Misplaced bug report or support request" to the /moderate page instead of /flagged

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2088]
**Describe the bug**
Since we do want to restrict the change/moderation of question topics to agents only we also need to have a safety net and to give agents the possibility of correcting mistakes performed during moderation. While testing out our existing flows we've noticed the following:

1. If an agent performs a mistake while moderating a question (assigning a wrong topic to the question) and becomes aware of that immediately after clicking on the "Update" button he might want to access the question and perform the change manually via the `Question Details` section. But since we've disabled this action in https://github.com/mozilla/sumo/issues/2058 agents won't be able to correct topic categorization mistakes manually.
2. If we want to keep the `Question Details` section (as per https://github.com/mozilla/sumo/issues/2087) the question topic becomes visible to our contributors. Contributors might spot a mistake (a wrong topic categorization performed by agents) and flag it be corrected via the "Report Abuse > Misplaced bug report or support request" option.

**The identified problem**
1. Agents are not able to manually correct the mistakes via the Question Details section.
2. Questions which are flagged as "Misplaced bug report or support request" will end up inside the `/flagged` page instead of the `/moderate` one.  Since the question was already moderated by an agent, contributors working on the `/flagged` page won't be able to handle the topic change (since the `/flagged` page lacks the functionality of modifying the question topic and the functionality of changing the topic from the Question Details sections gets automatically disabled after moderation).

**Possible solution**
We should give agents the possibility to correct mistakes performed during moderation (even if the mistake was spotted by the agent or by a different user/contributor).

This could be done by moving all questions which were flagged as `Misplaced bug report or support request` back to `/moderate`  (instead of `/flagged`) so we can:
1. Maintain the question moderation process in the hands of the agent.
2. We can instruct agents to report the question as "Misplaced bug report or support request" if they know that a mistake was made so the question is brought back to the `/moderate` tool for correction.
3. Have a way to track (via GA4?) mistakes performed by agents during the moderation process by keeping track of the number of valid "Misplaced bug report or support request" reports.
4. Maintain the involvement of our contributors in helping us spot potential mistakes made during the moderation process.

**Notes from Josh**
1. If a question was flagged as being "Misplaced bug report or support request" and brought back inside the `/moderator` tool we should have a visible marker for that question/ticket which should point out to agents that the question was previously moderated but flagged as wrongly moderated.

**Comment by emilghittasv** [comment]
`Have a way to track (via GA4?) mistakes performed by agents during the moderation process by keeping track of the number of valid "Misplaced bug report or support request" reports.`

I've double checked this ^ with Ryan. Currently we don't collect any GA4 data for the "Report Abuse" actions. So we need to add that if needed (but definitely not for v1)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6393

**Comment by akatsoulas** [comment]
When a user flags a question as wrongly categorized, there's a flag created per user. Although this makes sense from a user perspective, it creates multiple items for the same question in the moderation tool which is problematic. in order to solve for this, there's a PR that introduces the notion of DUPLICATE entries. If a moderated question is flagged as misplaced, the initial flag will be set back to PENDING and new additional flags (one per user that flags the question) will be created as duplicates. This will allow us to both capture user intention and accompanied data but to also keep a single item in the moderation queue.

PR https://github.com/mozilla/kitsune/pull/6396

**Comment by emilghittasv** [comment]
I can confirm that:
* If a user flags a question as `Misplaced bug report or support request`, the question will end up inside the `/moderate` page instead of the `/flagged` one.
* Moderators can successfully moderate the flagged question again (assign or remove tags or change the question topic if needed)

I'm moving this ticket inside the `release` column.
