### ISSUE TITLE
Flagging the same question as Misplaced bug report or support request by multiple users (at least 2) will create ticket duplications inside the moderation queue 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2093]
**Preconditions**
Have 3 accounts ready to be used.

**Steps to reproduce**
1. Sign in with account A and post a question to any AAQ forum.
2. Sign in with account B and flag the question as Misplaced bug report or support request.
3. Sign in with account C and flag the question as Misplaced bug report or support request.
4. Access the https://support.allizom.org/en-US/moderate page

**Expected behavior**
No ticket duplication.

**Actual behavior**
The question posted in step 1 is duplicated inside the moderate queue 

**Screencasts**
![ticketDuplication](https://github.com/user-attachments/assets/983a739a-64b4-45fe-a40d-f0b89de51634)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6397

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

Moving this ticket inside the `release` column.
