### ISSUE TITLE
500 Attribute error when trying to create a topic redirect

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2094]
**Preconditions**
Sign in to SUMO with an account that has admin access permissions.

**Steps to reproduce**
1. Go to /products/topicslughistory/
2. Search for `multimedia` and try creating a redirect to `Audio and Video`

**Expected behavior**
A topic redirect can be successfully applied.

**Actual behavior**
500 error and sentry fires https://mozilla.sentry.io/issues/6077432484/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6400

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
