### ISSUE TITLE
Some user avatars are no longer being displayed

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#2096]
User avatars sourced from https://secure.gravatar.com are blocked by our CSP (see https://support.mozilla.org/en-US/user/markh2/).

That image source was mistakenly removed by https://github.com/mozilla/kitsune/pull/6328, and should be added back into the `CSP_IMG_SRC` setting.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

User avatars sourced from gravatar.com are no longer blocked by our CSP (https://support.allizom.org/en-US/user/markh2/)

Moving this ticket inside the `release` column.
