### ISSUE TITLE
Optimize get_hierarchical_topics function

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2097]
When there are many flags, the said function causes a timeout. We should find an alternative to indent the topics without affecting performance

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6404

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The moderation queue was unblocked and I've tried finding a breaking point by increasing the number of items inside the queue to 300 without any success in breaking it.

Moving this ticket inside the `release` column.
