### ISSUE TITLE
"Language" link in footer locale selector leads to www.m.o

### ISSUE THREAD

**Issue by janbrasna** [mozilla/sumo#2100]
**Describe the bug**

The "Language" heading above the locale dropdown is clickable, and links to https://www.mozilla.org/locales/ for overview of _bedrock_ locales available for the homepage content, not _sumo_…

**Steps to reproduce**

1. Open any page and scroll to the black footer
2. Click on 'Language' heading above the locale dropdown
3. (Arrive at bedrock…)
4. Pick any locale, and end up at mozilla.org home page instead of sumo.

**Expected behavior**

Stay on _sumo_.

**Actual behavior**

End up on _bedrock_.

**Additional context**

This was an addition in Protocol: https://github.com/mozilla/protocol/issues/259

https://protocol.mozilla.org/components/detail/language-switcher says:
> "The link mzp-c-cta-link is optional, and should be used only if a website has a page dedicated to language selection. If omitted, the form <label> will be displayed visually instead"

So it should only be configured in case the site has its own page to link to from such heading.

**Comment by janbrasna** [comment]
There are https://support.mozilla.org/locales available, so that should be configured for the component.

**Comment by emilghittasv** [comment]
I can confirm that the "Language" link from the footer section redirects the user to the `/locales` page.

Moving this ticket inside the `release` column.
