### ISSUE TITLE
On the Knowledge Base Dashboard page the selected time interval is not highlighted 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo#280]
STR:

1. Go to https://support.allizom.org/en-US/contributors
2. Select another time interval (ex. "Last 90 days")

ER: The interval is changed and highlighted. 
AR: The interval is changed but is not highlighted.

**Comment by akatsoulas** [comment]
This is minor so let's tackle it in the second iteration.

**Comment by emilghittasv** [comment]
Bug fix candidate for the current sprint.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/6299

**Comment by akatsoulas** [comment]
The PR is marked as draft so I am moving this card back to In Progress

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.
