### ISSUE TITLE
Allow SVG files for product cards.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#312]

**Comment by emilghittasv** [comment]
I can confirm that SVG images can be successfully added to products.

![Image](https://github.com/mozilla/sumo/assets/28087895/742acb02-e35a-4429-8e2e-bf6a5807f79c)
![Image](https://github.com/mozilla/sumo/assets/28087895/679af810-62e9-4c70-be4a-c00614cb2dfb)

Tested on:
* Windows 10 (Firefox, Chrome and Edge)
* Huawei P40Pro (Firefox)
* Iphone 13 (Safari)

During the verification of this ticket I've also verified that no regressions were introduced when adding non-SVG images to products.

Moving this ticket inside the `release` column,
