### ISSUE TITLE
Private messages to multiple people result into server error

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo#353]
I can't send private messages to multiple people at once (I tried reducing my list and still getting error for 7 people)

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by emilghittasv** [comment]
I am unable to reproduce this issue.

I believe that this might have been fixed along the way.

Closing this ticket but feel free to re-open if this issue is still reproducible on your end.
