### ISSUE TITLE
New images aren't loaded when customising a KB article

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo#367]
STR:

1. Open: https://support.mozilla.org/en-US/kb/push-notifications-firefox#firefox:win10:fx70
2. Switch Firefox version to version 69

ER:

Firefox 69 specific image is shown.

AR:

No image is shown, until you scroll the page, then the image is shown.

![Peek 2020-04-16 14-36](https://user-images.githubusercontent.com/755354/79462749-d83cdc80-7fef-11ea-9b1f-c101ba190d8c.gif)

This issue also existed pre-responsive redesign, so I don't think we need to fix it today.

**Comment by emilghittasv** [comment]
I am unable to reproduce this issue on prod environment. 

Tested using Firefox, Chrome and Safari.

@LeoMcA Please feel free to re-open this ticket if you are still able to reproduce!
