### ISSUE TITLE
Cannot upload GIF image files as GIF in Media Gallery or Questions

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#468]
**Affected platforms:**
Windows 10 64-bit
Android 8
macOS 14.10.6

**Browser version:**
FF 77
Chrome 83.1
Safari 

Environment:
Production
Stage
Dev

**Precondition:** 
Create account and sign in.

**Steps to reproduce:**

1. Go to Contributor Tools> Media gallery and select to Upload a New Media File.
2. Browse a GIF file and select it. 

**Expected results:**
A second 'Upload a New Media file' modal should show up containing fields such as Locale, Tile and Description info to fill in before uploading. 

**Actual Results:**
No second modal shows up and file remains selected even if modal is closed until page is refreshed. 

![Cannot upload video file Prod](https://user-images.githubusercontent.com/53306802/83889104-69f4da80-a753-11ea-874d-d484f73795c8.gif)

Note: This does not occur when uploading a smaller sized image (PNG, JPEG) https://github.com/mozilla/sumo/issues/1026

**Comment by mirunacurtean** [comment]
Updating issue after re-test. 
![image](https://user-images.githubusercontent.com/53306802/109500070-69009780-7a9e-11eb-8463-a27864847148.png)

**Comment by AliceWyman** [comment]
I also see this problem now when I try to upload a PNG file to the Media Gallery. I tried a JPG file and that still works.

**Comment by AliceWyman** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1751620 on the PNG issue.

**Comment by mirunacurtean** [comment]
Updating this with new repro steps: 
1. From https://support.allizom.org/en-US/gallery/images select Upload a New Media File
2. Select browse and navigate the local folders to the image folders. 
3. Select a GIF image under 10 MB. 
4. Finish uploading it and look at the 

**Results:**
Like in the bugzilla ticket [comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1751620#c1) regarding JPEG, the GIF is submitted as a PNG.
![image](https://user-images.githubusercontent.com/53306802/173590374-7d2c16ae-cdb9-49d2-be6e-9dd268fa3c9d.png)

Example:
https://support.allizom.org/en-US/gallery/images
