### ISSUE TITLE
Knowledge Base dashboard sorting by number of days does not work for All Products

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#470]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
77.0 on Dev environment
Firefox 68.6.0
Chrome 83.1

**Steps to reproduce:**

1. Go to https://support.mozilla.org/en-US/contributors
2. View that Articles are sorted by the time since they have been posted, by default, in the last 30 days, in the All Producuts default category. 
3. Choose to sort them by one of the other time period options. 

**Expected results:**
All Products results are updated to show articles and other data gathered in the "last x days/ all time" option chosen. The chosen option is highlighted. 

**Actual Results:**
Results are not updated to show articles and other data gathered in the "last x days/ all time" option chosen. The chosen option is not highlighted (This is logged in  #280) 

![All product results not filtered by time period](https://user-images.githubusercontent.com/53306802/98276977-72ba3880-1f9f-11eb-9ded-82e7de4476fe.gif)

**NOTE: When selecting from the product drop down menu another product category and then switching to another time period, it can be seen that the results are updated - by the number of visits at least.**

**Comment by emilghittasv** [comment]
It seems that this issue might have been fixed along the way. The tables are successfully updated when changing different time filters.

Tested on:
- Both stage & prod environments.
- Using Chrome, Safari & Firefox browser (desktop)
- Using Firefox browser (Android)

As a side note, https://github.com/mozilla/sumo/issues/280 is still reproducible.
