### ISSUE TITLE
Implement Firefox download button navigation + sticky nav

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo#500]
- [ ] remove any/all in-page Firefox download buttons that may still be on the site

- [ ] remove the extra links around the download button. (ie 'Privacy, Whats New, and Systems and Languages')

- [ ] Move download buttons to be placed only in nav header + within the sticky header on desktop only (for non-firefox users), the sizing should be the same as the sign in/up button ---> **Placement** should be just to the left of the profile avatar and name when signed in. When signed out it should be just to the left of the sign in/up button. This download button should always be in the primary blue button style - this way it is not conflicting with the sign in/up button. For the sticky nav (desktop only) --- > place between the search bar and the profile avatar (or sign in/up button, in either case). Reduce length of search bar only if necessary  

- [ ] Mobile placement of download button should be within the hamburger collapsed menu... right now (seen in iOS) the download button on mobile lives within the profile avatar menu, lets move it from there and have it inside the hamburger menu instead.
Similar to this, except lets move our download button below the menu items, and use primary (blue fill) button style:
![image](https://user-images.githubusercontent.com/54991698/85794864-4ba44e00-b705-11ea-83fc-f3148be76a4c.png)

**Comment by akatsoulas** [comment]
Assigning this to the engineering board too
