### ISSUE TITLE
Dashboard Page not Found when filtering Articles first by product and then by type

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#532]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
FF Release 78.0.1
Firefox 68.10.0
Chrome 83.0.4

**Environment:** 
Production  and STAGE

Preconditions. 
Create and login with account and login to be able to see Contributor Tools.

**Steps to reproduce:**
 
1. From Contributor Tools select to view Dashboard. 
2. Select All Product drop down menu and choose a particular product (not Firefox or Thunderbird)
3. After that choice is applied, select another options but the default "all" from Filter By Type menu. 

**Expected results:**
Article results are being filtered by product category and selected type and displayed as previous results. 
If there are no results found an appropriate message will be displayed. 

**Actual Results:**
Wehn first filtering by product and then by type, the result is a Page Not Found. 

![Dashboard Page not found when filtering certain products by type](https://user-images.githubusercontent.com/53306802/86891011-d5411c00-c106-11ea-8003-cfa76697091b.gif)

**NOTE:** 
**1. This issue does not occur for Firefox or Thunderbird product categories.**
2. The results are displayed for other product categories when filter by type is applied while on Firefox or Thunderbird product categories. Then another product can be selected and the results will show up. 

![Results are displayed when filter is first selected and the product](https://user-images.githubusercontent.com/53306802/86891341-5ac4cc00-c107-11ea-9581-91996809447d.gif)

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5622

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed on both `stage` and `dev` envs. 

Filtering by `product` first and then by `type` no longer updates the product query parameter to a value which leads to having a Page not Found displayed.

Thank you @smithellis for this fix!

Moving this ticket inside the "Release" column.

**Comment by emilghittasv** [comment]
This ticket was fixed & verified fixed. It seems that it remained open after release.

Closing.
