### ISSUE TITLE
Translated article showing unreviewed data

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#566]
Environment:
Stage and Production

What is the issue: 
Translated article showing unreviewed title and data. 

Examples:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1712241
* https://bugzilla.mozilla.org/show_bug.cgi?id=1682551

**Comment by kelimuttu** [comment]
To give more context on this:

article title is part of the _Edit Description_ section on the article edit page. Unlike the _Edit Content_ section, editing _Edit Description_ section doesn't require any review/approval when it comes to non-English articles. Hence, we have this problem where random user would change the title of (often times) an article that hasn't even translated.

**Comment by mirunacurtean** [comment]
Contributor (no permissions)  - cannot see Edit Title/ Slug/ Description section. Can only see content and modify it 

- Can see Unreviewed versions in [Revision history](https://support.allizom.org/en-US/kb/webpack-article-test-changes-made-title/history) but cannot access them
- Can see [Recent Revisions](https://support.allizom.org/en-US/kb/revisions) the most recent version updated by a superuser (even if it is not reviewed) and may be able to edit it’s content only
- Cannot edit translated versions of the article

**Comment by mirunacurtean** [comment]
I can confirm that the users with the permissions listed in [comment 7](https://bugzilla.mozilla.org/show_bug.cgi?id=1682551#c7) are the ones that can view or approve revisions for articles (english or localised), depending on what group/locale they are part of.
