### ISSUE TITLE
Solve UX in profile to move away from needing display names

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo#639]
Step 2 of these previous tickets #580 and #75 
With the ability for users to now edit their username.... I think we need to rethink the need and purpose of display names.
Is this something users still need?
Can the username now just function as a display name?

- [ ] discuss need for display with platform team - understand this from dev perspective @akatsoulas @LeoMcA 

- [ ] talk with Kiki and understand the communities relationship to display names and usernames, gather some insights there from community

- [ ] create UX solution and propose to team for review and implementation

**Comment by kelimuttu** [comment]
Do we have the ability to anonymize username in the end? @akatsoulas
