### ISSUE TITLE
Forums - logged in users - change 'Top Contributors' button to 'Ask the Community' to align with logged out forum view

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo#688]
![Screen Shot 2020-11-03 at 4 59 56 PM](https://user-images.githubusercontent.com/54991698/98045278-3d261b80-1df6-11eb-81db-e526ab78e85d.png)

For UX consistency I think it makes most sense to have these buttons be the same whether you are logged-in or logged out... "Top Contributors" can be found in the community hub /contributor link from the nav... I think we are losing a valuable opportunity here to continue to the make the AAQ more accessible.

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5145
