### ISSUE TITLE
Other user is unable to delete through editing the images posted by a superuser/ moderator account

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#692]
**Browsers:**
Firefox
Chrome
Safari

**Devices:** 
Windows pro 10
macOS 10.14.6
Android 9.0.0

**Preconditions:**
Account A is a moderator/ superuser account. 
Account B is a regular user account. 

**Steps to reproduce:**
1. Sign in with account B and and post a new question in which at least one image has been added. https://support.allizom.org/en-US/questions/new/desktop/form.
2. Login on another profile/ browser with account A and go to the question thread. 
3. With account A choose to edit the question and upload and post a new image. 
4. With account B refresh the question and then try hover over the images and then try to edit the question. 

**Actual result:**
While hovering of the images as posted on the thread or when going over the uploaded images in "Edit this question" mode it can be noticed that only the image added by the question owner can be deleted. 
This applies to editing replies as well, not only the initial question. 
This applies to other user's posts as well - the user may edit their post and their own image, but not the one added by the moderator account. 

**Expected result:** 
Not sure. Should the question owner be able to delete any images added by a user account with more permissions (moderator/superuser)? 

![moderator vs regular account image delete test](https://user-images.githubusercontent.com/53306802/98712916-990d1900-238f-11eb-90f8-52d69b7b71d0.gif)

**Comment by LeoMcA** [comment]
This feels like acceptable behaviour to me, since I can't see moderators attaching images to users' posts all that often, if at all. Indeed should we perhaps strip them of that permission and only give them permission to remove images? @akatsoulas @madasan thoughts?
