### ISSUE TITLE
Topics and articles not showing up in "Contributors" category

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo#698]
We have a Contributors category/product that we've purposely hidden from the support.mozilla.org home page. Kiki has added topics to it but they're not showing up on the Contributors page (https://support.mozilla.org/en-US/products/contributor) even though she's added articles to them.

Steps to reproduce:
1. Go to https://support.mozilla.org/en-US/products/contributor

Expected result: Topics are showing up.
Actual result: No topics

**Comment by AliceWyman** [comment]
https://support.mozilla.org/en-US/products/contributor is now showing topics.  The search field is also working and displays  "How to contribute" article results.
