### ISSUE TITLE
Merge the contributor groups

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo#786]
We have two:

1. "Contributors": https://github.com/mozilla/kitsune/blob/06860ed23d85830d91894846f2e7b14baa26308f/kitsune/groups/views.py#L223

2. "Registered as contributor": https://github.com/mozilla/kitsune/blob/30cb647d8013f14ae2b6fb56435bd26b1e88f35d/kitsune/users/utils.py#L17

The first is set using a url which nothing seems to link to any more.

**Comment by akatsoulas** [comment]
There is functionality to remove users from the old groups when they choose one of the new contribution areas. These 2 legacy groups will be completely removed after a short period of time. I will open a new issue as a placeholder for that removal
