### ISSUE TITLE
API gallery:The timestamp is not updated on editing

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo#83]
[STR]:
1.Go to https://support.allizom.org/en-US/gallery/images
2.Upload a new media file
3.Go to the uploaded media file (e.g.https://support.allizom.org/en-US/gallery/image/30617) and update the description after a while
4.In a new tab open https://support.allizom.org/api/1/gallery/image/<id>

[Expected result]:
Updated field should display the time when the image was edited

[Actual result]:
Created and Updated time are the same
<img width="277" alt="Screenshot 2019-10-08 at 11 50 46" src="https://user-images.githubusercontent.com/41474886/66383985-968b0380-e9c6-11e9-91ca-4a501baa591f.png">

@akatsoulas

**Comment by mirunacurtean** [comment]
The JSON results no longer contain 'created', 'updated' and 'updated_by' fields. Checked on stage and production. 
![image](https://user-images.githubusercontent.com/53306802/89531407-dabe7e80-d7f8-11ea-95f3-6049057ef33e.png)

**Comment by emilghittasv** [comment]
@akatsoulas as Miruna mentioned, the JSON result no longer contains the "created", "updated" & "updated_by" keys. 

On the UI part I noticed that we are displaying only he "Uploaded" date.

Are we planning to bring those keys back in the future? Or can we go ahead and close this ticket?
