### ISSUE TITLE
Do not show in the search results questions without answers.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#870]

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5575

**Comment by akatsoulas** [comment]
The PR removes from index any questions that don't have any answers

**Comment by emilghittasv** [comment]
I can confirm that:
* New questions (without answers) are not displayed/listed inside the search result. 
* Once a reply is provided, the question is successfully displayed/listed inside the search result.
* If the reply is deleted (and there are no more replies), the question is no longer displayed inside the search result.

Moving this ticket inside the ready for release column.

As discussed with Tasos in private, we need to reindex for old content (old questions) without answers/replies to have them excluded from the search results.
