### ISSUE TITLE
Add link to Private Network install page from the SUMO landing page

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo#88]
Sometimes, the SUMO page (https://support.mozilla.org/en-US/products/firefox-private-network) for Private Network out ranks the actual install page (https://private-network.firefox.com/).

We'd like to add a link to the install page on SUMO (en-us only)

1. Get attribution/link from @hoosteeno 
2. Get implementation ideas from Bob Micheletto.
3. Implement link on https://support.mozilla.org/en-US/products/firefox-private-network

**Comment by akatsoulas** [comment]
@hoosteeno @jonichan is this still relevant?
