### ISSUE TITLE
Changing the language of a page that is not setup in that locale can results in a Page not Found

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#936]
**Environment:** 
Production
Stage

**Steps to reproduce:**
1. Go to https://support.mozilla.org/az/kb/cox-sorusulan-suallar
2. Change language to Bulgarian, https://support.mozilla.org/bg/kb/cox-sorusulan-suallar

**Actual result:**
Due to the article not existing on the Bulgarian locale, this results in a Page not Found. 
![image](https://user-images.githubusercontent.com/53306802/130072088-9183540b-cf0a-47a5-a053-75f028d7ec45.png)

**Expected result:**
Redirect to the Bulgarian homepage. 
![image](https://user-images.githubusercontent.com/53306802/130072202-8e852db3-7330-486d-95a4-d537fdef1512.png)

**Comment by akatsoulas** [comment]
This feels like the expected behavior. Maybe the UX can be improved but it's not a priority atm
