### ISSUE TITLE
404 error displays in different languages in Nightly

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo#94]
Load this non-existent redirect link (https://support.mozilla.org/1/firefox/70.0a1/Darwin/en-US/cryptominers-report) in Firefox Nightly (en-us). Reload it a few times.

Expected result:
Show the "Page not found" page in English each time.

Actual result:
The "Page not found" shows up in different languages at each refresh.

It works as expected on Beta and on regular Firefox.

**Comment by mirunacurtean** [comment]
Just an update. The link https://support.mozilla.org/1/firefox/70.0a1/Darwin/en-US/cryptominers-report now redirects to https://support.mozilla.org/en-US/kb/trackers-and-scripts-firefox-blocks-enhanced-track?as=u&utm_source=inproduct#w_cryptominers.

The reported issue can instead be reproduced, as seen from the attachment, using the https://support.mozilla.org/1/firefox/ link. 
This occurs across Nightly, Beta and FF Release (79.0) most recent versions. 
![Redirect update ](https://user-images.githubusercontent.com/53306802/89788754-50438b00-db28-11ea-94e2-1ef6510d09b0.gif)

**Comment by mirunacurtean** [comment]
Verified fixed for en-us and also tested in RO and the page locale does not suffer any changes through page reload. 
Tested on Firefox, FF Nightly and Chrome. 
![jpeg upload post 400](https://user-images.githubusercontent.com/53306802/181061183-ce8f1324-63fe-406c-b477-625d7d7be0ea.gif)

**Comment by escattone** [comment]
@mirunacurtean It appears that you uploaded a different GIF than you intended.

**Comment by mirunacurtean** [comment]
@escattone Thanks. I've updated it with the proper one.
