### ISSUE TITLE
Layout issue in user profiles

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#959]
More info
https://bugzilla.mozilla.org/show_bug.cgi?id=1680203

**Comment by mirunacurtean** [comment]
Verified fixed. No regressions on other locales either. Tested across all locales and on desktop and mobile layouts.

![image](https://user-images.githubusercontent.com/53306802/182349266-1d07d11e-1f37-4af7-b7ca-f616d319a442.png)
![image](https://user-images.githubusercontent.com/53306802/182349401-5c006e3b-6fc8-4cc6-8121-dcae830d7c24.png)
![image](https://user-images.githubusercontent.com/53306802/182349525-4c0ed5ba-7e13-4183-b78b-0f93025ffa6d.png)
![image](https://user-images.githubusercontent.com/53306802/182349750-38366d37-fed4-44d5-b2dc-120f1cb757d1.png)
![image](https://user-images.githubusercontent.com/53306802/182350318-89579ef6-c47b-4562-b882-931ab3eeed53.png)

![image](https://user-images.githubusercontent.com/53306802/182350051-bc2e0296-2ddc-49f8-aac4-beb7070a93ab.png)
