### ISSUE TITLE
Replace oauth2client

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#983]
Deprecation warning in version 4

Note: oauth2client is deprecated. No more features will be added to the libraries and the core team is turning down support. We recommend you use google-auth and oauthlib.

**Comment by LeoMcA** [comment]
We're still using oaut2client: https://github.com/mozilla/kitsune/pull/5062

**Comment by mirunacurtean** [comment]
No problems notivced when signing in/ up on stage. 
@escattone anything else I should check?
