### ISSUE TITLE
remove jquery-ui datepicker

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo#985]
entirely unnecessary nowadays: https://caniuse.com/input-datetime

remove the module and associated css should save a bunch of space in the common bundle

**Comment by LeoMcA** [comment]
QA: This picker appears on https://support.allizom.org/en-US/kb/revisions, and at the bottom of the edit page for any document listed on https://support.allizom.org/en-US/contributors with an "expiry date" set (and, indeed, adding an expiry date to a document should make it appear in this column).

Due to the mozilla-focused nature of these pages, cross browser testing isn't required, but cross-locale testing would be great (given different date formats in different locales, so en-us and anything european should suffice).

**Comment by mirunacurtean** [comment]
Expiry date is indeed added instantly after an article revision has been approved to the [Contributors lists](https://support.allizom.org/en-US/contributors). I've added and updated expiry dates for English and non-English locale articles. I cannot add an expiry date to the translated articles, only to the English original. 
English locale
![image](https://user-images.githubusercontent.com/53306802/149301537-8020236c-607b-4412-81d4-d0204e7d9dd9.png)

Spanish locale
![image](https://user-images.githubusercontent.com/53306802/149301798-2f6ae6e3-1e81-425a-9e0d-670cae8e0e6e.png)

Japanese
![image](https://user-images.githubusercontent.com/53306802/149305847-adcfa02d-0a81-4d81-afd1-8c844b2a917d.png)


@LeoMcA Is the article supposed to be listed in the column when using the expiry date picker, if the article expiry date is further than the End date picker date? Please check the attached example for more details. 

![image](https://user-images.githubusercontent.com/53306802/149304345-647130ec-89bb-423c-8e99-f5d1d9592589.png)

**Comment by LeoMcA** [comment]
> @LeoMcA Is the article supposed to be listed in the column when using the expiry date picker, if the article expiry date is further than the End date picker date? Please check the attached example for more details.

Yes, the date picker on the recent revisions page filters by when revisions were created, rather than being anything to do with the expiry date.
